import { I, dish } from "./catalog-kit";
import type { Recipe } from "./types";

/** Sauces and dry rubs live in the main library — search them, do not silo them. */
export const SAUCE_RECIPES: Recipe[] = [
  dish({
    id: "donair-sauce-mom-pop",
    name: "Mom-and-pop donair sauce",
    description: "East Coast shop sauce: evaporated milk, sugar, garlic, and vinegar. The one that drips down the pita.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Nova Scotia",
    tags: ["sauce", "maritimes", "atlantic", "nova-scotia", "vegetarian", "quick"],
    aliases: ["mom and pop donair sauce", "homemade donair sauce", "halifax garlic sauce", "donair sweet sauce"],
    nutrition: { cal: 90, protein: 2, carbs: 14, fat: 3 },
    ingredients: [
      I("evaporated milk", 1, "can", "Pantry"),
      I("white sugar", 0.66, "cup", "Pantry"),
      I("garlic powder", 2, "tsp", "Herbs & Spices"),
      I("white vinegar", 3, "tbsp", "Pantry"),
      I("onion powder", 0.25, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Whisk evaporated milk, sugar, garlic powder, and onion powder until the sugar dissolves.",
      "Stream in vinegar. It will thicken in a minute. Taste — it should be sweet, garlicky, and just sharp.",
      "Chill 20 minutes. Spoon generously over donair meat, fries, or pizza.",
    ],
  }),
  dish({
    id: "donair-sauce-greco",
    name: "Greco-style donair sauce",
    description: "The chain-shop cousin: thicker, sweeter, heavier on garlic. The sauce people mean when they say Greco.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Nova Scotia",
    tags: ["sauce", "maritimes", "atlantic", "nova-scotia", "vegetarian", "quick"],
    aliases: ["greco donair sauce", "greco sauce", "greek pizza donair sauce", "greco garlic sauce"],
    nutrition: { cal: 110, protein: 2, carbs: 18, fat: 3 },
    ingredients: [
      I("evaporated milk", 1, "can", "Pantry"),
      I("condensed milk", 0.25, "cup", "Pantry"),
      I("white sugar", 0.5, "cup", "Pantry"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("white vinegar", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Whisk both milks with sugar and garlic powder until smooth and glossy.",
      "Add vinegar last. It should stand up on a spoon, not run.",
      "Cold overnight is better. This is the sauce for a late-night donair pizza.",
    ],
  }),
  dish({
    id: "donair-sauce-pizza-delight",
    name: "Pizza Delight donair sauce",
    description: "Maritime pizza-shop style: a little tangier, garlic-salt forward, made for donair pizza and garlic fingers.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "New Brunswick",
    tags: ["sauce", "maritimes", "atlantic", "new-brunswick", "vegetarian", "quick"],
    aliases: [
      "pizza delight donair sauce",
      "pizza delight sauce",
      "pd donair sauce",
      "garlic fingers sauce",
      "donair pizza sauce",
    ],
    nutrition: { cal: 95, protein: 2, carbs: 15, fat: 3 },
    ingredients: [
      I("evaporated milk", 1, "can", "Pantry"),
      I("white sugar", 0.5, "cup", "Pantry"),
      I("garlic salt", 1.5, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("white vinegar", 4, "tbsp", "Pantry"),
      I("lemon juice", 1, "tsp", "Produce"),
    ],
    steps: [
      "Whisk milk, sugar, garlic salt, and garlic powder.",
      "Add vinegar and lemon. It should taste brighter than mom-and-pop sauce.",
      "Chill. Pour over donair pizza, garlic fingers, or a pita.",
    ],
  }),
  dish({
    id: "memphis-dry-rub",
    name: "Memphis dry rub",
    description: "Paprika, brown sugar, chili. The ribs do not need a mop — this is the bark.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "tennessee", "vegetarian", "quick"],
    aliases: ["memphis rub", "rib rub", "dry rib rub"],
    nutrition: { cal: 20, protein: 0, carbs: 4, fat: 0 },
    ingredients: [
      I("paprika", 0.25, "cup", "Herbs & Spices"),
      I("brown sugar", 3, "tbsp", "Pantry"),
      I("kosher salt", 1, "tbsp", "Herbs & Spices"),
      I("black pepper", 1, "tbsp", "Herbs & Spices"),
      I("chili powder", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 2, "tsp", "Herbs & Spices"),
      I("cayenne", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Mix everything. Store in a jar.",
      "Pat meat dry. Rub until it looks like red sand.",
      "Rest 30 minutes or overnight before smoke or oven.",
    ],
  }),
  dish({
    id: "texas-brisket-rub",
    name: "Texas brisket rub",
    description: "Salt, pepper, a little garlic. That is the whole sermon.",
    minutes: 5,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "texas", "vegetarian", "quick"],
    aliases: ["dalmatian rub", "salt and pepper brisket", "texas rub"],
    nutrition: { cal: 8, protein: 0, carbs: 1, fat: 0 },
    ingredients: [
      I("coarse black pepper", 0.25, "cup", "Herbs & Spices"),
      I("kosher salt", 3, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Stir. Coat a brisket or a cheap chuck roast. Smoke or slow-roast until it surrenders."],
  }),
  dish({
    id: "montreal-steak-spice",
    name: "Montreal steak spice",
    description: "Cracked pepper, coriander, garlic, dill. The Canadian steakhouse shaker.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "canadian", "vegetarian", "quick"],
    aliases: ["montreal steak seasoning", "steak spice"],
    nutrition: { cal: 10, protein: 0, carbs: 2, fat: 0 },
    ingredients: [
      I("coarse black pepper", 2, "tbsp", "Herbs & Spices"),
      I("kosher salt", 2, "tbsp", "Herbs & Spices"),
      I("coriander seed", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("dill seed", 1, "tsp", "Herbs & Spices"),
      I("red pepper flakes", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Crush the seeds roughly. Mix. Press onto steak or roasted potatoes."],
  }),
  dish({
    id: "jerk-dry-rub",
    name: "Jerk dry rub",
    description: "Allspice, thyme, scotch bonnet heat. Wet jerk is a paste — this is the pantry version.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "Caribbean",
    tags: ["dry-rub", "sauce", "spicy", "vegetarian", "quick"],
    aliases: ["jerk seasoning", "jamaican jerk rub"],
    nutrition: { cal: 12, protein: 0, carbs: 2, fat: 0 },
    ingredients: [
      I("allspice", 2, "tbsp", "Herbs & Spices"),
      I("dried thyme", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("onion powder", 1, "tbsp", "Herbs & Spices"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("cayenne", 2, "tsp", "Herbs & Spices"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    steps: ["Mix. Rub on chicken, pork, or cauliflower. Rest. Grill or roast hot."],
  }),
  dish({
    id: "cajun-blackening-rub",
    name: "Cajun blackening rub",
    description: "Paprika, thyme, oregano, cayenne. For a screaming-hot skillet and a fish fillet.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "louisiana", "spicy", "vegetarian", "quick"],
    aliases: ["blackening spice", "cajun seasoning"],
    nutrition: { cal: 10, protein: 0, carbs: 2, fat: 0 },
    ingredients: [
      I("paprika", 3, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("onion powder", 1, "tbsp", "Herbs & Spices"),
      I("dried thyme", 1, "tsp", "Herbs & Spices"),
      I("dried oregano", 1, "tsp", "Herbs & Spices"),
      I("cayenne", 2, "tsp", "Herbs & Spices"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    steps: ["Mix. Dip buttered fish or chicken in the rub. Sear in a nearly smoking skillet."],
  }),
  dish({
    id: "kc-bbq-sauce",
    name: "Kansas City BBQ sauce",
    description: "Tomato, molasses, smoke. Thick enough to cling to burnt ends.",
    minutes: 25,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "kansas", "missouri", "vegetarian"],
    aliases: ["kc sauce", "missouri barbecue sauce", "sweet bbq"],
    nutrition: { cal: 70, protein: 1, carbs: 16, fat: 0 },
    ingredients: [
      I("ketchup", 1.5, "cups", "Pantry"),
      I("molasses", 0.25, "cup", "Pantry"),
      I("brown sugar", 0.25, "cup", "Pantry"),
      I("apple cider vinegar", 0.25, "cup", "Pantry"),
      I("worcestershire", 2, "tbsp", "Pantry"),
      I("smoked paprika", 1, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Simmer everything 15 minutes until glossy. Brush on in the last 10 minutes of cooking."],
  }),
  dish({
    id: "carolina-vinegar-sauce",
    name: "Carolina vinegar sauce",
    description: "Eastern North Carolina: vinegar, pepper, a pinch of sugar. For pulled pork, not ribs.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "north-carolina", "vegetarian", "quick"],
    aliases: ["eastern nc sauce", "vinegar pepper sauce", "whole hog sauce"],
    nutrition: { cal: 15, protein: 0, carbs: 3, fat: 0 },
    ingredients: [
      I("apple cider vinegar", 1.5, "cups", "Pantry"),
      I("red pepper flakes", 2, "tsp", "Herbs & Spices"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
      I("kosher salt", 1, "tsp", "Herbs & Spices"),
      I("brown sugar", 1, "tbsp", "Pantry"),
    ],
    steps: ["Shake in a jar. Pour over chopped pork while it is still hot."],
  }),
  dish({
    id: "alabama-white-sauce",
    name: "Alabama white sauce",
    description: "Mayo, vinegar, black pepper. North Alabama chicken, dunked while it is hot.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "alabama", "vegetarian", "quick"],
    aliases: ["white bbq sauce", "big bob gibson sauce"],
    nutrition: { cal: 90, protein: 0, carbs: 1, fat: 10 },
    ingredients: [
      I("mayonnaise", 1, "cup", "Pantry"),
      I("apple cider vinegar", 0.25, "cup", "Pantry"),
      I("black pepper", 1, "tbsp", "Herbs & Spices"),
      I("lemon juice", 1, "tbsp", "Produce"),
      I("prepared horseradish", 1, "tsp", "Pantry"),
    ],
    steps: ["Whisk. Dunk grilled chicken or drizzle on smoked turkey."],
  }),
  dish({
    id: "chimichurri",
    name: "Chimichurri",
    description: "Parsley, garlic, oregano, oil, vinegar. The steak's best friend from Argentina.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "green",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["argentine chimichurri", "parsley garlic sauce"],
    nutrition: { cal: 80, protein: 1, carbs: 2, fat: 8 },
    ingredients: [
      I("fresh parsley", 1, "bunch", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("dried oregano", 1, "tsp", "Herbs & Spices"),
      I("red wine vinegar", 3, "tbsp", "Pantry"),
      I("olive oil", 0.5, "cup", "Pantry"),
      I("red pepper flakes", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Chop parsley and garlic fine. Stir with oregano, vinegar, oil, chili, and salt. Rest 10 minutes."],
  }),
  dish({
    id: "hollandaise",
    name: "Hollandaise",
    description: "Egg yolks, butter, lemon. For asparagus, eggs Benedict, or a quiet Tuesday fish.",
    minutes: 15,
    servings: 4,
    protein: "eggs",
    plate: "bowl",
    cuisine: "French",
    tags: ["sauce", "quick"],
    aliases: ["benedict sauce", "butter lemon sauce"],
    nutrition: { cal: 180, protein: 3, carbs: 1, fat: 18 },
    ingredients: [
      I("egg yolks", 3, "", "Dairy & Eggs"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("lemon", 1, "", "Produce"),
      I("cayenne", 1, "pinch", "Herbs & Spices"),
    ],
    steps: [
      "Whisk yolks and lemon over barely simmering water until thick.",
      "Stream in warm melted butter. Season with salt and cayenne. Do not scramble.",
    ],
  }),
  dish({
    id: "tzatziki",
    name: "Tzatziki",
    description: "Yogurt, cucumber, garlic, dill. Cold against grilled meat or stuffed in pita.",
    minutes: 15,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Greek",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["cacik", "cucumber yogurt sauce"],
    nutrition: { cal: 60, protein: 4, carbs: 5, fat: 3 },
    ingredients: [
      I("greek yogurt", 2, "cups", "Dairy & Eggs"),
      I("cucumber", 1, "", "Produce"),
      I("garlic", 2, "cloves", "Produce"),
      I("fresh dill", 2, "tbsp", "Produce"),
      I("lemon", 0.5, "", "Produce"),
      I("olive oil", 1, "tbsp", "Pantry"),
    ],
    steps: ["Grate and salt cucumber. Squeeze dry. Stir into yogurt with garlic, dill, lemon, oil."],
  }),
  dish({
    id: "romesco",
    name: "Romesco",
    description: "Roasted peppers, tomato, almond, bread. Spanish sauce for fish, eggs, or a spoon.",
    minutes: 25,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Spanish",
    tags: ["sauce", "vegetarian", "nuts"],
    aliases: ["spanish pepper sauce", "romesco sauce"],
    nutrition: { cal: 140, protein: 4, carbs: 10, fat: 10 },
    ingredients: [
      I("roasted red peppers", 2, "", "Pantry"),
      I("tomato", 1, "", "Produce"),
      I("almonds", 0.5, "cup", "Pantry"),
      I("stale bread", 1, "slice", "Bakery"),
      I("garlic", 2, "cloves", "Produce"),
      I("sherry vinegar", 2, "tbsp", "Pantry"),
      I("olive oil", 0.25, "cup", "Pantry"),
    ],
    steps: ["Blend everything until rustic, not baby food. Salt. Spoon on grilled calçots or any fish."],
  }),
  dish({
    id: "buffalo-sauce",
    name: "Buffalo sauce",
    description: "Hot sauce melted with butter. Buffalo, New York, and every Super Bowl.",
    minutes: 8,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "new-york", "spicy", "vegetarian", "quick"],
    aliases: ["frank's butter", "wing sauce"],
    nutrition: { cal: 90, protein: 0, carbs: 1, fat: 10 },
    ingredients: [
      I("hot sauce", 0.66, "cup", "Pantry"),
      I("butter", 0.33, "cup", "Dairy & Eggs"),
      I("white vinegar", 1, "tsp", "Pantry"),
      I("garlic powder", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Melt butter into hot sauce over low heat. Toss with fried or roasted wings."],
  }),
  dish({
    id: "tartar-sauce",
    name: "Tartar sauce",
    description: "Mayo, pickle, caper, lemon. For fish cakes, haddock, or a Friday fry.",
    minutes: 8,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Newfoundland",
    tags: ["sauce", "atlantic", "vegetarian", "quick"],
    aliases: ["tartare", "fish sauce mayo"],
    nutrition: { cal: 95, protein: 0, carbs: 2, fat: 10 },
    ingredients: [
      I("mayonnaise", 0.75, "cup", "Pantry"),
      I("dill pickle", 2, "", "Pantry"),
      I("capers", 1, "tbsp", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
      I("fresh dill", 1, "tbsp", "Produce"),
    ],
    steps: ["Chop pickle and capers. Stir into mayo with lemon and dill. Chill."],
  }),
  dish({
    id: "alfredo-sauce",
    name: "Alfredo sauce",
    description: "Butter, cream, parmesan. Roman-ish, American-loved, weeknight-ready.",
    minutes: 15,
    servings: 4,
    protein: "veg",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["fettuccine alfredo sauce", "cream parmesan sauce"],
    nutrition: { cal: 280, protein: 8, carbs: 4, fat: 26 },
    ingredients: [
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("heavy cream", 1, "cup", "Dairy & Eggs"),
      I("parmesan", 1.5, "cups", "Dairy & Eggs"),
      I("garlic", 1, "clove", "Produce"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Melt butter with garlic. Add cream. Off heat, melt in parmesan. Toss with pasta water."],
  }),
  dish({
    id: "peanut-sauce",
    name: "Peanut sauce",
    description: "The satay dunk: peanut butter, soy, lime, a little heat.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "nuts", "quick"],
    aliases: ["satay sauce", "gado gado sauce"],
    nutrition: { cal: 140, protein: 6, carbs: 8, fat: 10 },
    ingredients: [
      I("peanut butter", 0.5, "cup", "Pantry"),
      I("soy sauce", 2, "tbsp", "Pantry"),
      I("lime", 1, "", "Produce"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("garlic", 1, "clove", "Produce"),
      I("chili garlic sauce", 1, "tsp", "Pantry"),
      I("warm water", 0.25, "cup", "Other"),
    ],
    steps: ["Whisk everything until pourable. Serve with chicken satay, tofu, or cucumber."],
  }),
  dish({
    id: "sweet-chili-sauce",
    name: "Sweet chili sauce",
    description: "Thai-style: sugar, vinegar, chili, garlic. For spring rolls or a boring chicken breast.",
    minutes: 15,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "spicy", "quick"],
    aliases: ["mae ploy style", "thai sweet chili"],
    nutrition: { cal: 50, protein: 0, carbs: 12, fat: 0 },
    ingredients: [
      I("rice vinegar", 0.5, "cup", "Pantry"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("water", 0.25, "cup", "Other"),
      I("garlic", 3, "cloves", "Produce"),
      I("red pepper flakes", 2, "tsp", "Herbs & Spices"),
      I("cornstarch", 1, "tbsp", "Pantry"),
    ],
    steps: ["Simmer vinegar, sugar, water, garlic, chili. Thicken with cornstarch slurry. Cool."],
  }),
  dish({
    id: "ranch-dressing",
    name: "Ranch dressing",
    description: "Buttermilk, herbs, garlic. Hidden-valley energy, made in a jar.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["homemade ranch", "buttermilk ranch"],
    nutrition: { cal: 80, protein: 1, carbs: 2, fat: 8 },
    ingredients: [
      I("mayonnaise", 0.5, "cup", "Pantry"),
      I("sour cream", 0.5, "cup", "Dairy & Eggs"),
      I("buttermilk", 0.33, "cup", "Dairy & Eggs"),
      I("dried dill", 1, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("onion powder", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Whisk. Chill 20 minutes. For pizza crusts, wings, and people who will not eat a salad without it."],
  }),
  dish({
    id: "teriyaki-sauce",
    name: "Teriyaki sauce",
    description: "Soy, mirin, sugar, ginger. Gloss for salmon, chicken, or a pan of broccoli.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["homemade teriyaki", "soy ginger glaze"],
    nutrition: { cal: 45, protein: 1, carbs: 8, fat: 0 },
    ingredients: [
      I("soy sauce", 0.5, "cup", "Pantry"),
      I("mirin", 0.25, "cup", "Pantry"),
      I("brown sugar", 3, "tbsp", "Pantry"),
      I("fresh ginger", 1, "tbsp", "Produce"),
      I("garlic", 1, "clove", "Produce"),
      I("cornstarch", 1, "tsp", "Pantry"),
    ],
    steps: ["Simmer soy, mirin, sugar, ginger, garlic. Thicken with a splash of cornstarch. Brush and broil."],
  }),
  dish({
    id: "basil-pesto",
    name: "Basil pesto",
    description: "Genoa in a jar: basil, pine nuts, garlic, parmesan, oil. Freeze in ice-cube trays.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Italian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["pesto genovese", "green sauce pasta"],
    nutrition: { cal: 160, protein: 4, carbs: 2, fat: 16 },
    ingredients: [
      I("fresh basil", 2, "bunches", "Produce"),
      I("pine nuts", 0.33, "cup", "Pantry"),
      I("garlic", 2, "cloves", "Produce"),
      I("parmesan", 0.5, "cup", "Dairy & Eggs"),
      I("olive oil", 0.5, "cup", "Pantry"),
    ],
    steps: ["Blitz basil, nuts, garlic, cheese. Stream oil. Salt. Toss with hot pasta or smear on toast."],
  }),
  dish({
    id: "salsa-verde",
    name: "Salsa verde",
    description: "Tomatillo, cilantro, jalapeño, lime. The green that belongs on eggs and pork.",
    minutes: 20,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Mexican",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["tomatillo salsa", "green salsa"],
    nutrition: { cal: 25, protein: 1, carbs: 4, fat: 1 },
    ingredients: [
      I("tomatillos", 1, "lb", "Produce"),
      I("jalapeño", 2, "", "Produce"),
      I("cilantro", 1, "bunch", "Produce"),
      I("onion", 0.5, "", "Produce"),
      I("lime", 1, "", "Produce"),
    ],
    steps: ["Roast tomatillos and jalapeño until blistered. Blend with cilantro, onion, lime, salt."],
  }),
  dish({
    id: "weeknight-mole",
    name: "Weeknight mole",
    description: "Not Oaxaca, not a joke: chile, cocoa, peanut butter, broth. Spoon over chicken.",
    minutes: 25,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Mexican",
    tags: ["sauce", "vegetarian"],
    aliases: ["mole poblano shortcut", "chocolate chile sauce"],
    nutrition: { cal: 90, protein: 3, carbs: 8, fat: 6 },
    ingredients: [
      I("ancho chile", 3, "", "Herbs & Spices"),
      I("cocoa powder", 1, "tbsp", "Pantry"),
      I("peanut butter", 2, "tbsp", "Pantry"),
      I("tomato paste", 1, "tbsp", "Pantry"),
      I("chicken broth", 1.5, "cups", "Pantry"),
      I("cinnamon", 0.25, "tsp", "Herbs & Spices"),
    ],
    steps: ["Soak chiles, blend with cocoa, peanut butter, tomato, broth, cinnamon. Simmer 10 minutes. Salt."],
  }),
  dish({
    id: "peri-peri-sauce",
    name: "Peri-peri sauce",
    description: "African bird's eye heat, lemon, garlic, oil. The chicken shop sauce you can make.",
    minutes: 15,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "African",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["piri piri", "peri peri", "nandos sauce"],
    nutrition: { cal: 40, protein: 1, carbs: 3, fat: 3 },
    ingredients: [
      I("red chiles", 8, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("lemon", 1, "", "Produce"),
      I("smoked paprika", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 3, "tbsp", "Pantry"),
      I("red wine vinegar", 2, "tbsp", "Pantry"),
    ],
    steps: ["Blend everything until smooth. Taste for salt and lemon. Brush on chicken and grill."],
  }),
  dish({
    id: "harissa",
    name: "Harissa",
    description: "Tunisian chile paste: roasted peppers, caraway, cumin, garlic. A spoon wakes a stew.",
    minutes: 25,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian", "spicy"],
    aliases: ["tunisian harissa", "chile paste"],
    nutrition: { cal: 30, protein: 1, carbs: 3, fat: 2 },
    ingredients: [
      I("dried chiles", 8, "", "Herbs & Spices"),
      I("roasted red pepper", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("caraway", 1, "tsp", "Herbs & Spices"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 3, "tbsp", "Pantry"),
    ],
    steps: ["Soak chiles. Blend with pepper, garlic, spices, oil. Salt. Keep under a film of oil."],
  }),
  dish({
    id: "nuoc-cham",
    name: "Nước chấm",
    description: "Vietnamese dipping sauce: fish sauce, lime, sugar, chile, garlic. Spring rolls exist for this.",
    minutes: 8,
    servings: 6,
    protein: "fish",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "quick"],
    aliases: ["nuoc cham", "vietnamese dipping sauce", "fish sauce lime"],
    nutrition: { cal: 20, protein: 1, carbs: 4, fat: 0 },
    ingredients: [
      I("fish sauce", 3, "tbsp", "Pantry"),
      I("lime", 2, "", "Produce"),
      I("sugar", 2, "tbsp", "Pantry"),
      I("garlic", 2, "cloves", "Produce"),
      I("bird chile", 1, "", "Produce"),
      I("water", 0.33, "cup", "Other"),
    ],
    steps: ["Dissolve sugar in warm water. Add fish sauce, lime, minced garlic and chile."],
  }),
  dish({
    id: "yum-yum-sauce",
    name: "Yum yum sauce",
    description: "Hibachi mayo: ketchup, garlic, paprika, a little sugar. Shrimp, fried rice, broccoli.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["white sauce hibachi", "japanese steakhouse sauce"],
    nutrition: { cal: 90, protein: 0, carbs: 3, fat: 9 },
    ingredients: [
      I("mayonnaise", 1, "cup", "Pantry"),
      I("ketchup", 2, "tbsp", "Pantry"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
      I("sugar", 1, "tsp", "Pantry"),
      I("rice vinegar", 1, "tsp", "Pantry"),
    ],
    steps: ["Whisk. Chill. It tastes more like the restaurant after an hour."],
  }),
  dish({
    id: "cocktail-sauce",
    name: "Cocktail sauce",
    description: "Ketchup, horseradish, lemon. Shrimp cocktail and oyster bars.",
    minutes: 5,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["shrimp cocktail sauce", "seafood sauce"],
    nutrition: { cal: 25, protein: 0, carbs: 6, fat: 0 },
    ingredients: [
      I("ketchup", 1, "cup", "Pantry"),
      I("prepared horseradish", 3, "tbsp", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
      I("worcestershire", 1, "tsp", "Pantry"),
    ],
    steps: ["Stir. More horseradish if it does not make your eyes water a little."],
  }),
  dish({
    id: "marinara",
    name: "Marinara",
    description: "Tomato, garlic, olive oil, basil. The weeknight red sauce that is never a jar if you have 20 minutes.",
    minutes: 20,
    servings: 6,
    protein: "veg",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["sunday sauce shortcut", "red sauce"],
    nutrition: { cal: 70, protein: 2, carbs: 8, fat: 4 },
    ingredients: [
      I("crushed tomatoes", 28, "oz", "Pantry"),
      I("garlic", 4, "cloves", "Produce"),
      I("olive oil", 3, "tbsp", "Pantry"),
      I("fresh basil", 8, "leaves", "Produce"),
      I("kosher salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Warm oil and garlic. Add tomatoes and salt. Simmer 15 minutes. Basil at the end."],
  }),
  dish({
    id: "garlic-aioli",
    name: "Garlic aioli",
    description: "Mayo if you are in a hurry, egg and oil if you are not. Fries, fish, sandwiches.",
    minutes: 10,
    servings: 8,
    protein: "eggs",
    plate: "bowl",
    cuisine: "French",
    tags: ["sauce", "quick"],
    aliases: ["aioli", "garlic mayo"],
    nutrition: { cal: 90, protein: 0, carbs: 1, fat: 10 },
    ingredients: [
      I("mayonnaise", 0.75, "cup", "Pantry"),
      I("garlic", 3, "cloves", "Produce"),
      I("lemon", 0.5, "", "Produce"),
      I("olive oil", 1, "tbsp", "Pantry"),
    ],
    steps: ["Mash garlic with salt. Whisk into mayo with lemon and oil."],
  }),
  dish({
    id: "bearnaise",
    name: "Béarnaise",
    description: "Tarragon, shallot, vinegar, egg yolk, butter. Steak's best friend.",
    minutes: 15,
    servings: 4,
    protein: "eggs",
    plate: "bowl",
    cuisine: "French",
    tags: ["sauce"],
    aliases: ["bearnaise", "tarragon butter sauce"],
    nutrition: { cal: 180, protein: 2, carbs: 1, fat: 19 },
    ingredients: [
      I("egg yolks", 3, "", "Dairy & Eggs"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("shallot", 1, "", "Produce"),
      I("tarragon", 2, "tbsp", "Produce"),
      I("white wine vinegar", 2, "tbsp", "Pantry"),
    ],
    steps: ["Reduce vinegar with shallot and tarragon. Whisk yolks over low heat. Stream warm butter. Strain if you want it fancy."],
  }),
  dish({
    id: "poutine-gravy",
    name: "Poutine gravy",
    description: "Brown gravy that stays pourable on fries and cheese curds. Canadian, not optional.",
    minutes: 20,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian"],
    aliases: ["brown gravy", "poutine sauce", "fry gravy"],
    nutrition: { cal: 60, protein: 2, carbs: 6, fat: 3 },
    ingredients: [
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("beef broth", 2, "cups", "Pantry"),
      I("worcestershire", 1, "tsp", "Pantry"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Roux the butter and flour. Whisk in broth. Worcestershire, pepper. Simmer until it coats a spoon."],
  }),
  dish({
    id: "gochujang-glaze",
    name: "Gochujang glaze",
    description: "Korean chile paste, soy, honey, sesame. Wings, tofu, a sheet-pan of broccoli.",
    minutes: 8,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["gochujang sauce", "korean chile glaze"],
    nutrition: { cal: 50, protein: 1, carbs: 9, fat: 1 },
    ingredients: [
      I("gochujang", 3, "tbsp", "Pantry"),
      I("soy sauce", 2, "tbsp", "Pantry"),
      I("honey", 2, "tbsp", "Pantry"),
      I("sesame oil", 1, "tsp", "Pantry"),
      I("garlic", 2, "cloves", "Produce"),
      I("rice vinegar", 1, "tsp", "Pantry"),
    ],
    steps: ["Stir until smooth. Brush on in the last minutes of heat so the honey does not scorch."],
  }),
  dish({
    id: "zhug",
    name: "Zhug",
    description: "Yemeni green heat: cilantro, chile, cumin, cardamom. Falafel's other sauce.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["schug", "skhug", "yemeni hot sauce"],
    nutrition: { cal: 35, protein: 1, carbs: 2, fat: 3 },
    ingredients: [
      I("cilantro", 1, "bunch", "Produce"),
      I("parsley", 0.5, "bunch", "Produce"),
      I("green chiles", 3, "", "Produce"),
      I("garlic", 3, "cloves", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("cardamom", 0.25, "tsp", "Herbs & Spices"),
      I("olive oil", 0.25, "cup", "Pantry"),
    ],
    steps: ["Pulse herbs, chile, garlic, spices. Loosen with oil. Salt. Keep it coarse."],
  }),
  dish({
    id: "toum",
    name: "Toum",
    description: "Lebanese garlic cloud. A lot of garlic, oil, lemon. Shawarma, roast chicken, bread.",
    minutes: 15,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian"],
    aliases: ["lebanese garlic sauce", "garlic whip"],
    nutrition: { cal: 80, protein: 0, carbs: 1, fat: 9 },
    ingredients: [
      I("garlic", 1, "head", "Produce"),
      I("neutral oil", 1.5, "cups", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("ice water", 3, "tbsp", "Other"),
    ],
    steps: ["Blitz peeled garlic with salt. Stream oil and lemon slowly, like mayonnaise, with a splash of ice water when it threatens to break."],
  }),
  dish({
    id: "ponzu",
    name: "Ponzu",
    description: "Soy, citrus, a hint of seaweed if you have it. Dumplings, fish, a cold tofu night.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["ponzu sauce", "citrus soy"],
    nutrition: { cal: 15, protein: 1, carbs: 2, fat: 0 },
    ingredients: [
      I("soy sauce", 0.5, "cup", "Pantry"),
      I("rice vinegar", 2, "tbsp", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("orange", 0.5, "", "Produce"),
      I("mirin", 1, "tbsp", "Pantry"),
    ],
    steps: ["Stir soy, vinegar, citrus, mirin. Rest 10 minutes. Better the next day."],
  }),
  dish({
    id: "muhammara",
    name: "Muhammara",
    description: "Aleppo: roasted red pepper, walnuts, pomegranate molasses. Dip, spread, or a spoon on grilled lamb.",
    minutes: 20,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian"],
    aliases: ["walnut red pepper dip", "aleppo dip"],
    nutrition: { cal: 110, protein: 3, carbs: 8, fat: 8 },
    ingredients: [
      I("roasted red peppers", 2, "", "Produce"),
      I("walnuts", 0.75, "cup", "Pantry"),
      I("pomegranate molasses", 2, "tbsp", "Pantry"),
      I("garlic", 1, "clove", "Produce"),
      I("cumin", 0.5, "tsp", "Herbs & Spices"),
      I("olive oil", 3, "tbsp", "Pantry"),
    ],
    steps: ["Pulse peppers, walnuts, molasses, garlic, cumin. Stream oil. Salt. It should be thick, not a puree."],
  }),
  dish({
    id: "mojo",
    name: "Mojo",
    description: "Cuban citrus-garlic: sour orange if you can, lime and orange if you cannot. Pork's marinade.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Caribbean",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["mojo criollo", "cuban garlic sauce"],
    nutrition: { cal: 45, protein: 1, carbs: 4, fat: 3 },
    ingredients: [
      I("garlic", 8, "cloves", "Produce"),
      I("orange", 2, "", "Produce"),
      I("lime", 2, "", "Produce"),
      I("oregano", 1, "tsp", "Herbs & Spices"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 0.25, "cup", "Pantry"),
    ],
    steps: ["Mash garlic with salt. Whisk in citrus, oregano, cumin, oil. Pour over pork or use as a table sauce."],
  }),
  dish({
    id: "come-back-sauce",
    name: "Come-back sauce",
    description: "Jackson, Mississippi: mayo, chili sauce, lemon, onion, a little Worcestershire. Everything dip.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["comeback sauce", "mississippi come back"],
    nutrition: { cal: 95, protein: 0, carbs: 3, fat: 10 },
    ingredients: [
      I("mayonnaise", 1, "cup", "Pantry"),
      I("chili sauce", 0.25, "cup", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("onion", 2, "tbsp", "Produce"),
      I("worcestershire", 1, "tsp", "Pantry"),
      I("garlic powder", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Grate onion. Whisk everything. Chill. Put it on shrimp, fries, and sandwiches."],
  }),
  dish({
    id: "honey-mustard",
    name: "Honey mustard",
    description: "Dijon, honey, a splash of vinegar. Chicken tenders, pretzels, a grain salad.",
    minutes: 5,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["honey dijon", "pretzel sauce"],
    nutrition: { cal: 45, protein: 0, carbs: 7, fat: 2 },
    ingredients: [
      I("dijon mustard", 0.33, "cup", "Pantry"),
      I("honey", 0.25, "cup", "Pantry"),
      I("mayonnaise", 2, "tbsp", "Pantry"),
      I("apple cider vinegar", 1, "tsp", "Pantry"),
    ],
    steps: ["Stir until glossy. Salt. It should be sharp and sweet, not candy."],
  }),
  dish({
    id: "sweet-sour-sauce",
    name: "Sweet and sour sauce",
    description: "Pineapple, vinegar, ketchup, a pinch of ginger. The takeout red you can make in one pan.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["sweet and sour", "takeout red sauce"],
    nutrition: { cal: 50, protein: 0, carbs: 12, fat: 0 },
    ingredients: [
      I("pineapple juice", 0.5, "cup", "Pantry"),
      I("rice vinegar", 0.25, "cup", "Pantry"),
      I("ketchup", 3, "tbsp", "Pantry"),
      I("brown sugar", 3, "tbsp", "Pantry"),
      I("soy sauce", 1, "tbsp", "Pantry"),
      I("cornstarch", 1, "tbsp", "Pantry"),
    ],
    steps: ["Simmer juice, vinegar, ketchup, sugar, soy. Thicken with cornstarch slurry."],
  }),
  dish({
    id: "zaatar-rub",
    name: "Za'atar rub",
    description: "Thyme, sesame, sumac. Oil a chicken or a tray of pita and dust generously.",
    minutes: 5,
    servings: 12,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["dry-rub", "vegetarian", "quick"],
    aliases: ["zaatar", "zaatar spice"],
    nutrition: { cal: 15, protein: 1, carbs: 1, fat: 1 },
    ingredients: [
      I("dried thyme", 2, "tbsp", "Herbs & Spices"),
      I("sesame seeds", 2, "tbsp", "Pantry"),
      I("sumac", 1, "tbsp", "Herbs & Spices"),
      I("kosher salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Toast sesame. Mix with thyme, sumac, salt. Store dry. Oil the food, then the rub."],
  }),
  dish({
    id: "coffee-cocoa-rub",
    name: "Coffee cocoa rub",
    description: "Espresso, cocoa, brown sugar, chile. Brisket, ribs, a thick steak.",
    minutes: 5,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["dry-rub", "vegetarian", "quick"],
    aliases: ["espresso rub", "coffee chile rub"],
    nutrition: { cal: 12, protein: 0, carbs: 2, fat: 0 },
    ingredients: [
      I("finely ground coffee", 2, "tbsp", "Pantry"),
      I("cocoa powder", 1, "tbsp", "Pantry"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("smoked paprika", 1, "tbsp", "Herbs & Spices"),
      I("kosher salt", 1, "tbsp", "Herbs & Spices"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
    ],
    steps: ["Mix. Pat meat dry. Rub on. Rest 30 minutes or overnight."],
  }),
  dish({
    id: "lemon-pepper-rub",
    name: "Lemon pepper rub",
    description: "Zest, cracked pepper, garlic. Wings, fish, a tray of potatoes.",
    minutes: 8,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["dry-rub", "vegetarian", "quick"],
    aliases: ["lemon pepper", "citrus pepper rub"],
    nutrition: { cal: 8, protein: 0, carbs: 1, fat: 0 },
    ingredients: [
      I("lemons", 2, "", "Produce"),
      I("black pepper", 2, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    steps: ["Zest lemons and dry the zest in a low oven 8 minutes. Mix with pepper, garlic, salt."],
  }),
];
