import { I, dish } from "./catalog-kit";
import type { Protein, Recipe } from "./types";

function place(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Protein,
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  aliases: string[] = [],
  nutrition?: Recipe["nutrition"],
): Recipe {
  return dish({
    id,
    name,
    description,
    minutes,
    protein,
    plate,
    cuisine,
    tags,
    aliases,
    ingredients,
    steps,
    nutrition,
  });
}

export const ATLANTIC_RECIPES: Recipe[] = [
  place(
    "rappie-pie",
    "Rappie pie",
    "Nova Scotia",
    ["atlantic", "nova-scotia", "acadian"],
    "chicken",
    "roast",
    150,
    "Acadian chicken and grated potato casserole from Clare and beyond. Sunday food.",
    [
      I("chicken", 1, "bird", "Meat & Seafood"),
      I("russet potatoes", 8, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("chicken broth", 4, "cups", "Pantry"),
    ],
    [
      "Simmer the chicken with the 2 onions in water until tender, 1 hour. Save the 4 cups of broth. Pull the meat off the bone.",
      "Peel and grate the 8 russet potatoes. Squeeze them in a towel until they are almost dry.",
      "Loosen the potato with the hot broth. Layer potato, chicken, and the 4 tablespoons of butter in a baking dish, ending with potato.",
      "Bake at 400°F until the top is a deep brown crust, 1–1½ hours. Serve hot.",
    ],
    ["rapure", "râpure", "acadian potato pie"],
    { cal: 520, protein: 32, carbs: 48, fat: 22 },
  ),
  place(
    "ns-lobster-roll",
    "Nova Scotia lobster roll",
    "Nova Scotia",
    ["atlantic", "nova-scotia", "seafood"],
    "seafood",
    "toast",
    20,
    "Warm butter or a little mayo, celery if you must, a toasted split-top bun. Do not bury the lobster.",
    [
      I("cooked lobster meat", 1, "lb", "Meat & Seafood"),
      I("split-top buns", 4, "", "Bakery"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("lemon", 1, "", "Produce"),
      I("chives", 1, "tbsp", "Produce"),
    ],
    ["Warm the 1 pound of cooked lobster meat in the 3 tablespoons of butter over low heat 2 minutes. Do not boil it.", "Toast the 4 split-top buns. Fill with lobster.", "Squeeze the lemon over and scatter the 1 tablespoon of chives. Eat outside if you can."],
    ["lobster roll", "south shore lobster roll"],
    { cal: 430, protein: 28, carbs: 28, fat: 22 },
  ),
  place(
    "oatcakes",
    "Cape Breton oatcakes",
    "Nova Scotia",
    ["atlantic", "nova-scotia", "vegetarian", "quick"],
    "veg",
    "toast",
    30,
    "Salty-sweet oat biscuits. Tea, cheddar, or a slice of leftover ham.",
    [
      I("rolled oats", 2, "cups", "Pantry"),
      I("flour", 1, "cup", "Pantry"),
      I("brown sugar", 0.5, "cup", "Pantry"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("kosher salt", 0.75, "tsp", "Herbs & Spices"),
    ],
    ["Heat the oven to 350°F. Rub the ½ cup of butter into the 2 cups of rolled oats, the 1 cup of flour, the ½ cup of brown sugar, and the ¾ teaspoon of kosher salt until the mix looks like damp crumbs.", "Press the mix about ¼ inch thick on a sheet. Cut into squares.", "Bake 18–22 minutes, until the edges bronze. Cool on the sheet so they firm up."],
    ["cape breton oatcakes", "maritime oatcakes"],
    { cal: 210, protein: 4, carbs: 28, fat: 10 },
  ),
  place(
    "chicken-fricot",
    "Chicken fricot",
    "New Brunswick",
    ["atlantic", "new-brunswick", "acadian"],
    "chicken",
    "soup",
    90,
    "Acadian chicken and potato soup with dumplings. The house smells like summer savory.",
    [
      I("chicken thighs", 8, "", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("summer savory", 2, "tsp", "Herbs & Spices"),
      I("flour", 1, "cup", "Pantry"),
      I("baking powder", 1.5, "tsp", "Pantry"),
    ],
    [
      "Brown the 8 chicken thighs in a heavy pot 6 minutes. Cover with water, the 2 chopped onions, the 2 carrots, and the 2 teaspoons of summer savory. Simmer until the chicken is tender, 40 minutes.",
      "Add the 4 diced potatoes. Mix the 1 cup of flour and the 1½ teaspoons of baking powder with enough cold water to make a droppable dumpling dough.",
      "Drop spoonfuls of dough on the simmering soup. Cover the pot 15 minutes — do not lift the lid. Serve hot.",
    ],
    ["fricot", "acadian chicken soup"],
    { cal: 480, protein: 34, carbs: 42, fat: 18 },
  ),
  place(
    "poutine-rapee",
    "Poutine râpée",
    "New Brunswick",
    ["atlantic", "new-brunswick", "acadian"],
    "pork",
    "bowl",
    120,
    "Grated-potato dumplings stuffed with salted pork. Acadian, filling, not Quebec poutine.",
    [
      I("russet potatoes", 6, "", "Produce"),
      I("salt pork", 0.5, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    [
      "Grate 3 of the russet potatoes and squeeze them dry in a towel. Boil and mash the other 3. Mix the grated and mashed potato with the 2 teaspoons of kosher salt.",
      "Cut the ½ pound of salt pork into small cubes. With wet hands, wrap a ball of potato around each cube.",
      "Simmer the dumplings in salted water until they float and the centers are hot, 30–40 minutes. Serve with butter and pepper.",
    ],
    ["poutine rapee", "acadian potato dumpling"],
    { cal: 510, protein: 18, carbs: 52, fat: 26 },
  ),
  place(
    "ployes",
    "Ployes",
    "New Brunswick",
    ["atlantic", "new-brunswick", "acadian", "vegetarian", "quick"],
    "veg",
    "toast",
    25,
    "Buckwheat pancakes from the Madawaska. No flip — cook one side, eat with butter or creton.",
    [
      I("buckwheat flour", 1, "cup", "Pantry"),
      I("all-purpose flour", 0.5, "cup", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("water", 1.5, "cups", "Other"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    [
      "Whisk the 1 cup of buckwheat flour, the ½ cup of all-purpose flour, and the 2 teaspoons of baking powder with the 1½ cups of water to a pourable batter. Rest 5 minutes.",
      "Heat a dry skillet over medium. Pour a thin round. Cook until the top is set with holes, 2–3 minutes. Do not flip.",
      "Slide onto a plate. Butter with the 2 tablespoons of butter while hot. Eat as they come.",
    ],
    ["ployes pancakes", "buckwheat ployes"],
    { cal: 240, protein: 6, carbs: 40, fat: 6 },
  ),
  place(
    "fiddlehead-saute",
    "Fiddleheads with garlic",
    "New Brunswick",
    ["atlantic", "new-brunswick", "vegetarian", "quick"],
    "veg",
    "green",
    20,
    "Spring on the St. John River. Boil first, then butter and garlic. Do not eat them raw.",
    [
      I("fiddleheads", 1, "lb", "Produce"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
      I("garlic", 2, "cloves", "Produce"),
      I("lemon", 0.5, "", "Produce"),
    ],
    ["Rinse the 1 pound of fiddleheads well and trim brown ends. Boil in salted water 10 minutes. Drain.", "Melt the 2 tablespoons of butter in a skillet. Add the 2 minced garlic cloves and cook 30 seconds.", "Add the fiddleheads and sauté 2 minutes. Squeeze the lemon over. Serve hot. Do not eat them raw."],
    ["fiddlehead greens", "ostrich fern"],
    { cal: 140, protein: 5, carbs: 10, fat: 9 },
  ),
  place(
    "pei-potato-scallop",
    "PEI scalloped potatoes",
    "Prince Edward Island",
    ["atlantic", "pei", "vegetarian"],
    "veg",
    "roast",
    70,
    "The island grows the potatoes. You supply cream, onion, and patience.",
    [
      I("PEI potatoes", 3, "lb", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cream", 1.5, "cups", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    [
      "Heat the oven to 350°F. Slice the 3 pounds of PEI potatoes thin. Slice the onion.",
      "Layer potatoes and onion in a buttered dish, salting each layer. Pour over the 1½ cups of cream and dot with the 3 tablespoons of butter.",
      "Bake covered 45 minutes, then uncovered 15 minutes, until a knife slides through.",
      "Scatter the 1 cup of cheddar on top and bake 5 minutes more, until melted. Serve hot.",
    ],
    ["scalloped potatoes", "pei potato bake"],
    { cal: 420, protein: 12, carbs: 48, fat: 20 },
  ),
  place(
    "malpeque-mussels",
    "Malpeque mussels",
    "Prince Edward Island",
    ["atlantic", "pei", "seafood", "quick"],
    "seafood",
    "bowl",
    20,
    "PEI mussels, white wine, garlic, cream if you want to be fancy. Bread for the broth.",
    [
      I("mussels", 3, "lb", "Meat & Seafood"),
      I("garlic", 4, "cloves", "Produce"),
      I("shallot", 1, "", "Produce"),
      I("white wine", 0.75, "cup", "Pantry"),
      I("cream", 0.25, "cup", "Dairy & Eggs"),
      I("parsley", 0.25, "cup", "Produce"),
      I("crusty bread", 1, "loaf", "Bakery"),
    ],
    [
      "Scrub the 3 pounds of mussels and pull the beards. Discard any that stay open when tapped.",
      "Cook the 4 minced garlic cloves and the chopped shallot in a wide pot 1 minute. Pour in the ¾ cup of white wine.",
      "Add the mussels. Cover and cook 5–7 minutes, until they open. Discard any that stay shut.",
      "Stir in the ¼ cup of cream and the ¼ cup of parsley. Serve with the crusty bread for the broth.",
    ],
    ["pei mussels", "steamed mussels"],
    { cal: 380, protein: 32, carbs: 22, fat: 14 },
  ),
  place(
    "pei-lobster-supper",
    "PEI lobster supper",
    "Prince Edward Island",
    ["atlantic", "pei", "seafood"],
    "seafood",
    "fish",
    45,
    "Church-basement energy: boiled lobster, potato salad, rolls, a slice of pie later.",
    [
      I("live lobsters", 4, "", "Meat & Seafood"),
      I("potato", 6, "", "Produce"),
      I("mayonnaise", 0.5, "cup", "Pantry"),
      I("celery", 2, "stalks", "Produce"),
      I("dinner rolls", 8, "", "Bakery"),
      I("butter", 0.25, "cup", "Dairy & Eggs"),
    ],
    ["Boil the 6 potatoes until tender, 15 minutes. Cool, dice, and fold with the ½ cup of mayonnaise and the chopped celery. Salt.", "Bring a large pot of heavily salted water to a rolling boil. Add the 4 lobsters, head first. Boil 12 minutes for 1¼-pound lobsters, 15 minutes if they are larger. Drain.", "Warm the 8 dinner rolls with the ¼ cup of butter.", "Crack the lobsters at the table. Serve with the potato salad, rolls, and bibs."],
    ["church lobster supper", "new glasgow lobster"],
    { cal: 620, protein: 42, carbs: 40, fat: 28 },
  ),
];

const USA: Recipe[] = [
  place("al-white-bbq-chicken", "Alabama white BBQ chicken", "American", ["alabama", "usa"], "chicken", "skillet", 45, "Grilled chicken dunked in mayo-vinegar white sauce. North Alabama on a plate.", [I("chicken pieces", 8, "", "Meat & Seafood"), I("mayonnaise", 1, "cup", "Pantry"), I("apple cider vinegar", 0.25, "cup", "Pantry"), I("black pepper", 1, "tbsp", "Herbs & Spices"), I("kosher salt", 2, "tsp", "Herbs & Spices")], ["Pat the 8 chicken pieces dry and season with the 2 teaspoons of kosher salt.", "Grill or roast at 425°F, turning once, until the thickest piece is 165°F, 25–35 minutes.", "Whisk the 1 cup of mayonnaise with the ¼ cup of apple cider vinegar and the 1 tablespoon of black pepper until pourable.", "Dunk the hot chicken in the white sauce, or spoon it over both sides. Serve extra sauce at the table."], ["white sauce chicken"], { cal: 520, protein: 38, carbs: 2, fat: 40 }),
  place("ak-salmon-chowder", "Alaska salmon chowder", "American", ["alaska", "usa"], "fish", "soup", 40, "Salmon, potato, dill, a little cream. The Last Frontier in a bowl.", [I("salmon", 1, "lb", "Meat & Seafood"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("milk", 2, "cups", "Dairy & Eggs"), I("dill", 2, "tbsp", "Produce"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Melt the 2 tablespoons of butter in a heavy pot over medium heat. Add the chopped onion and cook 4 minutes, until soft.", "Add the 3 diced potatoes and water to cover by an inch. Simmer until the potatoes are tender, 12–15 minutes.", "Cut the 1 pound of salmon into chunks. Add the salmon and the 2 cups of milk. Cook at a bare simmer 5 minutes, until the fish flakes. Do not boil hard.", "Stir in the 2 tablespoons of dill. Taste for salt. Serve hot."], ["alaskan salmon soup"], { cal: 410, protein: 32, carbs: 28, fat: 18 }),
  place("az-navajo-tacos", "Arizona Navajo tacos", "American", ["arizona", "usa"], "beef", "taco", 40, "Fry bread piled with chili, lettuce, cheese, and tomato.", [I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("warm water", 0.75, "cup", "Other"), I("ground beef", 1, "lb", "Meat & Seafood"), I("chili powder", 2, "tbsp", "Herbs & Spices"), I("cheddar", 1, "cup", "Dairy & Eggs"), I("lettuce", 0.5, "head", "Produce"), I("neutral oil", 2, "cups", "Pantry")], ["Stir the 2 cups of flour, the 2 teaspoons of baking powder, and a pinch of salt with the ¾ cup of warm water to a soft dough. Rest 10 minutes. Pat into 6-inch rounds.", "Heat ½ inch of the oil in a skillet to 350°F. Fry each round 1–2 minutes a side, until puffed and gold. Drain on paper.", "Brown the 1 pound of ground beef with the 2 tablespoons of chili powder, 8 minutes, until no pink remains.", "Pile the beef on the fry bread. Top with the 1 cup of cheddar and the shredded lettuce. Serve hot."], ["indian taco", "fry bread taco"], { cal: 640, protein: 32, carbs: 52, fat: 32 }),
  place("ar-fried-catfish", "Arkansas fried catfish", "American", ["arkansas", "usa"], "fish", "fish", 30, "Cornmeal crust, hot oil, lemon. A Friday night on the river.", [I("catfish fillets", 4, "", "Meat & Seafood"), I("cornmeal", 1, "cup", "Pantry"), I("cayenne", 1, "tsp", "Herbs & Spices"), I("oil", 2, "cups", "Pantry"), I("lemon", 1, "", "Produce"), I("kosher salt", 1, "tsp", "Herbs & Spices")], ["Pat the 4 catfish fillets dry. Season with the 1 teaspoon of kosher salt.", "Mix the 1 cup of cornmeal with the 1 teaspoon of cayenne. Dredge each fillet so the cornmeal sticks on all sides.", "Heat the 2 cups of oil in a deep skillet to 350°F. Fry the fillets 3–4 minutes a side, until the crust is gold and the fish flakes.", "Drain on a rack. Squeeze the lemon over. Serve hot."], ["southern catfish"], { cal: 480, protein: 28, carbs: 22, fat: 30 }),
  place("ca-fish-tacos", "California fish tacos", "American", ["california", "usa"], "fish", "taco", 30, "Baja energy: fried or grilled fish, cabbage, crema, lime.", [I("white fish", 1, "lb", "Meat & Seafood"), I("corn tortillas", 8, "", "Bakery"), I("cabbage", 0.25, "head", "Produce"), I("sour cream", 0.5, "cup", "Dairy & Eggs"), I("lime", 2, "", "Produce"), I("olive oil", 2, "tbsp", "Pantry")], ["Pat the 1 pound of white fish dry. Rub with 1 tablespoon of the olive oil, salt, and the juice of 1 lime.", "Cook the fish in a hot skillet 3–4 minutes a side, until it flakes. Break into large pieces.", "Warm the 8 corn tortillas in a dry pan until they flex, 20 seconds a side.", "Shred the cabbage. Stir the ½ cup of sour cream with the juice of the second lime. Fill tortillas with fish, cabbage, and crema. Serve at once."], ["baja fish tacos"], { cal: 420, protein: 28, carbs: 36, fat: 16 }),
  place("co-green-chile-stew", "Colorado green chile stew", "American", ["colorado", "usa"], "pork", "soup", 80, "Pork, roasted Hatch-style chiles, potato. The mountain bowl.", [I("pork shoulder", 1.5, "lb", "Meat & Seafood"), I("green chiles", 8, "", "Produce"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("cumin", 1, "tsp", "Herbs & Spices")], ["Cut the 1½ pounds of pork shoulder into cubes. Brown in a heavy pot over medium-high heat 8 minutes.", "Add the chopped onion and the 8 chopped roasted green chiles. Cook 4 minutes. Stir in the 1 teaspoon of cumin.", "Add the 3 diced potatoes and water to cover. Simmer until the pork is tender, 50–60 minutes. Taste for salt. Serve hot."], ["hatch green chile stew"], { cal: 490, protein: 36, carbs: 28, fat: 24 }),
  place("ct-white-clam-pizza", "Connecticut white clam pizza", "American", ["connecticut", "usa"], "seafood", "toast", 25, "New Haven: clam, garlic, oil, oregano. No mozzarella required.", [I("pizza dough", 1, "lb", "Bakery"), I("chopped clams", 1, "cup", "Meat & Seafood"), I("garlic", 4, "cloves", "Produce"), I("olive oil", 3, "tbsp", "Pantry"), I("oregano", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 500°F with a sheet or stone inside.", "Stretch the 1 pound of pizza dough thin on a floured peel or parchment.", "Scatter the 1 cup of chopped clams, the 4 minced garlic cloves, the 3 tablespoons of olive oil, and the 1 teaspoon of oregano over the dough.", "Bake 8–10 minutes, until the edges are blistered and gold. Cut and serve hot."], ["new haven clam pie"], { cal: 520, protein: 24, carbs: 60, fat: 18 }),
  place("de-scrapple-breakfast", "Delaware scrapple breakfast", "American", ["delaware", "usa"], "pork", "skillet", 20, "Sliced scrapple, fried crisp, eggs on the side.", [I("scrapple", 8, "oz", "Meat & Seafood"), I("eggs", 4, "", "Dairy & Eggs"), I("butter", 1, "tbsp", "Dairy & Eggs")], ["Slice the 8 ounces of scrapple ½ inch thick.", "Melt the 1 tablespoon of butter in a skillet over medium heat. Fry the scrapple 4–5 minutes a side, until the crust is brown and crisp. Move to plates.", "Fry the 4 eggs in the same pan, 2–3 minutes, until the whites are set. Serve with the scrapple."], ["mid-atlantic scrapple"], { cal: 480, protein: 28, carbs: 18, fat: 32 }),
  place("fl-key-lime-shrimp", "Florida key lime shrimp", "American", ["florida", "usa"], "seafood", "skillet", 20, "Shrimp, key lime, garlic, butter. Eat with the windows open.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("key limes", 4, "", "Produce"), I("garlic", 3, "cloves", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs")], ["Pat the 1½ pounds of shrimp dry. Season with salt.", "Melt the 3 tablespoons of butter in a skillet over medium heat. Add the 3 minced garlic cloves and cook 30 seconds, until fragrant.", "Add the shrimp. Cook 2 minutes a side, until just pink.", "Squeeze the 4 key limes over the pan. Toss and serve at once."], ["key west shrimp"], { cal: 310, protein: 36, carbs: 4, fat: 16 }),
  place("ga-peach-chicken", "Georgia peach skillet chicken", "American", ["georgia", "usa"], "chicken", "skillet", 35, "Chicken thighs, ripe peaches, a little vinegar and thyme.", [I("chicken thighs", 6, "", "Meat & Seafood"), I("peaches", 3, "", "Produce"), I("apple cider vinegar", 2, "tbsp", "Pantry"), I("thyme", 4, "sprigs", "Produce")], ["Heat the oven to 400°F. Pat the 6 chicken thighs dry and salt both sides.", "Brown the thighs skin-side down in an oven-safe skillet 6–8 minutes, until the skin is gold. Turn.", "Tuck in the 3 peaches, cut into wedges, with the 2 tablespoons of apple cider vinegar and the 4 thyme sprigs.", "Roast 18–20 minutes, until the thighs are 165°F and the peaches are sticky. Serve hot."], ["peach chicken"], { cal: 440, protein: 34, carbs: 18, fat: 24 }),
  place("hi-loco-moco", "Hawaii loco moco", "American", ["hawaii", "usa"], "beef", "bowl", 25, "Rice, burger, fried egg, brown gravy. A plate lunch that is also breakfast.", [I("ground beef", 1, "lb", "Meat & Seafood"), I("cooked rice", 4, "cups", "Pantry"), I("eggs", 4, "", "Dairy & Eggs"), I("onion", 1, "", "Produce"), I("beef broth", 1.5, "cups", "Pantry"), I("flour", 1, "tbsp", "Pantry")], ["Shape the 1 pound of ground beef into 4 patties. Salt both sides. Sear in a skillet over medium-high heat 3–4 minutes a side, until browned. Move to a plate.", "Add the chopped onion to the drippings and cook 3 minutes. Sprinkle the 1 tablespoon of flour, then pour in the 1½ cups of beef broth. Simmer 3–4 minutes, until the gravy thickens.", "Fry the 4 eggs until the whites are set and the yolks are still runny, 2–3 minutes.", "Spoon the 4 cups of cooked rice onto plates. Set a patty on the rice, an egg on the patty, and the onion gravy over everything. Serve hot."], ["loco moco"], { cal: 720, protein: 38, carbs: 62, fat: 34 }),
  place("id-finger-steaks", "Idaho finger steaks", "American", ["idaho", "usa"], "beef", "skillet", 30, "Strips of steak, battered, fried. Fry sauce on the side, potatoes of course.", [I("sirloin", 1.5, "lb", "Meat & Seafood"), I("flour", 1, "cup", "Pantry"), I("buttermilk", 1, "cup", "Dairy & Eggs"), I("russet potatoes", 4, "", "Produce"), I("neutral oil", 2, "cups", "Pantry"), I("kosher salt", 1, "tsp", "Herbs & Spices")], ["Cut the 4 russet potatoes into wedges. Toss with 2 tablespoons of the oil and salt. Roast at 425°F for 25 minutes, until gold.", "Cut the 1½ pounds of sirloin into finger-width strips. Season with the 1 teaspoon of kosher salt.", "Dip the strips in the 1 cup of buttermilk, then the 1 cup of flour, shaking off extra.", "Heat the rest of the oil to 350°F. Fry the strips 2–3 minutes, until the crust is gold. Drain. Serve with the potatoes."], ["boise finger steaks"], { cal: 680, protein: 40, carbs: 42, fat: 36 }),
  place("il-italian-beef", "Illinois Italian beef", "American", ["illinois", "usa"], "beef", "toast", 180, "Chicago: thin beef, giardiniera, a roll dunked in jus.", [I("beef roast", 3, "lb", "Meat & Seafood"), I("giardiniera", 1, "cup", "Pantry"), I("italian rolls", 6, "", "Bakery"), I("garlic", 6, "cloves", "Produce"), I("oregano", 1, "tbsp", "Herbs & Spices"), I("beef broth", 2, "cups", "Pantry")], ["Heat the oven to 300°F. Rub the 3-pound beef roast with the 6 cloves of garlic, smashed, the 1 tablespoon of oregano, and salt.", "Set the roast in a pan with the 2 cups of beef broth. Cover and roast 3 hours, until the beef pulls apart easily.", "Rest 15 minutes. Slice the beef as thin as you can. Return the slices to the warm jus.", "Split the 6 italian rolls. Pile on the beef, spoon jus over so the bread soaks, and top with the 1 cup of giardiniera. Serve hot."], ["chicago italian beef"], { cal: 610, protein: 42, carbs: 44, fat: 26 }),
  place("in-pork-tenderloin", "Indiana pork tenderloin sandwich", "American", ["indiana", "usa"], "pork", "toast", 30, "A pounded cutlet bigger than the bun. Pickles, mustard, onion.", [I("pork loin", 1, "lb", "Meat & Seafood"), I("breadcrumbs", 1.5, "cups", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("buns", 4, "", "Bakery"), I("dill pickle", 4, "", "Pantry"), I("mustard", 2, "tbsp", "Pantry"), I("neutral oil", 1, "cup", "Pantry")], ["Slice the 1 pound of pork loin into 4 pieces. Pound each piece between parchment until it is about ¼ inch thick and wider than the bun. Salt both sides.", "Beat the 2 eggs in a dish. Put the 1½ cups of breadcrumbs in another. Dip each cutlet in egg, then breadcrumbs, pressing the crumbs on.", "Heat ½ inch of the oil in a wide skillet to 350°F. Fry each cutlet 2–3 minutes a side, until gold. Drain on a rack.", "Toast the 4 buns. Spread with the 2 tablespoons of mustard, add a cutlet and pickle slices. Serve hot."], ["hoosier tenderloin"], { cal: 640, protein: 36, carbs: 48, fat: 32 }),
  place("ia-loose-meat", "Iowa loose-meat sandwich", "American", ["iowa", "usa"], "beef", "toast", 25, "Maid-Rite energy: seasoned crumbled beef, mustard, pickle, a steamed bun.", [I("ground beef", 1.5, "lb", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("buns", 6, "", "Bakery"), I("mustard", 3, "tbsp", "Pantry"), I("dill pickle", 6, "", "Pantry"), I("water", 0.5, "cup", "Other")], ["Crumble the 1½ pounds of ground beef into a skillet with the chopped onion. Add the ½ cup of water.", "Simmer over medium heat, stirring, until the beef is cooked and loose, 10–12 minutes. Salt and pepper. The mix should be wet, not a patty.", "Steam or warm the 6 buns. Pile the beef on, then mustard and pickle. Serve at once."], ["maid-rite", "tavern sandwich"], { cal: 480, protein: 32, carbs: 32, fat: 24 }),
  place("ks-burnt-ends", "Kansas burnt ends", "American", ["kansas", "usa"], "beef", "bowl", 240, "Brisket point cubed, sauced, and caramelized. Kansas City via the smoker — oven works too.", [I("beef brisket point", 3, "lb", "Meat & Seafood"), I("kosher salt", 2, "tbsp", "Herbs & Spices"), I("black pepper", 2, "tbsp", "Herbs & Spices"), I("bbq sauce", 1, "cup", "Pantry")], ["Rub the 3-pound brisket point with the 2 tablespoons of kosher salt and the 2 tablespoons of black pepper.", "Roast at 275°F until a probe slides in with little resistance, about 3½–4 hours. Rest 20 minutes.", "Cube the point. Toss with the 1 cup of BBQ sauce. Return to a 400°F oven 20–25 minutes, until the edges are sticky and caramelized.", "Serve hot, with extra sauce on the side."], ["kc burnt ends"], { cal: 620, protein: 44, carbs: 14, fat: 40 }),
  place("ky-hot-brown", "Kentucky Hot Brown", "American", ["kentucky", "usa"], "turkey", "toast", 25, "Open-face turkey, Mornay, bacon, tomato. Louisville after the races.", [I("turkey slices", 12, "oz", "Meat & Seafood"), I("white bread", 4, "slices", "Bakery"), I("parmesan", 0.5, "cup", "Dairy & Eggs"), I("milk", 1.5, "cups", "Dairy & Eggs"), I("bacon", 8, "slices", "Meat & Seafood"), I("tomato", 2, "", "Produce")], ["Heat the broiler. Toast the white bread on both sides until gold, about 2 minutes a side.", "Cook the bacon in a skillet over medium heat for 6–8 minutes, until crisp. Drain on paper.", "Warm the milk in a saucepan over medium-low. Stir in the parmesan until the sauce coats a spoon, 3–4 minutes. Salt and pepper.", "Set the toast on an oven-safe plate. Lay the turkey slices on the toast. Pour the sauce over the turkey.", "Broil 2–3 minutes, until the sauce is bubbling. Cross the bacon on top and add tomato slices. Serve hot."], ["hot brown"], { cal: 690, protein: 42, carbs: 36, fat: 40 }),
  place("la-red-beans-rice", "Louisiana red beans and rice", "American", ["louisiana", "usa"], "pork", "bowl", 150, "Monday pot: red beans, andouille, rice. The laundry-day classic.", [I("red beans", 1, "lb", "Pantry"), I("andouille", 12, "oz", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("green pepper", 1, "", "Produce"), I("rice", 2, "cups", "Pantry"), I("water", 8, "cups", "Other")], ["Soak the 1 pound of red beans in water overnight, then drain. (Or cover with water, boil 2 minutes, and soak 1 hour.)", "Slice the 12 ounces of andouille. Cook in a heavy pot 4 minutes. Add the chopped onion, celery, and green pepper. Cook 6 minutes, until soft.", "Add the beans and the 8 cups of water. Simmer uncovered until the beans are creamy, 1½–2 hours, stirring so the bottom does not catch. Mash a few beans against the pot to thicken. Salt to taste.", "Cook the 2 cups of rice. Spoon beans over the rice. Serve hot."], ["red beans"], { cal: 560, protein: 28, carbs: 68, fat: 18 }),
  place("me-lobster-roll", "Maine lobster roll", "American", ["maine", "usa"], "seafood", "toast", 20, "Cold mayo or warm butter, both legal. A split-top bun, toasted.", [I("cooked lobster meat", 1, "lb", "Meat & Seafood"), I("mayonnaise", 3, "tbsp", "Pantry"), I("split-top buns", 4, "", "Bakery"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce")], ["Pick over the 1 pound of cooked lobster meat and cut any large pieces so they fit the bun.", "Fold the lobster with the 3 tablespoons of mayonnaise, a pinch of salt, and a squeeze of the lemon. Keep it cold.", "Butter the 4 split-top buns with the 2 tablespoons of butter. Toast them cut-side down 1–2 minutes, until gold.", "Fill each bun with lobster. Do not overpack. Squeeze the rest of the lemon over. Eat right away so the bun stays crisp."], ["maine roll"], { cal: 440, protein: 28, carbs: 28, fat: 24 }),
  place("md-crab-cakes", "Maryland crab cakes", "American", ["maryland", "usa"], "seafood", "skillet", 25, "Mostly crab, barely any filler, Old Bay, a hot pan.", [I("lump crab", 1, "lb", "Meat & Seafood"), I("mayonnaise", 3, "tbsp", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("Old Bay", 2, "tsp", "Herbs & Spices"), I("saltines", 8, "", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Crush the 8 saltines into coarse crumbs. Pick over the 1 pound of lump crab for shell.", "Fold the crab gently with the 3 tablespoons of mayonnaise, the egg, the 2 teaspoons of Old Bay, and the crumbs. Do not mash the lumps.", "Shape 8 cakes. Chill 15 minutes so they hold.", "Melt the 2 tablespoons of butter in a skillet over medium heat. Cook the cakes 3–4 minutes a side, until the crust is bronze. Serve hot."], ["old bay crab cakes"], { cal: 320, protein: 28, carbs: 8, fat: 18 }),
  place("ma-clam-chowder", "Massachusetts clam chowder", "American", ["massachusetts", "usa"], "seafood", "soup", 40, "New England: clams, potato, cream. Oyster crackers. No tomato in this house.", [I("chopped clams", 2, "cups", "Meat & Seafood"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("cream", 1, "cup", "Dairy & Eggs"), I("salt pork", 2, "oz", "Meat & Seafood")], ["Dice the 2 ounces of salt pork. Render in a heavy pot over medium heat 5 minutes, until the fat runs and the bits are gold.", "Add the chopped onion and cook 4 minutes. Add the 3 diced potatoes and the clam liquor (or water to cover). Simmer until the potatoes are tender, 12–15 minutes.", "Stir in the 2 cups of chopped clams and the 1 cup of cream. Heat through 3 minutes. Do not boil.", "Taste for salt. Serve hot, with crackers if you have them."], ["new england clam chowder"], { cal: 420, protein: 22, carbs: 28, fat: 24 }),
  place("mi-pasty", "Michigan pasty", "American", ["michigan", "usa"], "beef", "roast", 70, "Upper Peninsula miner food: beef, potato, rutabaga, crust you can hold.", [I("pie dough", 2, "rounds", "Bakery"), I("beef stew meat", 1, "lb", "Meat & Seafood"), I("potato", 2, "", "Produce"), I("rutabaga", 1, "", "Produce"), I("onion", 1, "", "Produce")], ["Heat the oven to 375°F. Dice the 1 pound of beef stew meat, the 2 potatoes, the rutabaga, and the onion. Salt and pepper the filling.", "Roll each pie dough round. Pile filling on one half. Fold over and crimp the edge so it is sealed. Cut 2 steam slits.", "Bake 50–55 minutes, until the crust is gold and the filling is hot.", "Rest 5 minutes. Serve with ketchup or gravy, depending on which side of the argument you are on."], ["up pasty", "cornish pasty michigan"], { cal: 640, protein: 28, carbs: 52, fat: 34 }),
  place("mn-wild-rice-soup", "Minnesota wild rice soup", "American", ["minnesota", "usa"], "chicken", "soup", 50, "Creamy wild rice, chicken, mushrooms. Cabin food.", [I("wild rice", 1, "cup", "Pantry"), I("chicken", 2, "cups", "Meat & Seafood"), I("mushrooms", 8, "oz", "Produce"), I("cream", 1, "cup", "Dairy & Eggs"), I("celery", 2, "stalks", "Produce"), I("chicken broth", 6, "cups", "Pantry"), I("onion", 1, "", "Produce")], ["Simmer the 1 cup of wild rice in salted water until the grains split, 40 minutes. Drain.", "In a pot, cook the chopped onion, celery, and the 8 ounces of sliced mushrooms in a little butter 6 minutes.", "Add the 6 cups of chicken broth, the cooked rice, and the 2 cups of shredded chicken. Simmer 10 minutes.", "Stir in the 1 cup of cream. Heat through. Taste for salt. Serve hot."], ["minnesota soup"], { cal: 430, protein: 26, carbs: 36, fat: 20 }),
  place("ms-come-back-shrimp", "Mississippi comeback shrimp", "American", ["mississippi", "usa"], "seafood", "skillet", 20, "Shrimp with Jackson comeback sauce — mayo, chili, lemon, garlic.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("mayonnaise", 0.5, "cup", "Pantry"), I("chili sauce", 3, "tbsp", "Pantry"), I("lemon", 1, "", "Produce"), I("garlic", 2, "cloves", "Produce"), I("butter", 1, "tbsp", "Dairy & Eggs")], ["Whisk the ½ cup of mayonnaise with the 3 tablespoons of chili sauce, the juice of the lemon, and the 2 minced garlic cloves.", "Pat the 1½ pounds of shrimp dry. Melt the 1 tablespoon of butter in a skillet over medium-high heat.", "Cook the shrimp 2 minutes a side, until just pink.", "Toss with enough comeback sauce to coat, or serve the sauce for dunking. Serve hot."], ["come back sauce shrimp"], { cal: 360, protein: 32, carbs: 8, fat: 22 }),
  place("mo-toasted-ravioli", "Missouri toasted ravioli", "American", ["missouri", "usa"], "beef", "bowl", 30, "St. Louis: breaded ravioli, fried, marinara, parmesan.", [I("meat ravioli", 1, "lb", "Frozen"), I("breadcrumbs", 1, "cup", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("marinara", 1.5, "cups", "Pantry"), I("parmesan", 0.5, "cup", "Dairy & Eggs"), I("neutral oil", 2, "cups", "Pantry")], ["Thaw the 1 pound of meat ravioli. Beat the 2 eggs. Dip each ravioli in egg, then the 1 cup of breadcrumbs.", "Heat the oil to 350°F. Fry the ravioli in batches 2–3 minutes, until gold. Drain on a rack.", "Warm the 1½ cups of marinara.", "Pile the ravioli, spoon marinara over, and scatter the ½ cup of parmesan. Serve hot."], ["t-ravs", "st louis ravioli"], { cal: 540, protein: 22, carbs: 52, fat: 26 }),
  place("mt-bison-skillet", "Montana bison skillet", "American", ["montana", "usa"], "beef", "skillet", 35, "Bison or beef, mushrooms, whiskey-ish pan sauce, mashed potatoes.", [I("bison or beef steak", 1.5, "lb", "Meat & Seafood"), I("mushrooms", 8, "oz", "Produce"), I("onion", 1, "", "Produce"), I("beef broth", 0.75, "cup", "Pantry"), I("potato", 4, "", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs")], ["Peel the 4 potatoes, boil until tender, 15 minutes. Mash with 2 tablespoons of the butter. Keep warm.", "Pat the 1½ pounds of steak dry. Sear in a skillet over high heat 3 minutes a side for medium-rare. Rest on a plate.", "Add the remaining butter, the sliced mushrooms, and the chopped onion. Cook 5 minutes. Pour in the ¾ cup of beef broth and simmer 2 minutes.", "Slice the steak. Serve over the mash with the mushroom pan sauce."], ["montana steak skillet"], { cal: 560, protein: 42, carbs: 32, fat: 26 }),
  place("ne-runza", "Nebraska runza", "American", ["nebraska", "usa"], "beef", "toast", 50, "Yeast bun stuffed with beef, cabbage, onion. Road-trip food.", [I("bread dough", 1.5, "lb", "Bakery"), I("ground beef", 1, "lb", "Meat & Seafood"), I("cabbage", 0.5, "head", "Produce"), I("onion", 1, "", "Produce")], ["Brown the 1 pound of ground beef with the chopped onion, 8 minutes. Stir in the shredded cabbage and cook until wilted, 6 minutes. Salt. Cool 10 minutes.", "Heat the oven to 375°F. Divide the 1½ pounds of bread dough into 8 pieces. Flatten each, pile on filling, and pinch the dough closed.", "Set seam-side down on a sheet. Bake 20–25 minutes, until the buns are brown.", "Rest 5 minutes so the filling is not molten. Serve warm."], ["bierock", "runza sandwich"], { cal: 520, protein: 28, carbs: 48, fat: 22 }),
  place("nv-cowboy-ribeye", "Nevada cowboy ribeye", "American", ["nevada", "usa"], "beef", "skillet", 30, "A thick ribeye, salt, pepper, a screaming pan. Steakhouse desert energy.", [I("ribeye steaks", 2, "", "Meat & Seafood"), I("kosher salt", 2, "tsp", "Herbs & Spices"), I("black pepper", 2, "tsp", "Herbs & Spices"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Pat the 2 ribeye steaks dry. Season all over with the 2 teaspoons of kosher salt and the 2 teaspoons of black pepper. Rest 20 minutes at room temperature.", "Heat a heavy skillet until it smokes. Sear the steaks 3–4 minutes a side for medium-rare (125°F in the center for a thick steak).", "Add the 2 tablespoons of butter. Tilt the pan and baste the steaks 1 minute.", "Rest 8 minutes. Slice across the grain. Serve hot."], ["vegas ribeye"], { cal: 720, protein: 52, carbs: 0, fat: 56 }),
  place("nh-maple-pork", "New Hampshire maple cider pork", "American", ["new-hampshire", "usa"], "pork", "skillet", 40, "Pork chops, maple, cider, mustard. Fall on a plate.", [I("pork chops", 4, "", "Meat & Seafood"), I("maple syrup", 3, "tbsp", "Pantry"), I("apple cider", 0.5, "cup", "Pantry"), I("dijon", 1, "tbsp", "Pantry")], ["Pat the 4 pork chops dry and salt both sides. Sear in a skillet over medium-high heat 4 minutes a side, until browned. Move to a plate.", "Pour the ½ cup of apple cider into the pan. Scrape up the browned bits. Stir in the 3 tablespoons of maple syrup and the 1 tablespoon of Dijon.", "Return the chops. Simmer 4–6 minutes, until the chops are 145°F and the sauce is a glaze.", "Spoon the glaze over. Serve hot."], ["maple pork chops"], { cal: 480, protein: 36, carbs: 18, fat: 28 }),
  place("nj-pork-roll", "New Jersey pork roll breakfast", "American", ["new-jersey", "usa"], "pork", "toast", 15, "Taylor pork roll, egg, cheese, a kaiser. The Garden State morning.", [I("pork roll", 8, "slices", "Meat & Seafood"), I("eggs", 4, "", "Dairy & Eggs"), I("american cheese", 4, "slices", "Dairy & Eggs"), I("kaiser rolls", 4, "", "Bakery")], ["Cut a nick in the edge of each of the 8 pork roll slices so they do not cup. Fry in a skillet over medium heat 2 minutes a side, until the edges crisp.", "Fry the 4 eggs in the same pan, 2–3 minutes, until the whites are set.", "Split and toast the 4 kaiser rolls. Lay 2 slices of pork roll on each, then an egg and a slice of American cheese so it melts.", "Close the rolls. Serve hot."], ["taylor ham", "pork roll egg and cheese"], { cal: 540, protein: 28, carbs: 32, fat: 32 }),
  place("nm-stacked-enchiladas", "New Mexico stacked enchiladas", "American", ["new-mexico", "usa"], "chicken", "roast", 40, "Flat corn tortillas stacked with red or green chile, cheese, a fried egg.", [I("corn tortillas", 12, "", "Bakery"), I("red chile sauce", 2, "cups", "Pantry"), I("chicken", 2, "cups", "Meat & Seafood"), I("cheddar", 2, "cups", "Dairy & Eggs"), I("eggs", 4, "", "Dairy & Eggs")], ["Heat the oven to 375°F. Warm the 2 cups of red chile sauce. Dip each of the 12 corn tortillas in the sauce so both sides are wet.", "In a baking dish, stack tortillas with the 2 cups of shredded chicken and the 2 cups of cheddar, three tortillas high per serving.", "Bake 15 minutes, until the cheese melts and the edges bubble.", "Fry the 4 eggs. Set one on each stack. Serve hot with extra chile sauce."], ["christmas enchiladas"], { cal: 610, protein: 38, carbs: 42, fat: 30 }),
  place("ny-chopped-cheese", "New York chopped cheese", "American", ["new-york", "usa"], "beef", "toast", 20, "Bodega hero: chopped burger, cheese, onion, lettuce, tomato, hero roll.", [I("ground beef", 1, "lb", "Meat & Seafood"), I("american cheese", 6, "slices", "Dairy & Eggs"), I("hero rolls", 4, "", "Bakery"), I("onion", 1, "", "Produce"), I("lettuce", 0.5, "head", "Produce"), I("tomato", 2, "", "Produce")], ["Heat a griddle or skillet until hot. Add the 1 pound of ground beef and the chopped onion. Chop the beef with a spatula as it cooks, 6–8 minutes, until browned.", "Lay the 6 American cheese slices over the meat. Let them melt 1 minute, then chop the cheese through the beef.", "Split the 4 hero rolls. Pile the chopped cheese on, then shredded lettuce and tomato slices.", "Close the sandwiches. Serve hot."], ["chop cheese"], { cal: 620, protein: 34, carbs: 40, fat: 34 }),
  place("nc-vinegar-pork", "North Carolina vinegar pork", "American", ["north-carolina", "usa"], "pork", "bowl", 240, "Pulled pork dressed in vinegar and pepper. Coleslaw on the tray.", [I("pork shoulder", 4, "lb", "Meat & Seafood"), I("apple cider vinegar", 1, "cup", "Pantry"), I("red pepper flakes", 2, "tsp", "Herbs & Spices"), I("cabbage", 0.5, "head", "Produce"), I("kosher salt", 1, "tbsp", "Herbs & Spices")], ["Heat the oven to 300°F. Rub the 4-pound pork shoulder with the 1 tablespoon of kosher salt. Roast uncovered until the meat pulls apart, about 4 hours.", "Rest 20 minutes. Pull the pork into shreds, discarding big pieces of fat.", "Toss the pork with the 1 cup of apple cider vinegar and the 2 teaspoons of red pepper flakes. Taste for salt.", "Shred the cabbage into a slaw. Serve the pork with slaw on the tray."], ["eastern nc pork"], { cal: 540, protein: 42, carbs: 8, fat: 36 }),
  place("nd-knoephla", "North Dakota knoephla soup", "American", ["north-dakota", "usa"], "chicken", "soup", 45, "Creamy chicken and dumpling soup. German-Russian prairie food.", [I("chicken broth", 6, "cups", "Pantry"), I("potato", 3, "", "Produce"), I("cream", 1, "cup", "Dairy & Eggs"), I("flour", 1.5, "cups", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("celery", 2, "stalks", "Produce"), I("water", 0.5, "cup", "Other")], ["Simmer the 3 diced potatoes and the sliced celery in the 6 cups of chicken broth until the potatoes are almost tender, 12 minutes.", "Stir the 1½ cups of flour with the egg, the ½ cup of water, and a pinch of salt to a stiff dumpling dough.", "Drop small pieces of dough into the simmering soup. Cook 10 minutes, until the knoephla are cooked through.", "Stir in the 1 cup of cream. Heat through. Taste for salt. Serve hot."], ["knoephla"], { cal: 390, protein: 14, carbs: 48, fat: 16 }),
  place("oh-cincinnati-chili", "Ohio Cincinnati chili", "American", ["ohio", "usa"], "beef", "pasta", 90, "Spaghetti, spiced meat sauce, cheddar mountain. Three-way, four-way, five-way.", [I("ground beef", 2, "lb", "Meat & Seafood"), I("tomato sauce", 2, "cups", "Pantry"), I("cinnamon", 1, "tsp", "Herbs & Spices"), I("cocoa", 1, "tsp", "Pantry"), I("spaghetti", 1, "lb", "Pantry"), I("cheddar", 3, "cups", "Dairy & Eggs"), I("chili powder", 2, "tbsp", "Herbs & Spices"), I("onion", 1, "", "Produce")], ["Crumble the 2 pounds of ground beef into a pot with water to cover. Bring to a boil, then lower to a simmer, skimming foam, 20 minutes. This is the Cincinnati way — do not brown it first.", "Stir in the 2 cups of tomato sauce, the 2 tablespoons of chili powder, the 1 teaspoon of cinnamon, the 1 teaspoon of cocoa, and the chopped onion. Simmer uncovered 45 minutes, until thick.", "Cook the 1 pound of spaghetti. Drain.", "Plate spaghetti, ladle chili over, and pile on the 3 cups of cheddar. Serve hot."], ["skyline chili", "3-way"], { cal: 680, protein: 38, carbs: 58, fat: 32 }),
  place("ok-chicken-fried-steak", "Oklahoma chicken-fried steak", "American", ["oklahoma", "usa"], "beef", "skillet", 45, "Cubed steak, peppered gravy, mashed potatoes. The state meal energy.", [I("cubed steak", 4, "", "Meat & Seafood"), I("flour", 1.5, "cups", "Pantry"), I("buttermilk", 1, "cup", "Dairy & Eggs"), I("milk", 2, "cups", "Dairy & Eggs"), I("potato", 4, "", "Produce"), I("neutral oil", 1.5, "cups", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("black pepper", 2, "tsp", "Herbs & Spices"), I("kosher salt", 2, "tsp", "Herbs & Spices")], ["Peel the 4 potatoes and cut into chunks. Boil in salted water until a fork slides through, 15–18 minutes. Drain. Mash with 2 tablespoons of the butter. Cover and keep warm.", "Season the 4 cubed steaks with 1 teaspoon of the kosher salt and 1 teaspoon of the black pepper. Put the 1½ cups of flour in a shallow dish and the 1 cup of buttermilk in another. Dredge each steak in flour, dip in buttermilk, then flour again, pressing the coating on.", "Pour the 1½ cups of oil into a wide skillet to about ½ inch. Heat over medium-high until a pinch of flour sizzles. Fry the steaks 3–4 minutes a side, until the crust is deep gold. Move to a rack. Pour off all but 3 tablespoons of the drippings.", "Whisk 3 tablespoons of the leftover flour into the drippings and cook 1 minute. Slowly whisk in the 2 cups of milk. Simmer 4–5 minutes, until the gravy is thick. Stir in the rest of the black pepper. Taste for salt.", "Plate each steak with mashed potatoes. Spoon the peppered gravy over both. Serve hot."], ["cfs"], { cal: 740, protein: 38, carbs: 48, fat: 42 }),
  place("or-marionberry-pork", "Oregon marionberry pork", "American", ["oregon", "usa"], "pork", "skillet", 35, "Pork chops with marionberry or blackberry pan sauce.", [I("pork chops", 4, "", "Meat & Seafood"), I("blackberries", 1.5, "cups", "Produce"), I("shallot", 1, "", "Produce"), I("balsamic", 1, "tbsp", "Pantry")], ["Pat the 4 pork chops dry and salt both sides. Sear in a skillet over medium-high heat 4 minutes a side, until browned. Move to a plate.", "Add the minced shallot to the pan and cook 1 minute. Add the 1½ cups of blackberries and the 1 tablespoon of balsamic.", "Crush some of the berries with a spoon. Simmer 3 minutes, until the sauce is jammy.", "Return the chops for 2 minutes. Spoon the berry sauce over. Serve hot."], ["oregon blackberry pork"], { cal: 460, protein: 36, carbs: 14, fat: 28 }),
  place("pa-cheesesteak", "Pennsylvania cheesesteak", "American", ["pennsylvania", "usa"], "beef", "toast", 20, "Ribeye, onions, Cheez Whiz or provolone, an Amoroso-style roll.", [I("ribeye", 1.5, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("provolone", 8, "slices", "Dairy & Eggs"), I("hoagie rolls", 4, "", "Bakery")], ["Slice the 1½ pounds of ribeye as thin as you can (partially frozen meat slices easier). Salt.", "Heat a griddle or wide skillet until very hot. Cook the sliced onions 6–8 minutes, until soft and browned. Push to the side.", "Add the ribeye. Chop it with a spatula as it cooks, 2–3 minutes, until just browned. Mix with the onions.", "Split the 4 hoagie rolls. Pile in the meat and onions, lay 2 slices of provolone on each, and let the cheese melt. Serve hot."], ["philly cheesesteak"], { cal: 680, protein: 42, carbs: 40, fat: 38 }),
  place("ri-stuffies", "Rhode Island stuffies", "American", ["rhode-island", "usa"], "seafood", "fish", 40, "Stuffed quahogs: chopped clam, bread, chorizo, baked in the shell.", [I("chopped clams", 2, "cups", "Meat & Seafood"), I("stale bread", 3, "cups", "Bakery"), I("chorizo", 4, "oz", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 1, "stalk", "Produce")], ["Heat the oven to 375°F. Tear the 3 cups of stale bread into crumbs.", "Cook the 4 ounces of crumbled chorizo with the chopped onion and celery 5 minutes, until the fat runs.", "Fold in the 2 cups of chopped clams and the bread crumbs. Moisten with clam liquor if it is dry. Taste for salt.", "Pack into clam shells or a small baking dish. Bake 20–25 minutes, until the tops are browned. Serve hot."], ["stuffed quahogs"], { cal: 380, protein: 24, carbs: 32, fat: 16 }),
  place("sc-shrimp-grits", "South Carolina shrimp and grits", "American", ["south-carolina", "usa"], "seafood", "bowl", 35, "Lowcountry: creamy grits, shrimp, bacon, a little heat.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("grits", 1, "cup", "Pantry"), I("bacon", 4, "slices", "Meat & Seafood"), I("cheddar", 1, "cup", "Dairy & Eggs"), I("scallion", 4, "", "Produce"), I("water", 4, "cups", "Other")], ["Bring the 4 cups of water to a boil with a pinch of salt. Whisk in the 1 cup of grits. Cook, stirring, until thick, 15–20 minutes. Stir in the 1 cup of cheddar. Cover.", "Fry the 4 bacon slices until crisp, 6–8 minutes. Move to paper. Keep the drippings in the pan.", "Pat the 1½ pounds of shrimp dry. Cook in the bacon drippings 2 minutes a side, until just pink.", "Spoon the grits into bowls. Top with shrimp, crumbled bacon, and the sliced scallions. Serve hot."], ["lowcountry shrimp and grits"], { cal: 560, protein: 38, carbs: 36, fat: 28 }),
  place("sd-chislic", "South Dakota chislic", "American", ["south-dakota", "usa"], "beef", "skillet", 20, "Cubes of lamb or beef, fried or grilled, garlic salt. A bar snack that is dinner.", [I("lamb or sirloin", 1.5, "lb", "Meat & Seafood"), I("garlic salt", 2, "tsp", "Herbs & Spices"), I("oil", 2, "tbsp", "Pantry")], ["Cut the 1½ pounds of lamb or sirloin into 1-inch cubes. Toss with 1 teaspoon of the garlic salt.", "Heat the 2 tablespoons of oil in a skillet until it shimmers, or heat a grill to high.", "Cook the cubes 2–3 minutes, turning, until browned outside and still pink in the middle for medium.", "Toss with the rest of the garlic salt. Serve on toothpicks, hot."], ["chislic"], { cal: 420, protein: 36, carbs: 0, fat: 30 }),
  place("tn-hot-chicken", "Tennessee hot chicken", "American", ["tennessee", "usa"], "chicken", "skillet", 45, "Nashville: fried chicken painted with cayenne oil. Pickles, white bread.", [I("chicken pieces", 8, "", "Meat & Seafood"), I("buttermilk", 2, "cups", "Dairy & Eggs"), I("flour", 2, "cups", "Pantry"), I("cayenne", 3, "tbsp", "Herbs & Spices"), I("lard or oil", 3, "cups", "Pantry"), I("white bread", 8, "slices", "Bakery"), I("kosher salt", 2, "tsp", "Herbs & Spices")], ["Soak the 8 chicken pieces in the 2 cups of buttermilk and 1 teaspoon of the salt at least 30 minutes.", "Heat the lard or oil to 325°F. Dredge the chicken in the 2 cups of flour mixed with 1 teaspoon of salt. Fry 12–16 minutes, turning, until 165°F in the thickest part. Drain on a rack.", "Ladle ½ cup of the hot frying oil into a bowl. Whisk in the 3 tablespoons of cayenne. Paint the fried chicken with the cayenne oil.", "Set each piece on a slice of white bread. Serve hot, with pickles if you have them."], ["nashville hot chicken"], { cal: 720, protein: 38, carbs: 36, fat: 46 }),
  place("tx-oven-brisket", "Texas oven brisket", "American", ["texas", "usa"], "beef", "roast", 300, "Salt, pepper, low oven, patience. Smoke if you have it. Slices with pickles.", [I("beef brisket", 4, "lb", "Meat & Seafood"), I("kosher salt", 2, "tbsp", "Herbs & Spices"), I("coarse black pepper", 2, "tbsp", "Herbs & Spices")], ["Pat the 4-pound brisket dry. Rub all over with the 2 tablespoons of kosher salt and the 2 tablespoons of coarse black pepper. Rest 30 minutes.", "Heat the oven to 275°F. Set the brisket on a rack in a pan, fat-side up. Roast until a probe slides in with little resistance, about 4–5 hours (around 200°F inside).", "Wrap in foil and rest 45 minutes.", "Slice against the grain, about ¼ inch thick. Serve with pickles."], ["texas brisket"], { cal: 580, protein: 46, carbs: 0, fat: 42 }),
  place("ut-funeral-potatoes", "Utah funeral potatoes", "American", ["utah", "usa"], "veg", "roast", 50, "Hash browns, cream soup, sour cream, cornflakes. Comfort that travels well.", [I("hash browns", 30, "oz", "Frozen"), I("cream of chicken soup", 1, "can", "Pantry"), I("sour cream", 2, "cups", "Dairy & Eggs"), I("cheddar", 2, "cups", "Dairy & Eggs"), I("cornflakes", 2, "cups", "Pantry"), I("butter", 0.25, "cup", "Dairy & Eggs")], ["Heat the oven to 350°F. Thaw the 30 ounces of hash browns.", "Mix the hash browns with the 1 can of cream of chicken soup, the 2 cups of sour cream, and 1½ cups of the cheddar. Spread in a buttered 9×13 dish.", "Crush the 2 cups of cornflakes. Toss with the ¼ cup of melted butter. Scatter over the potatoes with the rest of the cheddar.", "Bake 40–45 minutes, until bubbling and the top is gold. Rest 10 minutes. Serve hot."], ["cheesy potatoes"], { cal: 480, protein: 14, carbs: 38, fat: 30 }),
  place("vt-maple-mac", "Vermont maple cheddar mac", "American", ["vermont", "usa"], "veg", "pasta", 30, "Sharp cheddar, a whisper of maple, breadcrumbs.", [I("elbow pasta", 1, "lb", "Pantry"), I("sharp cheddar", 3, "cups", "Dairy & Eggs"), I("milk", 2, "cups", "Dairy & Eggs"), I("maple syrup", 1, "tbsp", "Pantry"), I("breadcrumbs", 0.5, "cup", "Pantry"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry")], ["Heat the oven to 400°F. Cook the 1 pound of elbow pasta in salted water until just shy of tender. Drain.", "Melt the 3 tablespoons of butter in a saucepan. Whisk in the 3 tablespoons of flour and cook 1 minute. Slowly whisk in the 2 cups of milk until the sauce thickens, 4–5 minutes.", "Stir in the 3 cups of sharp cheddar and the 1 tablespoon of maple syrup. Fold in the pasta. Spread in a baking dish. Scatter the ½ cup of breadcrumbs.", "Bake 10–12 minutes, until the top is gold. Serve hot."], ["vermont mac"], { cal: 620, protein: 26, carbs: 68, fat: 26 }),
  place("va-peanut-soup", "Virginia peanut soup", "American", ["virginia", "usa"], "veg", "soup", 35, "Colonial Williamsburg energy: peanut, celery, cream.", [I("peanut butter", 1, "cup", "Pantry"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("chicken broth", 4, "cups", "Pantry"), I("cream", 0.5, "cup", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Melt the 2 tablespoons of butter in a pot over medium heat. Add the chopped onion and celery. Cook 6 minutes, until soft.", "Whisk in the 4 cups of chicken broth, then the 1 cup of peanut butter, until smooth.", "Simmer 15 minutes. Stir in the ½ cup of cream. Taste for salt.", "Blend if you want it silk-smooth. Serve hot."], ["williamsburg peanut soup"], { cal: 380, protein: 16, carbs: 16, fat: 28 }),
  place("wa-cedar-salmon", "Washington cedar-plank salmon", "American", ["washington", "usa"], "fish", "fish", 30, "Salmon, brown sugar, a plank or a sheet pan if that is what you have.", [I("salmon fillet", 2, "lb", "Meat & Seafood"), I("brown sugar", 2, "tbsp", "Pantry"), I("soy sauce", 1, "tbsp", "Pantry"), I("lemon", 1, "", "Produce")], ["If you have a cedar plank, soak it in water 1 hour. Heat the grill to medium or the oven to 400°F.", "Pat the 2-pound salmon fillet dry. Rub with the 2 tablespoons of brown sugar and the 1 tablespoon of soy sauce.", "Set the salmon on the plank or a sheet pan. Cook until the thickest part is just set and flakes, 12–16 minutes. Do not overcook.", "Squeeze the lemon over. Serve hot."], ["pnw salmon"], { cal: 420, protein: 38, carbs: 6, fat: 26 }),
  place("wv-pepperoni-rolls", "West Virginia pepperoni rolls", "American", ["west-virginia", "usa"], "pork", "toast", 40, "Soft rolls wrapped around pepperoni. Miner lunch, still a gas-station king.", [I("bread dough", 1.5, "lb", "Bakery"), I("pepperoni sticks", 8, "", "Meat & Seafood"), I("mozzarella", 1, "cup", "Dairy & Eggs")], ["Heat the oven to 375°F. Divide the 1½ pounds of bread dough into 8 pieces.", "Flatten each piece. Lay on a pepperoni stick and a pinch of the 1 cup of mozzarella. Roll the dough around and pinch the seam closed.", "Set seam-side down on a sheet. Bake 18–22 minutes, until the rolls are gold.", "Cool 10 minutes so the cheese is not molten. Serve warm or pack for later."], ["pepperoni roll"], { cal: 480, protein: 22, carbs: 44, fat: 24 }),
  place("wi-beer-brats", "Wisconsin beer brats", "American", ["wisconsin", "usa"], "pork", "skillet", 40, "Brats simmered in beer and onion, then grilled. Mustard, a hard roll.", [I("bratwurst", 6, "", "Meat & Seafood"), I("beer", 2, "bottles", "Pantry"), I("onion", 2, "", "Produce"), I("hard rolls", 6, "", "Bakery"), I("mustard", 4, "tbsp", "Pantry")], ["Slice the 2 onions. Put them in a wide pot with the 6 bratwurst and the 2 bottles of beer. Simmer 15 minutes. Do not boil hard or the casings split.", "Heat a grill or skillet to medium-high. Brown the brats 3–4 minutes, turning, until the skins snap.", "Pile onions on the 6 hard rolls. Add a brat and the mustard.", "Serve hot, with extra onions from the beer."], ["sheboygan brats"], { cal: 560, protein: 26, carbs: 32, fat: 34 }),
  place("wy-chili", "Wyoming range chili", "American", ["wyoming", "usa"], "beef", "bowl", 90, "Beef chili, no beans if you are stubborn, cheddar and onion if you are kind.", [I("beef chuck", 2, "lb", "Meat & Seafood"), I("chili powder", 3, "tbsp", "Herbs & Spices"), I("onion", 2, "", "Produce"), I("tomato sauce", 2, "cups", "Pantry"), I("beef broth", 1, "cup", "Pantry")], ["Cut the 2 pounds of beef chuck into small cubes. Brown in a heavy pot over medium-high heat 8 minutes. Do not crowd the pan.", "Add the chopped onions and the 3 tablespoons of chili powder. Cook 3 minutes.", "Stir in the 2 cups of tomato sauce and the 1 cup of beef broth. Simmer uncovered 1 hour, until the beef is tender and the chili is thick.", "Taste for salt. Serve hot, with cheddar and onion if you want them."], ["range chili"], { cal: 520, protein: 42, carbs: 16, fat: 32 }),
];

export const PLACE_RECIPES: Recipe[] = [...ATLANTIC_RECIPES, ...USA];
