import { I, dish } from "./catalog-kit";
import type { Recipe, RecipeSource } from "./types";

function src(book: string, author: string, year: number, era: string, archiveId: string, credit: string): RecipeSource {
  return { book, author, year, era, archiveId, credit };
}

const foreign365 = src("365 Foreign Dishes", "Anonymous", 1908, "1900s", "365foreigndishes00newy", "365 Foreign Dishes (George W. Jacobs, 1908). Public domain.");
const paDutch = src("Pennsylvania German household cooking", "Traditional", 1900, "1900s", "pagermanhousehold", "Pennsylvania German household dishes as cooked in 19th-century kitchens. Traditional, public domain.");
const picayune = src("The Picayune Creole Cook Book", "The Picayune", 1901, "1900s", "picayunecreoleco00neworich", "The Picayune Creole Cook Book (New Orleans, 1901). Public domain.");
const kephart = src("Camping and Woodcraft", "Horace Kephart", 1917, "1910s", "campingwoodcraft00keph", "Horace Kephart, Camping and Woodcraft (1917). Public domain.");
const ladiesAid = src("Woman Suffrage Cook Book", "Mrs. Hattie A. Burr", 1886, "1880s", "womansuffragecoo00burr", "Mrs. Hattie A. Burr, The Woman Suffrage Cook Book (Boston, 1886), and typical Ladies' Aid church-supper dishes. Public domain.");
const hill = src("Salads, Sandwiches and Chafing Dishes", "Janet McKenzie Hill", 1909, "1900s", "saladssandwiches00hill", "Janet McKenzie Hill, Salads, Sandwiches and Chafing Dishes (1909). Public domain.");
const bosse = src("Chinese-Japanese Cook Book", "Sara Bosse & Onoto Watanna", 1914, "1910s", "chinesejapanesec00boss", "Sara Bosse and Onoto Watanna (Winnifred Eaton), Chinese-Japanese Cook Book (Rand McNally, 1914). Public domain.");
const oliveGreen = src("How to Cook Fish", "Olive Green", 1908, "1900s", "howtocookfish00gree", "Olive Green, How to Cook Fish (Putnam, 1908). Public domain.");
const jewish = src("The International Jewish Cook Book", "Florence Kreisler Greenbaum", 1918, "1910s", "internationaljew00gree", "Florence Kreisler Greenbaum, The International Jewish Cook Book (Bloch, 1918). Public domain.");
const fulton = src("Vegetarian cookery, 1900–1910", "Early vegetarian household", 1904, "1900s", "earlyveg1904", "Early American vegetarian household cooking, 1900–1910. Public domain.");
const desserts365 = src("365 Desserts", "Anonymous", 1900, "1900s", "365desserts00newy", "365 Desserts: A Dessert for Every Day in the Year (1900). Public domain.");
const twenties = src("American luncheon cookery", "Household pages, 1925", 1925, "1920s", "americanluncheon1925", "American luncheon dishes from public-domain 1925 and earlier household sources.");

function h(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: RecipeSource,
  nutrition: Recipe["nutrition"],
): Recipe {
  return dish({
    id, name, cuisine, description, minutes, protein, plate,
    tags: Array.from(new Set(["vintage", ...tags])),
    ingredients, steps, nutrition, source,
  });
}

export const BOOK_RECIPES: Recipe[] = [
  h("vh-365-goulash", "Hungarian goulash", "Hungarian", ["era-1900s", "book-365-foreign", "international", "old-school"], "beef", "bowl", 120, "Beef, onion, paprika, potato. The 1908 foreign-dishes goulash, a stew not a soup.", [I("beef chuck", 2, "lb", "Meat & Seafood"), I("onions", 3, "", "Produce"), I("sweet paprika", 3, "tbsp", "Herbs & Spices"), I("potato", 3, "", "Produce"), I("lard or oil", 2, "tbsp", "Pantry"), I("caraway", 1, "tsp", "Herbs & Spices")], ["Cut the beef into 1½-inch cubes. Slice the onions. Brown the beef in the fat 8 minutes. Take it out.", "Cook the onions in the same pot 10 minutes, until soft and gold.", "Stir in the paprika and caraway off the heat so the paprika does not burn. Return the beef. Add water to almost cover.", "Cover the pot and simmer the beef 75 minutes. Add the cubed potatoes. Cook 25 minutes more, until beef and potato are tender.", "Salt. The sauce should be thick. Serve in bowls with bread."], foreign365, { cal: 440, protein: 36, carbs: 22, fat: 22 }),
  h("vh-365-irish-stew", "Irish stew", "Irish", ["era-1900s", "book-365-foreign", "international", "old-school"], "beef", "bowl", 90, "Neck of lamb, potato, onion, layered and stewed. No browning.", [I("lamb shoulder", 2, "lb", "Meat & Seafood"), I("potatoes", 2, "lb", "Produce"), I("onions", 3, "", "Produce"), I("parsley", 3, "tbsp", "Produce"), I("thyme", 1, "tsp", "Herbs & Spices"), I("salt", 1.5, "tsp", "Herbs & Spices")], ["Cut the lamb into chunks. Peel and thick-slice the potatoes. Slice the onions.", "In a heavy pot, layer potato, onion, and lamb, repeating, with thyme, salt, and pepper on each layer. End with potato.", "Add water to come just below the top layer. Cover tightly.", "Simmer 80 minutes, until the lamb is tender and the potatoes have thickened the liquor. Do not stir or it will break.", "Scatter chopped parsley over the stew. Serve from the pot."], foreign365, { cal: 460, protein: 34, carbs: 32, fat: 20 }),
  h("vh-365-swedish-balls", "Swedish meatballs", "Swedish", ["era-1900s", "book-365-foreign", "international"], "beef", "skillet", 40, "Beef and pork, crumbs, cream, browned, a pan sauce. The 1908 luncheon ball.", [I("ground beef", 0.75, "lb", "Meat & Seafood"), I("ground pork", 0.5, "lb", "Meat & Seafood"), I("bread crumbs", 0.5, "cup", "Bakery"), I("cream", 0.5, "cup", "Dairy & Eggs"), I("onion", 0.5, "", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs")], ["Soak the crumbs in half the cream 5 minutes. Mix with the beef, pork, grated onion, 1 teaspoon salt, and pepper. Shape into small balls.", "Brown the balls in butter over medium heat, turning, 8 minutes. Take them out.", "Stir a spoon of flour into the pan if the drippings are thin. Pour in the remaining cream and ½ cup water.", "Return the balls. Simmer 10 minutes, until cooked through and the sauce coats them.", "Serve the meatballs with boiled potatoes or buttered noodles."], foreign365, { cal: 420, protein: 26, carbs: 12, fat: 28 }),
  h("vh-365-borscht", "Russian borscht", "Russian", ["era-1900s", "book-365-foreign", "international", "soup"], "beef", "soup", 90, "Beet, cabbage, beef broth, sour cream. The 1908 foreign-dishes beet soup.", [I("beef shank", 1, "lb", "Meat & Seafood"), I("beets", 4, "", "Produce"), I("cabbage", 0.25, "head", "Produce"), I("onion", 1, "", "Produce"), I("sour cream", 0.5, "cup", "Dairy & Eggs"), I("vinegar", 1, "tbsp", "Pantry")], ["Cover the beef with water. Simmer 45 minutes. Lift out, chop the meat, return it. Keep the broth.", "Peel and grate the beets. Shred the cabbage. Chop the onion.", "Add the vegetables to the broth. Simmer 30 minutes, until the beet is tender and the soup is red.", "Add vinegar, salt, and pepper. Taste for sour.", "Ladle into bowls. Spoon sour cream on each. Serve hot."], foreign365, { cal: 260, protein: 20, carbs: 16, fat: 12 }),
  h("vh-365-german-potato", "Warm German potato salad", "German", ["era-1900s", "book-365-foreign", "international", "salad"], "pork", "green", 30, "Hot potatoes, bacon, vinegar, onion. Dressed while the potatoes can drink.", [I("waxy potatoes", 2, "lb", "Produce"), I("bacon", 6, "slices", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("cider vinegar", 0.33, "cup", "Pantry"), I("sugar", 1, "tsp", "Pantry"), I("parsley", 2, "tbsp", "Produce")], ["Boil the potatoes in their skins until just tender, 20 minutes. Drain, peel, and slice while warm.", "Cook the bacon until crisp. Lift out. Cook the chopped onion in the fat 4 minutes.", "Stir in vinegar, sugar, salt, and pepper. Bring to a bubble.", "Pour the hot dressing over the potatoes. Fold in crumbled bacon and parsley.", "Serve warm. This is a salad, not a bake."], foreign365, { cal: 280, protein: 8, carbs: 32, fat: 14 }),
  h("vh-365-curry-chicken", "East Indian chicken curry", "Indian", ["era-1900s", "book-365-foreign", "international", "curry"], "chicken", "curry", 45, "The 1908 American-kitchen curry: chicken, onion, curry powder, a little apple.", [I("chicken", 1, "bird", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("curry powder", 2, "tbsp", "Herbs & Spices"), I("apple", 1, "", "Produce"), I("flour", 2, "tbsp", "Pantry"), I("chicken broth", 2, "cups", "Pantry")], ["Joint the chicken. Brown the pieces in a little fat 8 minutes. Take them out.", "Cook the sliced onion 6 minutes. Stir in the curry powder and flour 1 minute.", "Add the broth and the chopped apple. Return the chicken.", "Cover and simmer 25 minutes, until the joints run clear.", "Salt the curry. Serve it hot with boiled rice."], foreign365, { cal: 400, protein: 36, carbs: 12, fat: 22 }),
  h("vh-365-onion-soup", "French onion soup", "French", ["era-1900s", "book-365-foreign", "international", "soup"], "beef", "soup", 70, "Onions cooked long in butter, beef broth, toast, cheese.", [I("onions", 2, "lb", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("beef broth", 6, "cups", "Pantry"), I("baguette", 8, "slices", "Bakery"), I("gruyere or Swiss", 6, "oz", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices")], ["Slice the onions thin. Cook them in the butter over medium-low heat 30 minutes, stirring, until they are deep gold and sweet. Do not rush this.", "Add the broth. Simmer 20 minutes. Salt and pepper.", "Toast the bread. Ladle the soup into oven-safe bowls. Float toast on each. Cover with grated cheese.", "Broil 2–3 minutes, until the cheese bubbles and browns.", "Serve at once. Warn the table the bowls are hot."], foreign365, { cal: 360, protein: 16, carbs: 32, fat: 18 }),
  h("vh-365-spanish-rice", "Spanish rice", "Spanish", ["era-1900s", "book-365-foreign", "international", "budget"], "pork", "bowl", 40, "Rice fried with onion and tomato, broth, a little ham.", [I("rice", 1.5, "cups", "Pantry"), I("onion", 1, "", "Produce"), I("tomatoes", 3, "", "Produce"), I("ham", 4, "oz", "Meat & Seafood"), I("green pepper", 1, "", "Produce"), I("chicken broth", 3, "cups", "Pantry")], ["Dice the ham, onion, and pepper. Cook in a little oil 5 minutes.", "Add the rice and stir 2 minutes, until the grains look coated.", "Add chopped tomatoes and the broth. Salt, pepper, a pinch of paprika.", "Cover and simmer 18 minutes, until the rice is tender and the liquid is gone. Do not stir while it cooks.", "Rest 5 minutes, lid on. Fluff and serve."], foreign365, { cal: 340, protein: 12, carbs: 52, fat: 8 }),

  h("vh-pd-pot-pie", "Pennsylvania pot pie", "American", ["era-1900s", "book-pa-dutch", "old-school", "hometown"], "chicken", "soup", 90, "Bott boi: chicken stew with square noodle dough dropped on top, not a crust pie.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 2, "cups", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("parsley", 3, "tbsp", "Produce")], ["Cover the chicken with water. Simmer 45 minutes. Lift out, pull the meat, return it. Add cubed potato and onion.", "Make a stiff dough of flour, egg, ½ teaspoon salt, and enough water to bring it together. Roll thin. Cut into 2-inch squares.", "When the potato is half done, lay the dough squares on the simmering stew. They will steam, not boil hard.", "Cover 15 minutes, until the squares are cooked through and the stew is thick.", "Salt, pepper, parsley. Serve in bowls. This is noodle pot pie, not a baked crust."], paDutch, { cal: 420, protein: 36, carbs: 38, fat: 12 }),
  h("vh-pd-schnitz", "Schnitz un knepp", "American", ["era-1900s", "book-pa-dutch", "old-school"], "pork", "bowl", 120, "Ham, dried apples, dumplings. The Pennsylvania German pot of sweet and salt.", [I("smoked ham", 2, "lb", "Meat & Seafood"), I("dried apples", 2, "cups", "Pantry"), I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("milk", 0.75, "cup", "Dairy & Eggs"), I("brown sugar", 2, "tbsp", "Pantry")], ["Soak the dried apples in water 1 hour. Cover the ham with water and simmer 60 minutes.", "Add the apples with their soaking water and the brown sugar. Simmer 20 minutes more.", "Stir flour, baking powder, ½ teaspoon salt, and milk into a drop-dumpling batter.", "Drop spoonfuls onto the simmering ham and apples. Cover tightly 15 minutes — do not lift the lid.", "Slice the ham. Serve with apples and dumplings in the liquor."], paDutch, { cal: 480, protein: 36, carbs: 44, fat: 16 }),
  h("vh-pd-sauerkraut", "Pork and sauerkraut", "American", ["era-1900s", "book-pa-dutch", "old-school", "gluten-free"], "pork", "roast", 180, "A pork roast on sauerkraut, slow. New Year's on the Pennsylvania table any day.", [I("pork shoulder", 3, "lb", "Meat & Seafood"), I("sauerkraut", 2, "lb", "Pantry"), I("onion", 1, "", "Produce"), I("apple", 1, "", "Produce"), I("caraway", 1, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 325°F. Salt and pepper the pork. Brown it on all sides in a Dutch oven, 8 minutes.", "Add the drained sauerkraut, sliced onion, sliced apple, and caraway around the meat.", "Pour ½ cup water around the pork. Cover the pot tightly.", "Bake 2½ hours, until the pork pulls with a fork.", "Slice the pork. Serve on the sauerkraut with boiled potatoes."], paDutch, { cal: 460, protein: 38, carbs: 10, fat: 28 }),
  h("vh-pd-rivvel", "Rivvel soup", "American", ["era-1900s", "book-pa-dutch", "soup", "budget", "old-school"], "chicken", "soup", 30, "Chicken broth with tiny flour-and-egg crumbs dropped in. Rivels, not noodles.", [I("chicken broth", 8, "cups", "Pantry"), I("flour", 1, "cup", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("potato", 2, "", "Produce"), I("parsley", 2, "tbsp", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Bring the broth to a simmer with cubed potato. Cook 12 minutes.", "Rub the egg into the flour and salt with your fingers until you have pea-size crumbs — rivels.", "Drop the rivels into the simmering broth, stirring so they do not clump.", "Cook 8 minutes, until the rivels are tender and the soup has thickened slightly.", "Salt the soup. Scatter parsley. Serve hot in bowls."], paDutch, { cal: 180, protein: 8, carbs: 26, fat: 4 }),
  h("vh-pd-shoofly", "Shoofly pie", "American", ["era-1900s", "book-pa-dutch", "dessert", "baking", "vegetarian", "old-school"], "veg", "dessert", 55, "Molasses crumb pie: wet bottom, crumbs on top, baked in a crust.", [I("pie crust", 1, "", "Bakery"), I("molasses", 1, "cup", "Pantry"), I("flour", 1.5, "cups", "Pantry"), I("brown sugar", 0.75, "cup", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("baking soda", 1, "tsp", "Pantry")], ["Heat the oven to 375°F. Lay the crust in a 9-inch pie tin. Crimp the edge.", "Rub the flour, brown sugar, and butter into crumbs with your fingers.", "Stir the baking soda into ¾ cup hot water, then into the molasses.", "Pour the molasses mix into the crust. Scatter the crumbs evenly over the top.", "Bake 35–40 minutes, until the filling is set and the crumbs are gold. Cool before slicing."], paDutch, { cal: 380, protein: 4, carbs: 62, fat: 14 }),
  h("vh-pd-scrapple", "Scrapple", "American", ["era-1900s", "book-pa-dutch", "breakfast", "old-school"], "pork", "skillet", 90, "Pork broth, cornmeal, sage, chilled and fried. The Pennsylvania breakfast slice.", [I("pork shoulder", 1.5, "lb", "Meat & Seafood"), I("cornmeal", 1.5, "cups", "Pantry"), I("sage", 1, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices"), I("salt", 2, "tsp", "Herbs & Spices"), I("lard or oil", 3, "tbsp", "Pantry")], ["Cover the pork with water. Simmer 60 minutes until it shreds. Lift out, chop fine, and measure 4 cups of the broth.", "Bring the broth to a boil. Rain in the cornmeal, stirring. Add the pork, sage, salt, and pepper.", "Cook over low heat 15 minutes, until very thick. Pack into a greased loaf pan. Chill until firm, at least 4 hours.", "Slice ½ inch thick. Fry in fat over medium heat 4 minutes a side, until a brown crust forms.", "Serve the fried scrapple hot with molasses or fried eggs."], paDutch, { cal: 280, protein: 16, carbs: 20, fat: 16 }),
  h("vh-pd-corn-pie", "Pennsylvania corn pie", "American", ["era-1900s", "book-pa-dutch", "vegetarian", "baking", "old-school"], "eggs", "roast", 50, "Sweet corn in a custard, a crust, baked until set. A harvest pie that is not dessert.", [I("corn kernels", 3, "cups", "Produce"), I("eggs", 3, "", "Dairy & Eggs"), I("milk", 1, "cup", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("pie crust", 1, "", "Bakery"), I("salt", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 375°F. Lay the crust in a pie tin.", "Beat the eggs with the milk, melted butter, salt, and pepper.", "Stir the corn into the custard. Pour the filling into the crust.", "Bake 35–40 minutes, until the center is just set and a knife comes out clean.", "Cool 10 minutes. Serve warm as a supper pie, not as a sweet."], paDutch, { cal: 320, protein: 10, carbs: 32, fat: 16 }),

  h("vh-pc-gumbo-file", "Gumbo filé", "Creole", ["era-1900s", "book-picayune", "southern", "soup"], "chicken", "soup", 90, "The Picayune's filé gumbo: a brown roux, chicken, oyster or shrimp, filé off the fire.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 0.33, "cup", "Pantry"), I("lard or oil", 0.33, "cup", "Pantry"), I("onion", 2, "", "Produce"), I("oysters or shrimp", 1, "pint", "Meat & Seafood"), I("filé powder", 1, "tbsp", "Herbs & Spices")], ["Joint the chicken. Make a roux of the fat and flour over medium heat, stirring, 12–15 minutes, until it is the color of peanut butter. Do not burn it.", "Add the chopped onion. Cook 4 minutes. Add the chicken and 2 quarts water. Simmer 45 minutes.", "Add the oysters or shrimp. Cook 5 minutes, until the oysters ruffle or the shrimp turn pink.", "Take off the heat. Stir in the filé. Never boil after the filé goes in or the gumbo turns stringy.", "Salt, cayenne, parsley. Serve over rice."], picayune, { cal: 380, protein: 32, carbs: 12, fat: 22 }),
  h("vh-pc-red-beans", "Red beans and rice", "Creole", ["era-1900s", "book-picayune", "southern", "budget"], "pork", "bowl", 180, "Monday beans: red beans, a ham bone, onion, celery, bell pepper, rice on the side.", [I("dried red beans", 1, "lb", "Pantry"), I("ham bone or pickled pork", 1, "", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("green pepper", 1, "", "Produce"), I("rice", 1.5, "cups", "Pantry")], ["Soak the beans overnight. Drain. Cover with fresh water, add the ham bone, and simmer 1 hour.", "Add chopped onion, celery, and pepper. Cook 45 minutes more, until the beans are soft.", "Mash a cup of beans against the pot to thicken. Salt, cayenne, a bay leaf if you have it. Simmer 15 minutes.", "Boil the rice in salted water until tender, 18 minutes. Drain.", "Serve the beans over or beside the rice. This is a Monday pot."], picayune, { cal: 420, protein: 22, carbs: 64, fat: 8 }),
  h("vh-pc-grillades", "Grillades and grits", "Creole", ["era-1900s", "book-picayune", "southern"], "beef", "skillet", 70, "Browned beef rounds in a tomato gravy, grits underneath. The Picayune breakfast.", [I("beef round steaks", 1.5, "lb", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("tomatoes", 3, "", "Produce"), I("flour", 0.33, "cup", "Pantry"), I("grits", 1, "cup", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Pound the steaks thin. Salt, pepper, and dredge in flour. Brown in fat 3 minutes a side. Take out.", "Cook the chopped onion 5 minutes. Add chopped tomatoes and 1 cup water. Simmer 10 minutes.", "Return the meat. Cover and simmer 40 minutes, until the grillades are tender.", "Cook the grits in 4 cups salted water 20 minutes, stirring, until thick. Stir in butter.", "Spoon grits onto plates. Lay grillades and gravy over. Serve hot."], picayune, { cal: 480, protein: 36, carbs: 36, fat: 20 }),
  h("vh-pc-trout-meuniere", "Trout meunière", "Creole", ["era-1900s", "book-picayune", "southern", "quick"], "fish", "fish", 20, "The Picayune trout: floured, fried in butter, a lemon-butter pan sauce.", [I("trout fillets", 1.5, "lb", "Meat & Seafood"), I("flour", 0.5, "cup", "Pantry"), I("butter", 6, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce"), I("parsley", 2, "tbsp", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Pat the trout dry. Salt and pepper. Dredge in flour and shake off the extra.", "Heat 3 tablespoons of butter in a skillet until it foams. Fry the fish 3 minutes a side, until gold and the flesh flakes. Plate it.", "Wipe the pan. Add the remaining butter and cook until it smells nutty, 1 minute — do not blacken it.", "Squeeze in the lemon. Stir in the parsley.", "Pour the butter over the trout. Serve at once."], picayune, { cal: 360, protein: 32, carbs: 8, fat: 22 }),
  h("vh-pc-calas", "Calas", "Creole", ["era-1900s", "book-picayune", "southern", "breakfast", "vegetarian"], "veg", "skillet", 40, "Rice fritters, yeasted, fried, sugared. The old New Orleans street cry.", [I("cooked rice", 2, "cups", "Pantry"), I("flour", 0.5, "cup", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("sugar", 3, "tbsp", "Pantry"), I("yeast", 1, "tsp", "Pantry"), I("oil for frying", 2, "cups", "Pantry")], ["Mash the rice. Mix with flour, eggs, 2 tablespoons sugar, yeast, and ¼ cup warm water. Rest 1 hour, until puffy.", "Heat 2 inches of oil in a deep pot to 365°F.", "Drop the batter by tablespoons. Fry 2–3 minutes, turning, until deep gold.", "Drain on paper. Dust with the remaining sugar.", "Serve the calas hot. These rice cakes do not keep."], picayune, { cal: 180, protein: 4, carbs: 24, fat: 8 }),
  h("vh-pc-pain-perdu", "Pain perdu", "Creole", ["era-1900s", "book-picayune", "southern", "breakfast", "vegetarian"], "eggs", "skillet", 20, "Lost bread: stale slices soaked in egg and milk, fried, sugared.", [I("stale French bread", 8, "slices", "Bakery"), I("eggs", 3, "", "Dairy & Eggs"), I("milk", 1, "cup", "Dairy & Eggs"), I("vanilla", 1, "tsp", "Pantry"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry")], ["Beat the eggs with the milk, vanilla, and a pinch of salt.", "Soak the bread in the custard 1 minute a side, until it drinks but does not fall apart.", "Melt the butter in a skillet over medium heat. Fry the slices 3 minutes a side, until gold.", "Dust the pain perdu with powdered sugar while it is hot.", "Serve at once, with cane syrup if you have it."], picayune, { cal: 280, protein: 10, carbs: 36, fat: 10 }),
  h("vh-pc-courtbouillon", "Redfish courtbouillon", "Creole", ["era-1900s", "book-picayune", "southern"], "fish", "soup", 45, "A Creole courtbouillon: a roux, tomato, a firm fish simmered in the sauce.", [I("redfish or snapper", 2, "lb", "Meat & Seafood"), I("flour", 3, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("tomatoes", 4, "", "Produce"), I("green pepper", 1, "", "Produce"), I("oil", 3, "tbsp", "Pantry")], ["Make a light-brown roux of oil and flour, 8 minutes, stirring. Add chopped onion and pepper. Cook 4 minutes.", "Add chopped tomatoes and 2 cups water. Simmer 15 minutes.", "Salt, cayenne, a bay leaf. Lay the fish pieces in the sauce.", "Cover and simmer 12 minutes, until the fish just flakes. Do not stir or it will break.", "Serve the courtbouillon in soup plates with boiled rice."], picayune, { cal: 320, protein: 36, carbs: 10, fat: 14 }),
  h("vh-pc-shrimp-creole", "Shrimp Creole", "Creole", ["era-1900s", "book-picayune", "southern"], "seafood", "bowl", 35, "The Picayune tomato shrimp: the trinity, a short simmer, rice.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("green pepper", 1, "", "Produce"), I("tomatoes", 4, "", "Produce"), I("rice", 1.5, "cups", "Pantry")], ["Cook the rice in salted water until tender, 18 minutes. Keep warm.", "Cook chopped onion, celery, and pepper in oil 6 minutes. Add chopped tomatoes. Simmer 12 minutes.", "Add the peeled shrimp. Cook 4–5 minutes, until they turn pink and curl. Do not overcook.", "Add salt, cayenne, and a pinch of thyme. Taste the sauce.", "Serve the shrimp and sauce over the rice."], picayune, { cal: 380, protein: 32, carbs: 44, fat: 8 }),
];
