import { I, dish } from "./catalog-kit.ts";
import type { Recipe, RecipeSource } from "./types";

function src(book: string, author: string, year: number, era: string, archiveId: string, credit: string): RecipeSource {
  return { book, author, year, era, archiveId, credit };
}

const jewish = src("The International Jewish Cook Book", "Florence Kreisler Greenbaum", 1918, "1910s", "internationaljew00gree", "Florence Kreisler Greenbaum, The International Jewish Cook Book (Bloch, 1918). Public domain.");
const fulton = src("Vegetarian cookery, 1900–1910", "Early vegetarian household", 1904, "1900s", "earlyveg1904", "Early American vegetarian household cooking, 1900–1910. Public domain.");
const desserts365 = src("365 Desserts", "Anonymous", 1900, "1900s", "365desserts00newy", "365 Desserts: A Dessert for Every Day in the Year (1900). Public domain.");
const twenties = src("American luncheon cookery", "Household pages, 1925", 1925, "1920s", "americanluncheon1925", "American luncheon dishes from public-domain 1925 and earlier household sources.");

function h(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: RecipeSource,
  nutrition: Recipe["nutrition"],
): Recipe {
  return dish({
    id, name, cuisine, description, minutes, protein, plate,
    tags: Array.from(new Set(["vintage", ...tags])),
    ingredients, steps, nutrition, source,
  });
}

export const SWEET_ERA_RECIPES: Recipe[] = [
  h("vh-jw-matzo-ball", "Chicken soup with knaidlach", "Jewish", ["era-1910s", "book-jewish-1918", "soup", "old-school"], "chicken", "soup", 90, "Greenbaum's chicken soup, matzo-meal dumplings simmered in the broth.", [I("chicken", 1, "bird", "Meat & Seafood"), I("matzo meal", 1, "cup", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("carrot", 3, "", "Produce"), I("celery", 3, "stalks", "Produce"), I("onion", 1, "", "Produce")], ["Cover the chicken with water. Add onion, carrot, celery, and salt. Simmer 60 minutes. Skim. Lift the chicken, pull the meat, return it.", "Mix matzo meal, eggs, 2 tablespoons schmaltz or oil, 1 teaspoon salt, and ¼ cup water. Rest 15 minutes.", "With wet hands, roll the matzo mix into walnut-size balls.", "Simmer the balls in the broth 20 minutes, covered, until they swell and are cooked through.", "Taste the soup for salt. Serve a few knaidlach in each bowl."], jewish, { cal: 320, protein: 28, carbs: 18, fat: 14 }),
  h("vh-jw-gefilte", "Gefilte fish", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "fish", "fish", 90, "Greenbaum: ground white fish and carp, onion, egg, poached in a fish broth. Not fried.", [I("white fish fillets", 1, "lb", "Meat & Seafood"), I("carp or pike", 1, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs"), I("matzo meal", 0.33, "cup", "Pantry"), I("carrot", 2, "", "Produce")], ["Grind the fish with 1 onion. Mix with eggs, matzo meal, 1 teaspoon salt, pepper, and ¼ cup cold water until sticky.", "With wet hands, shape the fish mix into oval quenelles.", "Simmer the remaining onion, carrot, fish bones if you have them, and 6 cups water 20 minutes. Strain, keep the carrot.", "Poach the quenelles in the barely simmering broth 30 minutes. Do not boil hard or they break.", "Cool in the liquor. Serve cold with horseradish and a slice of the carrot."], jewish, { cal: 220, protein: 28, carbs: 8, fat: 8 }),
  h("vh-jw-latkes", "Potato latkes", "Jewish", ["era-1910s", "book-jewish-1918", "vegetarian", "breakfast", "old-school"], "veg", "skillet", 35, "Greenbaum's potato pancakes: grated potato, onion, egg, fried in fat.", [I("russet potatoes", 2, "lb", "Produce"), I("onion", 1, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs"), I("flour or matzo meal", 3, "tbsp", "Pantry"), I("salt", 1.5, "tsp", "Herbs & Spices"), I("oil or schmaltz", 0.5, "cup", "Pantry")], ["Peel and grate the potatoes and onion. Squeeze out as much liquid as you can in a cloth.", "Mix the potato with eggs, flour, salt, and pepper.", "Heat ¼ inch of fat in a skillet until it shimmers.", "Drop 3-tablespoon mounds. Flatten. Fry 3–4 minutes a side, until deep gold and crisp at the edges.", "Drain on paper. Serve hot with applesauce or sour cream."], jewish, { cal: 220, protein: 5, carbs: 28, fat: 10 }),
  h("vh-jw-tzimmes", "Carrot tzimmes", "Jewish", ["era-1910s", "book-jewish-1918", "vegetarian", "gluten-free", "old-school"], "veg", "bowl", 50, "Carrots, prunes, honey, a long simmer. Greenbaum's sweet side.", [I("carrots", 2, "lb", "Produce"), I("prunes", 1, "cup", "Pantry"), I("honey", 3, "tbsp", "Pantry"), I("butter or oil", 2, "tbsp", "Dairy & Eggs"), I("cinnamon", 0.5, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Peel and slice the carrots thick. Put in a pot with the prunes, honey, fat, cinnamon, salt, and water to almost cover.", "Bring to a simmer. Cover and cook 35 minutes, until the carrots are very tender.", "Uncover and cook 8 minutes more if the liquor is thin, until it is syrupy.", "Taste. It should be sweet and the prunes soft.", "Serve warm with a roast, or as a Sabbath side."], jewish, { cal: 180, protein: 2, carbs: 36, fat: 5 }),
  h("vh-jw-kugel", "Noodle kugel", "Jewish", ["era-1910s", "book-jewish-1918", "vegetarian", "dessert", "old-school"], "eggs", "dessert", 60, "Greenbaum's baked lokshen kugel: noodles, egg, sugar, raisins.", [I("wide egg noodles", 12, "oz", "Pantry"), I("eggs", 4, "", "Dairy & Eggs"), I("sugar", 0.5, "cup", "Pantry"), I("cottage cheese or sour cream", 1, "cup", "Dairy & Eggs"), I("raisins", 0.5, "cup", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs")], ["Heat the oven to 350°F. Boil the noodles in salted water until just tender, 6 minutes. Drain. Toss with the butter.", "Beat the eggs with the sugar. Stir in the cheese and raisins.", "Fold into the noodles. Pour into a buttered baking dish.", "Bake 40 minutes, until the top is gold and the center is set.", "Cool 10 minutes. Cut into squares. Serve warm."], jewish, { cal: 340, protein: 12, carbs: 44, fat: 12 }),
  h("vh-jw-cabbage-rolls", "Holishkes", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "beef", "roast", 90, "Greenbaum's stuffed cabbage: beef and rice in cabbage leaves, a sweet-sour tomato sauce.", [I("green cabbage", 1, "head", "Produce"), I("ground beef", 1, "lb", "Meat & Seafood"), I("rice", 0.5, "cup", "Pantry"), I("onion", 1, "", "Produce"), I("tomato sauce", 2, "cups", "Pantry"), I("brown sugar", 2, "tbsp", "Pantry")], ["Boil the whole cabbage 8 minutes. Pull off 12 large leaves. Trim the thick rib so they roll.", "Mix beef, uncooked rice, grated onion, 1 teaspoon salt, and pepper. Put 2 tablespoons in each leaf. Fold and roll.", "Lay the rolls in a pot. Pour tomato sauce mixed with brown sugar, 2 tablespoons lemon juice, and ½ cup water over.", "Cover and simmer 70 minutes, until the rice is tender and the leaves are silky.", "Serve the holishkes with the tomato sauce spooned over."], jewish, { cal: 360, protein: 22, carbs: 28, fat: 16 }),
  h("vh-jw-chopped-liver", "Chopped liver", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "chicken", "bowl", 30, "Chicken livers, onion, hard egg, schmaltz. Greenbaum's spread, chopped, not a pâté mill.", [I("chicken livers", 1, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("eggs", 3, "", "Dairy & Eggs"), I("schmaltz or oil", 3, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Hard-cook the eggs 10 minutes. Cool and peel.", "Cook the sliced onion in the fat 12 minutes, until deep gold. Take out. In the same pan, cook the livers 6 minutes, until just pink inside. Cool.", "Chop livers, onion, and eggs together on a board until fine but not a paste.", "Season with salt and pepper. Add a spoon of fat if it is dry.", "Chill the chopped liver. Serve it with rye bread."], jewish, { cal: 260, protein: 20, carbs: 6, fat: 16 }),
  h("vh-jw-blintzes", "Cheese blintzes", "Jewish", ["era-1910s", "book-jewish-1918", "vegetarian", "breakfast"], "eggs", "skillet", 45, "Greenbaum's filled pancakes: a thin batter, farmer cheese, fried in butter.", [I("flour", 1, "cup", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("eggs", 3, "", "Dairy & Eggs"), I("farmer cheese or pot cheese", 1.5, "cups", "Dairy & Eggs"), I("sugar", 3, "tbsp", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs")], ["Beat 2 eggs with the milk, flour, and a pinch of salt into a thin batter. Rest 10 minutes.", "Cook thin 7-inch pancakes in a lightly greased pan, one side only, until the top is dry. Stack.", "Mix cheese, remaining egg, 2 tablespoons sugar, and a pinch of salt. Put a spoon on the cooked side of each pancake. Fold like an envelope.", "Fry the blintzes in butter 3 minutes a side, until gold.", "Dust with remaining sugar. Serve with sour cream."], jewish, { cal: 280, protein: 14, carbs: 24, fat: 14 }),

  h("vh-veg-nut-roast", "Nut roast", "American", ["era-1900s", "book-fulton-veg", "vegetarian", "old-school"], "veg", "roast", 60, "Walnuts, crumbs, onion, egg, baked. The early vegetarian Sunday roast.", [I("walnuts", 2, "cups", "Pantry"), I("bread crumbs", 1.5, "cups", "Bakery"), I("onion", 1, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs"), I("milk", 0.75, "cup", "Dairy & Eggs"), I("sage", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 350°F. Chop the walnuts and onion fine.", "Mix walnuts, crumbs, onion, sage, salt, and pepper.", "Beat the eggs with the milk. Stir into the dry mix until it holds a loaf.", "Pack into a greased pan. Bake 45 minutes, until the top is brown and a knife comes out clean.", "Rest 10 minutes. Slice. Serve with brown gravy or tomato sauce."], fulton, { cal: 400, protein: 12, carbs: 24, fat: 28 }),
  h("vh-veg-lentil-stew", "Lentil stew", "American", ["era-1900s", "book-golden-age", "vegetarian", "vegan", "plant-based", "budget", "soup"], "veg", "soup", 50, "Brown lentils, carrot, onion, a bay leaf. A meatless pot from the early vegetarian books.", [I("brown lentils", 1.5, "cups", "Pantry"), I("carrot", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("tomato paste", 1, "tbsp", "Pantry"), I("bay leaf", 1, "", "Herbs & Spices")], ["Rinse the lentils. Put them in a pot with 6 cups water, chopped onion, carrot, celery, tomato paste, and the bay leaf.", "Bring to a boil. Simmer 40 minutes, until the lentils are tender and the pot is thick.", "Discard the bay leaf. Salt and pepper the lentil stew.", "Mash a few lentils against the side if you want it thicker.", "Serve the lentil stew with bread. No meat is used."], fulton, { cal: 240, protein: 14, carbs: 40, fat: 2 }),
  h("vh-veg-macaroni-tomato", "Macaroni with tomato", "American", ["era-1900s", "book-no-animal", "vegetarian", "vegan", "plant-based", "budget"], "veg", "pasta", 25, "Pasta, a tomato sauce without meat or cheese if you skip it. Early vegetarian Friday.", [I("macaroni", 1, "lb", "Pantry"), I("tomatoes", 6, "", "Produce"), I("onion", 1, "", "Produce"), I("olive oil", 3, "tbsp", "Pantry"), I("basil or parsley", 3, "tbsp", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Boil the macaroni in salted water until just tender, 9 minutes. Drain.", "Cook the chopped onion in oil 6 minutes. Add chopped tomatoes. Simmer 12 minutes, until saucy.", "Salt and pepper the tomato sauce, then stir in the herbs.", "Toss the tomato sauce with the drained macaroni.", "Serve hot. Cheese at the table if your house allows it."], fulton, { cal: 380, protein: 12, carbs: 68, fat: 8 }),
  h("vh-veg-beans-no-pork", "Baked beans without pork", "American", ["era-1900s", "book-fulton-veg", "vegetarian", "vegan", "plant-based", "old-school"], "veg", "bowl", 240, "Pea beans, molasses, mustard, no pork. The vegetarian Boston pot.", [I("pea beans", 1, "lb", "Pantry"), I("molasses", 0.33, "cup", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("onion", 1, "", "Produce"), I("brown sugar", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Soak the beans overnight. Drain. Parboil 10 minutes, until the skins blow. Drain.", "Heat the oven to 300°F. Put beans in a pot with the onion, molasses, mustard, sugar, salt, and boiling water to cover.", "Cover. Bake 4 hours, adding water if they dry, until the beans are tender and the liquor is thick and dark.", "Uncover the last 30 minutes if you want a brown top.", "Serve the baked beans hot. They keep well for the next day."], fulton, { cal: 280, protein: 14, carbs: 52, fat: 1 }),
  h("vh-veg-spinach-eggs", "Spinach with eggs", "American", ["era-1900s", "book-golden-age", "vegetarian", "gluten-free"], "eggs", "skillet", 20, "Wilted spinach, butter, eggs poached or fried on top. A meatless supper.", [I("spinach", 2, "lb", "Produce"), I("eggs", 4, "", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("nutmeg", 1, "pinch", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.25, "tsp", "Herbs & Spices")], ["Wash the spinach well. Put it in a pot with only the water on the leaves. Cover and cook 5 minutes, until wilted. Drain and press dry. Chop.", "Melt the butter. Warm the spinach with nutmeg, salt, and pepper 2 minutes.", "Make four hollows. Crack an egg into each. Cover 4 minutes, until the whites are set and the yolks are still soft.", "Or fry the eggs separately and lay them on.", "Serve the spinach and eggs at once while the yolks are still soft."], fulton, { cal: 180, protein: 12, carbs: 6, fat: 12 }),
  h("vh-veg-hash", "Vegetable hash", "American", ["era-1900s", "book-no-animal", "vegetarian", "budget", "old-school"], "veg", "skillet", 25, "Yesterday's boiled vegetables, chopped, browned in a pan until a crust forms.", [I("cooked potatoes", 3, "cups", "Produce"), I("cooked carrots", 1, "cup", "Produce"), I("onion", 1, "", "Produce"), I("cabbage or leftover greens", 1, "cup", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("parsley", 2, "tbsp", "Produce")], ["Chop the potatoes, carrots, and cabbage. Chop the onion.", "Melt the butter in a skillet. Cook the onion 4 minutes.", "Add the vegetables. Press into an even layer. Cook without stirring 10 minutes, until a brown crust forms.", "Fold or turn out crust-side up. Salt and pepper.", "Scatter parsley. Serve with a fried egg if you eat eggs."], fulton, { cal: 240, protein: 5, carbs: 32, fat: 10 }),


  h("vh-20-club-sandwich", "Club sandwich", "American", ["era-1920s", "sandwich", "old-school"], "chicken", "toast", 20, "Three slices of toast, chicken, bacon, lettuce, tomato, mayonnaise. The 1920s luncheon stack.", [I("white bread", 12, "slices", "Bakery"), I("cooked chicken", 12, "oz", "Meat & Seafood"), I("bacon", 8, "slices", "Meat & Seafood"), I("tomato", 2, "", "Produce"), I("lettuce", 8, "leaves", "Produce"), I("mayonnaise", 0.5, "cup", "Pantry")], ["Toast the bread. Cook the bacon until crisp. Slice the tomato and the chicken.", "Spread mayonnaise on every slice of toast, out to the edges.", "Stack: toast, chicken, lettuce; toast, bacon, tomato; toast on top. Repeat for four sandwiches.", "Pin with toothpicks. Cut in half on the diagonal.", "Serve the club sandwiches at once so the toast stays crisp."], twenties, { cal: 480, protein: 28, carbs: 32, fat: 26 }),
  h("vh-20-deviled-eggs", "Deviled eggs", "American", ["era-1920s", "vegetarian", "quick", "old-school"], "eggs", "green", 20, "The 1920s cocktail egg: yolks mashed with mayonnaise and mustard.", [I("eggs", 8, "", "Dairy & Eggs"), I("mayonnaise", 3, "tbsp", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("vinegar", 1, "tsp", "Pantry"), I("paprika", 0.25, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Cover the eggs with cold water. Bring to a boil, then simmer 10 minutes. Cool in cold water. Peel.", "Halve. Mash the yolks with mayonnaise, mustard, vinegar, and salt until smooth.", "Spoon or pipe the yolk mix back into the egg whites.", "Dust the stuffed eggs with paprika before they go to the table.", "Chill the eggs until serving. These are not baked."], twenties, { cal: 110, protein: 7, carbs: 1, fat: 9 }),
  h("vh-20-cheese-straws", "Cheese straws", "American", ["era-1920s", "baking", "vegetarian", "old-school"], "veg", "bowl", 35, "A 1920s luncheon nibble: cheese pastry, cut in strips, baked crisp.", [I("flour", 1, "cup", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("sharp cheddar", 1, "cup", "Dairy & Eggs"), I("egg yolk", 1, "", "Dairy & Eggs"), I("cayenne", 1, "pinch", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Heat the oven to 375°F. Rub the butter into the flour. Stir in grated cheese, salt, and cayenne.", "Bind with the yolk and a spoon of ice water if needed. Roll ¼ inch thick.", "Cut into 4-inch straws. Twist each if you like.", "Bake 12–14 minutes, until the edges are gold.", "Cool on the sheet. They crisp as they cool."], twenties, { cal: 90, protein: 3, carbs: 6, fat: 6 }),
  h("vh-20-tomato-cocktail", "Tomato juice cocktail", "American", ["era-1920s", "drink", "vegetarian", "vegan", "plant-based", "quick"], "veg", "bowl", 10, "Chilled tomato juice, lemon, Worcestershire, celery salt. The 1920s first course.", [I("tomato juice", 4, "cups", "Pantry"), I("lemon juice", 2, "tbsp", "Produce"), I("Worcestershire", 1, "tsp", "Pantry"), I("celery salt", 0.5, "tsp", "Herbs & Spices"), I("black pepper", 0.25, "tsp", "Herbs & Spices")], ["Chill the tomato juice well, at least 1 hour in the icebox.", "Stir in lemon, Worcestershire, celery salt, and pepper.", "Taste the cocktail. Add a drop more lemon if it is flat.", "Pour the tomato cocktail into small glasses.", "Serve ice-cold before lunch. This is a drink, not a soup."], twenties, { cal: 40, protein: 2, carbs: 8, fat: 0 }),
  h("vh-20-salmon-wiggle", "Salmon wiggle", "American", ["era-1920s", "old-school", "pescatarian", "quick"], "fish", "toast", 20, "The 1920s chafing-dish: canned salmon and peas in white sauce on toast.", [I("canned salmon", 1, "lb", "Meat & Seafood"), I("frozen or canned peas", 1, "cup", "Frozen"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("milk", 2, "cups", "Dairy & Eggs"), I("toast", 8, "slices", "Bakery")], ["Drain and flake the salmon, removing skin and bones.", "Melt the butter, add the flour, cook 2 minutes. Whisk in the milk until smooth and thick, 4 minutes.", "Fold in the salmon and the peas. Heat 3 minutes. Salt and pepper.", "Do not boil hard or the sauce will break.", "Spoon the salmon wiggle over toast. Serve at once."], twenties, { cal: 320, protein: 24, carbs: 22, fat: 14 }),
  h("vh-20-pineapple-gelatin", "Pineapple gelatin salad", "American", ["era-1920s", "dessert", "vegetarian"], "veg", "dessert", 15, "Lemon gelatin, canned pineapple, a mold. The 1920s luncheon sweet salad.", [I("lemon gelatin", 1, "box", "Pantry"), I("canned pineapple", 1, "cup", "Pantry"), I("boiling water", 1, "cup", "Other"), I("celery", 0.5, "cup", "Produce"), I("lettuce", 1, "head", "Produce")], ["Dissolve the gelatin in boiling water. Add 1 cup of the pineapple juice and cold water mixed.", "When it is syrupy, fold in drained pineapple and chopped celery.", "Pour into a mold. Chill the mold at least 4 hours, until the gelatin is set.", "Unmold the pineapple gelatin onto a bed of lettuce.", "Serve cold. Do not bake, and do not add flour."], twenties, { cal: 120, protein: 2, carbs: 28, fat: 0 }),
];
