import type { Recipe } from "./types";

const I = (
  name: string,
  qty: number,
  unit: string,
  aisle: Recipe["ingredients"][number]["aisle"],
) => ({ name, qty, unit, aisle });

function dish(
  partial: Omit<Recipe, "nutrition" | "pack" | "servings"> & {
    nutrition?: Recipe["nutrition"];
    pack?: Recipe["pack"];
    servings?: number;
  },
): Recipe {
  return {
    pack: "free",
    servings: 4,
    nutrition: { cal: 400, protein: 20, carbs: 36, fat: 16 },
    ...partial,
  };
}

export const EXTRA_RECIPES: Recipe[] = [
  dish({
    id: "jiggs-dinner",
    nutrition: { cal: 455, protein: 21, carbs: 73, fat: 11 },
    name: "Jiggs dinner",
    description: "Newfoundland boiled dinner: salt beef, pease pudding, cabbage, and root veg.",
    minutes: 180,
    protein: "beef",
    plate: "roast",
    cuisine: "Newfoundland",
    tags: ["old-school", "newfoundland", "sunday", "atlantic", "comfort"],
    aliases: [
      "boiled dinner",
      "salt beef dinner",
      "salt meat dinner",
      "jigs dinner",
      "jigg's dinner",
      "scoff",
      "sunday scoff",
      "newfoundland dinner",
    ],
    ingredients: [
      I("salt beef", 2, "lb", "Meat & Seafood"),
      I("yellow split peas", 1, "cup", "Pantry"),
      I("cabbage", 1, "head", "Produce"),
      I("potato", 6, "", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("turnip", 1, "", "Produce"),
      I("figgy duff mix or raisins", 1, "cup", "Pantry"),
    ],
    steps: [
      "Soak the 2 pounds of salt beef overnight, changing the water once. Drain, cover with fresh water, and simmer 2 hours, skimming.",
      "Tie the 1 cup of yellow split peas loosely in a pudding cloth — loosely, they swell — and drop the bag in with the meat so they cook into pease pudding.",
      "Tie the 1 cup of figgy duff mix or raisins into a second cloth bag and add it to the pot for the last hour.",
      "Add the 6 potatoes, the 4 carrots, and the turnip, and put the 1 head of quartered cabbage in for the last 40 minutes.",
      "Lift everything onto a platter and slice the beef. Turn the pease pudding out of its bag and mash it with butter. Serve with mustard pickles and a jug of the pot liquor.",
    ],
  }),
  dish({
    id: "toutons",
    nutrition: { cal: 250, protein: 6, carbs: 39, fat: 8 },
    name: "Toutons",
    description: "Fried bread dough, Newfoundland breakfast, with molasses.",
    minutes: 25,
    protein: "veg",
    plate: "toast",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "breakfast", "vegetarian", "atlantic"],
    aliases: ["touton", "touts", "fried dough", "nl breakfast"],
    ingredients: [
      I("bread dough", 1, "lb", "Bakery"),
      I("pork fat or oil", 3, "tbsp", "Pantry"),
      I("molasses", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Pull the 1 pound of risen bread dough into pieces about 3 inches across and flatten each into a disc ½ inch thick.",
      "Melt the 3 tablespoons of pork fat or oil in a wide skillet over medium heat — medium, not high, or the outside colours before the middle cooks.",
      "Fry the discs 3–4 minutes a side, until deep gold and cooked all the way through.",
      "Drain briefly and pour the ¼ cup of molasses over while they are still hot.",
      "Serve right away, while they are still crisp at the edges.",
    ],
  }),
  dish({
    id: "fish-and-brewis",
    nutrition: { cal: 60, protein: 2, carbs: 12, fat: 1 },
    name: "Fish and brewis",
    description: "Salt cod, hard bread, and scrunchions. A winter staple.",
    minutes: 40,
    protein: "fish",
    plate: "bowl",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school", "pescatarian"],
    aliases: ["fish n brewis", "fish 'n brewis", "brewis", "hard bread and fish"],
    ingredients: [
      I("salt cod", 1, "lb", "Meat & Seafood"),
      I("hard bread", 4, "cakes", "Bakery"),
      I("salt pork scrunchions", 4, "oz", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
    ],
    steps: [
      "Soak the 1 pound of salt cod and the 4 cakes of hard bread in separate bowls of cold water overnight. Drain.",
      "Simmer the fish and the bread in fresh water until both are tender, 10–15 minutes. Drain and keep warm.",
      "Set a skillet over medium-high heat. Fry the 4 ounces of salt pork scrunchions with the chopped onion until the pork is crisp and the fat has rendered.",
      "Pile the fish and bread in bowls. Pour the fat and onions over and serve hot.",
    ],
  }),
  dish({
    id: "cod-au-gratin",
    nutrition: { cal: 535, protein: 41, carbs: 14, fat: 35 },
    name: "Cod au gratin",
    description: "Newfoundland baked cod under a cheddar crust.",
    minutes: 45,
    protein: "fish",
    plate: "fish",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "pescatarian", "comfort"],
    aliases: ["cod gratin", "cheesy cod", "nl cod bake"],
    ingredients: [
      I("cod fillets", 1.5, "lb", "Meat & Seafood"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("cheddar", 8, "oz", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
    ],
    steps: [
      "Heat the oven to 375°F. Soften the chopped onion in 1 tablespoon of the butter until translucent, 5 minutes.",
      "Melt the rest of the 3 tablespoons of butter, stir in the 3 tablespoons of flour, and cook 1 minute. Whisk in the 2 cups of milk a little at a time and simmer to a smooth sauce.",
      "Take it off the heat and stir in the onion and two-thirds of the 8 ounces of grated cheddar, just until it melts in. Season well.",
      "Lay the 1½ pounds of raw cod fillets in a buttered dish, pour the sauce over, and scatter the last of the cheddar on top.",
      "Bake 20–25 minutes, until the top is gold and the fish flakes at the thickest part.",
    ],
  }),
  dish({
    id: "pea-soup-doughboys",
    nutrition: { cal: 405, protein: 19, carbs: 55, fat: 12 },
    name: "Pea soup with doughboys",
    description: "Split-pea pot with fluffy dumplings on top.",
    minutes: 90,
    protein: "pork",
    plate: "soup",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school", "budget"],
    aliases: ["doughboys", "pea soup dumplings", "nl pea soup"],
    ingredients: [
      I("yellow split peas", 2, "cups", "Pantry"),
      I("ham bone or salt meat", 1, "", "Meat & Seafood"),
      I("carrot", 2, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("flour", 1.5, "cups", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Rinse the 2 cups of yellow split peas. Put them in a heavy pot with the ham bone or salt meat and 8 cups of water. Bring to a boil, skim, then simmer 75 minutes, until the peas have collapsed.",
      "Soften the chopped onion and the 2 diced carrots in the 2 tablespoons of oil and stir them into the pot. Simmer 15 minutes more. Lift the bone out, pull off any meat, and return it.",
      "Make the doughboys: stir the 1½ cups of flour with the 2 teaspoons of baking powder and a pinch of salt, then mix in the ¾ cup of milk to a soft, sticky dough.",
      "Drop spoonfuls onto the simmering soup, leaving room between them. Cover and cook 15 minutes without lifting the lid — the steam is what raises them.",
      "Season the soup and serve with a doughboy or two in each bowl.",
    ],
  }),
  dish({
    id: "meatloaf",
    nutrition: { cal: 745, protein: 66, carbs: 24, fat: 45 },
    name: "Classic meatloaf",
    description: "The old-school loaf with a ketchup glaze.",
    minutes: 75,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort", "american"],
    aliases: ["meat loaf", "mom's meatloaf", "ketchup loaf"],
    ingredients: [
      I("ground beef", 2, "lb", "Meat & Seafood"),
      I("breadcrumb", 1, "cup", "Pantry"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
      I("ketchup", 0.5, "cup", "Pantry"),
      I("Worcestershire", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Heat the oven to 350°F. Mix the 2 pounds of ground beef, the 1 cup of breadcrumb, the 2 eggs, the chopped onion, the 1 tablespoon of Worcestershire, and 2 tablespoons of the ketchup until just combined. Overworking it makes the loaf dense.",
      "Shape into a loaf in a pan and paint the top with the rest of the ½ cup of ketchup.",
      "Bake about 1 hour, until a thermometer in the middle reads 160°F.",
      "Rest 10 minutes so it slices clean. Cut thick slices and serve.",
    ],
  }),
  dish({
    id: "tuna-casserole",
    nutrition: { cal: 660, protein: 40, carbs: 77, fat: 21 },
    name: "Tuna noodle casserole",
    description: "Creamy noodles, peas, and a crunchy top. Church-basement famous.",
    minutes: 40,
    protein: "fish",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "budget", "pescatarian"],
    aliases: ["tuna bake", "tuna hotdish", "noodle casserole"],
    ingredients: [
      I("egg noodles", 12, "oz", "Pantry"),
      I("canned tuna", 2, "cans", "Pantry"),
      I("cream of mushroom soup", 1, "can", "Pantry"),
      I("frozen peas", 1, "cup", "Frozen"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
      I("potato chips or crumbs", 1, "cup", "Pantry"),
    ],
    steps: [
      "Heat the oven to 375°F. Boil the 12 ounces of egg noodles 2 minutes shy of the packet time, then drain — they finish cooking in the oven.",
      "Warm the 2 tablespoons of oil in a wide pan and stir in the 1 can of cream of mushroom soup with ½ cup of water until smooth.",
      "Fold through the 2 cans of drained tuna, the 1 cup of frozen peas, half the 1 cup of cheddar, the noodles, and the 1 teaspoon of salt.",
      "Scrape into a baking dish, scatter the rest of the cheddar over, then the 1 cup of crushed potato chips.",
      "Bake 25 minutes, until it bubbles at the edges and the top is crisp and gold.",
    ],
  }),
  dish({
    id: "shepherds-pie",
    nutrition: { cal: 820, protein: 52, carbs: 63, fat: 39 },
    name: "Shepherd's pie",
    description: "Minced lamb (or beef cottage pie) under mashed potato.",
    minutes: 60,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort", "british"],
    aliases: ["cottage pie", "shepards pie", "mince and tatties", "potato pie"],
    ingredients: [
      I("ground lamb or beef", 1.5, "lb", "Meat & Seafood"),
      I("potato", 2, "lb", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("peas", 1, "cup", "Frozen"),
      I("onion", 1, "", "Produce"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("milk", 0.5, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 400°F. Boil the 2 pounds of potato until tender, then mash with the 3 tablespoons of butter and the ½ cup of milk. Season well.",
      "Brown the 1½ pounds of ground lamb or beef in a wide skillet with the chopped onion and the 2 diced carrots, 8 minutes, until no pink remains.",
      "Sprinkle over a tablespoon of flour, stir a minute, then add a cup of water or stock and simmer 5 minutes to a thick gravy — without it the filling is dry and the mash slides off.",
      "Stir in the 1 cup of peas and season. Spread the mash over the top in an even layer, sealing it right to the edges.",
      "Bake 25 minutes, until the top is gold and the filling bubbles up at the sides.",
    ],
  }),
  dish({
    id: "chicken-pot-pie",
    nutrition: { cal: 650, protein: 37, carbs: 42, fat: 38 },
    name: "Chicken pot pie",
    description: "A pastry lid over a creamy chicken stew.",
    minutes: 70,
    protein: "chicken",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["pot pie", "chicken pie", "potpie"],
    ingredients: [
      I("cooked chicken", 3, "cups", "Meat & Seafood"),
      I("pie crust", 1, "", "Bakery"),
      I("carrot", 2, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("frozen peas", 1, "cup", "Frozen"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("flour", 0.33, "cup", "Pantry"),
      I("chicken broth", 2, "cups", "Pantry"),
    ],
    steps: [
      "Melt the 4 tablespoons of butter and soften the 2 diced carrots and the 2 stalks of celery, 8 minutes, until they give when pressed.",
      "Stir in the ⅓ cup of flour and cook 1 minute, then whisk in the 2 cups of chicken broth a little at a time. Simmer 4–5 minutes to a thick gravy.",
      "Fold in the 3 cups of cooked chicken and the 1 cup of frozen peas. Season well and cool slightly — a boiling filling melts the pastry before it bakes.",
      "Pour into a dish, lay the pie crust over, trim, and cut two vents in the lid so the steam escapes.",
      "Bake 35 minutes at 400°F, until the crust is deep gold and the filling bubbles at the vents.",
    ],
  }),
  dish({
    id: "beef-stroganoff",
    nutrition: { cal: 860, protein: 61, carbs: 72, fat: 35 },
    name: "Beef stroganoff",
    description: "Sour-cream beef and mushrooms over egg noodles.",
    minutes: 40,
    protein: "beef",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["stroganov", "beef strog", "sour cream beef"],
    ingredients: [
      I("beef sirloin", 1.5, "lb", "Meat & Seafood"),
      I("mushrooms", 8, "oz", "Produce"),
      I("onion", 1, "", "Produce"),
      I("sour cream", 1, "cup", "Dairy & Eggs"),
      I("egg noodles", 12, "oz", "Pantry"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Bring a pot of salted water to a boil and cook the 12 ounces of egg noodles until just tender. Drain.",
      "Set a wide skillet over medium-high heat. Sear strips of the 1½ pounds of beef sirloin until browned. Move to a plate.",
      "In the same pan, melt the 2 tablespoons of butter. Cook the 8 ounces of mushrooms and the chopped onion until soft.",
      "Return the beef. Take the pan off the heat and stir in the 1 cup of sour cream until the sauce is even.",
      "Spoon over the egg noodles and serve hot.",
    ],
  }),
  dish({
    id: "moussaka",
    nutrition: { cal: 745, protein: 52, carbs: 35, fat: 45 },
    name: "Moussaka",
    description: "Layered eggplant, spiced lamb, and béchamel.",
    minutes: 110,
    protein: "beef",
    plate: "roast",
    cuisine: "Greek",
    tags: ["greek", "bake"],
    aliases: ["musaka", "eggplant lamb bake"],
    ingredients: [
      I("eggplant", 2, "", "Produce"),
      I("ground lamb or beef", 1.5, "lb", "Meat & Seafood"),
      I("tomato sauce", 2, "cups", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("flour", 4, "tbsp", "Pantry"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 350°F. Salt slices of the 2 eggplants. Roast until soft and gold, about 25 minutes.",
      "Cook the 1½ pounds of ground lamb or beef with the chopped onion, the 2 cups of tomato sauce, and the ½ teaspoon of cinnamon until the sauce is thick.",
      "Make a béchamel: melt the 4 tablespoons of butter, stir in the 4 tablespoons of flour, then whisk in the 2 cups of milk until thick.",
      "Layer eggplant and meat in a dish. Pour the béchamel over the top in an even layer.",
      "Bake 45 minutes, until the top is gold and the center is set. Rest 10 minutes before cutting.",
    ],
  }),
  dish({
    id: "souvlaki",
    nutrition: { cal: 535, protein: 44, carbs: 32, fat: 26 },
    name: "Chicken souvlaki",
    description: "Lemon-oregano skewers with pita and tzatziki.",
    minutes: 35,
    protein: "chicken",
    plate: "skillet",
    cuisine: "Greek",
    tags: ["greek", "grill"],
    aliases: ["souvlakia", "greek skewers", "kebab greek"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("lemon", 2, "", "Produce"),
      I("dried oregano", 2, "tsp", "Herbs & Spices"),
      I("garlic", 4, "cloves", "Produce"),
      I("pita", 4, "", "Bakery"),
      I("cucumber", 1, "", "Produce"),
      I("Greek yogurt", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Cut the 1½ pounds of chicken thighs into 1½-inch pieces and toss with the juice of 1 lemon, the 2 teaspoons of dried oregano, half the 4 cloves of garlic, the 1 teaspoon of salt, and the 2 tablespoons of oil. Leave 20 minutes.",
      "Thread onto skewers and grill, or sear in a hot ridged pan, 10–12 minutes, turning, until charred at the edges and the pieces read 165°F.",
      "Make the tzatziki: grate the cucumber, squeeze it dry, and stir it into the 1 cup of Greek yogurt with the rest of the garlic, a pinch of salt, and a squeeze of lemon.",
      "Warm the 4 pitas in a dry pan until they puff and flex.",
      "Pile the chicken into the pitas with a spoonful of tzatziki and the last of the lemon squeezed over.",
    ],
  }),
  dish({
    id: "spanakopita",
    nutrition: { cal: 630, protein: 21, carbs: 33, fat: 48 },
    name: "Spanakopita",
    description: "Spinach and feta in shatter-crisp phyllo.",
    minutes: 55,
    protein: "veg",
    plate: "toast",
    cuisine: "Greek",
    tags: ["greek", "vegetarian"],
    aliases: ["spinach pie", "spanakopitta", "greek spinach feta"],
    ingredients: [
      I("phyllo dough", 1, "pack", "Frozen"),
      I("spinach", 2, "lb", "Produce"),
      I("feta", 8, "oz", "Dairy & Eggs"),
      I("dill", 0.25, "cup", "Produce"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("olive oil", 0.33, "cup", "Pantry"),
    ],
    steps: [
      "Wilt spinach, squeeze dry, mix with feta, dill, and eggs.",
      "Layer oiled phyllo, fill, top, score, bake 35 minutes at 375°F.",
    ],
  }),
  dish({
    id: "horiatiki",
    nutrition: { cal: 345, protein: 11, carbs: 27, fat: 22 },
    name: "Horiatiki salad",
    description: "The real Greek village salad. No lettuce.",
    minutes: 15,
    protein: "veg",
    plate: "green",
    cuisine: "Greek",
    tags: ["greek", "vegetarian", "quick"],
    aliases: ["greek salad", "village salad", "horiatiki"],
    ingredients: [
      I("ripe tomatoes", 4, "", "Produce"),
      I("cucumber", 1, "", "Produce"),
      I("red onion", 0.5, "", "Produce"),
      I("Kalamata olives", 0.5, "cup", "Pantry"),
      I("feta slab", 6, "oz", "Dairy & Eggs"),
      I("olive oil", 3, "tbsp", "Pantry"),
      I("dried oregano", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Cut the 4 ripe tomatoes into thick wedges and the cucumber into half-moons. Slice the ½ red onion thin.",
      "Put them in a wide bowl with the ½ cup of Kalamata olives.",
      "Dress with the 3 tablespoons of olive oil and the 1 teaspoon of salt and toss gently, so the tomatoes give up a little juice.",
      "Lay the 6 ounce slab of feta on top whole, do not crumble it, and dust it with the 1 teaspoon of dried oregano.",
      "Let it sit 10 minutes, then serve at room temperature with bread for the juices.",
    ],
  }),
  dish({
    id: "cacio-e-pepe",
    nutrition: { cal: 450, protein: 23, carbs: 66, fat: 10 },
    name: "Cacio e pepe",
    description: "Pasta, pecorino, and a lot of black pepper.",
    minutes: 20,
    protein: "veg",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick", "vegetarian"],
    aliases: ["cacio pepe", "cheese and pepper pasta", "pecorino pasta"],
    ingredients: [
      I("spaghetti or tonnarelli", 12, "oz", "Pantry"),
      I("pecorino romano", 1.5, "cups", "Dairy & Eggs"),
      I("black pepper", 2, "tsp", "Herbs & Spices"),
      I("salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Boil the 12 ounces of spaghetti or tonnarelli in well-salted water. Use less water than usual so it ends up cloudy and thick; that cloudiness is what makes the sauce.",
      "Toast the 2 teaspoons of coarsely cracked black pepper in a dry wide pan over medium heat, 30 seconds, until it smells sharp. The pan stays dry — no fat belongs in this dish.",
      "Ladle in a splash of pasta water and swirl. Drain the pasta 2 minutes early and tip it into the pan with a little more of its water.",
      "Take the pan off the heat and let it stop sizzling. Add the 1½ cups of grated pecorino romano in handfuls, tossing hard — heat above a simmer makes the cheese seize into strings.",
      "Loosen with more pasta water until it turns to a glossy cream that clings to the strands. Serve at once.",
    ],
  }),
  dish({
    id: "carbonara",
    nutrition: { cal: 480, protein: 22, carbs: 67, fat: 12 },
    name: "Spaghetti carbonara",
    description: "Eggs, guanciale, pecorino. No cream.",
    minutes: 25,
    protein: "pork",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick"],
    aliases: ["carbonara pasta", "bacon egg pasta"],
    ingredients: [
      I("spaghetti", 12, "oz", "Pantry"),
      I("guanciale or pancetta", 6, "oz", "Meat & Seafood"),
      I("egg yolks", 4, "", "Dairy & Eggs"),
      I("pecorino romano", 1, "cup", "Dairy & Eggs"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Crisp guanciale. Whisk yolks with pecorino and pepper.",
      "Toss hot pasta with fat, then the egg mixture off heat with pasta water.",
    ],
  }),
  dish({
    id: "puttanesca",
    nutrition: { cal: 435, protein: 14, carbs: 71, fat: 11 },
    name: "Pasta puttanesca",
    description: "Anchovy, olive, caper, tomato. Pantry fireworks.",
    minutes: 25,
    protein: "fish",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick", "pescatarian"],
    aliases: ["putanesca", "olive caper pasta"],
    ingredients: [
      I("spaghetti", 12, "oz", "Pantry"),
      I("anchovy fillets", 6, "", "Pantry"),
      I("Kalamata olives", 0.5, "cup", "Pantry"),
      I("capers", 2, "tbsp", "Pantry"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("garlic", 4, "cloves", "Produce"),
    ],
    steps: [
      "Melt anchovy with garlic in oil. Add tomato, olives, capers. Simmer 10 minutes. Toss pasta.",
    ],
  }),
  dish({
    id: "osso-buco",
    servings: 9,
    nutrition: { cal: 445, protein: 47, carbs: 4, fat: 24 },
    name: "Osso buco",
    description: "Braised veal shanks with gremolata.",
    minutes: 150,
    protein: "beef",
    plate: "roast",
    cuisine: "Italian",
    tags: ["italian", "sunday"],
    aliases: ["ossobuco", "veal shank", "braised shank"],
    ingredients: [
      I("veal shanks", 4, "", "Meat & Seafood"),
      I("carrot", 2, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("onion", 1, "", "Produce"),
      I("white wine", 1, "cup", "Pantry"),
      I("lemon zest", 1, "tbsp", "Produce"),
      I("parsley", 0.25, "cup", "Produce"),
    ],
    steps: [
      "Pat the 4 veal shanks dry, season with the 1 teaspoon of salt, and tie a string round each so they hold together. Brown them hard in the 2 tablespoons of oil in a heavy pot and lift out.",
      "Soften the chopped onion, the 2 carrots, and the 2 stalks of celery in the same pot, 8 minutes.",
      "Pour in the 1 cup of white wine and let it bubble down by half, scraping the pot clean.",
      "Return the shanks standing up so the marrow stays in the bone, add water to come two-thirds up, and simmer covered — on the hob or at 325°F — for 2 hours, until the meat gives at the bone.",
      "Chop the ¼ cup of parsley with the 1 tablespoon of lemon zest and scatter this gremolata over each shank as it goes to the table. Cooked into the pot it loses the point.",
    ],
  }),
  dish({
    id: "tacos-al-pastor",
    nutrition: { cal: 715, protein: 52, carbs: 48, fat: 34 },
    name: "Tacos al pastor",
    description: "Achiote pork, pineapple, onion, cilantro.",
    minutes: 40,
    protein: "pork",
    plate: "taco",
    cuisine: "Mexican",
    tags: ["mexican"],
    aliases: ["al pastor", "pastor tacos", "pineapple pork tacos"],
    ingredients: [
      I("pork shoulder", 1.5, "lb", "Meat & Seafood"),
      I("achiote paste", 2, "tbsp", "Herbs & Spices"),
      I("pineapple", 1, "cup", "Produce"),
      I("corn tortillas", 12, "", "Bakery"),
      I("white onion", 1, "", "Produce"),
      I("cilantro", 1, "bunch", "Produce"),
    ],
    steps: [
      "Slice the 1½ pounds of pork shoulder as thin as you can — this is a thin-cut dish, and a thick slice of shoulder will not cook in a pan.",
      "Toss the slices with the 2 tablespoons of achiote paste and the 1 teaspoon of salt and leave 20 minutes.",
      "Sear in the 2 tablespoons of oil in a very hot skillet in batches, 2–3 minutes a side, until the edges char and no pink remains. Chop roughly.",
      "Char the 1 cup of pineapple in the same pan until it takes colour, then chop it in with the pork.",
      "Warm the 12 corn tortillas 20–30 seconds a side. Fill, and top with the finely diced white onion and the 1 bunch of chopped cilantro.",
    ],
  }),
  dish({
    id: "chicken-tikka-masala",
    nutrition: { cal: 675, protein: 46, carbs: 72, fat: 23 },
    name: "Chicken tikka masala",
    description: "Charred tikka in a creamy tomato masala.",
    minutes: 50,
    protein: "chicken",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "comfort"],
    aliases: ["CTM", "tikka masala", "butter chicken-ish"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("plain yogurt", 0.5, "cup", "Dairy & Eggs"),
      I("garam masala", 2, "tsp", "Herbs & Spices"),
      I("tomato puree", 1, "cup", "Pantry"),
      I("cream", 0.5, "cup", "Dairy & Eggs"),
      I("garlic", 4, "cloves", "Produce"),
      I("fresh ginger", 1, "tbsp", "Produce"),
    ],
    steps: [
      "Mix the 1½ pounds of chicken thighs with the ½ cup of plain yogurt, the 2 teaspoons of garam masala, and the 1 teaspoon of salt. Rest 20 minutes, or overnight in the fridge.",
      "Broil 10–12 minutes, turning once, until the edges char and the thickest piece reads 165°F.",
      "Simmer the 1 cup of tomato puree with the 4 cloves of garlic and the 1 tablespoon of ginger 6 minutes, then stir in the ½ cup of cream and cook 4 minutes more, until the sauce coats a spoon.",
      "Cut the chicken into chunks, nestle them into the sauce with any charred juices, and simmer 5 minutes so they drink the gravy.",
      "Serve over the 1½ cups of cooked rice.",
    ],
  }),
  dish({
    id: "chana-masala",
    nutrition: { cal: 325, protein: 14, carbs: 46, fat: 11 },
    name: "Chana masala",
    description: "Chickpeas in a tangy tomato-onion gravy.",
    minutes: 35,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian", "budget"],
    aliases: ["chole", "chickpea curry", "channa masala"],
    ingredients: [
      I("chickpeas", 2, "cans", "Pantry"),
      I("onion", 2, "", "Produce"),
      I("tomato", 3, "", "Produce"),
      I("garam masala", 2, "tsp", "Herbs & Spices"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("fresh ginger", 1, "tbsp", "Produce"),
      I("cilantro", 0.25, "cup", "Produce"),
    ],
    steps: [
      "Cook the 2 chopped onions in oil over medium heat 8 minutes, until gold.",
      "Stir in the 1 tablespoon of fresh ginger, the 2 teaspoons of garam masala, and the 1 teaspoon of cumin for 30 seconds.",
      "Add the 3 tomatoes. Cook 6 minutes, until they slump.",
      "Add the 2 cans of chickpeas and ½ cup of water. Simmer 15 minutes, until the gravy thickens.",
      "Scatter the ¼ cup of cilantro over. Serve hot.",
    ],
  }),
  dish({
    id: "mapo-tofu",
    nutrition: { cal: 230, protein: 19, carbs: 8, fat: 14 },
    name: "Mapo tofu",
    description: "Silken tofu in a numbing chili-pork sauce.",
    minutes: 25,
    protein: "pork",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["east-asian", "spicy", "quick"],
    aliases: ["mapo doufu", "spicy tofu", "sichuan tofu"],
    ingredients: [
      I("soft tofu", 14, "oz", "Produce"),
      I("ground pork", 4, "oz", "Meat & Seafood"),
      I("doubanjiang", 2, "tbsp", "Pantry"),
      I("garlic", 3, "cloves", "Produce"),
      I("ginger", 1, "tsp", "Produce"),
      I("soy sauce", 1, "tbsp", "Pantry"),
      I("green onion", 3, "", "Produce"),
    ],
    steps: [
      "Set a wide skillet over medium-high heat. Brown the 4 ounces of ground pork, breaking it up, 4–5 minutes.",
      "Add the 2 tablespoons of doubanjiang, the 3 cloves of garlic, and the 1 teaspoon of ginger. Stir 30 seconds until it smells hot and fermented.",
      "Cut the 14 ounces of soft tofu into cubes. Slide them into the pan with the 1 tablespoon of soy sauce and a splash of water.",
      "Simmer gently 5 minutes so the tofu drinks the sauce. Do not stir hard or the cubes will break.",
      "Scatter the 3 green onions over the top and serve hot.",
    ],
  }),
  dish({
    id: "okonomiyaki",
    nutrition: { cal: 300, protein: 8, carbs: 33, fat: 15 },
    name: "Okonomiyaki",
    description: "Osaka cabbage pancake with okonomi sauce.",
    minutes: 30,
    protein: "eggs",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east-asian", "japanese"],
    aliases: ["cabbage pancake", "osaka pancake", "okonomi"],
    ingredients: [
      I("cabbage", 0.5, "head", "Produce"),
      I("flour", 1, "cup", "Pantry"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("dashi or water", 0.75, "cup", "Pantry"),
      I("okonomi sauce", 3, "tbsp", "Pantry"),
      I("mayo", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Shred the ½ head of cabbage fine. Beat the 2 eggs with the ¾ cup of dashi or water and the 1 teaspoon of salt, then whisk in the 1 cup of flour to a thick batter.",
      "Fold the cabbage through — it should look like more cabbage than batter.",
      "Set a skillet over medium heat with the 2 tablespoons of oil. Spoon the mixture in and pat it into a round cake about an inch thick. Do not press it flat as it cooks or it turns dense.",
      "Cook 5–6 minutes, until the underside is deep gold and set, then flip and give it 5–6 minutes more, until a skewer comes out clean.",
      "Slide onto a plate. Brush the 3 tablespoons of okonomi sauce over the top and zigzag the 2 tablespoons of mayo across it. Serve hot.",
    ],
  }),
  dish({
    id: "falafel-pita",
    nutrition: { cal: 405, protein: 13, carbs: 49, fat: 18 },
    name: "Falafel pita",
    description: "Crisp chickpea fritters with tahini and pickles.",
    minutes: 40,
    protein: "veg",
    plate: "taco",
    cuisine: "Middle Eastern",
    tags: ["middle-eastern", "vegetarian"],
    aliases: ["falafel sandwich", "chickpea fritters", "taameya"],
    ingredients: [
      I("dried chickpeas", 1.5, "cups", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("parsley", 1, "bunch", "Produce"),
      I("cumin", 2, "tsp", "Herbs & Spices"),
      I("pita", 4, "", "Bakery"),
      I("tahini", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Soak the 1½ cups of dried chickpeas in plenty of cold water overnight. Do not cook them and do not use canned — cooked chickpeas will not hold together.",
      "Drain well and blitz with the chopped onion, the 4 cloves of garlic, the 1 bunch of parsley, the 2 teaspoons of cumin, and the 1 teaspoon of salt to a coarse paste. Rest 30 minutes, then shape into small patties.",
      "Fry in the 2 tablespoons of oil over medium heat, 3–4 minutes a side, until deep brown and crisp through. Drain on a rack.",
      "Loosen the ¼ cup of tahini with cold water and lemon until it pours.",
      "Warm the 4 pitas, split them, and fill with falafel, tahini, and pickles.",
    ],
  }),
  dish({
    id: "shakshuka-pepper",
    nutrition: { cal: 300, protein: 14, carbs: 27, fat: 15 },
    name: "Shakshuka with peppers",
    description: "North African eggs in a pepper-tomato pan.",
    minutes: 30,
    protein: "eggs",
    plate: "skillet",
    cuisine: "Middle Eastern",
    tags: ["middle-eastern", "vegetarian", "quick"],
    aliases: ["eggs in purgatory", "shakshouka", "matbucha eggs"],
    ingredients: [
      I("eggs", 6, "", "Dairy & Eggs"),
      I("bell peppers", 2, "", "Produce"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Set a skillet over medium heat with oil. Cook the chopped onion and the 2 bell peppers 6–8 minutes, until soft.",
      "Add the 1 can of crushed tomatoes, the 1 teaspoon of paprika, the 1 teaspoon of cumin, and a pinch of salt. Simmer 10 minutes, until the sauce is thick enough to hold a well.",
      "Make wells in the sauce with a spoon. Crack in the 6 eggs.",
      "Cover and cook 5–7 minutes, until the whites are set and the yolks are still soft.",
      "Rest 2 minutes, then plate and serve hot. Warm bread on the side if you have it.",
    ],
  }),
  dish({
    id: "coq-au-vin",
    nutrition: { cal: 805, protein: 78, carbs: 9, fat: 41 },
    name: "Coq au vin",
    description: "Chicken braised in red wine with lardons and mushrooms.",
    minutes: 120,
    protein: "chicken",
    plate: "roast",
    cuisine: "French",
    tags: ["french", "sunday"],
    aliases: ["chicken in wine", "coq au vin rouge"],
    ingredients: [
      I("chicken pieces", 3, "lb", "Meat & Seafood"),
      I("red wine", 2, "cups", "Pantry"),
      I("bacon lardons", 4, "oz", "Meat & Seafood"),
      I("mushrooms", 8, "oz", "Produce"),
      I("pearl onions", 1, "cup", "Produce"),
      I("thyme", 4, "sprigs", "Produce"),
    ],
    steps: [
      "Render the 4 ounces of bacon lardons in a heavy pot until crisp and lift them out. Pat the 3 pounds of chicken pieces dry, season with the 1 teaspoon of salt, and brown them hard in the fat with the 2 tablespoons of oil. Lift out.",
      "Brown the 1 cup of pearl onions and the 8 ounces of mushrooms in the same pot and set them aside with the bacon.",
      "Pour in the 2 cups of red wine, scraping the pot clean, and let it bubble 5 minutes to cook off the raw edge.",
      "Return the chicken and the 4 sprigs of thyme, cover, and simmer very gently 1 hour, until the meat pulls from the bone.",
      "Return the bacon, onions and mushrooms for the last 10 minutes. Skim the fat and serve from the pot.",
    ],
  }),
  dish({
    id: "biscuits-gravy",
    nutrition: { cal: 660, protein: 29, carbs: 37, fat: 45 },
    name: "Biscuits and sausage gravy",
    description: "Southern breakfast: tender biscuits drowned in peppered gravy.",
    minutes: 35,
    protein: "pork",
    plate: "toast",
    cuisine: "American",
    tags: ["old-school", "american", "breakfast"],
    aliases: ["sausage gravy", "sawmill gravy", "biscuits n gravy"],
    ingredients: [
      I("breakfast sausage", 1, "lb", "Meat & Seafood"),
      I("flour", 0.25, "cup", "Pantry"),
      I("milk", 3, "cups", "Dairy & Eggs"),
      I("biscuit mix or homemade biscuits", 8, "", "Bakery"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Bake the 8 biscuits, from mix or homemade, according to their packet or recipe, and keep them warm.",
      "Crumble the 1 pound of breakfast sausage into a wide skillet with the 2 tablespoons of oil and cook over medium heat 8 minutes, breaking it up, until no pink remains and the edges have browned.",
      "Sprinkle the ¼ cup of flour over the meat and its fat and cook 1–2 minutes, stirring, until the raw flour smell goes.",
      "Whisk in the 3 cups of milk a little at a time so it stays smooth. Simmer 6–8 minutes, stirring, until the gravy coats a spoon — it thickens further off the heat.",
      "Season hard with the 1 teaspoon of black pepper and the 1 teaspoon of salt. Split the biscuits and ladle the gravy over.",
    ],
  }),
  dish({
    id: "jerk-chicken",
    nutrition: { cal: 545, protein: 66, carbs: 4, fat: 29 },
    name: "Jerk chicken",
    description: "Scotch bonnet, allspice, and thyme on grilled chicken.",
    minutes: 50,
    protein: "chicken",
    plate: "roast",
    cuisine: "Caribbean",
    tags: ["caribbean", "spicy"],
    aliases: ["jamaican jerk", "jerk BBQ"],
    ingredients: [
      I("chicken pieces", 3, "lb", "Meat & Seafood"),
      I("scotch bonnet", 1, "", "Produce"),
      I("allspice", 1, "tbsp", "Herbs & Spices"),
      I("fresh thyme", 1, "tbsp", "Produce"),
      I("green onion", 4, "", "Produce"),
      I("soy sauce", 2, "tbsp", "Pantry"),
      I("lime", 1, "", "Produce"),
    ],
    steps: [
      "Blitz the scotch bonnet (seeds out unless you want it fierce), the 4 green onions, the 1 tablespoon of allspice, the 1 tablespoon of fresh thyme, the 2 tablespoons of soy sauce, the juice of the lime, the 1 teaspoon of salt, and the 2 tablespoons of oil to a rough paste. Wash your hands before touching your face.",
      "Rub it all over and into the 3 pounds of chicken pieces, getting under the skin. Marinate at least 4 hours, overnight for the real thing.",
      "Heat the oven to 400°F, or set a grill up for indirect heat.",
      "Cook 40–45 minutes, turning once, until the skin is blistered and dark and the thickest part reads 165°F.",
      "Rest 8–10 minutes, then chop through the bone into pieces the way it is served at the drum, and squeeze more lime over.",
    ],
  }),
  dish({
    id: "pad-thai",
    nutrition: { cal: 530, protein: 37, carbs: 61, fat: 16 },
    name: "Pad Thai",
    description: "Tamarind noodles, egg, shrimp or tofu, crushed peanut.",
    minutes: 30,
    protein: "seafood",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east-asian", "thai", "quick"],
    aliases: ["pad tai", "thai noodles", "phat thai"],
    ingredients: [
      I("rice noodles", 8, "oz", "Pantry"),
      I("shrimp", 12, "oz", "Meat & Seafood"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("tamarind paste", 2, "tbsp", "Pantry"),
      I("fish sauce", 2, "tbsp", "Pantry"),
      I("bean sprouts", 2, "cups", "Produce"),
      I("peanuts", 0.33, "cup", "Pantry"),
    ],
    steps: [
      "Soak the 8 ounces of rice noodles in hot tap water 20 minutes, until bendy but still firm. They finish in the pan; boiled, they turn to paste.",
      "Stir the 2 tablespoons of tamarind paste with the 2 tablespoons of fish sauce, the 1 teaspoon of salt, and a spoon of sugar to make the sauce.",
      "Get a wok or wide skillet very hot with the 2 tablespoons of oil. Sear the 12 ounces of shrimp 1 minute a side, until just pink, and push them to the side.",
      "Crack the 2 eggs into the space, scramble them roughly, then add the drained noodles and the sauce. Toss hard 2–3 minutes, until the noodles soften and take the colour.",
      "Throw in the 2 cups of bean sprouts and toss 30 seconds — they should stay raw and squeaky. Turn out and scatter the ⅓ cup of crushed peanuts over.",
    ],
  }),
  dish({
    id: "quiche-lorraine",
    nutrition: { cal: 765, protein: 29, carbs: 30, fat: 59 },
    name: "Quiche Lorraine",
    description: "Custard, bacon, and Gruyère in a pastry shell.",
    minutes: 60,
    protein: "eggs",
    plate: "toast",
    cuisine: "French",
    tags: ["french", "brunch"],
    aliases: ["bacon quiche", "lorraine tart"],
    ingredients: [
      I("pie crust", 1, "", "Bakery"),
      I("bacon", 6, "slices", "Meat & Seafood"),
      I("eggs", 4, "", "Dairy & Eggs"),
      I("cream", 1.5, "cups", "Dairy & Eggs"),
      I("Gruyère", 4, "oz", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 375°F. Blind-bake the pie crust 12 minutes, until the bottom looks dry and sandy.",
      "Cook the 6 slices of bacon until crisp, drain them, and chop. Raw bacon in the custard renders into a greasy layer and never crisps.",
      "Scatter the bacon and the 4 ounces of grated Gruyère over the base of the crust.",
      "Beat the 4 eggs with the 1½ cups of cream and the 1 teaspoon of salt and pour it over the filling.",
      "Bake 30–35 minutes, until the centre is just set and still has a faint wobble. Rest 10 minutes, then slice.",
    ],
  }),
  dish({
    id: "red-beans-rice",
    nutrition: { cal: 755, protein: 33, carbs: 107, fat: 22 },
    name: "Red beans and rice",
    description: "Monday pot: creamy beans, smoked sausage, rice.",
    minutes: 120,
    protein: "pork",
    plate: "bowl",
    cuisine: "American",
    tags: ["american", "old-school", "budget"],
    aliases: ["red beans", "monday beans", "cajun beans"],
    ingredients: [
      I("dried red kidney beans", 1, "lb", "Pantry"),
      I("andouille sausage", 12, "oz", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("rice", 2, "cups", "Pantry"),
    ],
    steps: [
      "Soak the 1 pound of dried red kidney beans in plenty of cold water overnight, or at least 8 hours. Drain and rinse.",
      "Cover the beans with fresh water and boil them hard for a full 10 minutes before doing anything else. Raw and undercooked red kidney beans contain a toxin that only a rolling boil destroys — a low simmer will not do it.",
      "Brown slices of the 12 ounces of andouille sausage in a heavy pot. Add the chopped onion, the 2 stalks of celery, and the chopped bell pepper and cook 5 minutes, until soft.",
      "Add the beans with their water and simmer 90 minutes, stirring now and then, until creamy. Mash a few against the side of the pot to thicken it. Season with the 1 teaspoon of salt.",
      "Cook the 2 cups of rice until tender. Spoon the beans over and serve hot.",
    ],
  }),
  dish({
    id: "pastitsio",
    servings: 6,
    nutrition: { cal: 795, protein: 49, carbs: 69, fat: 36 },
    name: "Pastitsio",
    description: "Greek baked pasta with cinnamon meat and béchamel.",
    minutes: 90,
    protein: "beef",
    plate: "pasta",
    cuisine: "Greek",
    tags: ["greek", "bake"],
    aliases: ["pastichio", "greek lasagna", "makaronia tou fournou"],
    ingredients: [
      I("bucatini or penne", 1, "lb", "Pantry"),
      I("ground beef", 1.5, "lb", "Meat & Seafood"),
      I("tomato sauce", 2, "cups", "Pantry"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("béchamel (milk, butter, flour)", 3, "cups", "Dairy & Eggs"),
      I("kefalotyri or parmesan", 4, "oz", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 350°F. Boil the 1 pound of bucatini or penne 2 minutes shy of al dente and drain.",
      "Brown the 1½ pounds of ground beef in a wide pan, breaking it up, until no pink remains. Add the 2 cups of tomato sauce, the ½ teaspoon of cinnamon, and the 1 teaspoon of salt, and simmer 15 minutes, until thick.",
      "Toss the pasta with half the 4 ounces of grated kefalotyri or parmesan and spread it in a baking dish.",
      "Spoon the meat over in an even layer, then pour the 3 cups of béchamel across the top and smooth it to the edges.",
      "Scatter the rest of the cheese and bake 45 minutes, until set and deep gold. Rest 20 minutes before cutting or it will not hold its layers.",
    ],
  }),
  dish({
    id: "welsh-rarebit",
    nutrition: { cal: 315, protein: 17, carbs: 16, fat: 20 },
    name: "Welsh rarebit",
    description: "Beer-cheese on toast. Old-school supper.",
    minutes: 20,
    protein: "veg",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "vegetarian", "quick", "british"],
    aliases: ["welsh rabbit", "cheese toast", "rarebit"],
    ingredients: [
      I("sharp cheddar", 8, "oz", "Dairy & Eggs"),
      I("ale or beer", 0.5, "cup", "Pantry"),
      I("mustard", 1, "tsp", "Pantry"),
      I("Worcestershire", 1, "tsp", "Pantry"),
      I("sourdough", 4, "slices", "Bakery"),
    ],
    steps: [
      "Toast the 4 slices of sourdough on both sides and set them on a tray that can go under the broiler.",
      "Melt the 8 ounces of grated sharp cheddar with the ½ cup of ale, the 1 teaspoon of mustard, and the 1 teaspoon of Worcestershire over low heat, stirring, until smooth. Do not let it boil or it will split.",
      "Spoon the hot cheese thickly over the toast, right to the crusts so the edges do not burn.",
      "Broil 1–2 minutes, until bubbling and spotted gold.",
      "Serve at once, while it is still flowing.",
    ],
  }),
];

