import { I, dish } from "./catalog-kit.ts";
import type { Recipe } from "./types";

/** Sauces and dry rubs live in the main library — search them, do not silo them. */
export const SAUCE_RECIPES: Recipe[] = [
  dish({
    id: "donair-sauce-mom-pop",
    name: "Mom-and-pop donair sauce",
    description: "East Coast shop sauce: evaporated milk, sugar, garlic, and vinegar. The one that drips down the pita.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Nova Scotia",
    tags: ["sauce", "maritimes", "atlantic", "nova-scotia", "vegetarian", "quick"],
    aliases: ["mom and pop donair sauce", "homemade donair sauce", "halifax garlic sauce", "donair sweet sauce"],
    nutrition: { cal: 135, protein: 4, carbs: 22, fat: 4 },
    ingredients: [
      I("evaporated milk", 1, "can", "Pantry"),
      I("white sugar", 0.66, "cup", "Pantry"),
      I("garlic powder", 2, "tsp", "Herbs & Spices"),
      I("white vinegar", 3, "tbsp", "Pantry"),
      I("onion powder", 0.25, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Whisk evaporated milk, sugar, garlic powder, and onion powder until the sugar dissolves.",
      "Stream in vinegar. It will thicken in a minute. Taste — it should be sweet, garlicky, and just sharp.",
      "Chill 20 minutes. Spoon generously over donair meat, fries, or pizza.",
    ],
  }),
  dish({
    id: "donair-sauce-greco",
    name: "Greco-style donair sauce",
    description: "The chain-shop cousin: thicker, sweeter, heavier on garlic. The sauce people mean when they say Greco.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Nova Scotia",
    tags: ["sauce", "maritimes", "atlantic", "nova-scotia", "vegetarian", "quick"],
    aliases: ["greco donair sauce", "greco sauce", "greek pizza donair sauce", "greco garlic sauce"],
    nutrition: { cal: 150, protein: 4, carbs: 23, fat: 5 },
    ingredients: [
      I("evaporated milk", 1, "can", "Pantry"),
      I("condensed milk", 0.25, "cup", "Pantry"),
      I("white sugar", 0.5, "cup", "Pantry"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("white vinegar", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Whisk the 1 can of evaporated milk with the ¼ cup of condensed milk, the ½ cup of white sugar, the 1 tablespoon of garlic powder, and the 1 teaspoon of salt until the sugar has dissolved.",
      "Stream in the 2 tablespoons of white vinegar a little at a time, whisking. It thickens as the acid hits the milk — pour it in all at once and it seizes into curds instead.",
      "Do not heat it. This sauce is never cooked; warming it splits it.",
      "Chill 20 minutes to firm up. It should be thick enough to coat a spoon and cling to a pita.",
    ],
  }),
  dish({
    id: "donair-sauce-pizza-delight",
    name: "Pizza Delight donair sauce",
    description: "Maritime pizza-shop style: a little tangier, garlic-salt forward, made for donair pizza and garlic fingers.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "New Brunswick",
    tags: ["sauce", "maritimes", "atlantic", "new-brunswick", "vegetarian", "quick"],
    aliases: [
      "pizza delight donair sauce",
      "pizza delight sauce",
      "pd donair sauce",
      "garlic fingers sauce",
      "donair pizza sauce",
    ],
    nutrition: { cal: 120, protein: 4, carbs: 18, fat: 4 },
    ingredients: [
      I("evaporated milk", 1, "can", "Pantry"),
      I("white sugar", 0.5, "cup", "Pantry"),
      I("garlic salt", 1.5, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("white vinegar", 4, "tbsp", "Pantry"),
      I("lemon juice", 1, "tsp", "Produce"),
    ],
    steps: [
      "Whisk the 1 can of evaporated milk with the ½ cup of white sugar, the 1½ teaspoons of garlic salt, and the 1 teaspoon of garlic powder until the sugar dissolves.",
      "Stream in the 4 tablespoons of white vinegar and the 1 teaspoon of lemon juice, whisking, until it thickens.",
      "Taste — this one should read brighter and sharper than a mom-and-pop sauce.",
      "Chill, then pour over donair pizza, garlic fingers, or a pita.",
    ],
  }),
  dish({
    id: "memphis-dry-rub",
    name: "Memphis dry rub",
    description: "Paprika, brown sugar, chili. The ribs do not need a mop — this is the bark.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "tennessee", "vegetarian", "quick"],
    aliases: ["memphis rub", "rib rub", "dry rib rub"],
    nutrition: { cal: 35, protein: 1, carbs: 8, fat: 1 },
    ingredients: [
      I("paprika", 0.25, "cup", "Herbs & Spices"),
      I("brown sugar", 3, "tbsp", "Pantry"),
      I("kosher salt", 1, "tbsp", "Herbs & Spices"),
      I("black pepper", 1, "tbsp", "Herbs & Spices"),
      I("chili powder", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 2, "tsp", "Herbs & Spices"),
      I("cayenne", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Mix the ¼ cup of paprika, the 3 tablespoons of brown sugar, the 1 tablespoon of kosher salt, the 1 tablespoon of black pepper, the 1 tablespoon of chili powder, the 2 teaspoons of garlic powder, and the ½ teaspoon of cayenne in a bowl until the colour is even with no clumps.",
      "Store what you do not use in a sealed jar; it keeps 6 months.",
      "Pat the meat dry and rub the mix on hard, until the surface looks like red sand.",
      "Rest 30 minutes on the counter, or overnight in the fridge, before it goes near smoke or oven.",
    ],
  }),
  dish({
    id: "texas-brisket-rub",
    name: "Texas brisket rub",
    description: "Salt, pepper, a little garlic. That is the whole sermon.",
    minutes: 5,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "texas", "vegetarian", "quick"],
    aliases: ["dalmatian rub", "salt and pepper brisket", "texas rub"],
    nutrition: { cal: 35, protein: 0, carbs: 8, fat: 0 },
    ingredients: [
      I("coarse black pepper", 0.25, "cup", "Herbs & Spices"),
      I("kosher salt", 3, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Mix the ¼ cup of coarse black pepper, the 3 tablespoons of kosher salt, the 1 teaspoon of garlic powder, and the ¼ cup of sugar in a bowl until even.",
      "Keep the pepper coarse. Finely ground, it turns dusty and bitter over a long cook.",
      "Pat the brisket dry and rub the mix over every surface, including the fat cap.",
      "Rest 30 minutes on the counter, or overnight in the fridge, so the salt draws in.",
      "This is a seasoning, not a dinner. Smoke or roast the meat however you like after it rests.",
    ],
  }),
  dish({
    id: "montreal-steak-spice",
    name: "Montreal steak spice",
    description: "Cracked pepper, coriander, garlic, dill. The Canadian steakhouse shaker.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "canadian", "vegetarian", "quick"],
    aliases: ["montreal steak seasoning", "steak spice"],
    nutrition: { cal: 35, protein: 0, carbs: 9, fat: 0 },
    ingredients: [
      I("coarse black pepper", 2, "tbsp", "Herbs & Spices"),
      I("kosher salt", 2, "tbsp", "Herbs & Spices"),
      I("coriander seed", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("dill seed", 1, "tsp", "Herbs & Spices"),
      I("red pepper flakes", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Crack the 1 tablespoon of coriander seed and the 1 teaspoon of dill seed coarsely in a mortar or under a pan — whole, they will not release anything.",
      "Mix them with the 2 tablespoons of coarse black pepper, the 2 tablespoons of kosher salt, the 1 tablespoon of garlic powder, the 1 teaspoon of red pepper flakes, the 1 teaspoon of paprika, and the ¼ cup of sugar until even.",
      "Pat the steak dry and press the mix onto both sides.",
      "Rest 30 minutes on the counter, or overnight in the fridge.",
      "This is a seasoning, not a dinner. Grill or sear the steak however you like after it rests.",
    ],
  }),
  dish({
    id: "jerk-dry-rub",
    name: "Jerk dry rub",
    description: "Allspice, thyme, scotch bonnet heat. Wet jerk is a paste — this is the pantry version.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "Caribbean",
    tags: ["dry-rub", "sauce", "spicy", "vegetarian", "quick"],
    aliases: ["jerk seasoning", "jamaican jerk rub"],
    nutrition: { cal: 25, protein: 1, carbs: 6, fat: 0 },
    ingredients: [
      I("allspice", 2, "tbsp", "Herbs & Spices"),
      I("dried thyme", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("onion powder", 1, "tbsp", "Herbs & Spices"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("cayenne", 2, "tsp", "Herbs & Spices"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Mix the 2 tablespoons of allspice, the 1 tablespoon of dried thyme, the 1 tablespoon of garlic powder, the 1 tablespoon of onion powder, the 1 tablespoon of brown sugar, the 2 teaspoons of cayenne, the ½ teaspoon of cinnamon, and the 2 teaspoons of kosher salt in a bowl until even.",
      "Pat the meat dry and rub the mix on all sides.",
      "Rest 30 minutes on the counter, or overnight in the fridge.",
      "This is the pantry version. Wet jerk is a paste with scotch bonnet, scallion and lime blended into it.",
      "Cook the food however you like after it rests — grill, oven, or drum.",
    ],
  }),
  dish({
    id: "cajun-blackening-rub",
    name: "Cajun blackening rub",
    description: "Paprika, thyme, oregano, cayenne. For a screaming-hot skillet and a fish fillet.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "skillet",
    cuisine: "American",
    tags: ["dry-rub", "sauce", "louisiana", "spicy", "vegetarian", "quick"],
    aliases: ["blackening spice", "cajun seasoning"],
    nutrition: { cal: 95, protein: 1, carbs: 10, fat: 7 },
    ingredients: [
      I("paprika", 3, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tbsp", "Herbs & Spices"),
      I("onion powder", 1, "tbsp", "Herbs & Spices"),
      I("dried thyme", 1, "tsp", "Herbs & Spices"),
      I("dried oregano", 1, "tsp", "Herbs & Spices"),
      I("cayenne", 2, "tsp", "Herbs & Spices"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Mix the 3 tablespoons of paprika, the 1 tablespoon of garlic powder, the 1 tablespoon of onion powder, the 1 teaspoon of dried thyme, the 1 teaspoon of dried oregano, the 2 teaspoons of cayenne, the 1 teaspoon of black pepper, the 2 teaspoons of kosher salt, and the ¼ cup of sugar in a bowl until even.",
      "Pat the fish or chicken dry and press the mix on thickly, on both sides.",
      "Blackening needs a screaming-hot cast-iron pan and a lot of smoke — open a window and turn the extractor on before you start.",
      "Cook 2–3 minutes a side in butter or oil, until the crust is dark, then check the fish flakes or the chicken reads 165°F.",
      "The dark crust is toasted spice, not burnt food. If it tastes acrid, the pan was too hot for too long.",
    ],
  }),
  dish({
    id: "kc-bbq-sauce",
    name: "Kansas City BBQ sauce",
    description: "Tomato, molasses, smoke. Thick enough to cling to burnt ends.",
    minutes: 25,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "kansas", "missouri", "vegetarian"],
    aliases: ["kc sauce", "missouri barbecue sauce", "sweet bbq"],
    nutrition: { cal: 145, protein: 1, carbs: 28, fat: 4 },
    ingredients: [
      I("ketchup", 1.5, "cups", "Pantry"),
      I("molasses", 0.25, "cup", "Pantry"),
      I("brown sugar", 0.25, "cup", "Pantry"),
      I("apple cider vinegar", 0.25, "cup", "Pantry"),
      I("worcestershire", 2, "tbsp", "Pantry"),
      I("smoked paprika", 1, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Set a small saucepan over medium-low heat with the 2 tablespoons of oil and warm the 1 teaspoon of garlic powder and the 1 teaspoon of smoked paprika in it for 30 seconds, until they smell toasted.",
      "Whisk in the 1½ cups of ketchup, the ¼ cup of molasses, the ¼ cup of brown sugar, the ¼ cup of apple cider vinegar, and the 2 tablespoons of worcestershire.",
      "Simmer 20 minutes, stirring, until it is thick enough to coat a spoon. Season with the 1 teaspoon of salt.",
      "Cool and keep in a jar. Brush it on in the last minutes of cooking — the sugar burns if it goes on early.",
    ],
  }),
  dish({
    id: "carolina-vinegar-sauce",
    name: "Carolina vinegar sauce",
    description: "Eastern North Carolina: vinegar, pepper, a pinch of sugar. For pulled pork, not ribs.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "north-carolina", "vegetarian", "quick"],
    aliases: ["eastern nc sauce", "vinegar pepper sauce", "whole hog sauce"],
    nutrition: { cal: 30, protein: 0, carbs: 8, fat: 0 },
    ingredients: [
      I("apple cider vinegar", 1.5, "cups", "Pantry"),
      I("red pepper flakes", 2, "tsp", "Herbs & Spices"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
      I("kosher salt", 1, "tsp", "Herbs & Spices"),
      I("brown sugar", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Put the 1½ cups of apple cider vinegar in a jar with the 2 teaspoons of red pepper flakes, the 1 teaspoon of black pepper, the 1 teaspoon of kosher salt, and the 1 tablespoon of brown sugar.",
      "Shake until the sugar and salt dissolve. It is not cooked, not thickened, and not a barbecue sauce in the bottled sense — it is a thin, hot, sour mop.",
      "Leave it at least an hour, overnight if you can, so the pepper bleeds into the vinegar.",
      "Toss it through pulled pork by the ladleful just before serving, and put more on the table. It is for shoulder, not ribs.",
    ],
  }),
  dish({
    id: "alabama-white-sauce",
    name: "Alabama white sauce",
    description: "Mayo, vinegar, black pepper. North Alabama chicken, dunked while it is hot.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "alabama", "vegetarian", "quick"],
    aliases: ["white bbq sauce", "big bob gibson sauce"],
    nutrition: { cal: 195, protein: 0, carbs: 2, fat: 21 },
    ingredients: [
      I("mayonnaise", 1, "cup", "Pantry"),
      I("apple cider vinegar", 0.25, "cup", "Pantry"),
      I("black pepper", 1, "tbsp", "Herbs & Spices"),
      I("lemon juice", 1, "tbsp", "Produce"),
      I("prepared horseradish", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Whisk the 1 cup of mayonnaise with the ¼ cup of apple cider vinegar until smooth and pourable.",
      "Whisk in the 1 tablespoon of black pepper, the 1 tablespoon of lemon juice, the 1 teaspoon of prepared horseradish, and the 1 teaspoon of salt.",
      "Do not put it on heat. It is a mayonnaise sauce and it will split; the recipe is cold from start to finish.",
      "Chill at least an hour so the pepper comes forward.",
      "Dunk hot smoked chicken straight into it, or brush it on in the last minute off the fire.",
    ],
  }),
  dish({
    id: "chimichurri",
    name: "Chimichurri",
    description: "Parsley, garlic, oregano, oil, vinegar. The steak's best friend from Argentina.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "green",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["argentine chimichurri", "parsley garlic sauce"],
    nutrition: { cal: 170, protein: 0, carbs: 1, fat: 18 },
    ingredients: [
      I("fresh parsley", 1, "bunch", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("dried oregano", 1, "tsp", "Herbs & Spices"),
      I("red wine vinegar", 3, "tbsp", "Pantry"),
      I("olive oil", 0.5, "cup", "Pantry"),
      I("red pepper flakes", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Chop parsley and garlic fine. Stir with oregano, vinegar, oil, chili, and salt. Rest 10 minutes."],
  }),
  dish({
    id: "hollandaise",
    name: "Hollandaise",
    description: "Egg yolks, butter, lemon. For asparagus, eggs Benedict, or a quiet Tuesday fish.",
    minutes: 15,
    servings: 4,
    protein: "eggs",
    plate: "bowl",
    cuisine: "French",
    tags: ["sauce", "quick"],
    aliases: ["benedict sauce", "butter lemon sauce"],
    nutrition: { cal: 250, protein: 2, carbs: 2, fat: 26 },
    ingredients: [
      I("egg yolks", 3, "", "Dairy & Eggs"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("lemon", 1, "", "Produce"),
      I("cayenne", 1, "pinch", "Herbs & Spices"),
    ],
    steps: [
      "Melt the ½ cup of butter gently and keep it warm. Squeeze the lemon.",
      "Whisk the 3 egg yolks with a tablespoon of water and a squeeze of the lemon in a bowl set over — not in — barely simmering water.",
      "Whisk constantly 3–4 minutes, until the yolks thicken to ribbons and you can see the bottom of the bowl as you whisk. If the bowl gets too hot to touch, lift it off; this is where it scrambles.",
      "Off the heat, dribble the warm butter in a thread, whisking hard, until it thickens into a glossy sauce. Too fast and the emulsion breaks — a splash of warm water whisked in will usually bring it back.",
      "Season with the 1 teaspoon of salt, the rest of the lemon, and the pinch of cayenne. Keep it barely warm; it splits if it gets hot and sets if it gets cold.",
    ],
  }),
  dish({
    id: "tzatziki",
    name: "Tzatziki",
    description: "Yogurt, cucumber, garlic, dill. Cold against grilled meat or stuffed in pita.",
    minutes: 15,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Greek",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["cacik", "cucumber yogurt sauce"],
    nutrition: { cal: 90, protein: 5, carbs: 8, fat: 5 },
    ingredients: [
      I("greek yogurt", 2, "cups", "Dairy & Eggs"),
      I("cucumber", 1, "", "Produce"),
      I("garlic", 2, "cloves", "Produce"),
      I("fresh dill", 2, "tbsp", "Produce"),
      I("lemon", 0.5, "", "Produce"),
      I("olive oil", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Coarsely grate the cucumber, toss it with a good pinch of the 1 teaspoon of salt, and leave it in a sieve 15 minutes. Then squeeze it dry in a cloth, hard — skipping this is what makes watery tzatziki.",
      "Crush the 2 cloves of garlic to a paste with the rest of the salt.",
      "Stir the cucumber and garlic through the 2 cups of greek yogurt with the 2 tablespoons of chopped fresh dill.",
      "Add the juice of the ½ lemon and the 1 tablespoon of olive oil and stir just to combine. Do not blend it — this is a chunky sauce, not a smooth one.",
      "Chill 30 minutes before serving, cold, alongside grilled meat or in a pita.",
    ],
  }),
  dish({
    id: "romesco",
    name: "Romesco",
    description: "Roasted peppers, tomato, almond, bread. Spanish sauce for fish, eggs, or a spoon.",
    minutes: 25,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Spanish",
    tags: ["sauce", "vegetarian", "nuts"],
    aliases: ["spanish pepper sauce", "romesco sauce"],
    nutrition: { cal: 185, protein: 4, carbs: 9, fat: 15 },
    ingredients: [
      I("roasted red peppers", 2, "", "Pantry"),
      I("tomato", 1, "", "Produce"),
      I("almonds", 0.5, "cup", "Pantry"),
      I("stale bread", 1, "slice", "Bakery"),
      I("garlic", 2, "cloves", "Produce"),
      I("sherry vinegar", 2, "tbsp", "Pantry"),
      I("olive oil", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Toast the ½ cup of almonds and the 1 slice of stale bread in a dry pan until gold.",
      "Blend with the 2 roasted red peppers, the tomato, the 2 cloves of garlic, the 2 tablespoons of sherry vinegar, and the ¼ cup of olive oil until rustic, not baby food.",
      "Salt to taste. Spoon over grilled vegetables or fish.",
    ],
  }),
  dish({
    id: "buffalo-sauce",
    name: "Buffalo sauce",
    description: "Hot sauce melted with butter. Buffalo, New York, and every Super Bowl.",
    minutes: 8,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "new-york", "spicy", "vegetarian", "quick"],
    aliases: ["frank's butter", "wing sauce"],
    nutrition: { cal: 105, protein: 2, carbs: 2, fat: 10 },
    ingredients: [
      I("hot sauce", 0.66, "cup", "Pantry"),
      I("butter", 0.33, "cup", "Dairy & Eggs"),
      I("white vinegar", 1, "tsp", "Pantry"),
      I("garlic powder", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Melt the ⅓ cup of butter into the ⅔ cup of hot sauce over low heat.",
      "Stir in the 1 teaspoon of white vinegar and the ½ teaspoon of garlic powder.",
      "Toss with fried or roasted wings until every piece is coated.",
    ],
  }),
  dish({
    id: "tartar-sauce",
    name: "Tartar sauce",
    description: "Mayo, pickle, caper, lemon. For fish cakes, haddock, or a Friday fry.",
    minutes: 8,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Newfoundland",
    tags: ["sauce", "atlantic", "vegetarian", "quick"],
    aliases: ["tartare", "fish sauce mayo"],
    nutrition: { cal: 195, protein: 1, carbs: 2, fat: 21 },
    ingredients: [
      I("mayonnaise", 0.75, "cup", "Pantry"),
      I("dill pickle", 2, "", "Pantry"),
      I("capers", 1, "tbsp", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
      I("fresh dill", 1, "tbsp", "Produce"),
    ],
    steps: [
      "Chop the 2 dill pickles and the 1 tablespoon of capers fine — a processor turns them to slurry and the sauce needs the pieces.",
      "Chop the 1 tablespoon of fresh dill.",
      "Fold them through the ¾ cup of mayonnaise with the juice of the ½ lemon and the 1 teaspoon of salt.",
      "Taste for salt and sharpness; it should be sharper than you expect, because it is going on fried food.",
      "Chill 20 minutes. Serve cold — this is never heated.",
    ],
  }),
  dish({
    id: "alfredo-sauce",
    name: "Alfredo sauce",
    description: "Butter, cream, parmesan. Roman-ish, American-loved, weeknight-ready.",
    minutes: 15,
    servings: 4,
    protein: "veg",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["fettuccine alfredo sauce", "cream parmesan sauce"],
    nutrition: { cal: 440, protein: 14, carbs: 3, fat: 42 },
    ingredients: [
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("heavy cream", 1, "cup", "Dairy & Eggs"),
      I("parmesan", 1.5, "cups", "Dairy & Eggs"),
      I("garlic", 1, "clove", "Produce"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Melt the 4 tablespoons of butter over low heat with the 1 crushed clove of garlic. Let it infuse 2 minutes, then lift the garlic out.",
      "Pour in the 1 cup of heavy cream and warm it until it just steams. Do not let it boil.",
      "Take the pan off the heat before the cheese goes in. Add the 1½ cups of grated parmesan in handfuls, swirling, until it melts into a smooth sauce — held over heat it turns stringy and weeps butter.",
      "Season with the 1 teaspoon of salt and the ½ teaspoon of black pepper.",
      "Toss with hot pasta straight away, loosening with pasta water. It sets as it cools and does not reheat well.",
    ],
  }),
  dish({
    id: "peanut-sauce",
    name: "Peanut sauce",
    description: "The satay dunk: peanut butter, soy, lime, a little heat.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "nuts", "quick"],
    aliases: ["satay sauce", "gado gado sauce"],
    nutrition: { cal: 145, protein: 6, carbs: 8, fat: 11 },
    ingredients: [
      I("peanut butter", 0.5, "cup", "Pantry"),
      I("soy sauce", 2, "tbsp", "Pantry"),
      I("lime", 1, "", "Produce"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("garlic", 1, "clove", "Produce"),
      I("chili garlic sauce", 1, "tsp", "Pantry"),
      I("warm water", 0.25, "cup", "Other"),
    ],
    steps: [
      "Whisk the ½ cup of peanut butter with the 2 tablespoons of soy sauce, the juice of the lime, the 1 tablespoon of brown sugar, the minced garlic, and the 1 teaspoon of chili garlic sauce.",
      "Thin with the ¼ cup of warm water until the sauce pours off a spoon.",
      "Taste. Serve with chicken satay, tofu, or cucumber.",
    ],
  }),
  dish({
    id: "sweet-chili-sauce",
    name: "Sweet chili sauce",
    description: "Thai-style: sugar, vinegar, chili, garlic. For spring rolls or a boring chicken breast.",
    minutes: 15,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "spicy", "quick"],
    aliases: ["mae ploy style", "thai sweet chili"],
    nutrition: { cal: 85, protein: 0, carbs: 14, fat: 3 },
    ingredients: [
      I("rice vinegar", 0.5, "cup", "Pantry"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("water", 0.25, "cup", "Other"),
      I("garlic", 3, "cloves", "Produce"),
      I("red pepper flakes", 2, "tsp", "Herbs & Spices"),
      I("cornstarch", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Put the ½ cup of rice vinegar, the ½ cup of sugar, the ¼ cup of water, the 3 minced cloves of garlic, the 2 teaspoons of red pepper flakes, and the 1 teaspoon of salt in a small pan.",
      "Bring to a simmer and cook 5–6 minutes, until the sugar has fully dissolved and it smells sweet rather than sharp.",
      "Stir the 1 tablespoon of cornstarch into 2 tablespoons of cold water until smooth. Cornstarch dropped in dry, or bloomed in hot oil, goes lumpy.",
      "Pour the slurry in while whisking and simmer 1 minute, until it turns clear and glossy and coats a spoon.",
      "Cool completely — it thickens a lot as it cools. Keep in a jar in the fridge.",
    ],
  }),
  dish({
    id: "ranch-dressing",
    name: "Ranch dressing",
    description: "Buttermilk, herbs, garlic. Hidden-valley energy, made in a jar.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["homemade ranch", "buttermilk ranch"],
    nutrition: { cal: 130, protein: 1, carbs: 2, fat: 13 },
    ingredients: [
      I("mayonnaise", 0.5, "cup", "Pantry"),
      I("sour cream", 0.5, "cup", "Dairy & Eggs"),
      I("buttermilk", 0.33, "cup", "Dairy & Eggs"),
      I("dried dill", 1, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("onion powder", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Whisk the mayonnaise, sour cream, buttermilk, dried dill, garlic powder, and onion powder until smooth.",
      "Taste. Add a pinch of salt if it tastes flat, a splash more buttermilk if it is stiff.",
      "Chill 20 minutes so it thickens. Spoon over pizza crusts, wings, or a salad.",
    ],
  }),
  dish({
    id: "teriyaki-sauce",
    name: "Teriyaki sauce",
    description: "Soy, mirin, sugar, ginger. Gloss for salmon, chicken, or a pan of broccoli.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["homemade teriyaki", "soy ginger glaze"],
    nutrition: { cal: 50, protein: 1, carbs: 9, fat: 0 },
    ingredients: [
      I("soy sauce", 0.5, "cup", "Pantry"),
      I("mirin", 0.25, "cup", "Pantry"),
      I("brown sugar", 3, "tbsp", "Pantry"),
      I("fresh ginger", 1, "tbsp", "Produce"),
      I("garlic", 1, "clove", "Produce"),
      I("cornstarch", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Put the ½ cup of soy sauce, the ¼ cup of mirin, the 3 tablespoons of brown sugar, the 1 tablespoon of grated ginger, and the 1 minced clove of garlic in a small pan.",
      "Simmer 5 minutes, until the sugar dissolves and the raw edge of the soy has cooked off.",
      "Stir the 1 teaspoon of cornstarch into a tablespoon of cold water and whisk it in.",
      "Simmer 1 minute more, until it turns glossy and thick enough to coat the back of a spoon.",
      "Take it off the heat. Brush onto salmon, chicken or broccoli in the last minutes of cooking — the sugar burns if it goes on early.",
    ],
  }),
  dish({
    id: "basil-pesto",
    name: "Basil pesto",
    description: "Genoa in a jar: basil, pine nuts, garlic, parmesan, oil. Freeze in ice-cube trays.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Italian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["pesto genovese", "green sauce pasta"],
    nutrition: { cal: 185, protein: 3, carbs: 2, fat: 18 },
    ingredients: [
      I("fresh basil", 2, "bunches", "Produce"),
      I("pine nuts", 0.33, "cup", "Pantry"),
      I("garlic", 2, "cloves", "Produce"),
      I("parmesan", 0.5, "cup", "Dairy & Eggs"),
      I("olive oil", 0.5, "cup", "Pantry"),
    ],
    steps: [
      "Toast the ⅓ cup of pine nuts in a dry pan 2–3 minutes, shaking, until they smell nutty and colour lightly. Cool them.",
      "Pound or pulse the 2 bunches of fresh basil leaves with the 2 cloves of garlic, the pine nuts, and the 1 teaspoon of salt to a coarse green paste. Pulse in bursts — a running blade heats the basil and turns it black.",
      "Work in the ½ cup of olive oil in a slow stream.",
      "Stir the ½ cup of grated parmesan through by hand at the end so it stays creamy.",
      "Taste for salt. Keep under a film of oil in the fridge, or freeze it in ice-cube trays.",
    ],
  }),
  dish({
    id: "salsa-verde",
    name: "Salsa verde",
    description: "Tomatillo, cilantro, jalapeño, lime. The green that belongs on eggs and pork.",
    minutes: 20,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Mexican",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["tomatillo salsa", "green salsa"],
    nutrition: { cal: 30, protein: 1, carbs: 6, fat: 1 },
    ingredients: [
      I("tomatillos", 1, "lb", "Produce"),
      I("jalapeño", 2, "", "Produce"),
      I("cilantro", 1, "bunch", "Produce"),
      I("onion", 0.5, "", "Produce"),
      I("lime", 1, "", "Produce"),
    ],
    steps: [
      "Husk the 1 pound of tomatillos and rinse the stickiness off. Put them on a tray with the 2 jalapeños and the ½ onion in thick wedges.",
      "Broil 8–10 minutes, turning once, until blackened in patches and collapsing. Roasting is what takes the raw squeak out — a raw tomatillo salsa is a different sauce.",
      "Tip everything, juices included, into a blender with the 1 bunch of cilantro and the 1 teaspoon of salt.",
      "Pulse to a loose, textured sauce — not a smooth purée.",
      "Squeeze the lime in and taste. Serve warm or cold on eggs, pork or tacos.",
    ],
  }),
  dish({
    id: "weeknight-mole",
    name: "Weeknight mole",
    description: "Not Oaxaca, not a joke: chile, cocoa, peanut butter, broth. Spoon over chicken.",
    minutes: 25,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "Mexican",
    tags: ["sauce", "vegetarian"],
    aliases: ["mole poblano shortcut", "chocolate chile sauce"],
    nutrition: { cal: 85, protein: 2, carbs: 3, fat: 8 },
    ingredients: [
      I("ancho chile", 3, "", "Herbs & Spices"),
      I("cocoa powder", 1, "tbsp", "Pantry"),
      I("peanut butter", 2, "tbsp", "Pantry"),
      I("tomato paste", 1, "tbsp", "Pantry"),
      I("chicken broth", 1.5, "cups", "Pantry"),
      I("cinnamon", 0.25, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Stem and seed the 3 ancho chiles, tear them up, and toast them in a dry pan 30 seconds a side, until they smell sweet. Burn them and the whole sauce turns bitter.",
      "Cover with hot water and soak 20 minutes, until soft.",
      "Warm the 2 tablespoons of oil and fry the 1 tablespoon of tomato paste 1 minute, then add the ¼ teaspoon of cinnamon.",
      "Blend the drained chiles with the tomato paste, the 1 tablespoon of cocoa powder, the 2 tablespoons of peanut butter, and the 1½ cups of chicken broth until smooth.",
      "Return to the pan and simmer 15 minutes, stirring, until it coats a spoon. Season with the 1 teaspoon of salt and spoon over chicken.",
    ],
  }),
  dish({
    id: "peri-peri-sauce",
    name: "Peri-peri sauce",
    description: "African bird's eye heat, lemon, garlic, oil. The chicken shop sauce you can make.",
    minutes: 15,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "African",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["piri piri", "peri peri", "nandos sauce"],
    nutrition: { cal: 55, protein: 0, carbs: 3, fat: 5 },
    ingredients: [
      I("red chiles", 8, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("lemon", 1, "", "Produce"),
      I("smoked paprika", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 3, "tbsp", "Pantry"),
      I("red wine vinegar", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Stem the 8 red chiles. Leave the seeds in for the heat the sauce is known for, or take them out for something gentler.",
      "Blend them with the 4 cloves of garlic, the juice and zest of the lemon, the 1 teaspoon of smoked paprika, the 2 tablespoons of red wine vinegar, and the 1 teaspoon of salt.",
      "With the blender running, pour in the 3 tablespoons of olive oil so it emulsifies into a loose sauce.",
      "Warm it gently in a pan 3–4 minutes if you want the raw garlic softened — but do not boil it, or the fresh chile flavour cooks away.",
      "Rest at least an hour before using. Marinate chicken in half and keep half for the table.",
    ],
  }),
  dish({
    id: "harissa",
    name: "Harissa",
    description: "Tunisian chile paste: roasted peppers, caraway, cumin, garlic. A spoon wakes a stew.",
    minutes: 25,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian", "spicy"],
    aliases: ["tunisian harissa", "chile paste"],
    nutrition: { cal: 45, protein: 0, carbs: 2, fat: 4 },
    ingredients: [
      I("dried chiles", 8, "", "Herbs & Spices"),
      I("roasted red pepper", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("caraway", 1, "tsp", "Herbs & Spices"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 3, "tbsp", "Pantry"),
    ],
    steps: [
      "Stem and seed the 8 dried chiles and soak them in boiling water 20 minutes, until soft and pliable.",
      "Toast the 1 teaspoon of caraway and the 1 teaspoon of cumin in a dry pan until they smell warm, 30 seconds, then grind them.",
      "Blend the drained chiles with the roasted red pepper, the 4 cloves of garlic, the ground spice, and the 1 teaspoon of salt to a thick paste.",
      "Work in the 3 tablespoons of olive oil.",
      "Pack into a jar and cover the surface with a film of oil — that seal is what keeps it for a month in the fridge.",
    ],
  }),
  dish({
    id: "nuoc-cham",
    name: "Nước chấm",
    description: "Vietnamese dipping sauce: fish sauce, lime, sugar, chile, garlic. Spring rolls exist for this.",
    minutes: 8,
    servings: 6,
    protein: "fish",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "quick"],
    aliases: ["nuoc cham", "vietnamese dipping sauce", "fish sauce lime"],
    nutrition: { cal: 30, protein: 1, carbs: 7, fat: 0 },
    ingredients: [
      I("fish sauce", 3, "tbsp", "Pantry"),
      I("lime", 2, "", "Produce"),
      I("sugar", 2, "tbsp", "Pantry"),
      I("garlic", 2, "cloves", "Produce"),
      I("bird chile", 1, "", "Produce"),
      I("water", 0.33, "cup", "Other"),
    ],
    steps: [
      "Dissolve the 2 tablespoons of sugar in the ⅓ cup of warm water — warm, not hot, and only to get the sugar to go.",
      "Stir in the 3 tablespoons of fish sauce and the juice of the 2 limes.",
      "Add the 2 finely minced cloves of garlic and the sliced bird chile. Cut the garlic fine enough to float rather than sink.",
      "Taste and balance: it should read salty, sour and sweet in that order, with the heat arriving last. Adjust with water if it is too strong.",
      "Serve at room temperature. It is never cooked and it does not keep much past a day.",
    ],
  }),
  dish({
    id: "yum-yum-sauce",
    name: "Yum yum sauce",
    description: "Hibachi mayo: ketchup, garlic, paprika, a little sugar. Shrimp, fried rice, broccoli.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["white sauce hibachi", "japanese steakhouse sauce"],
    nutrition: { cal: 225, protein: 0, carbs: 2, fat: 24 },
    ingredients: [
      I("mayonnaise", 1, "cup", "Pantry"),
      I("ketchup", 2, "tbsp", "Pantry"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
      I("sugar", 1, "tsp", "Pantry"),
      I("rice vinegar", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Whisk the 1 cup of mayonnaise with the 2 tablespoons of ketchup until the colour is even and pale coral.",
      "Whisk in the 1 teaspoon of garlic powder, the 1 teaspoon of paprika, the 1 teaspoon of sugar, the 1 teaspoon of rice vinegar, and the 1 teaspoon of salt.",
      "Thin with a tablespoon or two of water until it drizzles rather than sits.",
      "Do not heat it. It is a mayonnaise sauce and warming it breaks it into oil and curds.",
      "Chill at least an hour — it tastes flat straight after mixing and comes together cold.",
    ],
  }),
  dish({
    id: "cocktail-sauce",
    name: "Cocktail sauce",
    description: "Ketchup, horseradish, lemon. Shrimp cocktail and oyster bars.",
    minutes: 5,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["shrimp cocktail sauce", "seafood sauce"],
    nutrition: { cal: 35, protein: 1, carbs: 9, fat: 0 },
    ingredients: [
      I("ketchup", 1, "cup", "Pantry"),
      I("prepared horseradish", 3, "tbsp", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
      I("worcestershire", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Stir the 1 cup of ketchup with the 3 tablespoons of prepared horseradish.",
      "Add the juice of the ½ lemon and the 1 teaspoon of worcestershire.",
      "Taste. It should make your nose sting a little; horseradish fades fast in the fridge, so go heavier than feels right.",
      "Chill 30 minutes. Serve cold with shrimp or oysters.",
    ],
  }),
  dish({
    id: "marinara",
    name: "Marinara",
    description: "Tomato, garlic, olive oil, basil. The weeknight red sauce that is never a jar if you have 20 minutes.",
    minutes: 20,
    servings: 6,
    protein: "veg",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["sunday sauce shortcut", "red sauce"],
    nutrition: { cal: 95, protein: 2, carbs: 7, fat: 7 },
    ingredients: [
      I("crushed tomatoes", 28, "oz", "Pantry"),
      I("garlic", 4, "cloves", "Produce"),
      I("olive oil", 3, "tbsp", "Pantry"),
      I("fresh basil", 8, "leaves", "Produce"),
      I("kosher salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Warm the 3 tablespoons of olive oil in a wide pan over medium-low heat with the 4 sliced cloves of garlic. Cook 2 minutes, until it turns pale gold and smells sweet — browned garlic goes bitter and there is no fixing it.",
      "Add the 28 ounces of crushed tomatoes and the 1 teaspoon of kosher salt. Stand back; it spits.",
      "Simmer 20 minutes, uncovered, stirring now and then, until it darkens and a spoon dragged across the pan leaves a trail.",
      "Take it off the heat and tear the 8 leaves of fresh basil in. The heat left in the pan is enough; boiled basil turns black and tastes of nothing.",
      "Taste for salt. Use straight away or keep a week in the fridge.",
    ],
  }),
  dish({
    id: "garlic-aioli",
    name: "Garlic aioli",
    description: "Mayo if you are in a hurry, egg and oil if you are not. Fries, fish, sandwiches.",
    minutes: 10,
    servings: 8,
    protein: "eggs",
    plate: "bowl",
    cuisine: "French",
    tags: ["sauce", "quick"],
    aliases: ["aioli", "garlic mayo"],
    nutrition: { cal: 160, protein: 0, carbs: 1, fat: 17 },
    ingredients: [
      I("mayonnaise", 0.75, "cup", "Pantry"),
      I("garlic", 3, "cloves", "Produce"),
      I("lemon", 0.5, "", "Produce"),
      I("olive oil", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Crush the 3 cloves of garlic to a smooth paste with the 1 teaspoon of salt — a paste, not chopped, or you get hot bites of raw garlic.",
      "Stir the paste into the ¾ cup of mayonnaise.",
      "Add the juice of the ½ lemon and the 1 tablespoon of olive oil and stir by hand until glossy. Whisked hard or blended, it thins out.",
      "Rest 20 minutes so the garlic mellows into the mayonnaise.",
      "Serve cold with fries, fish or in a sandwich.",
    ],
  }),
  dish({
    id: "bearnaise",
    name: "Béarnaise",
    description: "Tarragon, shallot, vinegar, egg yolk, butter. Steak's best friend.",
    minutes: 15,
    servings: 4,
    protein: "eggs",
    plate: "bowl",
    cuisine: "French",
    tags: ["sauce"],
    aliases: ["bearnaise", "tarragon butter sauce"],
    nutrition: { cal: 255, protein: 3, carbs: 2, fat: 26 },
    ingredients: [
      I("egg yolks", 3, "", "Dairy & Eggs"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("shallot", 1, "", "Produce"),
      I("tarragon", 2, "tbsp", "Produce"),
      I("white wine vinegar", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Simmer the 2 tablespoons of white wine vinegar with the finely chopped shallot and half the 2 tablespoons of tarragon until only a spoonful of liquid is left. This reduction is what separates béarnaise from hollandaise.",
      "Melt the ½ cup of butter and keep it warm.",
      "Whisk the 3 egg yolks into the cooled reduction in a bowl set over — not in — barely simmering water. Whisk 3–4 minutes, until thick enough to ribbon.",
      "Off the heat, dribble the warm butter in a thread, whisking hard, until it emulsifies into a glossy sauce. If it breaks, whisk a spoon of warm water in and it usually comes back.",
      "Stir in the rest of the tarragon and the 1 teaspoon of salt. Keep barely warm — hot, it splits; cold, it sets.",
    ],
  }),
  dish({
    id: "poutine-gravy",
    name: "Poutine gravy",
    description: "Brown gravy that stays pourable on fries and cheese curds. Canadian, not optional.",
    minutes: 20,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian"],
    aliases: ["brown gravy", "poutine sauce", "fry gravy"],
    nutrition: { cal: 70, protein: 1, carbs: 3, fat: 6 },
    ingredients: [
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("beef broth", 2, "cups", "Pantry"),
      I("worcestershire", 1, "tsp", "Pantry"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: ["Roux the butter and flour. Whisk in broth. Worcestershire, pepper. Simmer until it coats a spoon."],
  }),
  dish({
    id: "gochujang-glaze",
    name: "Gochujang glaze",
    description: "Korean chile paste, soy, honey, sesame. Wings, tofu, a sheet-pan of broccoli.",
    minutes: 8,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["gochujang sauce", "korean chile glaze"],
    nutrition: { cal: 50, protein: 1, carbs: 9, fat: 1 },
    ingredients: [
      I("gochujang", 3, "tbsp", "Pantry"),
      I("soy sauce", 2, "tbsp", "Pantry"),
      I("honey", 2, "tbsp", "Pantry"),
      I("sesame oil", 1, "tsp", "Pantry"),
      I("garlic", 2, "cloves", "Produce"),
      I("rice vinegar", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Whisk the 3 tablespoons of gochujang with the 2 tablespoons of soy sauce, the 2 tablespoons of honey, the 2 minced cloves of garlic, and the 1 teaspoon of rice vinegar until smooth.",
      "Warm it in a small pan over low heat 3–4 minutes, just until it loosens and the garlic loses its raw edge.",
      "Take it off the heat before stirring in the 1 teaspoon of sesame oil — heated hard, sesame oil turns acrid and loses its point.",
      "Season with the 1 teaspoon of salt if it needs it; gochujang is already salty, so taste first.",
      "Brush onto wings, tofu or broccoli in the last few minutes of cooking. The honey will burn if it goes on any earlier.",
    ],
  }),
  dish({
    id: "zhug",
    name: "Zhug",
    description: "Yemeni green heat: cilantro, chile, cumin, cardamom. Falafel's other sauce.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian", "quick", "spicy"],
    aliases: ["schug", "skhug", "yemeni hot sauce"],
    nutrition: { cal: 70, protein: 1, carbs: 2, fat: 7 },
    ingredients: [
      I("cilantro", 1, "bunch", "Produce"),
      I("parsley", 0.5, "bunch", "Produce"),
      I("green chiles", 3, "", "Produce"),
      I("garlic", 3, "cloves", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("cardamom", 0.25, "tsp", "Herbs & Spices"),
      I("olive oil", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Toast the 1 teaspoon of cumin and the ¼ teaspoon of cardamom in a dry pan 30 seconds, until fragrant, then grind them.",
      "Put the 1 bunch of cilantro, the ½ bunch of parsley (stalks and all), the 3 green chiles, and the 3 cloves of garlic in a processor with the ground spice and the 1 teaspoon of salt.",
      "Pulse to a coarse, bright green paste. Do not let it run — heat from the blade dulls the colour and the flavour.",
      "Work in the ¼ cup of olive oil by hand.",
      "It is never cooked. Serve at room temperature with falafel, eggs or grilled meat; it keeps a week under a film of oil.",
    ],
  }),
  dish({
    id: "toum",
    name: "Toum",
    description: "Lebanese garlic cloud. A lot of garlic, oil, lemon. Shawarma, roast chicken, bread.",
    minutes: 15,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian"],
    aliases: ["lebanese garlic sauce", "garlic whip"],
    nutrition: { cal: 300, protein: 0, carbs: 2, fat: 33 },
    ingredients: [
      I("garlic", 1, "head", "Produce"),
      I("neutral oil", 1.5, "cups", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("ice water", 3, "tbsp", "Other"),
    ],
    steps: [
      "Peel the head of garlic and take the green germ out of any clove that has one — that is what makes toum bitter. Blitz the cloves with the 1 teaspoon of salt to a fine paste, scraping down twice.",
      "With the processor running, add the 1½ cups of neutral oil a few drops at a time to begin with. Rushing this is the only way to fail: the emulsion breaks and you get garlic soup.",
      "Once it starts to thicken and turn white, alternate a thin stream of oil with a little of the lemon juice and the 3 tablespoons of ice water.",
      "Keep going until it is stiff, matte and white like a whipped frosting. It should hold a peak.",
      "It is never heated. Chill it, and put it alongside shawarma or roast chicken; it keeps a month.",
    ],
  }),
  dish({
    id: "ponzu",
    name: "Ponzu",
    description: "Soy, citrus, a hint of seaweed if you have it. Dumplings, fish, a cold tofu night.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["ponzu sauce", "citrus soy"],
    nutrition: { cal: 20, protein: 1, carbs: 3, fat: 0 },
    ingredients: [
      I("soy sauce", 0.5, "cup", "Pantry"),
      I("rice vinegar", 2, "tbsp", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("orange", 0.5, "", "Produce"),
      I("mirin", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Squeeze the lemon and the ½ orange and strain out the pips and pulp.",
      "Stir the juice into the ½ cup of soy sauce with the 2 tablespoons of rice vinegar and the 1 tablespoon of mirin.",
      "If you have a piece of kombu or a pinch of bonito, drop it in — that is what gives a bottled ponzu its depth.",
      "Rest it in the fridge overnight so the citrus and the soy stop tasting like two separate things.",
      "Strain and serve cold with dumplings, sashimi or cold tofu. Never heated.",
    ],
  }),
  dish({
    id: "muhammara",
    name: "Muhammara",
    description: "Aleppo: roasted red pepper, walnuts, pomegranate molasses. Dip, spread, or a spoon on grilled lamb.",
    minutes: 20,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["sauce", "vegetarian"],
    aliases: ["walnut red pepper dip", "aleppo dip"],
    nutrition: { cal: 140, protein: 1, carbs: 7, fat: 13 },
    ingredients: [
      I("roasted red peppers", 2, "", "Produce"),
      I("walnuts", 0.75, "cup", "Pantry"),
      I("pomegranate molasses", 2, "tbsp", "Pantry"),
      I("garlic", 1, "clove", "Produce"),
      I("cumin", 0.5, "tsp", "Herbs & Spices"),
      I("olive oil", 3, "tbsp", "Pantry"),
    ],
    steps: [
      "Toast the ¾ cup of walnuts in a dry pan 3–4 minutes, until they smell rich, and cool them. Raw, they taste chalky and the dip falls flat.",
      "Pulse them with the 2 roasted red peppers, the 1 clove of garlic, the ½ teaspoon of cumin, and the 1 teaspoon of salt to a coarse paste with texture left in it.",
      "Add the 2 tablespoons of pomegranate molasses and pulse once more.",
      "Work in the 3 tablespoons of olive oil by hand.",
      "Rest an hour before serving so the molasses comes forward. Serve at room temperature.",
    ],
  }),
  dish({
    id: "mojo",
    name: "Mojo",
    description: "Cuban citrus-garlic: sour orange if you can, lime and orange if you cannot. Pork's marinade.",
    minutes: 10,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "Caribbean",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["mojo criollo", "cuban garlic sauce"],
    nutrition: { cal: 85, protein: 1, carbs: 7, fat: 7 },
    ingredients: [
      I("garlic", 8, "cloves", "Produce"),
      I("orange", 2, "", "Produce"),
      I("lime", 2, "", "Produce"),
      I("oregano", 1, "tsp", "Herbs & Spices"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Crush the 8 cloves of garlic with the 1 teaspoon of salt to a paste.",
      "Toast the 1 teaspoon of cumin and the 1 teaspoon of oregano in a dry pan a few seconds, until they smell warm.",
      "Warm the ¼ cup of olive oil until it just shimmers and pour it over the garlic and spice. It will hiss — that bloom is the whole flavour.",
      "Let it cool, then stir in the juice of the 2 oranges and the 2 limes. Sour orange if you can get it; this pair is the stand-in.",
      "Rest an hour. Use as a marinade for pork, or spoon it over after cooking.",
    ],
  }),
  dish({
    id: "come-back-sauce",
    name: "Come-back sauce",
    description: "Jackson, Mississippi: mayo, chili sauce, lemon, onion, a little Worcestershire. Everything dip.",
    minutes: 8,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["comeback sauce", "mississippi come back"],
    nutrition: { cal: 200, protein: 1, carbs: 3, fat: 21 },
    ingredients: [
      I("mayonnaise", 1, "cup", "Pantry"),
      I("chili sauce", 0.25, "cup", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("onion", 2, "tbsp", "Produce"),
      I("worcestershire", 1, "tsp", "Pantry"),
      I("garlic powder", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Grate the 2 tablespoons of onion fine, or the sauce will have raw chunks in it.",
      "Whisk it into the 1 cup of mayonnaise with the ¼ cup of chili sauce.",
      "Add the juice of the lemon, the 1 teaspoon of worcestershire, the ½ teaspoon of garlic powder, and the 1 teaspoon of salt.",
      "Do not heat it. Mayonnaise splits on the stove, and this sauce is served cold.",
      "Chill at least 2 hours — overnight is better. It is called come-back sauce because it improves sitting.",
    ],
  }),
  dish({
    id: "honey-mustard",
    name: "Honey mustard",
    description: "Dijon, honey, a splash of vinegar. Chicken tenders, pretzels, a grain salad.",
    minutes: 5,
    servings: 8,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["honey dijon", "pretzel sauce"],
    nutrition: { cal: 65, protein: 0, carbs: 9, fat: 3 },
    ingredients: [
      I("dijon mustard", 0.33, "cup", "Pantry"),
      I("honey", 0.25, "cup", "Pantry"),
      I("mayonnaise", 2, "tbsp", "Pantry"),
      I("apple cider vinegar", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Whisk the ⅓ cup of dijon mustard with the ¼ cup of honey until the colour is even.",
      "Whisk in the 2 tablespoons of mayonnaise, which is what keeps it clinging instead of running off.",
      "Add the 1 teaspoon of apple cider vinegar and the 1 teaspoon of salt.",
      "Taste and push it whichever way you want it — more honey for tenders, more mustard for a salad.",
      "Serve cold. It needs no cooking and keeps two weeks in the fridge.",
    ],
  }),
  dish({
    id: "sweet-sour-sauce",
    name: "Sweet and sour sauce",
    description: "Pineapple, vinegar, ketchup, a pinch of ginger. The takeout red you can make in one pan.",
    minutes: 12,
    servings: 6,
    protein: "veg",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["sauce", "vegetarian", "quick"],
    aliases: ["sweet and sour", "takeout red sauce"],
    nutrition: { cal: 55, protein: 0, carbs: 13, fat: 0 },
    ingredients: [
      I("pineapple juice", 0.5, "cup", "Pantry"),
      I("rice vinegar", 0.25, "cup", "Pantry"),
      I("ketchup", 3, "tbsp", "Pantry"),
      I("brown sugar", 3, "tbsp", "Pantry"),
      I("soy sauce", 1, "tbsp", "Pantry"),
      I("cornstarch", 1, "tbsp", "Pantry"),
      I("salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Put the ½ cup of pineapple juice, the ¼ cup of rice vinegar, the 3 tablespoons of ketchup, the 3 tablespoons of brown sugar, and the 1 tablespoon of soy sauce in a small pan.",
      "Bring to a simmer and cook 5 minutes, until the sugar has dissolved and the vinegar has lost its raw bite.",
      "Stir the 1 tablespoon of cornstarch into 2 tablespoons of cold water until smooth, then whisk it in.",
      "Simmer 1 minute more, until it turns clear and glossy and coats a spoon.",
      "Season with the 1 teaspoon of salt and cool. It thickens further as it cools.",
    ],
  }),
  dish({
    id: "zaatar-rub",
    name: "Za'atar rub",
    description: "Thyme, sesame, sumac. Oil a chicken or a tray of pita and dust generously.",
    minutes: 5,
    servings: 12,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["dry-rub", "vegetarian", "quick"],
    aliases: ["zaatar", "zaatar spice"],
    nutrition: { cal: 30, protein: 0, carbs: 1, fat: 3 },
    ingredients: [
      I("dried thyme", 2, "tbsp", "Herbs & Spices"),
      I("sesame seeds", 2, "tbsp", "Pantry"),
      I("sumac", 1, "tbsp", "Herbs & Spices"),
      I("kosher salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Toast the 2 tablespoons of sesame seeds in a dry pan over medium heat 2–3 minutes, shaking, until they colour and pop. Cool them completely.",
      "Rub the 2 tablespoons of dried thyme between your palms to break it down, then mix it with the sesame, the 1 tablespoon of sumac, and the 1 teaspoon of kosher salt.",
      "Keep it in a sealed jar away from light. Sumac fades within a couple of months and takes the sourness with it.",
      "Use it on oiled chicken, on a tray of pita before it goes in the oven, or stirred into olive oil as a dip.",
    ],
  }),
  dish({
    id: "coffee-cocoa-rub",
    name: "Coffee cocoa rub",
    description: "Espresso, cocoa, brown sugar, chile. Brisket, ribs, a thick steak.",
    minutes: 5,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["dry-rub", "vegetarian", "quick"],
    aliases: ["espresso rub", "coffee chile rub"],
    nutrition: { cal: 10, protein: 0, carbs: 2, fat: 0 },
    ingredients: [
      I("finely ground coffee", 2, "tbsp", "Pantry"),
      I("cocoa powder", 1, "tbsp", "Pantry"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("smoked paprika", 1, "tbsp", "Herbs & Spices"),
      I("kosher salt", 1, "tbsp", "Herbs & Spices"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Mix the 2 tablespoons of finely ground coffee, the 1 tablespoon of cocoa powder, the 1 tablespoon of brown sugar, the 1 tablespoon of smoked paprika, the 1 tablespoon of kosher salt, and the 1 teaspoon of black pepper in a bowl until the colour is even.",
      "Use unsweetened cocoa, not drinking chocolate, and grind the coffee fine — coarse grounds stay gritty on the crust.",
      "Pat the meat dry and press the rub over every surface.",
      "Rest 30 minutes on the counter, or overnight in the fridge.",
      "This is a seasoning, not a dinner. It suits brisket, ribs and a thick steak; the sugar means it wants a low fire or it will scorch.",
    ],
  }),
  dish({
    id: "lemon-pepper-rub",
    name: "Lemon pepper rub",
    description: "Zest, cracked pepper, garlic. Wings, fish, a tray of potatoes.",
    minutes: 8,
    servings: 10,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["dry-rub", "vegetarian", "quick"],
    aliases: ["lemon pepper", "citrus pepper rub"],
    nutrition: { cal: 30, protein: 0, carbs: 2, fat: 3 },
    ingredients: [
      I("lemons", 2, "", "Produce"),
      I("black pepper", 2, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Zest the 2 lemons with a fine grater, taking the yellow and none of the white pith underneath, which is bitter.",
      "Spread the zest on a plate and leave it somewhere warm 2–3 hours, or 20 minutes in a 200°F oven, until it is dry and crumbly. Damp zest clumps the rub and it will not keep.",
      "Crush the 2 tablespoons of black pepper coarsely and mix with the dried zest, the 1 teaspoon of garlic powder, and the 2 teaspoons of kosher salt.",
      "Pat the wings, fish or potatoes dry, oil them lightly, and rub the mix on all sides.",
      "It keeps a month in a jar. Cook the food however you like.",
    ],
  }),
];
