import type { Recipe } from "./types";

const I = (
  name: string,
  qty: number,
  unit: string,
  aisle: Recipe["ingredients"][number]["aisle"],
) => ({ name, qty, unit, aisle });

function sweet(
  partial: Omit<Recipe, "nutrition" | "pack" | "servings" | "plate" | "protein"> & {
    nutrition?: Recipe["nutrition"];
    plate?: Recipe["plate"];
    servings?: number;
    protein?: Recipe["protein"];
    photo?: string;
  },
): Recipe {
  const { nutrition, plate, servings, protein, ...rest } = partial;
  return {
    pack: "free",
    servings: servings ?? 8,
    plate: plate ?? "dessert",
    protein: protein ?? "veg",
    nutrition: nutrition ?? { cal: 320, protein: 4, carbs: 48, fat: 12 },
    ...rest,
  };
}

export const DESSERT_RECIPES: Recipe[] = [
  sweet({
    id: "blueberry-grunt",
    name: "Blueberry grunt",
    description: "Stewed wild blueberries with dumplings steamed on top. South Shore dessert that is also breakfast.",
    minutes: 40,
    cuisine: "Nova Scotia",
    tags: ["dessert", "fruit", "atlantic", "nova-scotia", "vegetarian", "breakfast"],
    aliases: ["blueberry cobbler", "grunt", "blueberry slump", "bleuet"],
    ingredients: [
      I("wild blueberries", 4, "cups", "Produce"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
      I("flour", 1.5, "cups", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("milk", 0.66, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Simmer the 4 cups of wild blueberries with the ½ cup of sugar, a splash of water, and the juice of the ½ lemon in a wide lidded pan until they slump and give up their juice, 5 minutes.",
      "Rub the 3 tablespoons of butter into the 1½ cups of flour with the 2 teaspoons of baking powder and the 1 teaspoon of salt, then stir in the ⅔ cup of milk to a soft, sticky dough.",
      "Drop spoonfuls of the dough onto the simmering berries, leaving gaps between them.",
      "Cover tightly and cook 15 minutes without lifting the lid. The dumplings steam rather than boil, and a peek lets the steam out and leaves them raw underneath.",
      "Spoon into bowls with the berries and their juice, and serve with cream.",
    ],
    nutrition: { cal: 280, protein: 5, carbs: 48, fat: 8 },
  }),
  sweet({
    id: "nanaimo-bars",
    name: "Nanaimo bars",
    description: "No-bake Canadian classic: coconut crumb, custard buttercream, chocolate cap.",
    minutes: 30,
    cuisine: "Homestyle",
    tags: ["dessert", "baking", "canadian", "vegetarian"],
    aliases: ["nanaimo", "canadian bar"],
    ingredients: [
      I("graham crumbs", 2, "cups", "Pantry"),
      I("shredded coconut", 1, "cup", "Pantry"),
      I("cocoa", 5, "tbsp", "Pantry"),
      I("butter", 1, "cup", "Dairy & Eggs"),
      I("custard powder", 2, "tbsp", "Pantry"),
      I("icing sugar", 2, "cups", "Pantry"),
      I("dark chocolate", 4, "oz", "Pantry"),
      I("egg", 1, "", "Dairy & Eggs"),
    ],
    steps: [
      "Melt ½ cup of the butter with the 5 tablespoons of cocoa in a bowl set over simmering water. Whisk the beaten egg in and keep whisking 3–4 minutes, until the mixture thickens like a custard and coats the spoon. This is the only heat the egg ever gets, so do not shortcut it.",
      "Stir in the 2 cups of graham crumbs and the 1 cup of shredded coconut and press firmly into a lined 8-inch pan. Chill 20 minutes.",
      "Beat the remaining ½ cup of butter with the 2 tablespoons of custard powder and the 2 cups of icing sugar until light, adding a spoon of milk if it is stiff. Spread over the base and chill 30 minutes.",
      "Melt the 4 ounces of dark chocolate with a teaspoon of butter and pour it over, tilting to level it. Chill just until set — rock-hard chocolate shatters instead of cutting.",
      "Cut into squares with a hot dry knife, wiping it between cuts.",
    ],
    nutrition: { cal: 310, protein: 3, carbs: 34, fat: 18 },
  }),
  sweet({
    id: "butter-tarts",
    name: "Butter tarts",
    description: "Runny brown-sugar filling in flaky shells. Raisins optional, fight about it later.",
    minutes: 45,
    cuisine: "Homestyle",
    tags: ["dessert", "baking", "canadian", "vegetarian"],
    aliases: ["butter tart", "tarte au sucre"],
    ingredients: [
      I("tart shells", 12, "", "Bakery"),
      I("brown sugar", 1, "cup", "Pantry"),
      I("butter", 0.33, "cup", "Dairy & Eggs"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("vanilla", 1, "tsp", "Herbs & Spices"),
      I("raisins", 0.5, "cup", "Pantry"),
    ],
    steps: [
      "Melt butter with brown sugar. Cool a minute, then beat in egg, vanilla, and a pinch of salt.",
      "Divide raisins into shells. Pour filling two-thirds full.",
      "Bake 375°F about 15 minutes until the tops blister and the centres still wobble.",
    ],
    nutrition: { cal: 290, protein: 3, carbs: 38, fat: 14 },
  }),
  sweet({
    id: "apple-crisp",
    name: "Apple crisp",
    description: "Tart apples under an oat lid. The weeknight pie.",
    minutes: 50,
    cuisine: "American",
    tags: ["dessert", "fruit", "baking", "vegetarian"],
    aliases: ["apple crumble", "crisp"],
    ingredients: [
      I("apples", 6, "", "Produce"),
      I("rolled oats", 1, "cup", "Pantry"),
      I("flour", 0.5, "cup", "Pantry"),
      I("brown sugar", 0.5, "cup", "Pantry"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("cinnamon", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Toss sliced apples with cinnamon and a spoon of sugar in a buttered dish.",
      "Rub butter into oats, flour, and brown sugar. Scatter.",
      "Bake 375°F 35–40 minutes until the fruit bubbles at the edge.",
    ],
    nutrition: { cal: 260, protein: 3, carbs: 42, fat: 10 },
  }),
  sweet({
    id: "molten-chocolate",
    name: "Molten chocolate cakes",
    description: "Warm cakes with a liquid centre. Fifteen minutes, if the oven is hot.",
    minutes: 20,
    cuisine: "French",
    tags: ["dessert", "baking", "vegetarian"],
    aliases: ["lava cake", "moelleux", "fondant au chocolat"],
    ingredients: [
      I("dark chocolate", 6, "oz", "Pantry"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("egg yolks", 2, "", "Dairy & Eggs"),
      I("sugar", 0.25, "cup", "Pantry"),
      I("flour", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Heat the oven to 425°F. Butter eight small ramekins and dust them with cocoa or sugar so the cakes turn out cleanly.",
      "Melt the 6 ounces of dark chocolate with the ½ cup of butter and let it cool slightly.",
      "Beat the 2 eggs, the 2 egg yolks, and the ¼ cup of sugar until pale and thick, then fold in the chocolate and the 2 tablespoons of flour.",
      "Divide between the ramekins and bake 11–13 minutes, until the edges are set and the middle still moves when you nudge the tin. Overbaked by two minutes and there is no molten centre.",
      "Rest 1 minute, run a knife round each, invert onto plates and serve at once.",
    ],
    protein: "eggs",
    nutrition: { cal: 410, protein: 7, carbs: 28, fat: 30 },
  }),
  sweet({
    id: "chip-cookies",
    name: "Sea salt chocolate chip cookies",
    description: "Brown-butter dough, puddles of chocolate, a flake of salt.",
    minutes: 35,
    cuisine: "American",
    tags: ["dessert", "baking", "vegetarian"],
    aliases: ["choc chip", "cookies"],
    ingredients: [
      I("butter", 1, "cup", "Dairy & Eggs"),
      I("brown sugar", 1, "cup", "Pantry"),
      I("white sugar", 0.5, "cup", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("flour", 2.25, "cups", "Pantry"),
      I("chocolate chips", 2, "cups", "Pantry"),
      I("flaky salt", 1, "tsp", "Herbs & Spices"),
      I("vanilla", 2, "tsp", "Pantry"),
      I("baking soda", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Brown the 1 cup of butter in a pan until it smells nutty and the solids go dark gold. Cool it until it is no longer hot to the touch.",
      "Beat it with the 1 cup of brown sugar and the ½ cup of white sugar, then the 2 eggs and the 2 teaspoons of vanilla.",
      "Fold in the 2¼ cups of flour and the 1 teaspoon of baking soda, then the 2 cups of chocolate chips. Chill the dough 30 minutes if you have time; it spreads less and tastes deeper.",
      "Scoop onto a lined sheet, spaced well apart. Bake at 375°F for 10–12 minutes, until the edges are set and the middles still look underdone.",
      "Scatter the 1 teaspoon of flaky salt over while they are hot, and cool on the sheet 5 minutes before moving them.",
    ],
    protein: "eggs",
    nutrition: { cal: 220, protein: 3, carbs: 28, fat: 11 },
  }),
  sweet({
    id: "yogurt-berries",
    name: "Honey yogurt and berries",
    description: "Thick yogurt, ripe berries, pistachios. Dessert that still loves Fuel.",
    minutes: 8,
    cuisine: "Homestyle",
    tags: ["dessert", "healthy", "chilled", "vegetarian", "quick", "breakfast"],
    aliases: ["parfait", "yogurt bowl", "healthy dessert"],
    servings: 2,
    ingredients: [
      I("greek yogurt", 2, "cups", "Dairy & Eggs"),
      I("mixed berries", 2, "cups", "Produce"),
      I("honey", 2, "tbsp", "Pantry"),
      I("pistachios", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Spoon the 2 cups of greek yogurt into cold bowls.",
      "Heap the 2 cups of mixed berries over the yogurt.",
      "Drizzle with the 2 tablespoons of honey and crush the ¼ cup of pistachios over the top. Serve cold.",
    ],
    nutrition: { cal: 240, protein: 18, carbs: 28, fat: 7 },
  }),
  sweet({
    id: "chia-pudding",
    name: "Coconut chia pudding",
    description: "Make it before bed. Cocoa or mango in the morning.",
    minutes: 10,
    cuisine: "Homestyle",
    tags: ["dessert", "healthy", "chilled", "vegetarian", "quick", "breakfast"],
    aliases: ["chia", "overnight pudding"],
    servings: 4,
    ingredients: [
      I("chia seeds", 0.5, "cup", "Pantry"),
      I("coconut milk", 2, "cups", "Pantry"),
      I("maple syrup", 2, "tbsp", "Pantry"),
      I("vanilla", 1, "tsp", "Herbs & Spices"),
      I("mango or berries", 1, "cup", "Produce"),
    ],
    steps: [
      "Whisk chia, coconut milk, maple, and vanilla. Rest 10 minutes, whisk again so it does not clump.",
      "Chill at least 4 hours. Top with fruit.",
    ],
    nutrition: { cal: 210, protein: 5, carbs: 18, fat: 14 },
  }),
  sweet({
    id: "tiramisu",
    name: "Tiramisu",
    description: "Espresso-soaked biscuits, mascarpone, cocoa. No oven.",
    minutes: 35,
    cuisine: "Italian",
    tags: ["dessert", "chilled", "world", "vegetarian"],
    aliases: ["tiramisù"],
    ingredients: [
      I("ladyfingers", 24, "", "Bakery"),
      I("espresso", 1.5, "cups", "Pantry"),
      I("mascarpone", 16, "oz", "Dairy & Eggs"),
      I("eggs", 3, "", "Dairy & Eggs"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("cocoa", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Separate the 3 eggs. The eggs in a tiramisu are never cooked, so use pasteurised eggs if you are serving anyone pregnant, elderly, very young, or unwell.",
      "Beat the yolks with the ½ cup of sugar until pale and thick, then fold in the 16 ounces of mascarpone.",
      "Whip the whites to soft peaks and fold them through in two goes, keeping the air in.",
      "Dip the 24 ladyfingers one at a time in the cooled 1½ cups of espresso — a second a side, no longer, or they collapse — and lay half of them in a dish. Spread over half the cream, then repeat.",
      "Dust the 2 tablespoons of cocoa over through a sieve and chill at least 4 hours, overnight for the best slice.",
    ],
    protein: "eggs",
    nutrition: { cal: 380, protein: 8, carbs: 32, fat: 24 },
  }),
  sweet({
    id: "mango-sticky-rice",
    name: "Mango sticky rice",
    description: "Warm coconut rice, ripe mango, a pinch of salt that makes it sing.",
    minutes: 45,
    cuisine: "East Asian",
    tags: ["dessert", "world", "fruit", "vegetarian"],
    aliases: ["khao niao mamuang", "thai mango rice"],
    servings: 4,
    ingredients: [
      I("glutinous rice", 1.5, "cups", "Pantry"),
      I("coconut milk", 1.5, "cups", "Pantry"),
      I("sugar", 0.33, "cup", "Pantry"),
      I("ripe mangoes", 2, "", "Produce"),
      I("salt", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Rinse the 1½ cups of glutinous rice and soak it at least 1 hour, then steam it over boiling water 25–30 minutes, until translucent and tender. It must be glutinous rice; nothing else goes sticky.",
      "Warm the 1½ cups of coconut milk with the ⅓ cup of sugar and the ½ teaspoon of salt until the sugar dissolves. Do not boil it.",
      "Pour two-thirds of it over the hot rice, stir once, and cover. Rest 20 minutes, until the rice has drunk it all.",
      "Peel and slice the 2 ripe mangoes.",
      "Mound the rice on plates, lay the mango alongside, and spoon the reserved coconut cream over the top.",
    ],
    nutrition: { cal: 340, protein: 5, carbs: 62, fat: 9 },
  }),
  sweet({
    id: "baklava",
    name: "Baklava",
    description: "Shatter pastry, walnuts, lemon-honey syrup.",
    minutes: 70,
    cuisine: "Middle Eastern",
    tags: ["dessert", "baking", "world", "vegetarian"],
    aliases: ["baqlawa"],
    ingredients: [
      I("phyllo", 1, "pack", "Frozen"),
      I("walnuts", 3, "cups", "Pantry"),
      I("butter", 1, "cup", "Dairy & Eggs"),
      I("honey", 0.75, "cup", "Pantry"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
    ],
    steps: [
      "Chop the 3 cups of walnuts coarsely and toss with a teaspoon of cinnamon.",
      "Brush a tin with the 1 cup of melted butter and lay in phyllo sheets, brushing each one, scattering a handful of nuts every few sheets. Keep the phyllo you are not using under a damp cloth or it turns to cornflakes.",
      "Finish with a good layer of phyllo on top and cut all the way through into diamonds before baking — cut afterwards, it shatters.",
      "Bake at 325°F for about 45 minutes, until deep gold all the way through.",
      "Meanwhile simmer the ¾ cup of honey with the ½ cup of sugar, ½ cup of water, and the juice of the ½ lemon 10 minutes, then cool it. Pour the cool syrup over the hot pastry — one hot and one cold is what makes it crisp instead of soggy. Rest 4 hours before cutting.",
    ],
    nutrition: { cal: 360, protein: 6, carbs: 38, fat: 22 },
  }),
  sweet({
    id: "churros",
    name: "Churros",
    description: "Ridged dough fried and rolled in cinnamon sugar. Thick chocolate to dip.",
    minutes: 40,
    cuisine: "Spanish",
    tags: ["dessert", "world", "vegetarian"],
    aliases: ["churro"],
    servings: 4,
    ingredients: [
      I("water", 1, "cup", "Other"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("flour", 1, "cup", "Pantry"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("cinnamon sugar", 0.5, "cup", "Pantry"),
      I("dark chocolate", 4, "oz", "Pantry"),
    ],
    steps: [
      "Boil water, butter, and a pinch of salt. Beat in flour off the heat, then the egg.",
      "Pipe into 375°F oil. Fry gold. Roll in cinnamon sugar.",
      "Melt chocolate with a splash of milk for dipping.",
    ],
    protein: "eggs",
    nutrition: { cal: 330, protein: 5, carbs: 38, fat: 18 },
  }),
  sweet({
    id: "flan",
    name: "Vanilla flan",
    description: "Burnt-sugar lid, silk custard. The fridge does the work.",
    minutes: 70,
    cuisine: "Mexican",
    tags: ["dessert", "chilled", "world", "vegetarian"],
    aliases: ["crème caramel", "caramel custard"],
    servings: 8,
    ingredients: [
      I("sugar", 1, "cup", "Pantry"),
      I("eggs", 5, "", "Dairy & Eggs"),
      I("evaporated milk", 1, "can", "Pantry"),
      I("sweetened condensed milk", 1, "can", "Pantry"),
      I("vanilla", 2, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Melt ½ cup of the sugar in a dry pan over medium heat until it turns amber. Pour it into the dish and swirl to coat the base — work fast, it sets in seconds and it will burn if you look away.",
      "Blend the 5 eggs with the 1 can of evaporated milk, the 1 can of sweetened condensed milk, the 2 teaspoons of vanilla, and the rest of the sugar until smooth. Let the foam settle, or the flan bakes with bubbles in it.",
      "Pour it over the caramel and set the dish in a roasting tin. Pour boiling water halfway up the sides.",
      "Bake at 325°F for about 50 minutes, until set at the edge and still trembling in the middle.",
      "Cool, then chill overnight. Run a knife round the edge and invert onto a lipped plate so the caramel runs over it.",
    ],
    protein: "eggs",
    nutrition: { cal: 290, protein: 8, carbs: 42, fat: 10 },
  }),
  sweet({
    id: "figgy-duff",
    name: "Figgy duff",
    description: "Newfoundland boiled pudding with raisins, steamed beside Jiggs.",
    minutes: 90,
    cuisine: "Newfoundland",
    tags: ["dessert", "baking", "atlantic", "newfoundland", "vegetarian"],
    aliases: ["figgy", "duff", "boiled pudding"],
    ingredients: [
      I("flour", 2, "cups", "Pantry"),
      I("raisins", 1, "cup", "Pantry"),
      I("molasses", 0.5, "cup", "Pantry"),
      I("butter", 0.25, "cup", "Dairy & Eggs"),
      I("baking soda", 1, "tsp", "Pantry"),
      I("cinnamon", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Stir flour, raisins, spices, and soda. Melt butter with molasses and a cup of water. Mix to a thick batter.",
      "Spoon into a pudding cloth or greased bowl. Steam 1 hour.",
      "Turn out. Serve with molasses sauce or cream.",
    ],
    nutrition: { cal: 270, protein: 4, carbs: 52, fat: 6 },
  }),
];
