import type { Recipe } from "./types";

const I = (
  name: string,
  qty: number,
  unit: string,
  aisle: Recipe["ingredients"][number]["aisle"],
) => ({ name, qty, unit, aisle });

function dish(
  partial: Omit<Recipe, "nutrition" | "pack" | "servings"> & {
    nutrition?: Recipe["nutrition"];
    pack?: Recipe["pack"];
    servings?: number;
  },
): Recipe {
  return {
    pack: "free",
    servings: 4,
    nutrition: { cal: 420, protein: 22, carbs: 38, fat: 16 },
    ...partial,
  };
}

export const WORLD_RECIPES: Recipe[] = [
  dish({
    id: "sloppy-joes",
    name: "Sloppy joes",
    description: "Sweet-savory saucy beef on a toasted bun. Cafeteria legend, still a weeknight win.",
    minutes: 25,
    protein: "beef",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "american", "quick", "budget"],
    aliases: ["sloppy joe", "loose meat", "barbecue beef sandwich"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("ketchup", 0.75, "cup", "Pantry"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("Worcestershire", 1, "tbsp", "Pantry"),
      I("hamburger buns", 4, "", "Bakery"),
    ],
    steps: [
      "Brown beef with chopped onion. Drain extra fat.",
      "Stir in ketchup, brown sugar, and Worcestershire. Simmer 10 minutes.",
      "Spoon onto toasted buns.",
    ],
  }),
  dish({
    id: "chicken-dumplings",
    name: "Chicken and dumplings",
    description: "Stewed chicken under fluffy drop dumplings. Grandmother energy.",
    minutes: 70,
    protein: "chicken",
    plate: "soup",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["chicken n dumplings", "chicken & dumplings", "dumpling stew"],
    ingredients: [
      I("bone-in chicken thighs", 2, "lb", "Meat & Seafood"),
      I("carrot", 3, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("onion", 1, "", "Produce"),
      I("flour", 1.5, "cups", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
      I("chicken broth", 6, "cups", "Pantry"),
    ],
    steps: [
      "Simmer chicken with onion, carrot, and celery in broth until tender. Shred the meat.",
      "Mix flour, baking powder, salt, and milk into a thick batter.",
      "Drop spoonfuls on the simmering stew. Cover 15 minutes — do not peek.",
    ],
  }),
  dish({
    id: "tater-tot-hotdish",
    name: "Tater tot hotdish",
    description: "Midwest church-basement classic: beef, cream soup, peas, tots.",
    minutes: 55,
    protein: "beef",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "american", "casserole", "budget"],
    aliases: ["hotdish", "tater tot casserole", "minnesota hotdish"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("frozen mixed vegetables", 2, "cups", "Frozen"),
      I("cream of mushroom soup", 1, "can", "Pantry"),
      I("frozen tater tots", 1, "bag", "Frozen"),
      I("onion", 1, "", "Produce"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Brown beef with onion. Stir in soup and vegetables. Spread in a baking dish.",
      "Top with tots and cheddar. Bake 40 minutes at 400°F until the tots are crisp.",
    ],
  }),
  dish({
    id: "salisbury-steak",
    name: "Salisbury steak",
    description: "Seasoned beef patties in onion gravy. TV-dinner glow, homemade.",
    minutes: 40,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["salisbury", "hamburger steak", "onion gravy patties"],
    ingredients: [
      I("ground beef", 1.5, "lb", "Meat & Seafood"),
      I("onion", 2, "", "Produce"),
      I("breadcrumbs", 0.5, "cup", "Pantry"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("beef broth", 2, "cups", "Pantry"),
      I("Worcestershire", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Mix beef with breadcrumbs, egg, and Worcestershire. Shape oval patties and brown.",
      "Sauté onions, add broth, simmer patties in gravy 15 minutes.",
    ],
  }),
  dish({
    id: "swedish-meatballs",
    name: "Swedish meatballs",
    description: "Tiny meatballs in cream gravy. Ikea wishes it tasted like this.",
    minutes: 45,
    protein: "beef",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["swedish meatball", "köttbullar", "cream gravy meatballs"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("ground pork", 0.5, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("breadcrumbs", 0.5, "cup", "Pantry"),
      I("allspice", 0.5, "tsp", "Herbs & Spices"),
      I("beef broth", 2, "cups", "Pantry"),
      I("heavy cream", 0.5, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Mix meats with onion, breadcrumbs, and allspice. Roll small balls and brown.",
      "Make gravy with pan drippings, broth, and cream. Simmer meatballs in it.",
    ],
  }),
  dish({
    id: "american-goulash",
    name: "American goulash",
    description: "One-pot elbow pasta, beef, and tomatoes. School-night old school.",
    minutes: 35,
    protein: "beef",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "american", "budget", "quick"],
    aliases: ["goulash", "american chop suey", "beefaroni", "chili mac"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("elbow macaroni", 12, "oz", "Pantry"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("garlic", 3, "cloves", "Produce"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Brown beef with onion and garlic. Add tomatoes, paprika, and water.",
      "Stir in dry pasta and simmer until tender, 12–15 minutes.",
    ],
  }),
  dish({
    id: "scalloped-ham",
    name: "Ham and scalloped potatoes",
    description: "Sunday leftover ham tucked into creamy potatoes.",
    minutes: 80,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["scalloped potatoes and ham", "au gratin ham", "funeral potatoes"],
    ingredients: [
      I("potato", 3, "lb", "Produce"),
      I("cooked ham", 2, "cups", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Layer sliced potatoes, ham, and onion in a buttered dish.",
      "Pour a milk-flour-butter sauce over. Bake 70 minutes at 350°F, cheddar on top at the end.",
    ],
  }),
  dish({
    id: "stuffed-peppers",
    name: "Stuffed peppers",
    description: "Bell peppers packed with beef, rice, and tomato. 1970s table, forever.",
    minutes: 65,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american"],
    aliases: ["stuffed bell peppers", "pepper boats"],
    ingredients: [
      I("bell peppers", 4, "", "Produce"),
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("cooked rice", 1.5, "cups", "Pantry"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Hollow peppers. Mix beef, rice, onion, and some tomato.",
      "Fill, stand in a dish with remaining tomato, bake 45 minutes at 375°F. Cheese last 10.",
    ],
  }),
  dish({
    id: "stovetop-mac",
    name: "Stovetop mac and cheese",
    description: "A pot of elbows in sharp cheddar sauce. No box required.",
    minutes: 25,
    protein: "veg",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "american", "vegetarian", "quick", "budget"],
    aliases: ["mac n cheese", "macaroni and cheese", "mac & cheese", "homemade kraft"],
    ingredients: [
      I("elbow macaroni", 12, "oz", "Pantry"),
      I("sharp cheddar", 10, "oz", "Dairy & Eggs"),
      I("milk", 1.5, "cups", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("mustard powder", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Bring a large pot of salted water to a boil. Cook the 12 ounces of elbow macaroni until just tender. Drain, saving a splash of the water.",
      "Melt the 3 tablespoons of butter in the same pot. Stir in the 3 tablespoons of flour and cook 1 minute. Whisk in the 1½ cups of milk until the sauce is smooth and thick.",
      "Take the pan off the heat. Stir in the 10 ounces of sharp cheddar and the ½ teaspoon of mustard powder until melted.",
      "Fold in the pasta. If the sauce is tight, loosen with a splash of the pasta water. Serve hot.",
    ],
  }),
  dish({
    id: "chicken-a-la-king",
    name: "Chicken à la king",
    description: "Creamed chicken with peppers and mushrooms on toast or rice.",
    minutes: 35,
    protein: "chicken",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["chicken a la king", "creamed chicken"],
    ingredients: [
      I("cooked chicken", 3, "cups", "Meat & Seafood"),
      I("mushrooms", 8, "oz", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("frozen peas", 1, "cup", "Frozen"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("flour", 4, "tbsp", "Pantry"),
      I("toast", 8, "slices", "Bakery"),
    ],
    steps: [
      "Melt the 4 tablespoons of butter in a skillet. Cook the 8 ounces of mushrooms and the chopped bell pepper until soft, 5 minutes.",
      "Stir in the 4 tablespoons of flour and cook 1 minute. Whisk in the 2 cups of milk until the sauce is smooth and thick.",
      "Add the 3 cups of cooked chicken and the 1 cup of frozen peas. Simmer 3–4 minutes, until everything is hot.",
      "Toast the 8 slices of toast. Spoon the chicken over the toast and serve at once.",
    ],
  }),
  dish({
    id: "pork-chops-apples",
    name: "Pork chops with applesauce",
    description: "Pan-seared chops and a warm cinnamon apple mash.",
    minutes: 30,
    protein: "pork",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "american", "quick"],
    aliases: ["pork chops and applesauce", "pork and apple"],
    ingredients: [
      I("pork chops", 4, "", "Meat & Seafood"),
      I("apples", 3, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Pat the 4 pork chops dry and salt both sides. Set a wide skillet over medium-high heat.",
      "Sear the chops until browned and just cooked through, 4–5 minutes per side. Move to a plate and rest.",
      "In the same pan, melt the 2 tablespoons of butter. Add the 3 apples (sliced) and the chopped onion with the ½ teaspoon of cinnamon.",
      "Cook until the apples slump into a sauce, 6–8 minutes. Spoon over the chops and serve.",
    ],
  }),
  dish({
    id: "cabbage-rolls",
    name: "Cabbage rolls",
    description: "Beef and rice wrapped in cabbage, baked in tomato. Homemade hall-of-fame.",
    minutes: 110,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["holubtsi", "golubtsi", "stuffed cabbage", "pigs in a blanket cabbage"],
    ingredients: [
      I("cabbage", 1, "head", "Produce"),
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("cooked rice", 1, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("crushed tomatoes", 2, "cans", "Pantry"),
    ],
    steps: [
      "Heat the oven to 325°F. Boil the whole head of cabbage 8 minutes. Pull off 12 large leaves and trim the thick rib so they roll.",
      "Mix the 1 pound of ground beef, the 1 cup of cooked rice, the chopped onion, salt, and pepper. Put 2 tablespoons in each leaf. Fold the sides in and roll.",
      "Lay the rolls in a dish. Pour the 2 cans of crushed tomatoes over.",
      "Cover and bake 90 minutes, until the leaves are silky and the filling is cooked through. Spoon the tomato over and serve.",
    ],
  }),
  dish({
    id: "classic-beef-stew",
    name: "Classic beef stew",
    description: "Chuck, potatoes, and carrots that fall apart if you give them time.",
    minutes: 150,
    protein: "beef",
    plate: "soup",
    cuisine: "Old school",
    tags: ["old-school", "american", "sunday"],
    aliases: ["beef stew", "irish stew beef", "pot of stew"],
    ingredients: [
      I("beef chuck", 2, "lb", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("beef broth", 4, "cups", "Pantry"),
      I("tomato paste", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Pat the 2 pounds of beef chuck dry and salt it. Set a heavy pot over medium-high heat.",
      "Brown the cubed chuck on all sides, 6–8 minutes. Add the chopped onion and the 2 tablespoons of tomato paste. Cook 1 minute.",
      "Pour in the 4 cups of beef broth. Simmer, partly covered, 90 minutes, until the beef starts to give.",
      "Add the 4 potatoes (chunked) and the 4 carrots. Cook until tender, 40 minutes more. Taste for salt and serve in warm bowls.",
    ],
  }),
  dish({
    id: "porcupine-meatballs",
    name: "Porcupine meatballs",
    description: "Rice-studded meatballs simmered in tomato. Kids named them, adults eat them.",
    minutes: 50,
    protein: "beef",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "american", "budget"],
    aliases: ["porcupine balls", "rice meatballs"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("uncooked rice", 0.5, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("tomato soup", 1, "can", "Pantry"),
      I("water", 1, "cup", "Other"),
    ],
    steps: [
      "Mix beef, rice, and onion. Roll balls.",
      "Simmer covered in tomato soup and water 40 minutes until rice pokes out.",
    ],
  }),
  dish({
    id: "tuna-melt",
    name: "Tuna melt",
    description: "Hot tuna salad under a blanket of cheddar. Lunch-counter forever.",
    minutes: 15,
    protein: "fish",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "american", "quick"],
    aliases: ["tuna melt sandwich", "grilled tuna sandwich"],
    ingredients: [
      I("canned tuna", 2, "cans", "Pantry"),
      I("mayonnaise", 3, "tbsp", "Pantry"),
      I("celery", 1, "stalk", "Produce"),
      I("cheddar", 4, "slices", "Dairy & Eggs"),
      I("bread", 8, "slices", "Bakery"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Mix tuna with mayo and celery. Pile on bread with cheddar.",
      "Griddle in butter until the cheese runs.",
    ],
  }),
  dish({
    id: "corned-beef-hash",
    name: "Corned beef hash",
    description: "Crisp potatoes, chopped corned beef, a fried egg if you have one.",
    minutes: 30,
    protein: "beef",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "american", "breakfast"],
    aliases: ["hash", "canned hash homemade"],
    ingredients: [
      I("cooked corned beef", 2, "cups", "Meat & Seafood"),
      I("potato", 3, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("eggs", 4, "", "Dairy & Eggs"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Dice the 3 potatoes and the onion. Set a wide skillet over medium-high heat with the 2 tablespoons of butter.",
      "Crisp the potato and onion, 8–10 minutes, pressing them into the pan so a crust forms.",
      "Add the 2 cups of chopped cooked corned beef. Press again and fry until the underside is crusty.",
      "Fry the 4 eggs in a second pan. Top each plate of hash with an egg and serve hot.",
    ],
  }),
  dish({
    id: "sunday-pot-roast",
    name: "Sunday pot roast",
    description: "Chuck roast, carrots, and potatoes in one pot. The house smells like home.",
    minutes: 210,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american", "sunday"],
    aliases: ["pot roast", "yankee pot roast", "chuck roast dinner"],
    ingredients: [
      I("beef chuck roast", 3, "lb", "Meat & Seafood"),
      I("potato", 6, "", "Produce"),
      I("carrot", 6, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("beef broth", 2, "cups", "Pantry"),
      I("tomato paste", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Brown the roast hard. Add onion, paste, and broth. Cover and roast 2.5 hours at 325°F.",
      "Add potato and carrot for the last 50 minutes. Rest, slice, spoon gravy.",
    ],
  }),
  dish({
    id: "spaghetti-meatballs",
    name: "Spaghetti and meatballs",
    description: "Sunday sauce, fat meatballs, a mountain of spaghetti.",
    minutes: 75,
    protein: "beef",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["old-school", "italian", "comfort"],
    aliases: ["spag and balls", "spaghetti & meatballs", "meatball pasta"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("spaghetti", 1, "lb", "Pantry"),
      I("crushed tomatoes", 2, "cans", "Pantry"),
      I("garlic", 5, "cloves", "Produce"),
      I("breadcrumbs", 0.5, "cup", "Pantry"),
      I("parmesan", 2, "oz", "Dairy & Eggs"),
      I("fresh basil", 1, "bunch", "Produce"),
    ],
    steps: [
      "Mix beef with breadcrumbs, parmesan, and garlic. Brown meatballs.",
      "Simmer in tomatoes 40 minutes. Boil spaghetti. Toss together with basil.",
    ],
  }),
  dish({
    id: "nl-fish-cakes",
    name: "Newfoundland fish cakes",
    description: "Salt cod and potato patties fried gold. Breakfast, supper, leftover scoff.",
    minutes: 40,
    protein: "fish",
    plate: "fish",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school"],
    aliases: ["fish cakes", "cod cakes", "salt fish cakes", "nl cakes"],
    ingredients: [
      I("salt cod", 1, "lb", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("savory", 1, "tsp", "Herbs & Spices"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 0.5, "cup", "Pantry"),
    ],
    steps: [
      "Soak salt cod, then simmer and flake. Mash with potato, onion, and savory.",
      "Shape cakes, dust with flour, fry in butter until both sides are crusted.",
    ],
  }),
  dish({
    id: "pan-fried-cod",
    name: "Pan-fried cod",
    description: "Crisp-edged fresh cod, lemon, a knob of butter. Outport weeknight.",
    minutes: 20,
    protein: "fish",
    plate: "fish",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "quick"],
    aliases: ["fried fish", "cod fry", "nl fried fish"],
    ingredients: [
      I("cod fillets", 1.5, "lb", "Meat & Seafood"),
      I("flour", 0.5, "cup", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("lemon", 1, "", "Produce"),
      I("savory", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Pat fish dry, season, dust with flour.",
      "Fry in butter 3–4 minutes a side. Finish with lemon and savory.",
    ],
  }),
  dish({
    id: "moose-stew",
    name: "Moose stew",
    description: "Slow moose, root veg, and a dark gravy. Cabin cooking.",
    minutes: 180,
    protein: "beef",
    plate: "soup",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school"],
    aliases: ["moose meat stew", "wild game stew", "nl stew"],
    ingredients: [
      I("moose stew meat or beef chuck", 2, "lb", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("turnip", 1, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("beef broth", 4, "cups", "Pantry"),
    ],
    steps: [
      "Brown the meat well. Add onion and broth. Simmer 2 hours.",
      "Add roots and cook until soft. Season hard with salt and pepper.",
    ],
  }),
  dish({
    id: "hodge-podge",
    name: "Hodge podge",
    description: "Maritimes cream of new vegetables — beans, carrots, potatoes, a little butter.",
    minutes: 40,
    protein: "veg",
    plate: "soup",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "vegetarian", "maritimes"],
    aliases: ["hodgepodge", "hodge podge soup", "nova scotia hodge podge"],
    ingredients: [
      I("new potatoes", 1, "lb", "Produce"),
      I("green beans", 0.5, "lb", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("peas", 1, "cup", "Produce"),
      I("cream", 1, "cup", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Simmer the 1 pound of new potatoes, the 4 carrots, the ½ pound of green beans, and the 1 cup of peas in salted water until just tender, 12–15 minutes. Drain most of the water.",
      "Stir in the 1 cup of cream and the 3 tablespoons of butter. Do not boil hard.",
      "Taste for salt. Serve in warm bowls.",
    ],
  }),
  dish({
    id: "halifax-donair",
    name: "Halifax donair",
    description: "Spiced beef, sweet garlic sauce, tomato and onion in a pita. East Coast pride.",
    minutes: 50,
    protein: "beef",
    plate: "taco",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "maritimes"],
    aliases: ["donair", "halifax donair", "east coast donair", "donair sauce"],
    ingredients: [
      I("ground beef", 1.5, "lb", "Meat & Seafood"),
      I("onion powder", 1, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
      I("evaporated milk", 0.75, "cup", "Pantry"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("garlic", 3, "cloves", "Produce"),
      I("pita", 4, "", "Bakery"),
      I("tomato", 2, "", "Produce"),
      I("onion", 1, "", "Produce"),
    ],
    steps: [
      "Season and pack beef, bake as a loaf, slice thin.",
      "Whisk evaporated milk, sugar, garlic, and vinegar into donair sauce.",
      "Warm pita, fill with meat, tomato, onion, and a reckless amount of sauce.",
    ],
  }),
  dish({
    id: "poutine",
    name: "Poutine",
    description: "Fries, cheese curds, hot gravy. Quebec’s gift to late night.",
    minutes: 40,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["canadian", "vegetarian", "comfort"],
    aliases: ["quebec poutine", "fries gravy curds"],
    ingredients: [
      I("russet potatoes", 4, "", "Produce"),
      I("cheese curds", 2, "cups", "Dairy & Eggs"),
      I("beef or veg gravy", 2, "cups", "Pantry"),
      I("oil for frying", 4, "cups", "Pantry"),
    ],
    steps: [
      "Cut fries, soak, double-fry until crisp.",
      "Top with room-temp curds and boiling gravy so they squeak and slump.",
    ],
  }),
  dish({
    id: "tourtiere",
    name: "Tourtière",
    description: "Spiced meat pie for Christmas Eve and every cold Sunday after.",
    minutes: 90,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "canadian", "christmas"],
    aliases: ["tourtiere", "french canadian meat pie", "pork pie"],
    ingredients: [
      I("ground pork", 1.5, "lb", "Meat & Seafood"),
      I("ground beef", 0.5, "lb", "Meat & Seafood"),
      I("potato", 1, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cinnamon", 0.25, "tsp", "Herbs & Spices"),
      I("clove", 0.125, "tsp", "Herbs & Spices"),
      I("pie pastry", 1, "double crust", "Bakery"),
    ],
    steps: [
      "Cook meats with onion, mashed potato, and spices until dry-ish.",
      "Fill a pie, vent, bake 45 minutes at 375°F. Serve with ketchup if you are honest.",
    ],
  }),
  dish({
    id: "toad-in-hole",
    name: "Toad in the hole",
    description: "Sausages baked in Yorkshire pudding batter. British supper, no amphibians.",
    minutes: 50,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "british"],
    aliases: ["toad in the hole", "sausage yorkshire", "toad-in-the-hole"],
    ingredients: [
      I("pork sausages", 8, "", "Meat & Seafood"),
      I("flour", 1, "cup", "Pantry"),
      I("eggs", 3, "", "Dairy & Eggs"),
      I("milk", 1, "cup", "Dairy & Eggs"),
      I("oil", 3, "tbsp", "Pantry"),
    ],
    steps: [
      "Heat oil and brown sausages in a roasting tin in a 425°F oven.",
      "Pour in a rest-beaten batter. Bake 25 minutes until puffed. Onion gravy if you have it.",
    ],
  }),
  dish({
    id: "bangers-mash",
    name: "Bangers and mash",
    description: "Sausages, buttery potatoes, onion gravy. Pub plate at home.",
    minutes: 40,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "british"],
    aliases: ["bangers & mash", "sausage and mash", "bangers"],
    ingredients: [
      I("pork sausages", 8, "", "Meat & Seafood"),
      I("potato", 2, "lb", "Produce"),
      I("onion", 2, "", "Produce"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("beef broth", 1.5, "cups", "Pantry"),
    ],
    steps: [
      "Mash boiled potatoes with butter. Brown sausages.",
      "Caramelize onions, add broth, simmer into gravy.",
    ],
  }),
  dish({
    id: "irish-stew",
    name: "Irish stew",
    description: "Lamb or mutton, potato, onion. Patience is the fourth ingredient.",
    minutes: 140,
    protein: "beef",
    plate: "soup",
    cuisine: "Old school",
    tags: ["old-school", "irish"],
    aliases: ["irish lamb stew", "mutton stew"],
    ingredients: [
      I("lamb shoulder", 2, "lb", "Meat & Seafood"),
      I("potato", 2, "lb", "Produce"),
      I("onion", 3, "", "Produce"),
      I("carrot", 3, "", "Produce"),
      I("thyme", 4, "sprigs", "Produce"),
      I("stock", 4, "cups", "Pantry"),
    ],
    steps: [
      "Layer meat and onion. Cover with stock. Simmer 90 minutes.",
      "Add potato and carrot. Cook until the broth goes silky.",
    ],
  }),
  dish({
    id: "colcannon",
    name: "Colcannon",
    description: "Mashed potato folded with cabbage or kale and a well of butter.",
    minutes: 35,
    protein: "veg",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "irish", "vegetarian"],
    aliases: ["irish mash", "cabbage mash"],
    ingredients: [
      I("potato", 2, "lb", "Produce"),
      I("cabbage or kale", 0.5, "head", "Produce"),
      I("scallion", 4, "", "Produce"),
      I("butter", 6, "tbsp", "Dairy & Eggs"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Boil potatoes. Wilt cabbage in butter.",
      "Mash with hot milk, fold cabbage and scallion, make a butter well.",
    ],
  }),
  dish({
    id: "amatriciana",
    name: "Bucatini all’amatriciana",
    description: "Guanciale, tomato, pecorino. Roman, loud, not creamy.",
    minutes: 30,
    protein: "pork",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick"],
    aliases: ["amatriciana", "bucatini amatriciana"],
    ingredients: [
      I("bucatini", 12, "oz", "Pantry"),
      I("guanciale", 5, "oz", "Meat & Seafood"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("pecorino romano", 2, "oz", "Dairy & Eggs"),
      I("red pepper flakes", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Render guanciale. Add tomato and pepper flakes.",
      "Toss with al dente bucatini and pecorino.",
    ],
  }),
  dish({
    id: "eggplant-parm",
    name: "Eggplant parmesan",
    description: "Fried eggplant, red sauce, mozzarella. Meatless Sunday.",
    minutes: 80,
    protein: "veg",
    plate: "roast",
    cuisine: "Italian",
    tags: ["italian", "vegetarian", "old-school"],
    aliases: ["eggplant parmigiana", "melanzane alla parmigiana", "eggplant parm"],
    ingredients: [
      I("eggplant", 2, "", "Produce"),
      I("mozzarella", 12, "oz", "Dairy & Eggs"),
      I("parmesan", 3, "oz", "Dairy & Eggs"),
      I("crushed tomatoes", 2, "cans", "Pantry"),
      I("breadcrumbs", 2, "cups", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
    ],
    steps: [
      "Salt, bread, and fry eggplant slices.",
      "Layer with sauce and cheeses. Bake 30 minutes at 375°F.",
    ],
  }),
  dish({
    id: "avgolemono",
    name: "Avgolemono",
    description: "Greek lemon-egg chicken soup. Bright, silky, homemade.",
    minutes: 45,
    protein: "chicken",
    plate: "soup",
    cuisine: "Greek",
    tags: ["greek", "comfort"],
    aliases: ["avgolemono soup", "greek lemon soup", "egg lemon soup"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("rice", 0.5, "cup", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("lemon", 2, "", "Produce"),
      I("chicken broth", 8, "cups", "Pantry"),
    ],
    steps: [
      "Simmer chicken, shred, cook rice in the broth.",
      "Whisk eggs with lemon, temper with hot broth, stir back in off heat.",
    ],
  }),
  dish({
    id: "gemista",
    name: "Gemista",
    description: "Tomatoes and peppers stuffed with herbed rice. Summer Greek table.",
    minutes: 90,
    protein: "veg",
    plate: "roast",
    cuisine: "Greek",
    tags: ["greek", "vegetarian"],
    aliases: ["yemista", "stuffed tomatoes greek"],
    ingredients: [
      I("ripe tomatoes", 6, "", "Produce"),
      I("bell peppers", 4, "", "Produce"),
      I("rice", 1, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("fresh mint", 0.5, "cup", "Produce"),
      I("olive oil", 0.5, "cup", "Pantry"),
      I("potato", 3, "", "Produce"),
    ],
    steps: [
      "Hollow tomatoes and peppers. Mix pulp with rice, onion, mint, oil.",
      "Fill, nestle potato wedges around, bake 70 minutes at 375°F.",
    ],
  }),
  dish({
    id: "huevos-rancheros",
    name: "Huevos rancheros",
    description: "Fried eggs on tortillas with a ranchero salsa. Breakfast that is dinner.",
    minutes: 25,
    protein: "eggs",
    plate: "taco",
    cuisine: "Mexican",
    tags: ["mexican", "vegetarian", "quick"],
    aliases: ["rancheros", "ranch eggs", "huevos"],
    ingredients: [
      I("eggs", 4, "", "Dairy & Eggs"),
      I("corn tortillas", 8, "", "Bakery"),
      I("tomato", 4, "", "Produce"),
      I("jalapeño", 1, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cilantro", 0.5, "bunch", "Produce"),
    ],
    steps: [
      "Chop the 4 tomatoes, the onion, and the jalapeño. Simmer in a skillet with a pinch of salt 8–10 minutes, until they slump into a salsa.",
      "Warm the 8 corn tortillas in a dry pan 20 seconds a side, until they flex.",
      "Fry the 4 eggs in a little oil over medium heat, 2–3 minutes, until the whites set and the yolks stay runny.",
      "Set the tortillas on plates. Top with an egg and a spoon of salsa. Scatter the cilantro over.",
    ],
  }),
  dish({
    id: "pozole-rojo",
    name: "Pozole rojo",
    description: "Pork and hominy in a chile broth. Garnish like you mean it.",
    minutes: 150,
    protein: "pork",
    plate: "soup",
    cuisine: "Mexican",
    tags: ["mexican", "sunday"],
    aliases: ["posole", "pozole", "red pozole"],
    ingredients: [
      I("pork shoulder", 2, "lb", "Meat & Seafood"),
      I("canned hominy", 2, "cans", "Pantry"),
      I("dried guajillo chiles", 6, "", "Herbs & Spices"),
      I("garlic", 6, "cloves", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cabbage", 0.25, "head", "Produce"),
      I("radish", 6, "", "Produce"),
      I("lime", 2, "", "Produce"),
    ],
    steps: [
      "Simmer pork until shreddable. Blend soaked chiles with garlic.",
      "Add chile puree and hominy. Serve with cabbage, radish, lime.",
    ],
  }),
  dish({
    id: "palak-paneer",
    name: "Palak paneer",
    description: "Spinach gravy, cubes of paneer. Homestyle Punjabi.",
    minutes: 40,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian"],
    aliases: ["saag paneer", "spinach paneer"],
    ingredients: [
      I("spinach", 1, "lb", "Produce"),
      I("paneer", 8, "oz", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("ginger", 1, "tbsp", "Produce"),
      I("garam masala", 1, "tsp", "Herbs & Spices"),
      I("cream", 0.25, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Blanch spinach, blend with ginger and garlic.",
      "Cook onion, add puree and garam masala, fold in fried paneer and cream.",
    ],
  }),
  dish({
    id: "dal-tadka",
    name: "Dal tadka",
    description: "Yellow lentils finished with a sizzling cumin-garlic tadka.",
    minutes: 40,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian", "budget"],
    aliases: ["tadka dal", "yellow dal", "daal"],
    ingredients: [
      I("toor or yellow lentils", 1, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("tomato", 2, "", "Produce"),
      I("cumin seed", 1, "tsp", "Herbs & Spices"),
      I("garlic", 4, "cloves", "Produce"),
      I("ghee or oil", 2, "tbsp", "Pantry"),
      I("turmeric", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Simmer lentils with turmeric until soft. Mash slightly.",
      "Sizzle cumin, garlic, onion, and tomato in ghee. Pour over the dal.",
    ],
  }),
  dish({
    id: "aloo-gobi",
    name: "Aloo gobi",
    description: "Dry-ish potato and cauliflower with cumin and turmeric.",
    minutes: 35,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian", "budget"],
    aliases: ["aloo gobhi", "potato cauliflower"],
    ingredients: [
      I("potato", 3, "", "Produce"),
      I("cauliflower", 1, "head", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cumin seed", 1, "tsp", "Herbs & Spices"),
      I("turmeric", 0.5, "tsp", "Herbs & Spices"),
      I("garam masala", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Fry cumin, onion, then potato and cauliflower with turmeric.",
      "Cover until tender. Finish with garam masala.",
    ],
  }),
  dish({
    id: "bibimbap",
    name: "Bibimbap",
    description: "Rice, sautéed vegetables, a fried egg, gochujang. Mix at the table.",
    minutes: 40,
    protein: "eggs",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["east asian", "korean"],
    aliases: ["korean mixed rice", "bibim bap"],
    ingredients: [
      I("rice", 2, "cups", "Pantry"),
      I("spinach", 4, "cups", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("zucchini", 1, "", "Produce"),
      I("bean sprouts", 2, "cups", "Produce"),
      I("eggs", 4, "", "Dairy & Eggs"),
      I("gochujang", 3, "tbsp", "Pantry"),
      I("sesame oil", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Season each vegetable separately with sesame and salt.",
      "Bowl rice, arrange veg, top with a fried egg and gochujang. Mix.",
    ],
  }),
  dish({
    id: "pho-bo",
    name: "Phở bò",
    description: "Beef noodle soup with star anise broth. Homemade takes a Saturday.",
    minutes: 180,
    protein: "beef",
    plate: "soup",
    cuisine: "East Asian",
    tags: ["east asian", "vietnamese"],
    aliases: ["pho", "pho bo", "vietnamese beef noodles"],
    ingredients: [
      I("beef bones", 3, "lb", "Meat & Seafood"),
      I("beef sirloin", 0.75, "lb", "Meat & Seafood"),
      I("rice noodles", 1, "lb", "Pantry"),
      I("onion", 2, "", "Produce"),
      I("ginger", 1, "piece", "Produce"),
      I("star anise", 4, "", "Herbs & Spices"),
      I("fish sauce", 3, "tbsp", "Pantry"),
      I("Thai basil", 1, "bunch", "Produce"),
      I("lime", 2, "", "Produce"),
    ],
    steps: [
      "Char onion and ginger. Simmer with bones and spices 3 hours. Season with fish sauce.",
      "Slice raw sirloin thin. Pour boiling broth over noodles and beef. Herbs and lime.",
    ],
  }),
  dish({
    id: "thai-green-curry",
    name: "Thai green curry",
    description: "Coconut, green curry paste, Thai basil. Heat you can tune.",
    minutes: 30,
    protein: "chicken",
    plate: "curry",
    cuisine: "East Asian",
    tags: ["east asian", "thai", "quick"],
    aliases: ["green curry", "gaeng keow wan"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("coconut milk", 1, "can", "Pantry"),
      I("green curry paste", 3, "tbsp", "Pantry"),
      I("Thai eggplant or zucchini", 2, "", "Produce"),
      I("Thai basil", 1, "bunch", "Produce"),
      I("fish sauce", 2, "tbsp", "Pantry"),
      I("palm or brown sugar", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Fry paste in a spoon of coconut cream. Add remaining coconut milk.",
      "Simmer chicken and veg. Finish with fish sauce, sugar, basil. Rice on the side.",
    ],
  }),
  dish({
    id: "kung-pao-chicken",
    name: "Kung pao chicken",
    description: "Diced chicken, dried chiles, peanuts. Sichuan-ish weeknight.",
    minutes: 25,
    protein: "chicken",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east asian", "chinese", "quick"],
    aliases: ["gong bao", "kung pao", "kungpo chicken"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("dried red chiles", 8, "", "Herbs & Spices"),
      I("roasted peanuts", 0.5, "cup", "Pantry"),
      I("soy sauce", 3, "tbsp", "Pantry"),
      I("Chinkiang vinegar", 1, "tbsp", "Pantry"),
      I("garlic", 4, "cloves", "Produce"),
      I("scallion", 4, "", "Produce"),
    ],
    steps: [
      "Velveting optional: toss chicken with a little soy and cornstarch. Stir-fry hot.",
      "Add chiles, garlic, sauce, peanuts, scallion. 2 minutes more.",
    ],
  }),
  dish({
    id: "potstickers",
    name: "Potstickers",
    description: "Pan-fried dumplings, steamed in the same skillet. Dip in vinegar-soy.",
    minutes: 45,
    protein: "pork",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east asian", "chinese"],
    aliases: ["gyoza", "guo tie", "dumplings", "jiaozi"],
    ingredients: [
      I("ground pork", 1, "lb", "Meat & Seafood"),
      I("napa cabbage", 2, "cups", "Produce"),
      I("scallion", 4, "", "Produce"),
      I("ginger", 1, "tbsp", "Produce"),
      I("dumpling wrappers", 40, "", "Frozen"),
      I("soy sauce", 3, "tbsp", "Pantry"),
    ],
    steps: [
      "Mix pork with squeezed cabbage, scallion, ginger, soy. Fill wrappers.",
      "Fry in oil until bottoms brown, add water, cover to steam, uncover to recrisp.",
    ],
  }),
  dish({
    id: "mujadara",
    name: "Mujadara",
    description: "Lentils, rice, and a pile of fried onions. Pantry feast.",
    minutes: 50,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["middle eastern", "vegetarian", "budget"],
    aliases: ["mujaddara", "lentils and rice", "mdardara"],
    ingredients: [
      I("brown lentils", 1, "cup", "Pantry"),
      I("rice", 1, "cup", "Pantry"),
      I("onion", 3, "", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 0.33, "cup", "Pantry"),
    ],
    steps: [
      "Cook lentils until almost tender. Add rice and cumin.",
      "Fry onions slow until deep brown. Pile on the pot.",
    ],
  }),
  dish({
    id: "kofta",
    name: "Beef kofta",
    description: "Spiced ground meat on skewers, yogurt, herbs. Grill or broiler.",
    minutes: 35,
    protein: "beef",
    plate: "skillet",
    cuisine: "Middle Eastern",
    tags: ["middle eastern"],
    aliases: ["kefte", "kofta kebab", "kefta"],
    ingredients: [
      I("ground beef or lamb", 1.5, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("parsley", 0.5, "bunch", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("coriander", 1, "tsp", "Herbs & Spices"),
      I("plain yogurt", 1, "cup", "Dairy & Eggs"),
      I("pita", 4, "", "Bakery"),
    ],
    steps: [
      "Mix meat with grated onion, parsley, and spices. Shape onto skewers.",
      "Grill or broil. Serve with yogurt and pita.",
    ],
  }),
  dish({
    id: "french-onion",
    name: "French onion soup",
    description: "Onions cooked past patience, stock, a Gruyère crouton.",
    minutes: 90,
    protein: "veg",
    plate: "soup",
    cuisine: "French",
    tags: ["french", "comfort"],
    aliases: ["soupe a l oignon", "onion soup"],
    ingredients: [
      I("onion", 4, "lb", "Produce"),
      I("beef broth", 8, "cups", "Pantry"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("dry white wine", 0.5, "cup", "Pantry"),
      I("baguette", 1, "", "Bakery"),
      I("Gruyère", 8, "oz", "Dairy & Eggs"),
    ],
    steps: [
      "Melt the 4 tablespoons of butter in a heavy pot over medium-low. Add the 4 pounds of sliced onions and cook 45 minutes, stirring often, until mahogany.",
      "Pour in the ½ cup of dry white wine and scrape the pot. Add the 8 cups of beef broth. Simmer 20 minutes.",
      "Heat the broiler. Ladle the soup into oven-safe bowls. Top with baguette slices and the 8 ounces of Gruyère.",
      "Broil 2–3 minutes, until the cheese bubbles. Serve hot.",
    ],
  }),
  dish({
    id: "ratatouille",
    name: "Ratatouille",
    description: "Late-summer vegetables stewed in olive oil until they agree.",
    minutes: 60,
    protein: "veg",
    plate: "skillet",
    cuisine: "French",
    tags: ["french", "vegetarian"],
    aliases: ["confit byaldi", "provencal vegetables"],
    ingredients: [
      I("eggplant", 1, "", "Produce"),
      I("zucchini", 2, "", "Produce"),
      I("bell pepper", 2, "", "Produce"),
      I("ripe tomatoes", 4, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("olive oil", 0.25, "cup", "Pantry"),
      I("fresh thyme", 4, "sprigs", "Produce"),
    ],
    steps: [
      "Brown vegetables in batches in olive oil.",
      "Stew together with tomato, garlic, and thyme until jammy.",
    ],
  }),
  dish({
    id: "croque-monsieur",
    name: "Croque monsieur",
    description: "Ham, béchamel, Gruyère, broiled. Add an egg and it is a madame.",
    minutes: 25,
    protein: "pork",
    plate: "toast",
    cuisine: "French",
    tags: ["french", "quick"],
    aliases: ["croque madame", "french ham sandwich"],
    ingredients: [
      I("pain de mie or white bread", 8, "slices", "Bakery"),
      I("ham", 8, "slices", "Meat & Seafood"),
      I("Gruyère", 6, "oz", "Dairy & Eggs"),
      I("milk", 1, "cup", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Make a quick béchamel. Assemble ham and cheese sandwiches, sauce on top.",
      "Broil until blistered.",
    ],
  }),
  dish({
    id: "paella",
    name: "Weeknight paella",
    description: "Saffron rice, chicken, shrimp, peas. Not Valencia-strict — Tuesday-friendly.",
    minutes: 50,
    protein: "chicken",
    plate: "skillet",
    cuisine: "Spanish",
    tags: ["spanish"],
    aliases: ["paella mixta", "spanish rice", "arroz con cosas"],
    ingredients: [
      I("short-grain rice", 1.5, "cups", "Pantry"),
      I("chicken thighs", 1, "lb", "Meat & Seafood"),
      I("shrimp", 0.75, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("tomato", 2, "", "Produce"),
      I("saffron", 1, "pinch", "Herbs & Spices"),
      I("chicken broth", 4, "cups", "Pantry"),
      I("frozen peas", 1, "cup", "Frozen"),
    ],
    steps: [
      "Brown chicken. Sofrito of onion and tomato. Add rice and saffron broth. Do not stir.",
      "Nestle shrimp and peas for the last 8 minutes. Rest 5.",
    ],
  }),
  dish({
    id: "spanish-tortilla",
    name: "Spanish tortilla",
    description: "Potato, onion, egg. Thick omelette, room-temp or hot.",
    minutes: 40,
    protein: "eggs",
    plate: "skillet",
    cuisine: "Spanish",
    tags: ["spanish", "vegetarian"],
    aliases: ["tortilla española", "spanish omelette", "potato omelette"],
    ingredients: [
      I("potato", 2, "lb", "Produce"),
      I("onion", 1, "", "Produce"),
      I("eggs", 6, "", "Dairy & Eggs"),
      I("olive oil", 0.75, "cup", "Pantry"),
    ],
    steps: [
      "Slow-cook potato and onion in olive oil until tender. Drain, mix with beaten eggs.",
      "Set in a pan, flip once. Cool slightly before slicing.",
    ],
  }),
  dish({
    id: "schnitzel",
    name: "Pork schnitzel",
    description: "Pound, bread, fry. Lemon wedge non-negotiable.",
    minutes: 30,
    protein: "pork",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "german", "quick"],
    aliases: ["wienerschnitzel", "wiener schnitzel", "breaded pork"],
    ingredients: [
      I("pork cutlets", 4, "", "Meat & Seafood"),
      I("flour", 0.5, "cup", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("breadcrumbs", 1.5, "cups", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("oil for frying", 1, "cup", "Pantry"),
    ],
    steps: [
      "Pound cutlets thin. Flour, egg, breadcrumb.",
      "Fry in 350°F oil until gold. Lemon.",
    ],
  }),
  dish({
    id: "pierogi",
    name: "Pierogi",
    description: "Potato-cheese dumplings boiled then butter-fried. Sour cream on the side.",
    minutes: 90,
    protein: "veg",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "polish", "vegetarian"],
    aliases: ["pyrohy", "vareniki", "perogies", "pierogies"],
    ingredients: [
      I("flour", 3, "cups", "Pantry"),
      I("eggs", 1, "", "Dairy & Eggs"),
      I("potato", 2, "lb", "Produce"),
      I("cheddar or farmer cheese", 1, "cup", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("sour cream", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Make a dough. Fill with mashed potato and cheese.",
      "Boil until they float, then fry in butter with onion. Sour cream.",
    ],
  }),
  dish({
    id: "rice-and-peas",
    name: "Rice and peas",
    description: "Coconut rice with kidney beans, thyme, and Scotch bonnet. Jamaican table.",
    minutes: 45,
    protein: "veg",
    plate: "bowl",
    cuisine: "Caribbean",
    tags: ["caribbean", "vegetarian"],
    aliases: ["rice n peas", "coconut rice and beans"],
    ingredients: [
      I("rice", 2, "cups", "Pantry"),
      I("kidney beans", 1, "can", "Pantry"),
      I("coconut milk", 1, "can", "Pantry"),
      I("thyme", 4, "sprigs", "Produce"),
      I("scallion", 3, "", "Produce"),
      I("Scotch bonnet", 1, "", "Produce"),
    ],
    steps: [
      "Simmer beans with coconut milk, thyme, scallion, and a whole Scotch bonnet.",
      "Add rice and cook until the liquid is gone. Do not burst the pepper unless you mean it.",
    ],
  }),
  dish({
    id: "gumbo",
    name: "Chicken and sausage gumbo",
    description: "Dark roux, holy trinity, okra or filé. Louisiana in a pot.",
    minutes: 120,
    protein: "chicken",
    plate: "soup",
    cuisine: "American",
    tags: ["american", "cajun"],
    aliases: ["gumbo ya ya", "chicken sausage gumbo"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("andouille sausage", 12, "oz", "Meat & Seafood"),
      I("flour", 0.75, "cup", "Pantry"),
      I("oil", 0.75, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("okra", 2, "cups", "Produce"),
      I("chicken broth", 8, "cups", "Pantry"),
    ],
    steps: [
      "Cook a dark roux. Add trinity. Add stock, chicken, sausage, okra.",
      "Simmer an hour. Rice in the bowl, gumbo over.",
    ],
  }),
  dish({
    id: "jambalaya",
    name: "Jambalaya",
    description: "Rice cooked with chicken, sausage, the trinity, and a little heat.",
    minutes: 50,
    protein: "chicken",
    plate: "skillet",
    cuisine: "American",
    tags: ["american", "cajun"],
    aliases: ["cajun jambalaya", "creole jambalaya"],
    ingredients: [
      I("chicken thighs", 1, "lb", "Meat & Seafood"),
      I("andouille sausage", 12, "oz", "Meat & Seafood"),
      I("rice", 1.5, "cups", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("chicken broth", 3, "cups", "Pantry"),
      I("Cajun seasoning", 1, "tbsp", "Herbs & Spices"),
    ],
    steps: [
      "Brown chicken and sausage. Sauté trinity. Add rice, tomato, broth, seasoning.",
      "Cover until the rice is done. Rest 5 minutes.",
    ],
  }),
  dish({
    id: "buttermilk-fried-chicken",
    name: "Buttermilk fried chicken",
    description: "Overnight buttermilk, a seasoned crust, a cast-iron pot.",
    minutes: 60,
    protein: "chicken",
    plate: "skillet",
    cuisine: "American",
    tags: ["american", "old-school"],
    aliases: ["fried chicken", "southern fried chicken"],
    ingredients: [
      I("chicken pieces", 3, "lb", "Meat & Seafood"),
      I("buttermilk", 2, "cups", "Dairy & Eggs"),
      I("flour", 2, "cups", "Pantry"),
      I("paprika", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("oil for frying", 4, "cups", "Pantry"),
    ],
    steps: [
      "Soak chicken in salted buttermilk (overnight if you can).",
      "Dredge in seasoned flour. Fry at 325°F until 175°F inside.",
    ],
  }),
  dish({
    id: "chicken-paprikash",
    name: "Chicken paprikash",
    description: "Chicken in a paprika-sour cream sauce. Dumplings or noodles under it.",
    minutes: 55,
    protein: "chicken",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "hungarian"],
    aliases: ["paprikash", "csirke paprikas", "paprika chicken"],
    ingredients: [
      I("chicken thighs", 2, "lb", "Meat & Seafood"),
      I("onion", 2, "", "Produce"),
      I("sweet paprika", 3, "tbsp", "Herbs & Spices"),
      I("sour cream", 1, "cup", "Dairy & Eggs"),
      I("chicken broth", 1.5, "cups", "Pantry"),
      I("egg noodles", 12, "oz", "Pantry"),
    ],
    steps: [
      "Brown chicken. Sweat onion, add paprika off heat so it does not burn.",
      "Add broth, simmer until tender. Stir sour cream in off heat. Noodles.",
    ],
  }),
];
