import type { Recipe } from "./types";

const I = (
  name: string,
  qty: number,
  unit: string,
  aisle: Recipe["ingredients"][number]["aisle"],
) => ({ name, qty, unit, aisle });

function dish(
  partial: Omit<Recipe, "nutrition" | "pack" | "servings"> & {
    nutrition?: Recipe["nutrition"];
    pack?: Recipe["pack"];
    servings?: number;
  },
): Recipe {
  return {
    pack: "free",
    servings: 4,
    nutrition: { cal: 400, protein: 20, carbs: 36, fat: 16 },
    ...partial,
  };
}

export const EXTRA_RECIPES: Recipe[] = [
  dish({
    id: "jiggs-dinner",
    name: "Jiggs dinner",
    description: "Newfoundland boiled dinner: salt beef, pease pudding, cabbage, and root veg.",
    minutes: 180,
    protein: "beef",
    plate: "roast",
    cuisine: "Newfoundland",
    tags: ["old-school", "newfoundland", "sunday", "atlantic", "comfort"],
    photo: "/food/jiggs.jpg",
    aliases: [
      "boiled dinner",
      "salt beef dinner",
      "salt meat dinner",
      "jigs dinner",
      "jigg's dinner",
      "scoff",
      "sunday scoff",
      "newfoundland dinner",
    ],
    ingredients: [
      I("salt beef", 2, "lb", "Meat & Seafood"),
      I("yellow split peas", 1, "cup", "Pantry"),
      I("cabbage", 1, "head", "Produce"),
      I("potato", 6, "", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("turnip", 1, "", "Produce"),
      I("figgy duff mix or raisins", 1, "cup", "Pantry"),
    ],
    steps: [
      "Soak the salt beef overnight. Drain, cover with fresh water, and simmer 2 hours.",
      "Tie the split peas in a cloth bag and add them to the pot so they cook into pease pudding.",
      "Add potato, carrot, and turnip, then the cabbage for the last 40 minutes.",
      "Lift the meat and vegetables onto a platter. Slice the beef.",
      "Serve with pease pudding, mustard pickles, and a jug of the pot liquor.",
    ],
  }),
  dish({
    id: "toutons",
    name: "Toutons",
    description: "Fried bread dough, Newfoundland breakfast, with molasses.",
    minutes: 25,
    protein: "veg",
    plate: "toast",
    cuisine: "Newfoundland",
    photo: "/food/toast.jpg",
    tags: ["newfoundland", "breakfast", "vegetarian", "atlantic"],
    aliases: ["touton", "touts", "fried dough", "nl breakfast"],
    ingredients: [
      I("bread dough", 1, "lb", "Bakery"),
      I("pork fat or oil", 3, "tbsp", "Pantry"),
      I("molasses", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Flatten pieces of risen dough. Fry in fat until gold on both sides.",
      "Serve hot with molasses or butter.",
    ],
  }),
  dish({
    id: "fish-and-brewis",
    name: "Fish and brewis",
    description: "Salt cod, hard bread, and scrunchions. A winter staple.",
    minutes: 40,
    protein: "fish",
    plate: "bowl",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school", "pescatarian"],
    aliases: ["fish n brewis", "fish 'n brewis", "brewis", "hard bread and fish"],
    ingredients: [
      I("salt cod", 1, "lb", "Meat & Seafood"),
      I("hard bread", 4, "cakes", "Bakery"),
      I("salt pork scrunchions", 4, "oz", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
    ],
    steps: [
      "Soak fish and hard bread separately overnight.",
      "Simmer both until tender. Fry pork bits and onion. Pour fat over the bowl.",
    ],
  }),
  dish({
    id: "cod-au-gratin",
    name: "Cod au gratin",
    description: "Newfoundland baked cod under a cheddar crust.",
    minutes: 45,
    protein: "fish",
    plate: "fish",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "pescatarian", "comfort"],
    aliases: ["cod gratin", "cheesy cod", "nl cod bake"],
    ingredients: [
      I("cod fillets", 1.5, "lb", "Meat & Seafood"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("cheddar", 8, "oz", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
    ],
    steps: [
      "Make a white sauce with butter, flour, and milk. Fold in most of the cheddar.",
      "Layer cooked cod in a dish, pour sauce, top with remaining cheese. Bake 20 minutes at 375°F.",
    ],
  }),
  dish({
    id: "pea-soup-doughboys",
    name: "Pea soup with doughboys",
    description: "Split-pea pot with fluffy dumplings on top.",
    minutes: 90,
    protein: "pork",
    plate: "soup",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school", "budget"],
    aliases: ["doughboys", "pea soup dumplings", "nl pea soup"],
    ingredients: [
      I("yellow split peas", 2, "cups", "Pantry"),
      I("ham bone or salt meat", 1, "", "Meat & Seafood"),
      I("carrot", 2, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("flour", 1.5, "cups", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Simmer peas with meat and veg until thick, about an hour.",
      "Mix dumpling dough, drop on the soup, cover 15 minutes. Do not peek.",
    ],
  }),
  dish({
    id: "meatloaf",
    name: "Classic meatloaf",
    description: "The old-school loaf with a ketchup glaze.",
    minutes: 75,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort", "american"],
    aliases: ["meat loaf", "mom's meatloaf", "ketchup loaf"],
    ingredients: [
      I("ground beef", 2, "lb", "Meat & Seafood"),
      I("breadcrumb", 1, "cup", "Pantry"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
      I("ketchup", 0.5, "cup", "Pantry"),
      I("Worcestershire", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Mix beef, crumbs, eggs, onion, and a spoon of ketchup. Shape into a loaf.",
      "Paint with ketchup. Bake 1 hour at 350°F. Rest 10 minutes.",
    ],
  }),
  dish({
    id: "tuna-casserole",
    name: "Tuna noodle casserole",
    description: "Creamy noodles, peas, and a crunchy top. Church-basement famous.",
    minutes: 40,
    protein: "fish",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "budget", "pescatarian"],
    aliases: ["tuna bake", "tuna hotdish", "noodle casserole"],
    ingredients: [
      I("egg noodles", 12, "oz", "Pantry"),
      I("canned tuna", 2, "cans", "Pantry"),
      I("cream of mushroom soup", 1, "can", "Pantry"),
      I("frozen peas", 1, "cup", "Frozen"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
      I("potato chips or crumbs", 1, "cup", "Pantry"),
    ],
    steps: [
      "Boil noodles. Mix with tuna, soup, peas, and cheese.",
      "Top with crushed chips. Bake 20 minutes at 375°F.",
    ],
  }),
  dish({
    id: "shepherds-pie",
    name: "Shepherd's pie",
    description: "Minced lamb (or beef cottage pie) under mashed potato.",
    minutes: 60,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort", "british"],
    aliases: ["cottage pie", "shepards pie", "mince and tatties", "potato pie"],
    ingredients: [
      I("ground lamb or beef", 1.5, "lb", "Meat & Seafood"),
      I("potato", 2, "lb", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("peas", 1, "cup", "Frozen"),
      I("onion", 1, "", "Produce"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("milk", 0.5, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Brown mince with onion and carrot. Add peas and a splash of stock.",
      "Mash potato with butter and milk. Spread over the mince. Bake 25 minutes at 400°F.",
    ],
  }),
  dish({
    id: "chicken-pot-pie",
    name: "Chicken pot pie",
    description: "A pastry lid over a creamy chicken stew.",
    minutes: 70,
    protein: "chicken",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["pot pie", "chicken pie", "potpie"],
    ingredients: [
      I("cooked chicken", 3, "cups", "Meat & Seafood"),
      I("pie crust", 1, "", "Bakery"),
      I("carrot", 2, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("frozen peas", 1, "cup", "Frozen"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("flour", 0.33, "cup", "Pantry"),
      I("chicken broth", 2, "cups", "Pantry"),
    ],
    steps: [
      "Make a gravy with butter, flour, and broth. Fold in chicken and veg.",
      "Pour into a dish, top with crust, vent, bake 35 minutes at 400°F.",
    ],
  }),
  dish({
    id: "beef-stroganoff",
    name: "Beef stroganoff",
    description: "Sour-cream beef and mushrooms over egg noodles.",
    minutes: 40,
    protein: "beef",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["stroganov", "beef strog", "sour cream beef"],
    ingredients: [
      I("beef sirloin", 1.5, "lb", "Meat & Seafood"),
      I("mushrooms", 8, "oz", "Produce"),
      I("onion", 1, "", "Produce"),
      I("sour cream", 1, "cup", "Dairy & Eggs"),
      I("egg noodles", 12, "oz", "Pantry"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Sear strips of beef. Sauté mushrooms and onion.",
      "Stir in sour cream off the heat. Serve over noodles.",
    ],
  }),
  dish({
    id: "moussaka",
    name: "Moussaka",
    description: "Layered eggplant, spiced lamb, and béchamel.",
    minutes: 110,
    protein: "beef",
    plate: "roast",
    cuisine: "Greek",
    tags: ["greek", "bake"],
    aliases: ["musaka", "eggplant lamb bake"],
    ingredients: [
      I("eggplant", 2, "", "Produce"),
      I("ground lamb or beef", 1.5, "lb", "Meat & Seafood"),
      I("tomato sauce", 2, "cups", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("flour", 4, "tbsp", "Pantry"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Salt and roast eggplant slices. Cook mince with onion, tomato, and cinnamon.",
      "Layer eggplant and meat. Pour béchamel. Bake 45 minutes at 350°F.",
    ],
  }),
  dish({
    id: "souvlaki",
    name: "Chicken souvlaki",
    description: "Lemon-oregano skewers with pita and tzatziki.",
    minutes: 35,
    protein: "chicken",
    plate: "skillet",
    cuisine: "Greek",
    tags: ["greek", "grill"],
    aliases: ["souvlakia", "greek skewers", "kebab greek"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("lemon", 2, "", "Produce"),
      I("dried oregano", 2, "tsp", "Herbs & Spices"),
      I("garlic", 4, "cloves", "Produce"),
      I("pita", 4, "", "Bakery"),
      I("cucumber", 1, "", "Produce"),
      I("Greek yogurt", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Marinate chicken in lemon, oregano, garlic, and oil. Skewer and grill.",
      "Stir yogurt with grated cucumber and garlic. Wrap in pita.",
    ],
  }),
  dish({
    id: "spanakopita",
    name: "Spanakopita",
    description: "Spinach and feta in shatter-crisp phyllo.",
    minutes: 55,
    protein: "veg",
    plate: "toast",
    cuisine: "Greek",
    tags: ["greek", "vegetarian"],
    aliases: ["spinach pie", "spanakopitta", "greek spinach feta"],
    ingredients: [
      I("phyllo dough", 1, "pack", "Frozen"),
      I("spinach", 2, "lb", "Produce"),
      I("feta", 8, "oz", "Dairy & Eggs"),
      I("dill", 0.25, "cup", "Produce"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("olive oil", 0.33, "cup", "Pantry"),
    ],
    steps: [
      "Wilt spinach, squeeze dry, mix with feta, dill, and eggs.",
      "Layer oiled phyllo, fill, top, score, bake 35 minutes at 375°F.",
    ],
  }),
  dish({
    id: "horiatiki",
    name: "Horiatiki salad",
    description: "The real Greek village salad. No lettuce.",
    minutes: 15,
    protein: "veg",
    plate: "green",
    cuisine: "Greek",
    tags: ["greek", "vegetarian", "quick"],
    aliases: ["greek salad", "village salad", "horiatiki"],
    ingredients: [
      I("ripe tomatoes", 4, "", "Produce"),
      I("cucumber", 1, "", "Produce"),
      I("red onion", 0.5, "", "Produce"),
      I("Kalamata olives", 0.5, "cup", "Pantry"),
      I("feta slab", 6, "oz", "Dairy & Eggs"),
      I("olive oil", 3, "tbsp", "Pantry"),
      I("dried oregano", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Chunk tomato, cucumber, and onion. Add olives.",
      "Lay a slab of feta on top. Olive oil, oregano, salt.",
    ],
  }),
  dish({
    id: "cacio-e-pepe",
    name: "Cacio e pepe",
    description: "Pasta, pecorino, and a lot of black pepper.",
    minutes: 20,
    protein: "veg",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick", "vegetarian"],
    aliases: ["cacio pepe", "cheese and pepper pasta", "pecorino pasta"],
    ingredients: [
      I("spaghetti or tonnarelli", 12, "oz", "Pantry"),
      I("pecorino romano", 1.5, "cups", "Dairy & Eggs"),
      I("black pepper", 2, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Boil pasta. Toast pepper in a pan. Toss with starchy water and pecorino off heat until creamy.",
    ],
  }),
  dish({
    id: "carbonara",
    name: "Spaghetti carbonara",
    description: "Eggs, guanciale, pecorino. No cream.",
    minutes: 25,
    protein: "pork",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick"],
    aliases: ["carbonara pasta", "bacon egg pasta"],
    ingredients: [
      I("spaghetti", 12, "oz", "Pantry"),
      I("guanciale or pancetta", 6, "oz", "Meat & Seafood"),
      I("egg yolks", 4, "", "Dairy & Eggs"),
      I("pecorino romano", 1, "cup", "Dairy & Eggs"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Crisp guanciale. Whisk yolks with pecorino and pepper.",
      "Toss hot pasta with fat, then the egg mixture off heat with pasta water.",
    ],
  }),
  dish({
    id: "puttanesca",
    name: "Pasta puttanesca",
    description: "Anchovy, olive, caper, tomato. Pantry fireworks.",
    minutes: 25,
    protein: "fish",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick", "pescatarian"],
    aliases: ["putanesca", "olive caper pasta"],
    ingredients: [
      I("spaghetti", 12, "oz", "Pantry"),
      I("anchovy fillets", 6, "", "Pantry"),
      I("Kalamata olives", 0.5, "cup", "Pantry"),
      I("capers", 2, "tbsp", "Pantry"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("garlic", 4, "cloves", "Produce"),
    ],
    steps: [
      "Melt anchovy with garlic in oil. Add tomato, olives, capers. Simmer 10 minutes. Toss pasta.",
    ],
  }),
  dish({
    id: "osso-buco",
    name: "Osso buco",
    description: "Braised veal shanks with gremolata.",
    minutes: 150,
    protein: "beef",
    plate: "roast",
    cuisine: "Italian",
    tags: ["italian", "sunday"],
    aliases: ["ossobuco", "veal shank", "braised shank"],
    ingredients: [
      I("veal shanks", 4, "", "Meat & Seafood"),
      I("carrot", 2, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("onion", 1, "", "Produce"),
      I("white wine", 1, "cup", "Pantry"),
      I("lemon zest", 1, "tbsp", "Produce"),
      I("parsley", 0.25, "cup", "Produce"),
    ],
    steps: [
      "Brown shanks. Sweat soffritto. Deglaze with wine. Braise covered 2 hours.",
      "Finish with lemon zest, garlic, and parsley.",
    ],
  }),
  dish({
    id: "tacos-al-pastor",
    name: "Tacos al pastor",
    description: "Achiote pork, pineapple, onion, cilantro.",
    minutes: 40,
    protein: "pork",
    plate: "taco",
    cuisine: "Mexican",
    tags: ["mexican"],
    aliases: ["al pastor", "pastor tacos", "pineapple pork tacos"],
    ingredients: [
      I("pork shoulder", 1.5, "lb", "Meat & Seafood"),
      I("achiote paste", 2, "tbsp", "Herbs & Spices"),
      I("pineapple", 1, "cup", "Produce"),
      I("corn tortillas", 12, "", "Bakery"),
      I("white onion", 1, "", "Produce"),
      I("cilantro", 1, "bunch", "Produce"),
    ],
    steps: [
      "Marinate thin pork in achiote and pineapple juice. Sear hot.",
      "Chop with grilled pineapple. Serve on tortillas with onion and cilantro.",
    ],
  }),
  dish({
    id: "chicken-tikka-masala",
    name: "Chicken tikka masala",
    description: "Charred tikka in a creamy tomato masala.",
    minutes: 50,
    protein: "chicken",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "comfort"],
    aliases: ["CTM", "tikka masala", "butter chicken-ish"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("plain yogurt", 0.5, "cup", "Dairy & Eggs"),
      I("garam masala", 2, "tsp", "Herbs & Spices"),
      I("tomato puree", 1, "cup", "Pantry"),
      I("cream", 0.5, "cup", "Dairy & Eggs"),
      I("garlic", 4, "cloves", "Produce"),
      I("fresh ginger", 1, "tbsp", "Produce"),
    ],
    steps: [
      "Marinate chicken in yogurt and spices. Broil until charred.",
      "Simmer tomato, garlic, ginger, and cream. Add chicken. Serve with rice or naan.",
    ],
  }),
  dish({
    id: "chana-masala",
    name: "Chana masala",
    description: "Chickpeas in a tangy tomato-onion gravy.",
    minutes: 35,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian", "budget"],
    aliases: ["chole", "chickpea curry", "channa masala"],
    ingredients: [
      I("chickpeas", 2, "cans", "Pantry"),
      I("onion", 2, "", "Produce"),
      I("tomato", 3, "", "Produce"),
      I("garam masala", 2, "tsp", "Herbs & Spices"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("fresh ginger", 1, "tbsp", "Produce"),
      I("cilantro", 0.25, "cup", "Produce"),
    ],
    steps: [
      "Brown onion. Add ginger, spices, and tomato. Simmer.",
      "Add chickpeas and a splash of water. Cook 15 minutes. Cilantro.",
    ],
  }),
  dish({
    id: "mapo-tofu",
    name: "Mapo tofu",
    description: "Silken tofu in a numbing chili-pork sauce.",
    minutes: 25,
    protein: "pork",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["east-asian", "spicy", "quick"],
    aliases: ["mapo doufu", "spicy tofu", "sichuan tofu"],
    ingredients: [
      I("soft tofu", 14, "oz", "Produce"),
      I("ground pork", 4, "oz", "Meat & Seafood"),
      I("doubanjiang", 2, "tbsp", "Pantry"),
      I("garlic", 3, "cloves", "Produce"),
      I("ginger", 1, "tsp", "Produce"),
      I("soy sauce", 1, "tbsp", "Pantry"),
      I("green onion", 3, "", "Produce"),
    ],
    steps: [
      "Brown pork. Add doubanjiang, garlic, ginger.",
      "Add tofu cubes and a little water. Simmer gently. Green onion.",
    ],
  }),
  dish({
    id: "okonomiyaki",
    name: "Okonomiyaki",
    description: "Osaka cabbage pancake with okonomi sauce.",
    minutes: 30,
    protein: "eggs",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east-asian", "japanese"],
    aliases: ["cabbage pancake", "osaka pancake", "okonomi"],
    ingredients: [
      I("cabbage", 0.5, "head", "Produce"),
      I("flour", 1, "cup", "Pantry"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("dashi or water", 0.75, "cup", "Pantry"),
      I("okonomi sauce", 3, "tbsp", "Pantry"),
      I("mayo", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Mix shredded cabbage with batter. Fry like a thick pancake.",
      "Stripe with sauce and mayo.",
    ],
  }),
  dish({
    id: "falafel-pita",
    name: "Falafel pita",
    description: "Crisp chickpea fritters with tahini and pickles.",
    minutes: 40,
    protein: "veg",
    plate: "taco",
    cuisine: "Middle Eastern",
    tags: ["middle-eastern", "vegetarian"],
    aliases: ["falafel sandwich", "chickpea fritters", "taameya"],
    ingredients: [
      I("dried chickpeas", 1.5, "cups", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("parsley", 1, "bunch", "Produce"),
      I("cumin", 2, "tsp", "Herbs & Spices"),
      I("pita", 4, "", "Bakery"),
      I("tahini", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Soak chickpeas overnight. Pulse with onion, garlic, herbs, and cumin. Do not use canned.",
      "Fry scoopfuls until deep brown. Stuff pita with tahini, tomato, and pickle.",
    ],
  }),
  dish({
    id: "shakshuka-pepper",
    name: "Shakshuka with peppers",
    description: "North African eggs in a pepper-tomato pan.",
    minutes: 30,
    protein: "eggs",
    plate: "skillet",
    cuisine: "Middle Eastern",
    tags: ["middle-eastern", "vegetarian", "quick"],
    aliases: ["eggs in purgatory", "shakshouka", "matbucha eggs"],
    ingredients: [
      I("eggs", 6, "", "Dairy & Eggs"),
      I("bell peppers", 2, "", "Produce"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Stew peppers and onion in tomato and spices.",
      "Nest eggs, cover until just set.",
    ],
  }),
  dish({
    id: "coq-au-vin",
    name: "Coq au vin",
    description: "Chicken braised in red wine with lardons and mushrooms.",
    minutes: 120,
    protein: "chicken",
    plate: "roast",
    cuisine: "French",
    tags: ["french", "sunday"],
    aliases: ["chicken in wine", "coq au vin rouge"],
    ingredients: [
      I("chicken pieces", 3, "lb", "Meat & Seafood"),
      I("red wine", 2, "cups", "Pantry"),
      I("bacon lardons", 4, "oz", "Meat & Seafood"),
      I("mushrooms", 8, "oz", "Produce"),
      I("pearl onions", 1, "cup", "Produce"),
      I("thyme", 4, "sprigs", "Produce"),
    ],
    steps: [
      "Brown chicken and lardons. Add wine, thyme, mushrooms, and onions.",
      "Simmer covered 1 hour until the sauce is glossy.",
    ],
  }),
  dish({
    id: "biscuits-gravy",
    name: "Biscuits and sausage gravy",
    description: "Southern breakfast: tender biscuits drowned in peppered gravy.",
    minutes: 35,
    protein: "pork",
    plate: "toast",
    cuisine: "American",
    tags: ["old-school", "american", "breakfast"],
    aliases: ["sausage gravy", "sawmill gravy", "biscuits n gravy"],
    ingredients: [
      I("breakfast sausage", 1, "lb", "Meat & Seafood"),
      I("flour", 0.25, "cup", "Pantry"),
      I("milk", 3, "cups", "Dairy & Eggs"),
      I("biscuit mix or homemade biscuits", 8, "", "Bakery"),
      I("black pepper", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Brown sausage. Sprinkle flour, then whisk in milk until thick. Heavy pepper.",
      "Split hot biscuits and ladle gravy over.",
    ],
  }),
  dish({
    id: "jerk-chicken",
    name: "Jerk chicken",
    description: "Scotch bonnet, allspice, and thyme on grilled chicken.",
    minutes: 50,
    protein: "chicken",
    plate: "roast",
    cuisine: "Caribbean",
    tags: ["caribbean", "spicy"],
    aliases: ["jamaican jerk", "jerk BBQ"],
    ingredients: [
      I("chicken pieces", 3, "lb", "Meat & Seafood"),
      I("scotch bonnet", 1, "", "Produce"),
      I("allspice", 1, "tbsp", "Herbs & Spices"),
      I("fresh thyme", 1, "tbsp", "Produce"),
      I("green onion", 4, "", "Produce"),
      I("soy sauce", 2, "tbsp", "Pantry"),
      I("lime", 1, "", "Produce"),
    ],
    steps: [
      "Blend marinade. Rub into chicken at least 1 hour.",
      "Grill or roast until the edges char and juices run clear.",
    ],
  }),
  dish({
    id: "pad-thai",
    name: "Pad Thai",
    description: "Tamarind noodles, egg, shrimp or tofu, crushed peanut.",
    minutes: 30,
    protein: "seafood",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east-asian", "thai", "quick"],
    aliases: ["pad tai", "thai noodles", "phat thai"],
    ingredients: [
      I("rice noodles", 8, "oz", "Pantry"),
      I("shrimp", 12, "oz", "Meat & Seafood"),
      I("egg", 2, "", "Dairy & Eggs"),
      I("tamarind paste", 2, "tbsp", "Pantry"),
      I("fish sauce", 2, "tbsp", "Pantry"),
      I("bean sprouts", 2, "cups", "Produce"),
      I("peanuts", 0.33, "cup", "Pantry"),
    ],
    steps: [
      "Soak noodles. Stir-fry shrimp, scramble egg.",
      "Add noodles and sauce. Toss with sprouts and peanuts.",
    ],
  }),
  dish({
    id: "quiche-lorraine",
    name: "Quiche Lorraine",
    description: "Custard, bacon, and Gruyère in a pastry shell.",
    minutes: 60,
    protein: "eggs",
    plate: "toast",
    cuisine: "French",
    tags: ["french", "brunch"],
    aliases: ["bacon quiche", "lorraine tart"],
    ingredients: [
      I("pie crust", 1, "", "Bakery"),
      I("bacon", 6, "slices", "Meat & Seafood"),
      I("eggs", 4, "", "Dairy & Eggs"),
      I("cream", 1.5, "cups", "Dairy & Eggs"),
      I("Gruyère", 4, "oz", "Dairy & Eggs"),
    ],
    steps: [
      "Blind-bake crust. Scatter bacon and cheese.",
      "Pour egg and cream. Bake 35 minutes at 350°F until just set.",
    ],
  }),
  dish({
    id: "red-beans-rice",
    name: "Red beans and rice",
    description: "Monday pot: creamy beans, smoked sausage, rice.",
    minutes: 120,
    protein: "pork",
    plate: "bowl",
    cuisine: "American",
    tags: ["american", "old-school", "budget"],
    aliases: ["red beans", "monday beans", "cajun beans"],
    ingredients: [
      I("dried red kidney beans", 1, "lb", "Pantry"),
      I("andouille sausage", 12, "oz", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("rice", 2, "cups", "Pantry"),
    ],
    steps: [
      "Soak beans. Simmer with trinity and sausage until creamy, 90 minutes.",
      "Serve over rice.",
    ],
  }),
  dish({
    id: "pastitsio",
    name: "Pastitsio",
    description: "Greek baked pasta with cinnamon meat and béchamel.",
    minutes: 90,
    protein: "beef",
    plate: "pasta",
    cuisine: "Greek",
    tags: ["greek", "bake"],
    aliases: ["pastichio", "greek lasagna", "makaronia tou fournou"],
    ingredients: [
      I("bucatini or penne", 1, "lb", "Pantry"),
      I("ground beef", 1.5, "lb", "Meat & Seafood"),
      I("tomato sauce", 2, "cups", "Pantry"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("béchamel (milk, butter, flour)", 3, "cups", "Dairy & Eggs"),
      I("kefalotyri or parmesan", 4, "oz", "Dairy & Eggs"),
    ],
    steps: [
      "Cook pasta. Make cinnamon meat sauce.",
      "Layer pasta, meat, béchamel. Bake 40 minutes at 350°F.",
    ],
  }),
  dish({
    id: "welsh-rarebit",
    name: "Welsh rarebit",
    description: "Beer-cheese on toast. Old-school supper.",
    minutes: 20,
    protein: "veg",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "vegetarian", "quick", "british"],
    aliases: ["welsh rabbit", "cheese toast", "rarebit"],
    ingredients: [
      I("sharp cheddar", 8, "oz", "Dairy & Eggs"),
      I("ale or beer", 0.5, "cup", "Pantry"),
      I("mustard", 1, "tsp", "Pantry"),
      I("Worcestershire", 1, "tsp", "Pantry"),
      I("sourdough", 4, "slices", "Bakery"),
    ],
    steps: [
      "Melt cheese with ale, mustard, and Worcestershire.",
      "Spoon on toast and broil until bubbling.",
    ],
  }),
];

