import { I, dish } from "./catalog-kit";
import type { Recipe, RecipeSource } from "./types";

function src(book: string, author: string, year: number, era: string, archiveId: string, credit: string): RecipeSource {
  return { book, author, year, era, archiveId, credit };
}

const kephart = src("Camping and Woodcraft", "Horace Kephart", 1917, "1910s", "campingwoodcraft00keph", "Horace Kephart, Camping and Woodcraft (1917). Public domain.");
const ladiesAid = src("Woman Suffrage Cook Book", "Mrs. Hattie A. Burr", 1886, "1880s", "womansuffragecoo00burr", "Mrs. Hattie A. Burr, The Woman Suffrage Cook Book (Boston, 1886), and typical Ladies' Aid church-supper dishes. Public domain.");
const kleber = src("The Suffrage Cook Book", "Mrs. L. O. Kleber", 1915, "1910s", "suffragecookbook00kleb", "Mrs. L. O. Kleber, The Suffrage Cook Book (Pittsburgh, 1915). Public domain.");
const hill = src("Salads, Sandwiches and Chafing Dishes", "Janet McKenzie Hill", 1909, "1900s", "saladssandwiches00hill", "Janet McKenzie Hill, Salads, Sandwiches and Chafing Dishes (1909). Public domain.");
const bosse = src("Chinese-Japanese Cook Book", "Sara Bosse & Onoto Watanna", 1914, "1910s", "chinesejapanesec00boss", "Sara Bosse and Onoto Watanna (Winnifred Eaton), Chinese-Japanese Cook Book (Rand McNally, 1914). Public domain.");
const oliveGreen = src("How to Cook Fish", "Olive Green", 1908, "1900s", "howtocookfish00gree", "Olive Green, How to Cook Fish (Putnam, 1908). Public domain.");

function h(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: RecipeSource,
  nutrition: Recipe["nutrition"],
): Recipe {
  return dish({
    id, name, cuisine, description, minutes, protein, plate,
    tags: Array.from(new Set(["vintage", ...tags])),
    ingredients, steps, nutrition, source,
  });
}

export const TABLE_RECIPES: Recipe[] = [
  h("vh-kp-bannock", "Camp bannock", "American", ["era-1910s", "book-kephart", "camping", "vegetarian", "budget"], "veg", "skillet", 25, "Kephart's trail bread: flour, baking powder, fat, water, fried in a skillet.", [I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("lard or bacon fat", 2, "tbsp", "Pantry"), I("water", 0.75, "cup", "Other")], ["Mix the flour, baking powder, and salt. Rub in the fat until the mix looks like meal.", "Add water to make a soft dough. Pat it into a ¾-inch round.", "Heat a greased skillet over the fire or a medium burner.", "Cook 8 minutes a side, until the crust is brown and a stick in the center comes out clean. Do not burn the bottom — raise the pan if you need to.", "Serve the bannock split, hot, with bacon drippings or jam."], kephart, { cal: 220, protein: 5, carbs: 36, fat: 6 }),
  h("vh-kp-mulligan", "Camp mulligan", "American", ["era-1910s", "book-kephart", "camping", "old-school"], "beef", "soup", 90, "Kephart's hunter stew: whatever meat, potato, onion, a long pot.", [I("beef stew meat", 1.5, "lb", "Meat & Seafood"), I("potato", 4, "", "Produce"), I("onion", 2, "", "Produce"), I("carrot", 3, "", "Produce"), I("flour", 2, "tbsp", "Pantry"), I("salt", 1.5, "tsp", "Herbs & Spices")], ["Dredge the beef in flour. Brown it in a little fat in the pot, 8 minutes.", "Add the chopped onion. Cook 4 minutes. Cover with water.", "Simmer 45 minutes. Add cubed potato and carrot.", "Cook 25 minutes more, until the meat is tender and the pot is thick. Salt and pepper.", "Serve from the pot. Kephart says any game stands in for the beef."], kephart, { cal: 380, protein: 32, carbs: 28, fat: 14 }),
  h("vh-kp-trail-beans", "Trail beans", "American", ["era-1910s", "book-kephart", "camping", "budget"], "pork", "bowl", 180, "Dried beans, salt pork, a slow pot. Camp breakfast and supper.", [I("dried navy beans", 1, "lb", "Pantry"), I("salt pork", 4, "oz", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("molasses", 2, "tbsp", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices")], ["Soak the beans overnight, or boil 2 minutes and sit 1 hour. Drain.", "Put beans, diced salt pork, chopped onion, molasses, and mustard in a pot with water to cover by an inch.", "Simmer 2 hours, adding water if they dry, until the beans are soft and the liquor is thick.", "Salt the beans. Taste — the pork should have flavored the whole pot.", "Spoon the beans from a cup, with bannock on the side."], kephart, { cal: 360, protein: 18, carbs: 48, fat: 10 }),
  h("vh-kp-foil-potato", "Campfire potatoes", "American", ["era-1910s", "book-kephart", "camping", "vegetarian", "gluten-free"], "veg", "roast", 50, "Whole potatoes in the coals, or wrapped if you have foil. Salt, butter.", [I("russet potatoes", 4, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Scrub the potatoes. Prick them. Rub with a little fat and salt.", "Bury in hot coals, or wrap and set at the edge of the fire, 45 minutes, until they give when squeezed.", "Split open. Add butter, salt, and pepper.", "Eat from the skin. A spoon of bacon grease if butter is short.", "Cook until the center is soft — a hard center is a wasted potato."], kephart, { cal: 240, protein: 4, carbs: 40, fat: 8 }),
  h("vh-kp-kabobs", "Scout kabobs", "American", ["era-1910s", "book-kephart", "camping"], "beef", "skillet", 25, "Meat and onion on a green stick, roasted over coals.", [I("beef sirloin", 1.5, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices"), I("bacon", 4, "slices", "Meat & Seafood")], ["Cut the beef into 1½-inch cubes. Cut the onion into wedges. Cut the bacon in half.", "Thread beef, onion, and bacon onto sticks or skewers. Salt and pepper.", "Hold or set over coals, turning, 12–15 minutes, until the beef is browned and just pink inside.", "Do not cook in the flame or the fat will catch.", "Slide off the stick onto a plate, or eat from the stick."], kephart, { cal: 380, protein: 32, carbs: 6, fat: 24 }),
  h("vh-kp-camp-coffee-stew", "Camp coffee beef", "American", ["era-1910s", "book-kephart", "camping"], "beef", "bowl", 120, "Leftover coffee in a beef stew — Kephart's trick for a dark gravy in camp.", [I("beef chuck", 2, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("strong coffee", 1, "cup", "Other"), I("water", 2, "cups", "Other"), I("potato", 3, "", "Produce"), I("flour", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Brown the cubed beef in fat 8 minutes. Add the sliced onion. Cook 4 minutes.", "Sprinkle the flour. Stir. Pour in the 1 cup of coffee and the 2 cups of water.", "Cover the pot and simmer the beef 75 minutes.", "Add cubed potato. Cook 25 minutes more, until tender.", "Salt and pepper. The coffee darkens the gravy; it should not taste like a cup of coffee."], kephart, { cal: 400, protein: 36, carbs: 20, fat: 18 }),

  h("vh-la-chicken-dumplings", "Church chicken and dumplings", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "old-school", "community"], "chicken", "soup", 80, "Ladies' Aid supper: a stewed hen, dropped dumplings on top.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("milk", 0.75, "cup", "Dairy & Eggs"), I("carrot", 3, "", "Produce"), I("celery", 3, "stalks", "Produce")], ["Cover the chicken with water. Add carrot, celery, salt. Simmer 50 minutes. Lift the chicken, pull the meat, return it. Keep the broth at a simmer.", "Stir flour, baking powder, ½ teaspoon salt, and milk into a soft dumpling dough.", "Drop spoonfuls onto the simmering broth. Cover tightly 15 minutes. Do not lift the lid.", "Cook until the dumplings are done through and the broth has thickened.", "Pepper, parsley if you have it. Serve in bowls."], ladiesAid, { cal: 420, protein: 36, carbs: 34, fat: 14 }),
  h("vh-la-ham-loaf", "Ham loaf", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "old-school", "community"], "pork", "roast", 70, "Ground ham and pork, crumbs, a brown-sugar glaze. Church-supper slice.", [I("ground ham", 1, "lb", "Meat & Seafood"), I("ground pork", 0.5, "lb", "Meat & Seafood"), I("bread crumbs", 1, "cup", "Bakery"), I("egg", 1, "", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("brown sugar", 0.25, "cup", "Pantry")], ["Heat the oven to 350°F. Mix ham, pork, crumbs, egg, milk, pepper, and a pinch of mustard until it holds together.", "Pack the ham mixture firmly into a loaf pan.", "Stir the brown sugar with 2 tablespoons vinegar and 1 tablespoon mustard. Spread over the loaf.", "Bake 55 minutes, until the center is 160°F and the glaze is bubbling.", "Rest 10 minutes. Slice. Serve hot or cold."], ladiesAid, { cal: 360, protein: 28, carbs: 16, fat: 20 }),
  h("vh-la-three-bean", "Three-bean salad", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "salad", "vegetarian", "vegan", "community"], "veg", "green", 15, "Green beans, wax beans, kidney beans, a sharp vinegar dressing. The covered-dish salad.", [I("green beans", 1, "lb", "Produce"), I("wax beans", 1, "lb", "Produce"), I("kidney beans", 1, "can", "Pantry"), I("onion", 0.5, "", "Produce"), I("cider vinegar", 0.5, "cup", "Pantry"), I("sugar", 0.25, "cup", "Pantry")], ["Cook the green and wax beans in salted water 6 minutes, until just tender. Drain and cool.", "Drain and rinse the kidney beans. Slice the onion thin.", "Heat vinegar, sugar, ⅓ cup oil, salt, and pepper until the sugar dissolves. Cool.", "Toss the three beans and onion with the dressing.", "Chill the bean salad at least 1 hour. Serve it cold."], ladiesAid, { cal: 180, protein: 6, carbs: 24, fat: 8 }),
  h("vh-la-scalloped-potato", "Scalloped potatoes", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "vegetarian", "old-school", "community"], "veg", "roast", 75, "Sliced potatoes, milk, flour, butter, baked until the top browns.", [I("potatoes", 3, "lb", "Produce"), I("milk", 2.5, "cups", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("onion", 1, "", "Produce"), I("salt", 1.5, "tsp", "Herbs & Spices")], ["Heat the oven to 350°F. Peel and slice the potatoes thin. Slice the onion.", "Layer potato and onion in a buttered dish, dusting flour, dots of butter, salt, and pepper on each layer.", "Pour the milk over until it comes just below the top.", "Cover and bake 45 minutes. Uncover and bake 20 minutes more, until the top is gold and the potatoes are tender.", "Rest the potatoes 10 minutes. Serve them from the dish."], ladiesAid, { cal: 280, protein: 7, carbs: 40, fat: 10 }),
  h("vh-la-jellied-fruit", "Jellied fruit salad", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "dessert", "community", "vegetarian"], "veg", "dessert", 20, "Gelatin, canned fruit, a mold. The Ladies' Aid sweet salad.", [I("lemon gelatin", 2, "boxes", "Pantry"), I("canned mixed fruit", 2, "cups", "Pantry"), I("celery", 0.5, "cup", "Produce"), I("boiling water", 2, "cups", "Other"), I("lettuce", 1, "head", "Produce")], ["Dissolve the gelatin in the boiling water. Stir until no granules remain. Add 1 cup cold water.", "Drain the fruit well. Chop the celery fine.", "When the gelatin is syrupy and just starting to thicken, fold in the fruit and celery. Pour into a mold.", "Chill the mold at least 4 hours, until the gelatin is set.", "Unmold the fruit salad onto a bed of lettuce. Serve cold. This is not baked, and there is no flour in it."], ladiesAid, { cal: 140, protein: 2, carbs: 32, fat: 0 }),
  h("vh-la-baked-macaroni", "Ladies' Aid macaroni", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "vegetarian", "old-school", "community"], "veg", "pasta", 45, "Elbows, a cheese sauce, crumbs. The church basement bake.", [I("elbow macaroni", 1, "lb", "Pantry"), I("cheddar", 12, "oz", "Dairy & Eggs"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("flour", 4, "tbsp", "Pantry"), I("milk", 3, "cups", "Dairy & Eggs"), I("bread crumbs", 0.75, "cup", "Bakery")], ["Heat the oven to 350°F. Boil the macaroni in salted water until just tender, 8 minutes. Drain.", "Melt the butter, add the flour, cook 2 minutes. Whisk in the milk until thick, 5 minutes. Stir in most of the cheese.", "Mix with the macaroni. Turn into a buttered pan. Top with crumbs and remaining cheese.", "Bake 25 minutes, until bubbling and the top is brown.", "Rest the macaroni 5 minutes. Serve it from the pan."], ladiesAid, { cal: 520, protein: 22, carbs: 52, fat: 24 }),

  h("vh-hi-tomato-aspic", "Tomato aspic", "American", ["era-1900s", "book-hill-salads", "salad", "vegetarian"], "veg", "green", 20, "Hill's molded tomato: gelatin, strained tomato, a ring mold, celery in the middle.", [I("canned tomatoes", 2, "cups", "Pantry"), I("gelatin", 2, "tbsp", "Pantry"), I("onion", 0.25, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("lemon juice", 1, "tbsp", "Produce"), I("lettuce", 1, "head", "Produce")], ["Bloom the gelatin in ¼ cup cold tomato liquor 5 minutes.", "Simmer the remaining tomato with the onion 10 minutes. Strain. Stir the gelatin into the hot tomato until dissolved. Add lemon juice and salt.", "Pour into a ring mold. Chill the mold at least 4 hours, until the gelatin is set.", "Unmold the aspic onto lettuce. Fill the center with chopped celery if you like.", "Serve the aspic cold on lettuce. Do not bake this."], hill, { cal: 60, protein: 3, carbs: 10, fat: 0 }),
  h("vh-hi-chicken-salad", "Hill's chicken salad", "American", ["era-1900s", "book-hill-salads", "salad", "old-school"], "chicken", "green", 25, "Cold chicken, celery, mayonnaise. The 1909 chafing-dish-book salad.", [I("cooked chicken", 3, "cups", "Meat & Seafood"), I("celery", 1.5, "cups", "Produce"), I("mayonnaise", 0.75, "cup", "Pantry"), I("lemon juice", 1, "tbsp", "Produce"), I("lettuce", 1, "head", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Cut the chicken into small dice. Cut the celery the same size.", "Fold mayonnaise, lemon, salt, and pepper into the chicken and celery. Do not mash it.", "Chill the chicken salad 30 minutes so the dressing sets.", "Spoon the chicken salad onto lettuce leaves.", "Serve cold. Capers or a little onion if the table likes them."], hill, { cal: 320, protein: 28, carbs: 4, fat: 22 }),
  h("vh-hi-cucumber-sandwich", "Cucumber sandwiches", "American", ["era-1900s", "book-hill-salads", "sandwich", "vegetarian", "quick"], "veg", "toast", 15, "Thin bread, butter, paper-thin cucumber, a little salt. Hill's afternoon sandwich.", [I("white bread", 12, "slices", "Bakery"), I("cucumber", 1, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("white pepper", 0.25, "tsp", "Herbs & Spices")], ["Peel the cucumber. Slice it as thin as you can. Salt the slices 10 minutes, then pat dry.", "Spread butter on each slice of bread, all the way to the edges.", "Lay cucumber on half the slices. Dust with white pepper. Top with the remaining bread.", "Trim the crusts. Cut into triangles or fingers.", "Serve the same hour. They weep if they wait."], hill, { cal: 160, protein: 4, carbs: 20, fat: 7 }),
  h("vh-hi-stuffed-eggs", "Stuffed eggs", "American", ["era-1900s", "book-hill-salads", "vegetarian", "quick"], "eggs", "green", 20, "Hill's stuffed eggs: yolks mashed with butter, mustard, vinegar, piled back.", [I("eggs", 8, "", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("mustard", 1, "tsp", "Herbs & Spices"), I("vinegar", 1, "tsp", "Pantry"), I("paprika", 0.25, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Cover the eggs with cold water. Bring to a boil, then simmer 10 minutes. Cool in cold water. Peel.", "Halve the eggs the long way. Lift the yolks into a bowl.", "Mash the yolks with butter, mustard, vinegar, salt, and a pinch of cayenne until smooth.", "Pile or pipe the yolk mix back into the whites.", "Dust the stuffed eggs with paprika. Serve them cold."], hill, { cal: 120, protein: 8, carbs: 1, fat: 9 }),
  h("vh-hi-cheese-dreams", "Cheese dreams", "American", ["era-1900s", "book-hill-salads", "vegetarian", "quick"], "veg", "toast", 15, "Hill's chafing-dish cheese toast: bread, cheese, mustard, broiled until bubbling.", [I("white bread", 8, "slices", "Bakery"), I("cheddar", 8, "oz", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("mustard", 1, "tsp", "Herbs & Spices"), I("paprika", 0.25, "tsp", "Herbs & Spices")], ["Heat the broiler. Butter one side of each of the 8 slices of white bread.", "Mix the 8 ounces of grated cheddar with the 1 teaspoon of mustard and a pinch of paprika.", "Spread the cheddar on the unbuttered side. Set butter-side down on a sheet.", "Broil 3–4 minutes, until the cheese bubbles and browns at the edges.", "Cut the cheese dreams in half. Serve them at once."], hill, { cal: 280, protein: 12, carbs: 20, fat: 16 }),
  h("vh-hi-egg-salad-sandwich", "Egg salad sandwiches", "American", ["era-1900s", "book-hill-salads", "sandwich", "vegetarian"], "eggs", "toast", 20, "Chopped egg, mayonnaise, a little onion, between buttered bread.", [I("eggs", 6, "", "Dairy & Eggs"), I("mayonnaise", 0.33, "cup", "Pantry"), I("white bread", 8, "slices", "Bakery"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("onion", 1, "tbsp", "Produce"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Hard-cook the eggs 10 minutes. Cool, peel, and chop.", "Fold in mayonnaise, minced onion, salt, and pepper.", "Butter the bread. Spread the egg salad. Close the sandwiches.", "Trim crusts if it is a luncheon. Cut in half.", "Serve the egg sandwiches the same day they are made."], hill, { cal: 320, protein: 14, carbs: 24, fat: 18 }),

  h("vh-bj-miso-soup", "Miso soup", "Japanese", ["era-1910s", "book-chinese-japanese", "international", "japanese", "soup", "vegetarian"], "veg", "soup", 15, "Bosse and Watanna, 1914: miso stirred into dashi, tofu, a few greens.", [I("dashi or water", 4, "cups", "Other"), I("miso", 4, "tbsp", "Pantry"), I("tofu", 8, "oz", "Pantry"), I("scallions", 2, "", "Produce"), I("wakame or spinach", 1, "cup", "Produce")], ["Heat the dashi until steaming — do not boil hard if you are using bona fide dashi.", "Put the miso in a bowl. Stir in a ladle of hot liquid until smooth, then return it to the pot.", "Add cubed tofu and the greens. Heat 2 minutes. Do not boil after the miso goes in.", "Taste the soup before you add salt — miso is already salty.", "Ladle the miso soup and serve with sliced scallion on top."], bosse, { cal: 90, protein: 8, carbs: 6, fat: 4 }),
  h("vh-bj-chicken-rice", "Chicken and rice, Japanese style", "Japanese", ["era-1910s", "book-chinese-japanese", "international", "japanese"], "chicken", "bowl", 40, "The 1914 book's donburi-like plate: chicken simmered with soy and sugar, over rice.", [I("chicken thighs", 1.5, "lb", "Meat & Seafood"), I("rice", 1.5, "cups", "Pantry"), I("soy sauce", 3, "tbsp", "Pantry"), I("sugar", 1, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs")], ["Cook the rice in 3 cups water 18 minutes. Keep covered.", "Slice the chicken. Simmer it with soy, sugar, sliced onion, and ½ cup water 12 minutes, until cooked through.", "Beat the eggs. Pour them over the chicken. Cover 1 minute, until just set.", "Spoon rice into bowls. Ladle chicken, onion, and egg over.", "Serve the chicken and rice at once while it is hot."], bosse, { cal: 480, protein: 32, carbs: 52, fat: 14 }),
  h("vh-bj-fried-rice", "Chinese fried rice", "Chinese", ["era-1910s", "book-chan-chinese", "international", "chinese"], "pork", "skillet", 20, "Cold rice, a little pork, egg, soy. The 1914 home-kitchen fried rice.", [I("cold cooked rice", 4, "cups", "Pantry"), I("roast pork", 6, "oz", "Meat & Seafood"), I("eggs", 2, "", "Dairy & Eggs"), I("scallions", 3, "", "Produce"), I("soy sauce", 2, "tbsp", "Pantry"), I("oil", 2, "tbsp", "Pantry")], ["Use rice that is cold and dry. Dice the pork. Beat the eggs.", "Heat the oil in a wide pan until hot. Scramble the eggs 30 seconds, then push aside.", "Add the pork and rice. Stir-fry 4 minutes, breaking clumps, until the rice is hot.", "Add the soy sauce and scallion. Toss 1 minute.", "Serve at once. Do not add water or it will go gluey."], bosse, { cal: 380, protein: 16, carbs: 48, fat: 12 }),
  h("vh-bj-steamed-fish", "Ginger steamed fish", "Chinese", ["era-1910s", "book-chan-chinese", "international", "chinese", "pescatarian"], "fish", "fish", 20, "A white fish, ginger, soy, a plate over boiling water. The 1914 method.", [I("white fish fillets", 1.5, "lb", "Meat & Seafood"), I("ginger", 2, "tbsp", "Produce"), I("soy sauce", 2, "tbsp", "Pantry"), I("scallions", 3, "", "Produce"), I("sesame oil", 1, "tsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Pat the fish dry. Salt lightly. Lay on a heatproof plate. Scatter shredded ginger on top.", "Set the plate on a rack over boiling water. Cover and steam 8–10 minutes, until the fish flakes.", "Pour off any watery liquid. Add soy and sesame oil.", "Scatter the sliced scallion over the steamed fish.", "Serve the steamed fish at once with hot rice."], bosse, { cal: 240, protein: 34, carbs: 2, fat: 10 }),
  h("vh-bj-sukiyaki", "Sukiyaki", "Japanese", ["era-1910s", "book-chinese-japanese", "international", "japanese"], "beef", "skillet", 30, "The 1914 American sukiyaki: thinly sliced beef, onion, soy, sugar, in a pan at the table.", [I("beef sirloin", 1, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("soy sauce", 0.33, "cup", "Pantry"), I("sugar", 2, "tbsp", "Pantry"), I("beef broth", 1, "cup", "Pantry"), I("green onion", 4, "", "Produce")], ["Slice the beef as thin as you can, across the grain. Slice the onions.", "Heat a wide pan. Render a little of the beef fat, or use oil.", "Cook the onion 3 minutes. Add the beef and sear 2 minutes.", "Add soy, sugar, and broth. Simmer 8 minutes, until the beef is just cooked and the sauce is glossy.", "Add green onion at the end. Serve the sukiyaki with a bowl of rice."], bosse, { cal: 360, protein: 28, carbs: 14, fat: 20 }),
  h("vh-bj-cabbage-pork", "Cabbage with pork", "Chinese", ["era-1910s", "book-chan-chinese", "international", "chinese", "budget"], "pork", "skillet", 20, "Shredded cabbage, a little pork, soy. A 1914 weeknight from the Chinese-Japanese book.", [I("cabbage", 1, "head", "Produce"), I("pork loin", 8, "oz", "Meat & Seafood"), I("soy sauce", 2, "tbsp", "Pantry"), I("ginger", 1, "tsp", "Produce"), I("oil", 2, "tbsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Shred the cabbage fine. Slice the pork as thin as you can.", "Heat the oil in a wide pan until hot. Stir-fry the pork 3 minutes, until it loses its pink.", "Add ginger and cabbage. Stir-fry 5 minutes, until the cabbage wilts but still has a bite.", "Add the soy sauce. Toss the cabbage 1 minute.", "Serve the cabbage and pork with a bowl of rice."], bosse, { cal: 240, protein: 18, carbs: 10, fat: 14 }),

  h("vh-og-baked-stuffed-fish", "Baked stuffed fish", "American", ["era-1900s", "book-olive-green", "pescatarian"], "fish", "fish", 45, "Olive Green: a whole fish, crumb stuffing, baked.", [I("whole white fish", 3, "lb", "Meat & Seafood"), I("bread crumbs", 1.5, "cups", "Bakery"), I("onion", 0.5, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("parsley", 3, "tbsp", "Produce"), I("lemon", 1, "", "Produce")], ["Heat the oven to 400°F. Clean the fish. Salt the cavity.", "Cook the chopped onion in 2 tablespoons butter 4 minutes. Mix with crumbs, parsley, salt, and pepper.", "Stuff the fish. Sew or skewer the opening. Rub the skin with remaining butter.", "Bake 30 minutes, until the flesh by the bone is opaque. Baste once.", "Serve the baked fish on a platter with lemon wedges."], oliveGreen, { cal: 320, protein: 36, carbs: 14, fat: 14 }),
  h("vh-og-broiled-mackerel", "Broiled mackerel", "American", ["era-1900s", "book-olive-green", "pescatarian", "quick"], "fish", "fish", 20, "Olive Green's broiled mackerel: split, buttered, a hot broiler, lemon.", [I("mackerel", 2, "", "Meat & Seafood"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices"), I("parsley", 2, "tbsp", "Produce")], ["Heat the broiler. Split the mackerel. Pat dry. Salt and pepper.", "Melt the butter. Brush the fish on both sides.", "Broil skin-side down 5 minutes, then skin-side up 4–5 minutes, until the flesh flakes.", "Squeeze lemon over the mackerel. Scatter chopped parsley.", "Serve the mackerel at once. It waits badly once it is cooked."], oliveGreen, { cal: 340, protein: 30, carbs: 1, fat: 24 }),
  h("vh-og-fish-cakes", "Fish cakes", "American", ["era-1900s", "book-olive-green", "pescatarian", "budget"], "fish", "skillet", 30, "Leftover boiled fish, mashed potato, egg, fried cakes. Olive Green's economy plate.", [I("cooked white fish", 2, "cups", "Meat & Seafood"), I("mashed potato", 2, "cups", "Produce"), I("egg", 1, "", "Dairy & Eggs"), I("parsley", 2, "tbsp", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices")], ["Flake the fish, removing bones. Mix with the potato, egg, parsley, salt, and pepper.", "Shape into cakes ¾ inch thick. Chill 15 minutes if they feel soft.", "Fry in butter over medium heat 4 minutes a side, until a brown crust forms.", "Do not crowd the pan or the fish cakes will steam instead of brown.", "Serve the fish cakes hot, with lemon or a white sauce."], oliveGreen, { cal: 280, protein: 20, carbs: 18, fat: 14 }),
  h("vh-og-creamed-cod", "Creamed salt cod", "American", ["era-1900s", "book-olive-green", "pescatarian", "budget"], "fish", "toast", 40, "Soaked salt cod in cream sauce on toast. Olive Green's New England plate.", [I("salt cod", 1, "lb", "Meat & Seafood"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("milk", 2, "cups", "Dairy & Eggs"), I("toast", 8, "slices", "Bakery"), I("parsley", 2, "tbsp", "Produce")], ["Soak the salt cod in cold water 12 hours, changing the water twice. Drain. Simmer 10 minutes. Flake, removing bones.", "Melt the butter, add the flour, cook 2 minutes. Whisk in the milk until smooth and thick, 4 minutes.", "Fold in the fish. Pepper. Taste before salting — it may not need any.", "Heat the creamed cod through 2 minutes. Do not let it boil.", "Spoon the creamed cod over toast. Scatter chopped parsley."], oliveGreen, { cal: 340, protein: 28, carbs: 24, fat: 14 }),
  h("vh-og-salmon-loaf", "Salmon loaf", "American", ["era-1900s", "book-olive-green", "pescatarian", "old-school"], "fish", "roast", 50, "Canned salmon, crumbs, egg, baked. Olive Green's loaf for a Friday table.", [I("canned salmon", 1, "lb", "Meat & Seafood"), I("bread crumbs", 1, "cup", "Bakery"), I("eggs", 2, "", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("lemon juice", 1, "tbsp", "Produce"), I("onion", 2, "tbsp", "Produce")], ["Heat the oven to 350°F. Drain the salmon. Remove skin and large bones. Flake it.", "Mix with crumbs, beaten eggs, milk, lemon, minced onion, salt, and pepper.", "Pack the salmon mix into a greased loaf pan.", "Bake 35–40 minutes, until set in the center.", "Rest 5 minutes. Slice. Serve with a white sauce or peas."], oliveGreen, { cal: 280, protein: 24, carbs: 12, fat: 14 }),
  h("vh-og-boiled-salmon", "Boiled salmon", "American", ["era-1900s", "book-olive-green", "pescatarian", "gluten-free"], "fish", "fish", 30, "A piece of salmon in salted water with vinegar, drained, served with a sauce.", [I("salmon", 2, "lb", "Meat & Seafood"), I("vinegar", 2, "tbsp", "Pantry"), I("salt", 1, "tbsp", "Herbs & Spices"), I("parsley", 4, "sprigs", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce")], ["Choose a pot that holds the fish. Add water, salt, vinegar, and parsley. Bring to a simmer.", "Lower the salmon in. The water should cover it. Simmer — never boil hard — 12 minutes per inch of thickness.", "The fish is done when the flesh is opaque and flakes. Lift it out carefully.", "Melt the butter with the lemon juice for a sauce.", "Serve the salmon with the butter and boiled potatoes."], oliveGreen, { cal: 360, protein: 34, carbs: 1, fat: 24 }),

  h("vh-sf-nut-bread", "Suffrage nut bread", "American", ["era-1910s", "book-suffrage", "hometown", "community", "baking", "vegetarian", "old-school"], "veg", "bowl", 80, "Kleber 1915: white and graham flour, sugar, nuts, a loaf that stands 20 minutes before the oven.", [I("white flour", 2, "cups", "Pantry"), I("graham flour", 2, "cups", "Pantry"), I("sugar", 0.5, "cup", "Pantry"), I("chopped walnuts", 1, "cup", "Pantry"), I("milk", 2, "cups", "Dairy & Eggs"), I("baking powder", 4, "tsp", "Pantry")], ["Heat the oven to 350°F. Grease a loaf pan. Sift the white flour with the baking powder and 1 teaspoon salt. Stir in the graham flour, sugar, and nuts.", "Pour in the milk and mix just until the dry flour disappears. Do not beat.", "Turn into the pan. Let it stand 20 minutes on the table.", "Bake 50–60 minutes, until a toothpick in the center comes out clean and the top is brown.", "Cool 10 minutes, then turn out. Slice thick. Serve with butter."], kleber, { cal: 240, protein: 6, carbs: 36, fat: 8 }),
  h("vh-sf-hot-slaw", "Suffrage hot slaw", "American", ["era-1910s", "book-suffrage", "hometown", "community", "old-school"], "pork", "skillet", 25, "Kleber: cabbage wilted in bacon fat with onion, vinegar, and a little sugar.", [I("green cabbage", 1, "head", "Produce"), I("bacon fat", 2, "tbsp", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("cider vinegar", 3, "tbsp", "Pantry"), I("sugar", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Cut the cabbage not too fine. Chop the onion.", "Heat the bacon fat in a wide pan. Cook the onion 3 minutes.", "Add the cabbage, salt, sugar, and vinegar. Toss over medium heat 8 minutes, until the cabbage is wilted but still has a bite.", "Pepper. Taste — it should be sharp and a little sweet.", "Serve hot, the same hour. This is a hot slaw, not a cold salad."], kleber, { cal: 140, protein: 3, carbs: 10, fat: 10 }),
  h("vh-sf-hawaiian-sandwich", "Hawaiian sandwiches", "American", ["era-1910s", "book-suffrage", "hometown", "community", "sandwich", "vegetarian"], "veg", "toast", 15, "Kleber: chopped pimento, green pepper, and cream cheese on buttered bread.", [I("pimento", 1, "", "Pantry"), I("green pepper", 1, "", "Produce"), I("cream cheese", 8, "oz", "Dairy & Eggs"), I("white bread", 12, "slices", "Bakery"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Chop the pimento and the seeded green pepper fine. Mix with the cream cheese and salt until spreadable.", "Spread butter on the bread lightly, all the way to the edges.", "Spread the cheese mix on half the slices. Close with the remaining bread.", "Trim the crusts. Cut into triangles or fingers.", "Serve the same hour. They weep if they wait."], kleber, { cal: 280, protein: 8, carbs: 24, fat: 16 }),
  h("vh-sf-carrot-croquettes", "Carrot croquettes", "American", ["era-1910s", "book-suffrage", "hometown", "community", "vegetarian"], "veg", "skillet", 40, "Kleber: boiled carrots through a sieve, bound with egg and crumbs, fried.", [I("carrots", 4, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs"), I("bread crumbs", 1, "cup", "Bakery"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("nutmeg", 1, "pinch", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices")], ["Boil the carrots until very tender, 20 minutes. Drain and rub through a sieve.", "Beat in one egg, the butter, salt, nutmeg, and 4 tablespoons of the crumbs until the mix holds a shape. Chill 20 minutes.", "Shape into small croquettes. Beat the remaining egg. Roll each croquette in crumbs, then egg, then crumbs again.", "Fry in 365°F fat 3–4 minutes, until deep gold. Drain on paper.", "Serve hot. These are a vegetable side, not a meat croquette."], kleber, { cal: 180, protein: 5, carbs: 18, fat: 10 }),
  h("vh-sf-tomato-toast", "Tomato toast", "American", ["era-1910s", "book-suffrage", "hometown", "community", "vegetarian", "quick"], "veg", "toast", 20, "Kleber savory: fried bread rounds, a hot tomato mix spooned over.", [I("white bread", 8, "slices", "Bakery"), I("tomatoes", 4, "", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("onion", 0.5, "", "Produce"), I("sugar", 0.5, "tsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Chop the tomatoes and the onion. Cook them in 1 tablespoon of the butter 10 minutes, until thick. Salt, pepper, the sugar.", "Cut the bread into rounds. Fry in the remaining butter until gold on both sides.", "Spoon the hot tomato over each fried round.", "Serve at once as a savory, not as a soup.", "Set a poached egg on top if the table wants a supper of it."], kleber, { cal: 220, protein: 5, carbs: 28, fat: 10 }),
  h("vh-sf-escalloped-oysters", "Escalloped oysters", "American", ["era-1880s", "book-suffrage", "hometown", "community", "old-school"], "seafood", "roast", 40, "Burr's suffrage-book supper: oysters layered with crumbs and butter, baked until bubbling.", [I("oysters", 1, "quart", "Meat & Seafood"), I("cracker crumbs", 2, "cups", "Bakery"), I("butter", 6, "tbsp", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Heat the oven to 400°F. Drain the oysters, saving ¼ cup of the liquor. Pick over for shell.", "Butter a baking dish. Put in a layer of crumbs, then a layer of oysters, dots of butter, salt, and pepper. Repeat, ending with crumbs.", "Pour the oyster liquor and the milk around the edge — do not drown the top layer.", "Bake 25 minutes, until the top is brown and the liquor is bubbling.", "Serve hot from the dish. Do not overbake or the oysters go tough."], ladiesAid, { cal: 380, protein: 18, carbs: 28, fat: 20 }),
];
