import type { Recipe } from "./types";

const I = (
  name: string,
  qty: number,
  unit: string,
  aisle: Recipe["ingredients"][number]["aisle"],
) => ({ name, qty, unit, aisle });

function sweet(
  partial: Omit<Recipe, "nutrition" | "pack" | "servings" | "plate" | "protein"> & {
    nutrition?: Recipe["nutrition"];
    plate?: Recipe["plate"];
    servings?: number;
    protein?: Recipe["protein"];
    photo?: string;
  },
): Recipe {
  const { nutrition, plate, servings, protein, ...rest } = partial;
  return {
    pack: "free",
    servings: servings ?? 8,
    plate: plate ?? "dessert",
    protein: protein ?? "veg",
    nutrition: nutrition ?? { cal: 320, protein: 4, carbs: 48, fat: 12 },
    ...rest,
  };
}

export const DESSERT_RECIPES: Recipe[] = [
  sweet({
    id: "blueberry-grunt",
    name: "Blueberry grunt",
    description: "Stewed wild blueberries with dumplings steamed on top. South Shore dessert that is also breakfast.",
    minutes: 40,
    cuisine: "Nova Scotia",
    photo: "/food/blueberry.jpg",
    tags: ["dessert", "fruit", "atlantic", "nova-scotia", "vegetarian", "breakfast"],
    aliases: ["blueberry cobbler", "grunt", "blueberry slump", "bleuet"],
    ingredients: [
      I("wild blueberries", 4, "cups", "Produce"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
      I("flour", 1.5, "cups", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("milk", 0.66, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Simmer berries, sugar, a splash of water, and lemon until they slump.",
      "Rub butter into flour, baking powder, and a pinch of salt. Stir in milk to a soft dough.",
      "Drop dumplings on the berries. Cover tightly 15 minutes — do not peek.",
      "Serve with cream or ice cream.",
    ],
    nutrition: { cal: 280, protein: 5, carbs: 48, fat: 8 },
  }),
  sweet({
    id: "nanaimo-bars",
    name: "Nanaimo bars",
    description: "No-bake Canadian classic: coconut crumb, custard buttercream, chocolate cap.",
    minutes: 30,
    cuisine: "Homestyle",
    photo: "/food/nanaimo.jpg",
    tags: ["dessert", "baking", "canadian", "vegetarian"],
    aliases: ["nanaimo", "canadian bar"],
    ingredients: [
      I("graham crumbs", 2, "cups", "Pantry"),
      I("shredded coconut", 1, "cup", "Pantry"),
      I("cocoa", 5, "tbsp", "Pantry"),
      I("butter", 1, "cup", "Dairy & Eggs"),
      I("custard powder", 2, "tbsp", "Pantry"),
      I("icing sugar", 2, "cups", "Pantry"),
      I("dark chocolate", 4, "oz", "Pantry"),
    ],
    steps: [
      "Melt butter with cocoa and a beaten egg over low heat. Stir in crumbs and coconut. Press into a pan.",
      "Beat remaining butter with custard powder and icing sugar. Spread.",
      "Melt chocolate with a spoon of butter. Pour. Chill, then cut with a hot knife.",
    ],
    nutrition: { cal: 310, protein: 3, carbs: 34, fat: 18 },
  }),
  sweet({
    id: "butter-tarts",
    name: "Butter tarts",
    description: "Runny brown-sugar filling in flaky shells. Raisins optional, fight about it later.",
    minutes: 45,
    cuisine: "Homestyle",
    photo: "/food/tarts.jpg",
    tags: ["dessert", "baking", "canadian", "vegetarian"],
    aliases: ["butter tart", "tarte au sucre"],
    ingredients: [
      I("tart shells", 12, "", "Bakery"),
      I("brown sugar", 1, "cup", "Pantry"),
      I("butter", 0.33, "cup", "Dairy & Eggs"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("vanilla", 1, "tsp", "Herbs & Spices"),
      I("raisins", 0.5, "cup", "Pantry"),
    ],
    steps: [
      "Melt butter with brown sugar. Cool a minute, then beat in egg, vanilla, and a pinch of salt.",
      "Divide raisins into shells. Pour filling two-thirds full.",
      "Bake 375°F about 15 minutes until the tops blister and the centres still wobble.",
    ],
    nutrition: { cal: 290, protein: 3, carbs: 38, fat: 14 },
  }),
  sweet({
    id: "apple-crisp",
    name: "Apple crisp",
    description: "Tart apples under an oat lid. The weeknight pie.",
    minutes: 50,
    cuisine: "American",
    photo: "/food/crisp.jpg",
    tags: ["dessert", "fruit", "baking", "vegetarian"],
    aliases: ["apple crumble", "crisp"],
    ingredients: [
      I("apples", 6, "", "Produce"),
      I("rolled oats", 1, "cup", "Pantry"),
      I("flour", 0.5, "cup", "Pantry"),
      I("brown sugar", 0.5, "cup", "Pantry"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("cinnamon", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Toss sliced apples with cinnamon and a spoon of sugar in a buttered dish.",
      "Rub butter into oats, flour, and brown sugar. Scatter.",
      "Bake 375°F 35–40 minutes until the fruit bubbles at the edge.",
    ],
    nutrition: { cal: 260, protein: 3, carbs: 42, fat: 10 },
  }),
  sweet({
    id: "molten-chocolate",
    name: "Molten chocolate cakes",
    description: "Warm cakes with a liquid centre. Fifteen minutes, if the oven is hot.",
    minutes: 20,
    cuisine: "French",
    photo: "/food/lava.jpg",
    tags: ["dessert", "baking", "vegetarian"],
    aliases: ["lava cake", "moelleux", "fondant au chocolat"],
    ingredients: [
      I("dark chocolate", 6, "oz", "Pantry"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("egg yolks", 2, "", "Dairy & Eggs"),
      I("sugar", 0.25, "cup", "Pantry"),
      I("flour", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Melt chocolate and butter. Beat eggs, yolks, and sugar pale. Fold together with flour.",
      "Butter four ramekins. Fill. Bake 425°F 11–13 minutes until the edges set and the middle sighs.",
      "Rest one minute, invert, serve immediately.",
    ],
    protein: "eggs",
    nutrition: { cal: 410, protein: 7, carbs: 28, fat: 30 },
  }),
  sweet({
    id: "chip-cookies",
    name: "Sea salt chocolate chip cookies",
    description: "Brown-butter dough, puddles of chocolate, a flake of salt.",
    minutes: 35,
    cuisine: "American",
    photo: "/food/cookies.jpg",
    tags: ["dessert", "baking", "vegetarian"],
    aliases: ["choc chip", "cookies"],
    ingredients: [
      I("butter", 1, "cup", "Dairy & Eggs"),
      I("brown sugar", 1, "cup", "Pantry"),
      I("white sugar", 0.5, "cup", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("flour", 2.25, "cups", "Pantry"),
      I("chocolate chips", 2, "cups", "Pantry"),
      I("flaky salt", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Brown the butter. Cool. Beat with sugars, then eggs and vanilla.",
      "Fold in flour, a teaspoon of baking soda, salt, and chocolate.",
      "Scoop onto a sheet. Bake 375°F 10–12 minutes. Salt while hot.",
    ],
    protein: "eggs",
    nutrition: { cal: 220, protein: 3, carbs: 28, fat: 11 },
  }),
  sweet({
    id: "yogurt-berries",
    name: "Honey yogurt and berries",
    description: "Thick yogurt, ripe berries, pistachios. Dessert that still loves Fuel.",
    minutes: 8,
    cuisine: "Homestyle",
    photo: "/food/yogurt.jpg",
    tags: ["dessert", "healthy", "chilled", "vegetarian", "quick", "breakfast"],
    aliases: ["parfait", "yogurt bowl", "healthy dessert"],
    servings: 2,
    ingredients: [
      I("greek yogurt", 2, "cups", "Dairy & Eggs"),
      I("mixed berries", 2, "cups", "Produce"),
      I("honey", 2, "tbsp", "Pantry"),
      I("pistachios", 0.25, "cup", "Pantry"),
    ],
    steps: [
      "Spoon yogurt into cold bowls.",
      "Heap berries. Drizzle honey. Crush pistachios over top.",
    ],
    nutrition: { cal: 240, protein: 18, carbs: 28, fat: 7 },
  }),
  sweet({
    id: "chia-pudding",
    name: "Coconut chia pudding",
    description: "Make it before bed. Cocoa or mango in the morning.",
    minutes: 10,
    cuisine: "Homestyle",
    photo: "/food/chia.jpg",
    tags: ["dessert", "healthy", "chilled", "vegetarian", "quick", "breakfast"],
    aliases: ["chia", "overnight pudding"],
    servings: 4,
    ingredients: [
      I("chia seeds", 0.5, "cup", "Pantry"),
      I("coconut milk", 2, "cups", "Pantry"),
      I("maple syrup", 2, "tbsp", "Pantry"),
      I("vanilla", 1, "tsp", "Herbs & Spices"),
      I("mango or berries", 1, "cup", "Produce"),
    ],
    steps: [
      "Whisk chia, coconut milk, maple, and vanilla. Rest 10 minutes, whisk again so it does not clump.",
      "Chill at least 4 hours. Top with fruit.",
    ],
    nutrition: { cal: 210, protein: 5, carbs: 18, fat: 14 },
  }),
  sweet({
    id: "tiramisu",
    name: "Tiramisu",
    description: "Espresso-soaked biscuits, mascarpone, cocoa. No oven.",
    minutes: 35,
    cuisine: "Italian",
    photo: "/food/tiramisu.jpg",
    tags: ["dessert", "chilled", "world", "vegetarian"],
    aliases: ["tiramisù"],
    ingredients: [
      I("ladyfingers", 24, "", "Bakery"),
      I("espresso", 1.5, "cups", "Pantry"),
      I("mascarpone", 16, "oz", "Dairy & Eggs"),
      I("eggs", 3, "", "Dairy & Eggs"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("cocoa", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Beat yolks with sugar. Fold in mascarpone. Whip whites and fold.",
      "Dip biscuits in cooled espresso. Layer with cream. Repeat.",
      "Cocoa on top. Chill 4 hours.",
    ],
    protein: "eggs",
    nutrition: { cal: 380, protein: 8, carbs: 32, fat: 24 },
  }),
  sweet({
    id: "mango-sticky-rice",
    name: "Mango sticky rice",
    description: "Warm coconut rice, ripe mango, a pinch of salt that makes it sing.",
    minutes: 45,
    cuisine: "East Asian",
    photo: "/food/mango.jpg",
    tags: ["dessert", "world", "fruit", "vegetarian"],
    aliases: ["khao niao mamuang", "thai mango rice"],
    servings: 4,
    ingredients: [
      I("glutinous rice", 1.5, "cups", "Pantry"),
      I("coconut milk", 1.5, "cups", "Pantry"),
      I("sugar", 0.33, "cup", "Pantry"),
      I("ripe mangoes", 2, "", "Produce"),
      I("salt", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Soak rice 1 hour, then steam until tender.",
      "Warm coconut milk with sugar and salt. Pour two-thirds over the rice. Rest 20 minutes.",
      "Slice mango. Plate rice, fruit, and the remaining coconut cream.",
    ],
    nutrition: { cal: 340, protein: 5, carbs: 62, fat: 9 },
  }),
  sweet({
    id: "baklava",
    name: "Baklava",
    description: "Shatter pastry, walnuts, lemon-honey syrup.",
    minutes: 70,
    cuisine: "Middle Eastern",
    photo: "/food/baklava.jpg",
    tags: ["dessert", "baking", "world", "vegetarian"],
    aliases: ["baqlawa"],
    ingredients: [
      I("phyllo", 1, "pack", "Frozen"),
      I("walnuts", 3, "cups", "Pantry"),
      I("butter", 1, "cup", "Dairy & Eggs"),
      I("honey", 0.75, "cup", "Pantry"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("lemon", 0.5, "", "Produce"),
    ],
    steps: [
      "Chop nuts with cinnamon. Layer phyllo with melted butter, scattering nuts every few sheets.",
      "Cut diamonds. Bake 325°F until deep gold, about 45 minutes.",
      "Pour cold lemon-honey syrup over hot pastry. Rest before serving.",
    ],
    nutrition: { cal: 360, protein: 6, carbs: 38, fat: 22 },
  }),
  sweet({
    id: "churros",
    name: "Churros",
    description: "Ridged dough fried and rolled in cinnamon sugar. Thick chocolate to dip.",
    minutes: 40,
    cuisine: "Spanish",
    photo: "/food/churros.jpg",
    tags: ["dessert", "world", "vegetarian"],
    aliases: ["churro"],
    servings: 4,
    ingredients: [
      I("water", 1, "cup", "Other"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("flour", 1, "cup", "Pantry"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("cinnamon sugar", 0.5, "cup", "Pantry"),
      I("dark chocolate", 4, "oz", "Pantry"),
    ],
    steps: [
      "Boil water, butter, and a pinch of salt. Beat in flour off the heat, then the egg.",
      "Pipe into 375°F oil. Fry gold. Roll in cinnamon sugar.",
      "Melt chocolate with a splash of milk for dipping.",
    ],
    protein: "eggs",
    nutrition: { cal: 330, protein: 5, carbs: 38, fat: 18 },
  }),
  sweet({
    id: "flan",
    name: "Vanilla flan",
    description: "Burnt-sugar lid, silk custard. The fridge does the work.",
    minutes: 70,
    cuisine: "Mexican",
    photo: "/food/flan.jpg",
    tags: ["dessert", "chilled", "world", "vegetarian"],
    aliases: ["crème caramel", "caramel custard"],
    servings: 8,
    ingredients: [
      I("sugar", 1, "cup", "Pantry"),
      I("eggs", 5, "", "Dairy & Eggs"),
      I("evaporated milk", 1, "can", "Pantry"),
      I("sweetened condensed milk", 1, "can", "Pantry"),
      I("vanilla", 2, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Melt half the sugar to amber. Pour into a dish and swirl.",
      "Blend remaining ingredients. Pour over caramel. Bake in a water bath 325°F until just set, about 50 minutes.",
      "Chill overnight. Invert onto a plate.",
    ],
    protein: "eggs",
    nutrition: { cal: 290, protein: 8, carbs: 42, fat: 10 },
  }),
  sweet({
    id: "figgy-duff",
    name: "Figgy duff",
    description: "Newfoundland boiled pudding with raisins, steamed beside Jiggs.",
    minutes: 90,
    cuisine: "Newfoundland",
    photo: "/food/figgy.jpg",
    tags: ["dessert", "baking", "atlantic", "newfoundland", "vegetarian"],
    aliases: ["figgy", "duff", "boiled pudding"],
    ingredients: [
      I("flour", 2, "cups", "Pantry"),
      I("raisins", 1, "cup", "Pantry"),
      I("molasses", 0.5, "cup", "Pantry"),
      I("butter", 0.25, "cup", "Dairy & Eggs"),
      I("baking soda", 1, "tsp", "Pantry"),
      I("cinnamon", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Stir flour, raisins, spices, and soda. Melt butter with molasses and a cup of water. Mix to a thick batter.",
      "Spoon into a pudding cloth or greased bowl. Steam 1 hour.",
      "Turn out. Serve with molasses sauce or cream.",
    ],
    nutrition: { cal: 270, protein: 4, carbs: 52, fat: 6 },
  }),
];
