import { I, dish } from "./catalog-kit.ts";
import type { Recipe, RecipeSource } from "./types";

function src(book: string, author: string, year: number, era: string, archiveId: string, credit: string): RecipeSource {
  return { book, author, year, era, archiveId, credit };
}

const jewish = src("The International Jewish Cook Book", "Florence Kreisler Greenbaum", 1918, "1910s", "cu31924003580952", "Florence Kreisler Greenbaum, The International Jewish Cook Book (Bloch, 1918). Public domain.");
const desserts365 = src("365 Desserts", "Anonymous", 1900, "1900s", "365dessertsdesse00nels", "365 Desserts: A Dessert for Every Day in the Year (1900). Public domain.");

function h(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: Recipe["source"],
  nutrition: Recipe["nutrition"],
  /** Portions this makes. Left out, dish() stamps four, which is wrong for
   * a whole cake or a joint. */
  servings?: number,
  /** Other names the dish goes by, so renaming it to the book's title
   * does not hide it from search. */
  aliases?: string[],
): Recipe {
  return dish({
    id, name, cuisine, description, minutes, protein, plate,
    tags: Array.from(new Set(["vintage", ...tags])),
    ingredients, steps, nutrition, source,
      ...(servings ? { servings } : {}),
      ...(aliases && aliases.length ? { aliases } : {}),
  });
}

export const SWEET_ERA_RECIPES: Recipe[] = [
  h("vh-jw-matzo-ball", "Yom-tov soup with matzoth meal kleis", "Jewish", ["era-1910s", "book-jewish-1918", "soup", "old-school"], "chicken", "soup", 140, "Greenbaum's holiday soup: beef ribs and a whole chicken simmered two hours with saffron, and the kleis that go with it — one egg to every spoonful of meal, spiced with ginger, cinnamon and almond.", [I("beef ribs", 2, "lb", "Meat & Seafood"), I("chicken", 1, "bird", "Meat & Seafood"), I("carrot", 1, "", "Produce"), I("onion", 1, "", "Produce"), I("celery", 1, "head", "Produce"), I("parsley root", 1, "", "Produce"), I("saffron", 1, "pinch", "Herbs & Spices"), I("matzo meal", 4, "tbsp", "Pantry"), I("eggs", 4, "", "Dairy & Eggs"), I("chicken fat", 2, "tbsp", "Pantry"), I("ground ginger", 0.25, "tsp", "Herbs & Spices"), I("cinnamon", 0.25, "tsp", "Herbs & Spices"), I("ground almonds", 2, "tbsp", "Pantry"), I("salt", 2, "tsp", "Herbs & Spices")], ["Put the 2 pounds of beef ribs and the chicken in a large cooking-vessel with plenty of water. Add the 1 carrot and the 1 onion split, the 1 head of celery, the 1 parsley root, pepper and the 2 teaspoons of salt to taste, and the pinch of saffron.", "Let the whole simmer two hours, until the chicken reads 175°F at the thigh and the beef is tender. Skim the soup as it goes.", "Take the meat out. It can be used as a separate dish — the soup is what is wanted here.", "Now the kleis, one egg to each tablespoon of meal. Beat the 4 eggs separately with the ¼ teaspoon of ground ginger, the ¼ teaspoon of powdered cinnamon, the 2 tablespoons of ground almonds, pepper and salt.", "Stir in the 4 tablespoons of matzo meal and work it to a paste with the 2 tablespoons of chicken fat. Form the paste into small balls.", "Boil the balls twenty minutes in the soup, until they swell and are cooked through, and serve them in it."], jewish, { cal: 475, protein: 53, carbs: 8, fat: 25 }, 8, ["chicken soup with knaidlach", "matzo ball soup", "knaidlach", "kleis"]),
  h("vh-jw-gefilte", "Gefilte fish", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "fish", "fish", 90, "Greenbaum's sliced gefillte fisch: a haddock cut into four-inch steaks, each hollowed and refilled with its own chopped meat, boiled slowly and sauced with the broth beaten into egg yolks.", [I("haddock", 5, "lb", "Meat & Seafood"), I("onions", 5, "", "Produce"), I("parsley", 3, "tbsp", "Produce"), I("eggs", 2, "", "Dairy & Eggs"), I("egg yolks", 2, "", "Dairy & Eggs"), I("cinnamon", 0.25, "tsp", "Herbs & Spices"), I("sugar", 1, "tbsp", "Pantry"), I("cracker dust", 0.5, "cup", "Pantry"), I("carrot", 1, "", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Cut the 5 pounds of haddock into four-inch slices. Cut a big hole into each slice, keeping the backbone and the skin.", "Put the meat cut from the fish into a wooden tray, add 4 of the 5 large onions and a sprig of the 3 tablespoons of parsley, and chop until very fine.", "Add the 2 eggs, a dash of pepper, the ¼ teaspoon of cinnamon, a pinch of the 1 teaspoon of salt and the 1 tablespoon of sugar. Add enough of the ½ cup of cracker dust to stiffen it, and put this filling into the holes cut in the fish.", "Put the last onion sliced, another sprig of parsley, the 1 small carrot sliced, a dash of pepper and a pinch of salt into a saucepan. Put the fish in, cover with cold water, and let it boil slowly one hour, until the fish flakes and the filling is firm.", "Take the fish out onto a platter. Keep the water it boiled in for the sauce.", "Beat the 2 egg yolks thoroughly and pour the hot gravy slowly into them, stirring constantly. Stand it at the back of the stove to boil five minutes, stirring so that it does not burn, and pour it over the fish."], jewish, { cal: 310, protein: 40, carbs: 15, fat: 9 }, 8, ["Gefillte fisch with egg sauce", "gefillte fisch"]),
  h("vh-jw-latkes", "Potato latkes", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "veg", "skillet", 45, "Greenbaum's latke: potatoes soaked for hours before they are grated, two eggs to every pint, fried small on a greased spider and served with apple sauce.", [I("potatoes", 6, "", "Produce"), I("eggs", 4, "", "Dairy & Eggs"), I("flour", 2, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("beef dripping", 4, "tbsp", "Pantry"), I("apple sauce", 1, "cup", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Peel the 6 large potatoes and soak them several hours in cold water. The long soak is the book's step and it is what keeps the cakes pale and crisp.", "Grate the potatoes and drain them well. Six large ones come to about two pints.", "Allow two eggs to every pint: beat the 4 eggs well and mix them with the potato, the 2 tablespoons of flour, the 1 teaspoon of salt and a little pepper. Add the juice squeezed from the 1 grated onion if you want it.", "Heat the 4 tablespoons of beef dripping in a spider. Fried in drippings the edges come out much crisper than in butter, which burns so readily.", "Drop the mixture by spoonfuls onto the hot greased spider in small cakes. Turn them and brown on both sides.", "Serve hot with the 1 cup of apple sauce."], jewish, { cal: 335, protein: 9, carbs: 42, fat: 14 }, 6, ["Potato pancakes", "latkes"]),
  h("vh-jw-tzimmes", "Carrot tzimmes", "Jewish", ["era-1910s", "book-jewish-1918", "vegetarian", "gluten-free", "old-school"], "veg", "bowl", 50, "Carrots, prunes, honey, a long simmer. Greenbaum's sweet side.", [I("carrots", 2, "lb", "Produce"), I("prunes", 1, "cup", "Pantry"), I("honey", 3, "tbsp", "Pantry"), I("butter or oil", 2, "tbsp", "Dairy & Eggs"), I("cinnamon", 0.5, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Peel the 2 pounds of carrots and slice them thick.", "Put them in a pot with the 1 cup of prunes, the 3 tablespoons of honey, the 2 tablespoons of butter or oil, the ½ teaspoon of cinnamon, the ½ teaspoon of salt and water to almost cover.", "Bring to a simmer, cover, and cook 35 minutes, until the carrots are very tender.", "Uncover and cook 8 minutes more if the liquor is thin, until it turns syrupy and glazes the carrots.", "Taste — it should be frankly sweet, and the prunes should be soft enough to eat with a spoon.", "Serve warm beside a roast, or as a Sabbath side."], undefined, { cal: 315, protein: 3, carbs: 68, fat: 6 }),
  h("vh-jw-kugel", "Noodle kugel", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "eggs", "roast", 60, "Greenbaum's lokshen kugel is pareve and not sweet: noodles, rendered fat and four eggs, baked brown in an iron pot and served with jelly or stewed fruit.", [I("broad egg noodles", 3, "cups", "Pantry"), I("chicken or goose fat", 0.75, "cup", "Pantry"), I("eggs", 4, "", "Dairy & Eggs"), I("raspberry jelly", 0.5, "cup", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 350°F and grease an iron pot well.", "Cook the 3 cups of broad egg noodles in salted boiling water ten minutes, then drain them.", "Add the ¾ cup of chicken or goose fat and the 4 eggs, well beaten, and the 1 teaspoon of salt, and mix them through the noodles.", "Put the mixture in the greased pot and bake until the top of the kugel is well browned, about 40 minutes.", "Serve it hot with the ½ cup of raspberry jelly, or with stewed fruit of any kind."], jewish, { cal: 260, protein: 14, carbs: 39, fat: 5 }, 6),
  h("vh-jw-cabbage-rolls", "Holishkes", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "beef", "bowl", 85, "Greenbaum's cabbage rolls: the rice is boiled first, the rolls are tied with string and fried brown before they are boiled, and a brown gravy goes over. No sweet-sour tomato in it.", [I("green cabbage", 1, "head", "Produce"), I("ground beef", 1, "lb", "Meat & Seafood"), I("rice", 1, "cup", "Pantry"), I("beef dripping", 3, "tbsp", "Pantry"), I("flour", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Boil the head of cabbage whole for ten minutes, then let it cool.", "Boil the 1 cup of rice in salted water until tender and drain it.", "Mix the 1 pound of chopped beef with the rice and the 1 teaspoon of salt and pepper.", "Separate the cabbage leaves. Put about three tablespoons of the meat and rice in each leaf, roll it up and tie it together with string.", "Fry the rolls in the 3 tablespoons of dripping until brown.", "Boil them half an hour in a little water, until the beef inside reads 160°F.", "Make a brown gravy: stir the 2 tablespoons of flour into the fat left in the pan and let it brown, then pour in the water the rolls boiled in and simmer it smooth. Pour it over. Cut the strings before serving."], jewish, { cal: 405, protein: 24, carbs: 35, fat: 20 }, 6, ["Kal dolmar", "stuffed cabbage"]),
  h("vh-jw-chopped-liver", "Chopped liver", "Jewish", ["era-1910s", "book-jewish-1918", "old-school"], "chicken", "bowl", 30, "Chicken livers, onion, hard egg, schmaltz. Greenbaum's spread, chopped, not a pâté mill.", [I("chicken livers", 1, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("eggs", 3, "", "Dairy & Eggs"), I("schmaltz or oil", 3, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Hard-cook the 3 eggs 10 minutes, then cool and peel them.", "Cook the 2 sliced onions in the 3 tablespoons of schmaltz or oil 12 minutes, until deep gold, and lift them out.", "Cook the 1 pound of chicken livers in the same fat 8 minutes, until they are cooked right through to 165°F with no pink left at the centre. Campylobacter lives inside the liver, not only on its surface, and the rare middle traditional in liver dishes is what causes the outbreaks. Let them cool.", "Chop the livers, onion and eggs together on a board until fine but still textured. A food processor makes pâté; this is chopped liver.", "Season with the 1 teaspoon of salt and the ½ teaspoon of black pepper, and work in a spoonful of the pan fat if it is dry.", "Chill and serve with the 4 slices of bread, rye for preference."], undefined, { cal: 360, protein: 37, carbs: 24, fat: 12 }),
  h("vh-jw-blintzes", "Cheese blintzes", "Jewish", ["era-1910s", "book-jewish-1918", "dessert", "vegetarian", "old-school"], "eggs", "dessert", 45, "Greenbaum's blintz: a one-egg batter made with water, not milk, cooked on one side only, filled with pot cheese, lemon peel and cinnamon, then fried in plenty of butter. The dough makes six.", [I("egg", 1, "", "Dairy & Eggs"), I("flour", 1, "cup", "Pantry"), I("pot cheese", 0.5, "lb", "Dairy & Eggs"), I("butter", 6, "tbsp", "Dairy & Eggs"), I("eggs", 1, "", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry"), I("lemon", 1, "", "Produce"), I("cinnamon", 0.5, "tsp", "Herbs & Spices"), I("powdered sugar", 2, "tbsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["With a fork beat up the 1 egg with the ½ teaspoon of salt, add 1 cup of water and the 1 cup of sifted flour, and beat until smooth.", "Grease a frying-pan very slightly with a little of the 6 tablespoons of butter. Pour in two tablespoons of the batter, tilting the pan so it runs all over.", "Fry over a low heat on one side only, then turn the semi-cooked cake out on a clean cloth with the uncooked side uppermost. Let the cakes cool. The dough makes six; double or triple it if more are wanted.", "Make the filling as for cheese kreplich: the ½ pound of pot cheese, a piece of butter the size of an egg, the 1 egg, a pinch of salt, the ½ teaspoon of cinnamon, the 2 tablespoons of sugar to taste and the grated peel of the 1 lemon.", "Spread the mixture on the cooled dough, fold it over and tuck the edges in well.", "Sprinkle with the 2 tablespoons of powdered sugar and a little more cinnamon, and fry in plenty of the remaining butter until gold on both sides. These blintzes are served hot."], jewish, { cal: 365, protein: 12, carbs: 25, fat: 24 }, 6),

  h("vh-veg-nut-roast", "Nut roast", "American", ["era-1900s", "vegetarian", "old-school"], "veg", "roast", 60, "Walnuts, crumbs, onion, egg, baked. The early vegetarian Sunday roast.", [I("walnuts", 2, "cups", "Pantry"), I("bread crumbs", 1.5, "cups", "Bakery"), I("onion", 1, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs"), I("milk", 0.75, "cup", "Dairy & Eggs"), I("sage", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 350°F. Chop the walnuts and onion fine.", "Mix walnuts, crumbs, onion, sage, salt, and pepper.", "Beat the eggs with the milk. Stir into the dry mix until it holds a loaf.", "Pack into a greased pan. Bake 45 minutes, until the top is brown and a knife comes out clean.", "Rest 10 minutes. Slice. Serve with brown gravy or tomato sauce."], undefined, { cal: 620, protein: 15, carbs: 43, fat: 46 }),
  h("vh-veg-lentil-stew", "Lentil stew", "American", ["era-1900s", "book-golden-age", "vegetarian", "vegan", "plant-based", "budget", "soup"], "veg", "soup", 50, "Brown lentils, carrot, onion, a bay leaf. A meatless pot from the early vegetarian books.", [I("brown lentils", 1.5, "cups", "Pantry"), I("carrot", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("tomato paste", 1, "tbsp", "Pantry"), I("bay leaf", 1, "", "Herbs & Spices")], ["Rinse the lentils. Put them in a pot with 6 cups water, chopped onion, carrot, celery, tomato paste, and the bay leaf.", "Bring to a boil. Simmer 40 minutes, until the lentils are tender and the pot is thick.", "Discard the bay leaf. Salt and pepper the lentil stew.", "Mash a few lentils against the side if you want it thicker.", "Serve the lentil stew with bread. No meat is used."], undefined, { cal: 200, protein: 10, carbs: 38, fat: 1 }),
  h("vh-veg-macaroni-tomato", "Macaroni with tomato", "American", ["era-1900s", "book-no-animal", "vegetarian", "vegan", "plant-based", "budget"], "veg", "pasta", 25, "Pasta, a tomato sauce without meat or cheese if you skip it. Early vegetarian Friday.", [I("macaroni", 1, "lb", "Pantry"), I("tomatoes", 6, "", "Produce"), I("onion", 1, "", "Produce"), I("olive oil", 3, "tbsp", "Pantry"), I("basil or parsley", 3, "tbsp", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Boil the 1 pound of macaroni in salted water until just tender, 9 minutes, and drain it.", "Cook the chopped onion in the 3 tablespoons of olive oil 6 minutes, until soft.", "Add the 6 tomatoes, chopped, and simmer 12 minutes, until the sauce comes together.", "Season with the 1 teaspoon of salt and pepper, then stir in the 3 tablespoons of basil or parsley off the heat so it stays green.", "Toss the sauce through the drained macaroni.", "Serve hot, with cheese at the table if your house allows it."], undefined, { cal: 570, protein: 17, carbs: 98, fat: 12 }),
  h("vh-veg-beans-no-pork", "Baked beans without pork", "American", ["era-1900s", "vegetarian", "vegan", "plant-based", "old-school"], "veg", "bowl", 240, "Pea beans, molasses, mustard, no pork. The vegetarian Boston pot.", [I("pea beans", 1, "lb", "Pantry"), I("molasses", 0.33, "cup", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("onion", 1, "", "Produce"), I("brown sugar", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Soak the 1 pound of pea beans overnight. Drain, then parboil 10 minutes, until the skins blow when you blow on a bean. Drain again.", "Heat the oven to 300°F. Put the beans in a pot with the onion, the ⅓ cup of molasses, the 1 teaspoon of mustard, the 2 tablespoons of brown sugar, the 1 teaspoon of salt and boiling water to cover.", "Cover and bake 4 hours, adding boiling water whenever the top threatens to dry, until the beans are tender and the liquor is thick and dark.", "Uncover for the last 30 minutes if you want a browned top.", "There is no pork in this pot; the molasses and mustard carry it.", "Serve hot. They keep well and are better the next day."], undefined, { cal: 175, protein: 3, carbs: 41, fat: 1 }),
  h("vh-veg-spinach-eggs", "Spinach with eggs", "American", ["era-1900s", "book-golden-age", "vegetarian", "gluten-free"], "eggs", "skillet", 20, "Wilted spinach, butter, eggs poached or fried on top. A meatless supper.", [I("spinach", 2, "lb", "Produce"), I("eggs", 4, "", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("nutmeg", 1, "pinch", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.25, "tsp", "Herbs & Spices")], ["Wash the 2 pounds of spinach well and put it in a pot with only the water clinging to the leaves. Cover and cook 5 minutes, until wilted. Drain, press it dry, and chop it.", "Melt the 2 tablespoons of butter and warm the spinach through 2 minutes with the pinch of nutmeg, the 1 teaspoon of salt and the ¼ teaspoon of black pepper.", "Make four hollows in the spinach with the back of a spoon.", "Crack an egg from the 4 eggs into each hollow.", "Cover the pan and cook 4 minutes, until the whites are set and the yolks still soft.", "Serve at once, while the yolks still run into the greens."], undefined, { cal: 180, protein: 13, carbs: 10, fat: 11 }),
  h("vh-veg-hash", "Vegetable hash", "American", ["era-1900s", "book-no-animal", "vegetarian", "budget", "old-school"], "veg", "skillet", 25, "Yesterday's boiled vegetables, chopped, browned in a pan until a crust forms.", [I("cooked potatoes", 3, "cups", "Produce"), I("cooked carrots", 1, "cup", "Produce"), I("onion", 1, "", "Produce"), I("cabbage or leftover greens", 1, "cup", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("parsley", 2, "tbsp", "Produce")], ["Chop the potatoes, carrots, and cabbage. Chop the onion.", "Melt the butter in a skillet. Cook the onion 4 minutes.", "Add the vegetables. Press into an even layer. Cook without stirring 10 minutes, until a brown crust forms.", "Fold or turn out crust-side up. Salt and pepper.", "Scatter parsley. Serve with a fried egg if you eat eggs."], undefined, { cal: 215, protein: 5, carbs: 27, fat: 10 }),

  h("vh-ds-blancmange", "Blancmange", "American", ["era-1900s", "book-365-desserts", "dessert", "vegetarian", "gluten-free", "old-school"], "veg", "dessert", 90, "The book's blanc mange is set with carrageen, not cornstarch: half an ounce of Irish moss soaked in a quart of milk and cooked down until it almost dissolves, then strained into a mould.", [I("Irish moss", 0.5, "oz", "Pantry"), I("milk", 4, "cups", "Dairy & Eggs"), I("sugar", 0.5, "cup", "Pantry"), I("sherry", 2, "tbsp", "Pantry")], ["Wash the ½ ounce of Irish moss through several cold waters, picking out any grit.", "Soak it one hour in the 4 cups of milk.", "Turn it into a farina boiler — a double boiler — and cook slowly until the moss is almost dissolved, about 30 minutes. The milk will thicken and pull a thread off the spoon.", "Add the ½ cup of sugar and the flavouring. If you use wine, sherry is the better flavouring, and the 2 tablespoons is enough.", "Strain it, turn it into a mould, and stand it in a very cold place to stiffen, at least 4 hours. Turn it out to serve. Nothing here is baked and there is no starch in it."], desserts365, { cal: 170, protein: 5, carbs: 25, fat: 5 }, 6, ["Irish moss blanc mange", "carrageen pudding"]),
  h("vh-ds-cottage-pudding", "Cottage pudding", "American", ["era-1900s", "book-365-desserts", "dessert", "baking", "vegetarian", "old-school"], "veg", "dessert", 40, "A plain one-egg cake, the yolk beaten light with the sugar and the white folded in last. No butter in it, and the book pours no sauce over.", [I("egg", 1, "", "Dairy & Eggs"), I("granulated sugar", 1, "cup", "Pantry"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("flour", 1.5, "cups", "Pantry"), I("baking powder", 1, "tsp", "Pantry"), I("butter", 1, "tbsp", "Dairy & Eggs")], ["Heat the oven to 325°F — a slow oven — and grease a baking dish with the 1 tablespoon of butter.", "Beat the yolk of the 1 egg light and add the 1 cup of granulated sugar to it gradually, beating all the while.", "Beat in the ½ cup of milk and the 1½ cups of flour until the batter is light and smooth.", "Beat the white of the egg to a stiff, dry froth and stir it gently into the batter with the 1 teaspoon of baking powder.", "Put it in the greased dish and bake 25 minutes, until a straw comes out clean. Serve it warm."], desserts365, { cal: 285, protein: 5, carbs: 58, fat: 4 }, 6),
  h("vh-ds-apple-tapioca", "Apple tapioca", "American", ["era-1900s", "book-365-desserts", "dessert", "baking", "vegetarian", "gluten-free", "old-school"], "veg", "dessert", 80, "Whole pared and cored apples in the dish, a soaked tapioca custard poured over, baked. Eaten with cream and sugar.", [I("pearl tapioca", 1, "cup", "Pantry"), I("eggs", 3, "", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry"), I("milk", 4, "cups", "Dairy & Eggs"), I("apples", 6, "", "Produce"), I("cream", 0.5, "cup", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices")], ["Soak the 1 cup of pearl tapioca in enough boiling water to cover it, until it is quite soft — about 45 minutes.", "Stir the 3 beaten eggs into the softened tapioca with the 2 tablespoons of sugar, the 4 cups of milk and the ¼ teaspoon of salt.", "Heat the oven to 350°F. Fill a pudding dish with the 6 apples, pared and cored.", "Stir the mixture well and pour it over the apples.", "Bake until the apples are tender and the pudding is set, about 55 minutes.", "Eat it with the ½ cup of cream and a little more sugar."], desserts365, { cal: 280, protein: 9, carbs: 43, fat: 9 }, 8, ["Apple tapioca pudding"]),
  h("vh-ds-snow-pudding", "Snow pudding", "American", ["era-1900s", "book-365-desserts", "dessert", "vegetarian"], "eggs", "dessert", 25, "Lemon gelatin beaten with egg white until it looks like snow. Custard with it.", [I("gelatin", 1, "tbsp", "Pantry"), I("lemon juice", 0.5, "cup", "Produce"), I("sugar", 0.75, "cup", "Pantry"), I("egg whites", 3, "", "Dairy & Eggs"), I("water", 1.25, "cups", "Other")], ["Bloom the gelatin in ¼ cup cold water 5 minutes. Dissolve it in 1 cup boiling water. Add sugar and lemon juice. Cool until syrupy.", "Beat the whites stiff. Beat the gelatin into the whites until the mix is white and holds a trail.", "Pour into a dish. Chill at least 3 hours, until set.", "Serve in spoonfuls. A boiled custard beside it if you use the yolks.", "Chill and serve. Do not bake this pudding, and do not add flour."], undefined, { cal: 175, protein: 5, carbs: 40, fat: 0 }),
  h("vh-ds-prune-whip", "Prune pudding", "American", ["era-1900s", "book-365-desserts", "dessert", "vegetarian", "gluten-free", "old-school"], "veg", "dessert", 90, "Prunes soaked overnight and cooked to a pulp, pressed through a colander, lightened with beaten whites and set with gelatine. Soft custard beside it.", [I("prunes", 1, "lb", "Pantry"), I("sugar", 1, "cup", "Pantry"), I("pasteurised egg whites", 3, "", "Dairy & Eggs"), I("gelatine", 1, "tbsp", "Pantry"), I("boiled custard", 1, "cup", "Dairy & Eggs")], ["Soak the 1 pound of prunes overnight.", "In the morning take out the stones and put the prunes in a heavy pan with just enough water to keep them from burning. Cover and cook slowly on the back of the stove until they are perfectly tender — about an hour.", "Add the 1 cup of sugar and stand the pan aside to cool. When it is cold, press the prunes through a colander to a smooth pulp.", "Soak the 1 tablespoon of gelatine half an hour in ½ cup of cold water, then stand it over the fire until it is dissolved.", "Beat the 3 pasteurised egg whites to a stiff froth and add them to the prunes, then stir the dissolved gelatine through. The whites are never cooked in this pudding, so use pasteurised whites — the book was written before anyone knew why that matters.", "Turn it into a mould and stand it away to harden, at least 4 hours. Turn it into a dish and serve with the 1 cup of soft boiled custard."], desserts365, { cal: 310, protein: 5, carbs: 73, fat: 2 }, 8, ["prune whip"]),
  h("vh-ds-rice-pudding", "Baked rice pudding", "American", ["era-1900s", "book-365-desserts", "dessert", "baking", "vegetarian", "gluten-free", "old-school"], "veg", "dessert", 100, "Two spoonfuls of rice to a quart of new milk, baked very slowly and stirred every two minutes until the last half hour. No butter and no vanilla.", [I("rice", 2, "tbsp", "Pantry"), I("sugar", 2, "tbsp", "Pantry"), I("milk", 4, "cups", "Dairy & Eggs"), I("nutmeg", 0.25, "tsp", "Herbs & Spices"), I("raisins", 0.25, "cup", "Pantry")], ["Heat the oven low, about 300°F. If the oven is too hot the pudding will come out too thick.", "Put the 2 tablespoons of rice and the 2 tablespoons of sugar into the 4 cups of new milk in a baking pan and stir until the sugar dissolves.", "Add a grating of the nutmeg, and the ¼ cup of raisins if you like them.", "Place the pan in the oven and cook very slowly about 1½ hours, stirring the pudding every two minutes until the last half hour.", "Leave it alone for that last half hour so the skin forms. Serve it warm, or cold the next day."], desserts365, { cal: 220, protein: 9, carbs: 30, fat: 8 }),
  h("vh-ds-boiled-custard", "Boiled custard", "American", ["era-1900s", "book-365-desserts", "dessert", "vegetarian", "gluten-free"], "eggs", "dessert", 20, "Milk, yolks, sugar, cooked until it coats a spoon. The 1900 sauce and the 1900 dessert.", [I("milk", 3, "cups", "Dairy & Eggs"), I("egg yolks", 4, "", "Dairy & Eggs"), I("sugar", 0.5, "cup", "Pantry"), I("vanilla", 1, "tsp", "Pantry"), I("salt", 1, "pinch", "Herbs & Spices")], ["Scald the milk. Beat the yolks with the sugar and salt.", "Stir a little hot milk into the yolks, then return all to the pan.", "Cook over low heat, stirring, until the custard coats a spoon, 5–7 minutes. Do not boil or it will curdle.", "Take off the heat. Add vanilla. Strain into a pitcher.", "Chill. Serve in cups, or pour over cake or fruit. This is stirred, not baked, and there is no flour."], undefined, { cal: 265, protein: 9, carbs: 35, fat: 11 }),
  h("vh-ds-charlotte", "Charlotte russe", "American", ["era-1900s", "book-365-desserts", "dessert", "vegetarian", "old-school"], "veg", "dessert", 40, "A cooked custard base set with gelatine, whipped cream folded through, hardened in a wet mould — and turned out under stale macaroons, not lined with ladyfingers.", [I("gelatine", 1, "tbsp", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("granulated sugar", 1, "cup", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("vanilla", 1, "tsp", "Pantry"), I("heavy cream", 2, "cups", "Dairy & Eggs"), I("stale macaroons", 12, "", "Bakery")], ["Cover the 1 tablespoon of gelatine with ¼ cup of cold water and let it stand half an hour, then dissolve it over hot water.", "Scald the 1 cup of milk, add the 1 cup of granulated sugar, and stir until it is dissolved and the milk looks blue.", "Beat the 1 egg very light and add it to the milk, stirring all the while. Cook it a minute over low heat, stirring, until it thickens enough to coat the spoon and reads 170°F — do not let it boil.", "Take it from the fire, add it to the dissolved gelatine and stir again. Flavour with the 1 teaspoon of vanilla and put it away to cool.", "Whip the 2 cups of cream and add it to the cooled custard. Turn it into a mould previously wet with cold water and stand it away to harden, at least 3 hours.", "When you are ready to use it, turn it out and cover it with the 12 stale macaroons."], desserts365, { cal: 405, protein: 5, carbs: 41, fat: 25 }, 8),

  h("vh-20-club-sandwich", "Club sandwich", "American", ["era-1920s", "sandwich", "old-school"], "chicken", "toast", 20, "Three slices of toast, chicken, bacon, lettuce, tomato, mayonnaise. The 1920s luncheon stack.", [I("white bread", 12, "slices", "Bakery"), I("cooked chicken", 12, "oz", "Meat & Seafood"), I("bacon", 8, "slices", "Meat & Seafood"), I("tomato", 2, "", "Produce"), I("lettuce", 8, "leaves", "Produce"), I("mayonnaise", 0.5, "cup", "Pantry")], ["Toast the bread. Cook the bacon until crisp. Slice the tomato and the chicken.", "Spread mayonnaise on every slice of toast, out to the edges.", "Stack: toast, chicken, lettuce; toast, bacon, tomato; toast on top. Repeat for four sandwiches.", "Pin with toothpicks. Cut in half on the diagonal.", "Serve the club sandwiches at once so the toast stays crisp."], undefined, { cal: 785, protein: 45, carbs: 45, fat: 46 }),
  h("vh-20-deviled-eggs", "Deviled eggs", "American", ["era-1920s", "vegetarian", "quick", "old-school"], "eggs", "green", 20, "The 1920s cocktail egg: yolks mashed with mayonnaise and mustard.", [I("eggs", 8, "", "Dairy & Eggs"), I("mayonnaise", 3, "tbsp", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("vinegar", 1, "tsp", "Pantry"), I("paprika", 0.25, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Cover the eggs with cold water. Bring to a boil, then simmer 10 minutes. Cool in cold water. Peel.", "Halve. Mash the yolks with mayonnaise, mustard, vinegar, and salt until smooth.", "Spoon or pipe the yolk mix back into the egg whites.", "Dust the stuffed eggs with paprika before they go to the table.", "Chill the eggs until serving. These are not baked."], undefined, { cal: 215, protein: 13, carbs: 1, fat: 17 }),
  h("vh-20-cheese-straws", "Cheese straws", "American", ["era-1920s", "baking", "vegetarian", "old-school"], "veg", "bowl", 35, "A 1920s luncheon nibble: cheese pastry, cut in strips, baked crisp.", [I("flour", 1, "cup", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("sharp cheddar", 1, "cup", "Dairy & Eggs"), I("egg yolk", 1, "", "Dairy & Eggs"), I("cayenne", 1, "pinch", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Heat the oven to 375°F. Rub the butter into the flour. Stir in grated cheese, salt, and cayenne.", "Bind with the yolk and a spoon of ice water if needed. Roll ¼ inch thick.", "Cut into 4-inch straws. Twist each if you like.", "Bake 12–14 minutes, until the edges are gold.", "Cool on the sheet. They crisp as they cool."], undefined, { cal: 345, protein: 11, carbs: 24, fat: 22 }),
  h("vh-20-tomato-cocktail", "Tomato juice cocktail", "American", ["era-1920s", "drink", "vegetarian", "vegan", "plant-based", "quick"], "veg", "bowl", 10, "Chilled tomato juice, lemon, Worcestershire, celery salt. The 1920s first course.", [I("tomato juice", 4, "cups", "Pantry"), I("lemon juice", 2, "tbsp", "Produce"), I("Worcestershire", 1, "tsp", "Pantry"), I("celery salt", 0.5, "tsp", "Herbs & Spices"), I("black pepper", 0.25, "tsp", "Herbs & Spices")], ["Chill the tomato juice well, at least 1 hour in the icebox.", "Stir in lemon, Worcestershire, celery salt, and pepper.", "Taste the cocktail. Add a drop more lemon if it is flat.", "Pour the tomato cocktail into small glasses.", "Serve ice-cold before lunch. This is a drink, not a soup."], undefined, { cal: 60, protein: 3, carbs: 13, fat: 1 }),
  h("vh-20-salmon-wiggle", "Salmon wiggle", "American", ["era-1920s", "old-school", "pescatarian", "quick"], "fish", "toast", 20, "The 1920s chafing-dish: canned salmon and peas in white sauce on toast.", [I("canned salmon", 1, "lb", "Meat & Seafood"), I("frozen or canned peas", 1, "cup", "Frozen"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("milk", 2, "cups", "Dairy & Eggs"), I("toast", 8, "slices", "Bakery")], ["Drain and flake the salmon, removing skin and bones.", "Melt the butter, add the flour, cook 2 minutes. Whisk in the milk until smooth and thick, 4 minutes.", "Fold in the salmon and the peas. Heat 3 minutes. Salt and pepper.", "Do not boil hard or the sauce will break.", "Spoon the salmon wiggle over toast. Serve at once."], undefined, { cal: 585, protein: 36, carbs: 43, fat: 29 }),
  h("vh-20-pineapple-gelatin", "Pineapple gelatin salad", "American", ["era-1920s", "dessert", "vegetarian"], "veg", "dessert", 15, "Lemon gelatin, canned pineapple, a mold. The 1920s luncheon sweet salad.", [I("lemon gelatin", 1, "box", "Pantry"), I("canned pineapple", 1, "cup", "Pantry"), I("boiling water", 1, "cup", "Other"), I("celery", 0.5, "cup", "Produce"), I("lettuce", 1, "head", "Produce")], ["Dissolve the gelatin in boiling water. Add 1 cup of the pineapple juice and cold water mixed.", "When it is syrupy, fold in drained pineapple and chopped celery.", "Pour into a mold. Chill the mold at least 4 hours, until the gelatin is set.", "Unmold the pineapple gelatin onto a bed of lettuce.", "Serve cold. Do not bake, and do not add flour."], undefined, { cal: 110, protein: 3, carbs: 26, fat: 0 }),
];
