import { I, dish } from "./catalog-kit";
import type { Protein, Recipe } from "./types";

function place(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Protein,
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  aliases: string[] = [],
  nutrition?: Recipe["nutrition"],
): Recipe {
  return dish({
    id,
    name,
    description,
    minutes,
    protein,
    plate,
    cuisine,
    tags,
    aliases,
    ingredients,
    steps,
    nutrition,
  });
}

export const ATLANTIC_RECIPES: Recipe[] = [
  place(
    "rappie-pie",
    "Rappie pie",
    "Nova Scotia",
    ["atlantic", "nova-scotia", "acadian"],
    "chicken",
    "roast",
    150,
    "Acadian chicken and grated potato casserole from Clare and beyond. Sunday food.",
    [
      I("chicken", 1, "bird", "Meat & Seafood"),
      I("russet potatoes", 8, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("chicken broth", 4, "cups", "Pantry"),
    ],
    [
      "Simmer the chicken with onion. Save the broth. Pull the meat.",
      "Grate potatoes and squeeze until they are almost dry.",
      "Loosen the potato with hot broth, layer with chicken and butter, bake until the top is a crust.",
    ],
    ["rapure", "râpure", "acadian potato pie"],
    { cal: 520, protein: 32, carbs: 48, fat: 22 },
  ),
  place(
    "ns-lobster-roll",
    "Nova Scotia lobster roll",
    "Nova Scotia",
    ["atlantic", "nova-scotia", "seafood"],
    "seafood",
    "toast",
    20,
    "Warm butter or a little mayo, celery if you must, a toasted split-top bun. Do not bury the lobster.",
    [
      I("cooked lobster meat", 1, "lb", "Meat & Seafood"),
      I("split-top buns", 4, "", "Bakery"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("lemon", 1, "", "Produce"),
      I("chives", 1, "tbsp", "Produce"),
    ],
    ["Warm lobster in butter. Toast buns. Fill. Lemon and chives. Eat outside if you can."],
    ["lobster roll", "south shore lobster roll"],
    { cal: 430, protein: 28, carbs: 28, fat: 22 },
  ),
  place(
    "oatcakes",
    "Cape Breton oatcakes",
    "Nova Scotia",
    ["atlantic", "nova-scotia", "vegetarian", "quick"],
    "veg",
    "toast",
    30,
    "Salty-sweet oat biscuits. Tea, cheddar, or a slice of leftover ham.",
    [
      I("rolled oats", 2, "cups", "Pantry"),
      I("flour", 1, "cup", "Pantry"),
      I("brown sugar", 0.5, "cup", "Pantry"),
      I("butter", 0.5, "cup", "Dairy & Eggs"),
      I("kosher salt", 0.75, "tsp", "Herbs & Spices"),
    ],
    ["Rub butter into oats, flour, sugar, salt. Press thin. Bake until the edges bronze."],
    ["cape breton oatcakes", "maritime oatcakes"],
    { cal: 210, protein: 4, carbs: 28, fat: 10 },
  ),
  place(
    "chicken-fricot",
    "Chicken fricot",
    "New Brunswick",
    ["atlantic", "new-brunswick", "acadian"],
    "chicken",
    "soup",
    90,
    "Acadian chicken and potato soup with dumplings. The house smells like summer savory.",
    [
      I("chicken thighs", 8, "", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("summer savory", 2, "tsp", "Herbs & Spices"),
      I("flour", 1, "cup", "Pantry"),
      I("baking powder", 1.5, "tsp", "Pantry"),
    ],
    [
      "Brown chicken. Cover with water, onion, carrot, savory. Simmer until tender.",
      "Add potatoes. Drop dumpling dough on top and lid the pot 15 minutes.",
    ],
    ["fricot", "acadian chicken soup"],
    { cal: 480, protein: 34, carbs: 42, fat: 18 },
  ),
  place(
    "poutine-rapee",
    "Poutine râpée",
    "New Brunswick",
    ["atlantic", "new-brunswick", "acadian"],
    "pork",
    "bowl",
    120,
    "Grated-potato dumplings stuffed with salted pork. Acadian, filling, not Quebec poutine.",
    [
      I("russet potatoes", 6, "", "Produce"),
      I("salt pork", 0.5, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("kosher salt", 2, "tsp", "Herbs & Spices"),
    ],
    [
      "Grate half the potatoes, mash the rest. Mix. Wrap around cubes of salt pork.",
      "Simmer gently until they float and the centers are hot. Butter and pepper.",
    ],
    ["poutine rapee", "acadian potato dumpling"],
    { cal: 510, protein: 18, carbs: 52, fat: 26 },
  ),
  place(
    "ployes",
    "Ployes",
    "New Brunswick",
    ["atlantic", "new-brunswick", "acadian", "vegetarian", "quick"],
    "veg",
    "toast",
    25,
    "Buckwheat pancakes from the Madawaska. No flip — cook one side, eat with butter or creton.",
    [
      I("buckwheat flour", 1, "cup", "Pantry"),
      I("all-purpose flour", 0.5, "cup", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("water", 1.5, "cups", "Other"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    ["Mix a pourable batter. Cook on a dry pan until the top is set with holes. Do not flip. Butter."],
    ["ployes pancakes", "buckwheat ployes"],
    { cal: 240, protein: 6, carbs: 40, fat: 6 },
  ),
  place(
    "fiddlehead-saute",
    "Fiddleheads with garlic",
    "New Brunswick",
    ["atlantic", "new-brunswick", "vegetarian", "quick"],
    "veg",
    "green",
    20,
    "Spring on the St. John River. Boil first, then butter and garlic. Do not eat them raw.",
    [
      I("fiddleheads", 1, "lb", "Produce"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
      I("garlic", 2, "cloves", "Produce"),
      I("lemon", 0.5, "", "Produce"),
    ],
    ["Boil cleaned fiddleheads 10 minutes. Drain. Sauté in butter and garlic. Lemon."],
    ["fiddlehead greens", "ostrich fern"],
    { cal: 140, protein: 5, carbs: 10, fat: 9 },
  ),
  place(
    "pei-potato-scallop",
    "PEI scalloped potatoes",
    "Prince Edward Island",
    ["atlantic", "pei", "vegetarian"],
    "veg",
    "roast",
    70,
    "The island grows the potatoes. You supply cream, onion, and patience.",
    [
      I("PEI potatoes", 3, "lb", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cream", 1.5, "cups", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    ["Slice potatoes thin. Layer with onion, cream, butter, salt. Bake until a knife slides. Cheddar on top at the end."],
    ["scalloped potatoes", "pei potato bake"],
    { cal: 420, protein: 12, carbs: 48, fat: 20 },
  ),
  place(
    "malpeque-mussels",
    "Malpeque mussels",
    "Prince Edward Island",
    ["atlantic", "pei", "seafood", "quick"],
    "seafood",
    "bowl",
    20,
    "PEI mussels, white wine, garlic, cream if you want to be fancy. Bread for the broth.",
    [
      I("mussels", 3, "lb", "Meat & Seafood"),
      I("garlic", 4, "cloves", "Produce"),
      I("shallot", 1, "", "Produce"),
      I("white wine", 0.75, "cup", "Pantry"),
      I("cream", 0.25, "cup", "Dairy & Eggs"),
      I("parsley", 0.25, "cup", "Produce"),
      I("crusty bread", 1, "loaf", "Bakery"),
    ],
    ["Sauté garlic and shallot. Add wine and mussels. Lid 5–7 minutes. Finish with cream and parsley."],
    ["pei mussels", "steamed mussels"],
    { cal: 380, protein: 32, carbs: 22, fat: 14 },
  ),
  place(
    "pei-lobster-supper",
    "PEI lobster supper",
    "Prince Edward Island",
    ["atlantic", "pei", "seafood"],
    "seafood",
    "fish",
    45,
    "Church-basement energy: boiled lobster, potato salad, rolls, a slice of pie later.",
    [
      I("live lobsters", 4, "", "Meat & Seafood"),
      I("potato", 6, "", "Produce"),
      I("mayonnaise", 0.5, "cup", "Pantry"),
      I("celery", 2, "stalks", "Produce"),
      I("dinner rolls", 8, "", "Bakery"),
      I("butter", 0.25, "cup", "Dairy & Eggs"),
    ],
    ["Boil lobsters in heavily salted water. Potato salad while they cool. Rolls, butter, bibs."],
    ["church lobster supper", "new glasgow lobster"],
    { cal: 620, protein: 42, carbs: 40, fat: 28 },
  ),
];

const USA: Recipe[] = [
  place("al-white-bbq-chicken", "Alabama white BBQ chicken", "American", ["alabama", "usa"], "chicken", "skillet", 45, "Grilled chicken dunked in mayo-vinegar white sauce. North Alabama on a plate.", [I("chicken pieces", 8, "", "Meat & Seafood"), I("mayonnaise", 1, "cup", "Pantry"), I("apple cider vinegar", 0.25, "cup", "Pantry"), I("black pepper", 1, "tbsp", "Herbs & Spices")], ["Grill chicken. Whisk mayo, vinegar, pepper. Dunk while hot."], ["white sauce chicken"], { cal: 520, protein: 38, carbs: 2, fat: 40 }),
  place("ak-salmon-chowder", "Alaska salmon chowder", "American", ["alaska", "usa"], "fish", "soup", 40, "Salmon, potato, dill, a little cream. The Last Frontier in a bowl.", [I("salmon", 1, "lb", "Meat & Seafood"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("milk", 2, "cups", "Dairy & Eggs"), I("dill", 2, "tbsp", "Produce")], ["Sweat onion. Add potato and water. When tender, add salmon and milk. Dill. Do not boil hard."], ["alaskan salmon soup"], { cal: 410, protein: 32, carbs: 28, fat: 18 }),
  place("az-navajo-tacos", "Arizona Navajo tacos", "American", ["arizona", "usa"], "beef", "taco", 40, "Fry bread piled with chili, lettuce, cheese, and tomato.", [I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("ground beef", 1, "lb", "Meat & Seafood"), I("chili powder", 2, "tbsp", "Herbs & Spices"), I("cheddar", 1, "cup", "Dairy & Eggs"), I("lettuce", 0.5, "head", "Produce")], ["Fry dough rounds. Brown beef with chili powder. Pile high."], ["indian taco", "fry bread taco"], { cal: 640, protein: 32, carbs: 52, fat: 32 }),
  place("ar-fried-catfish", "Arkansas fried catfish", "American", ["arkansas", "usa"], "fish", "fish", 30, "Cornmeal crust, hot oil, lemon. A Friday night on the river.", [I("catfish fillets", 4, "", "Meat & Seafood"), I("cornmeal", 1, "cup", "Pantry"), I("cayenne", 1, "tsp", "Herbs & Spices"), I("oil", 2, "cups", "Pantry"), I("lemon", 1, "", "Produce")], ["Dredge in seasoned cornmeal. Fry until gold. Lemon."], ["southern catfish"], { cal: 480, protein: 28, carbs: 22, fat: 30 }),
  place("ca-fish-tacos", "California fish tacos", "American", ["california", "usa"], "fish", "taco", 30, "Baja energy: fried or grilled fish, cabbage, crema, lime.", [I("white fish", 1, "lb", "Meat & Seafood"), I("corn tortillas", 8, "", "Bakery"), I("cabbage", 0.25, "head", "Produce"), I("sour cream", 0.5, "cup", "Dairy & Eggs"), I("lime", 2, "", "Produce")], ["Season and cook fish. Char tortillas. Cabbage, crema, lime."], ["baja fish tacos"], { cal: 420, protein: 28, carbs: 36, fat: 16 }),
  place("co-green-chile-stew", "Colorado green chile stew", "American", ["colorado", "usa"], "pork", "soup", 80, "Pork, roasted Hatch-style chiles, potato. The mountain bowl.", [I("pork shoulder", 1.5, "lb", "Meat & Seafood"), I("green chiles", 8, "", "Produce"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("cumin", 1, "tsp", "Herbs & Spices")], ["Brown pork. Add onion, chopped roasted chiles, potato, water. Simmer until the pork yields."], ["hatch green chile stew"], { cal: 490, protein: 36, carbs: 28, fat: 24 }),
  place("ct-white-clam-pizza", "Connecticut white clam pizza", "American", ["connecticut", "usa"], "seafood", "toast", 25, "New Haven: clam, garlic, oil, oregano. No mozzarella required.", [I("pizza dough", 1, "lb", "Bakery"), I("chopped clams", 1, "cup", "Meat & Seafood"), I("garlic", 4, "cloves", "Produce"), I("olive oil", 3, "tbsp", "Pantry"), I("oregano", 1, "tsp", "Herbs & Spices")], ["Stretch dough. Scatter clams, garlic, oil, oregano. Bake as hot as the oven will go."], ["new haven clam pie"], { cal: 520, protein: 24, carbs: 60, fat: 18 }),
  place("de-scrapple-breakfast", "Delaware scrapple breakfast", "American", ["delaware", "usa"], "pork", "skillet", 20, "Sliced scrapple, fried crisp, eggs on the side.", [I("scrapple", 8, "oz", "Meat & Seafood"), I("eggs", 4, "", "Dairy & Eggs"), I("butter", 1, "tbsp", "Dairy & Eggs")], ["Fry scrapple slices until the crust sings. Eggs in the same pan."], ["mid-atlantic scrapple"], { cal: 480, protein: 28, carbs: 18, fat: 32 }),
  place("fl-key-lime-shrimp", "Florida key lime shrimp", "American", ["florida", "usa"], "seafood", "skillet", 20, "Shrimp, key lime, garlic, butter. Eat with the windows open.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("key limes", 4, "", "Produce"), I("garlic", 3, "cloves", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs")], ["Sauté garlic in butter. Add shrimp. Finish with key lime juice."], ["key west shrimp"], { cal: 310, protein: 36, carbs: 4, fat: 16 }),
  place("ga-peach-chicken", "Georgia peach skillet chicken", "American", ["georgia", "usa"], "chicken", "skillet", 35, "Chicken thighs, ripe peaches, a little vinegar and thyme.", [I("chicken thighs", 6, "", "Meat & Seafood"), I("peaches", 3, "", "Produce"), I("apple cider vinegar", 2, "tbsp", "Pantry"), I("thyme", 4, "sprigs", "Produce")], ["Brown chicken. Add peach wedges, vinegar, thyme. Roast until sticky."], ["peach chicken"], { cal: 440, protein: 34, carbs: 18, fat: 24 }),
  place("hi-loco-moco", "Hawaii loco moco", "American", ["hawaii", "usa"], "beef", "bowl", 25, "Rice, burger, fried egg, brown gravy. A plate lunch that is also breakfast.", [I("ground beef", 1, "lb", "Meat & Seafood"), I("cooked rice", 4, "cups", "Pantry"), I("eggs", 4, "", "Dairy & Eggs"), I("onion", 1, "", "Produce"), I("beef broth", 1.5, "cups", "Pantry")], ["Patty and sear beef. Onion gravy from the drippings. Rice, patty, egg, gravy."], ["loco moco"], { cal: 720, protein: 38, carbs: 62, fat: 34 }),
  place("id-finger-steaks", "Idaho finger steaks", "American", ["idaho", "usa"], "beef", "skillet", 30, "Strips of steak, battered, fried. Fry sauce on the side, potatoes of course.", [I("sirloin", 1.5, "lb", "Meat & Seafood"), I("flour", 1, "cup", "Pantry"), I("buttermilk", 1, "cup", "Dairy & Eggs"), I("russet potatoes", 4, "", "Produce")], ["Cut steak into strips. Buttermilk, flour, fry. Potatoes roasted or fried."], ["boise finger steaks"], { cal: 680, protein: 40, carbs: 42, fat: 36 }),
  place("il-italian-beef", "Illinois Italian beef", "American", ["illinois", "usa"], "beef", "toast", 180, "Chicago: thin beef, giardiniera, a roll dunked in jus.", [I("beef roast", 3, "lb", "Meat & Seafood"), I("giardiniera", 1, "cup", "Pantry"), I("italian rolls", 6, "", "Bakery"), I("garlic", 6, "cloves", "Produce"), I("oregano", 1, "tbsp", "Herbs & Spices")], ["Slow-roast beef with garlic and oregano. Slice thin. Soak rolls. Giardiniera."], ["chicago italian beef"], { cal: 610, protein: 42, carbs: 44, fat: 26 }),
  place("in-pork-tenderloin", "Indiana pork tenderloin sandwich", "American", ["indiana", "usa"], "pork", "toast", 30, "A pounded cutlet bigger than the bun. Pickles, mustard, onion.", [I("pork loin", 1, "lb", "Meat & Seafood"), I("breadcrumbs", 1.5, "cups", "Pantry"), I("buns", 4, "", "Bakery"), I("dill pickle", 4, "", "Pantry"), I("mustard", 2, "tbsp", "Pantry")], ["Pound pork thin. Bread and fry. Bun, pickle, mustard, onion if you want it."], ["hoosier tenderloin"], { cal: 640, protein: 36, carbs: 48, fat: 32 }),
  place("ia-loose-meat", "Iowa loose-meat sandwich", "American", ["iowa", "usa"], "beef", "toast", 25, "Maid-Rite energy: seasoned crumbled beef, mustard, pickle, a steamed bun.", [I("ground beef", 1.5, "lb", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("buns", 6, "", "Bakery"), I("mustard", 3, "tbsp", "Pantry"), I("dill pickle", 6, "", "Pantry")], ["Simmer beef with onion and a splash of water until loose. Pile on buns."], ["maid-rite", "tavern sandwich"], { cal: 480, protein: 32, carbs: 32, fat: 24 }),
  place("ks-burnt-ends", "Kansas burnt ends", "American", ["kansas", "usa"], "beef", "bowl", 240, "Brisket point cubed, sauced, and caramelized. Kansas City via the smoker — oven works too.", [I("beef brisket point", 3, "lb", "Meat & Seafood"), I("kosher salt", 2, "tbsp", "Herbs & Spices"), I("black pepper", 2, "tbsp", "Herbs & Spices"), I("bbq sauce", 1, "cup", "Pantry")], ["Season and slow-roast the point. Cube. Toss with sauce. Return to heat until sticky."], ["kc burnt ends"], { cal: 620, protein: 44, carbs: 14, fat: 40 }),
  place("ky-hot-brown", "Kentucky Hot Brown", "American", ["kentucky", "usa"], "turkey", "toast", 25, "Open-face turkey, Mornay, bacon, tomato. Louisville after the races.", [I("turkey slices", 12, "oz", "Meat & Seafood"), I("white bread", 4, "slices", "Bakery"), I("parmesan", 0.5, "cup", "Dairy & Eggs"), I("milk", 1.5, "cups", "Dairy & Eggs"), I("bacon", 8, "slices", "Meat & Seafood"), I("tomato", 2, "", "Produce")], ["Heat the broiler. Toast the white bread on both sides until gold, about 2 minutes a side.", "Cook the bacon in a skillet over medium heat for 6–8 minutes, until crisp. Drain on paper.", "Warm the milk in a saucepan over medium-low. Stir in the parmesan until the sauce coats a spoon, 3–4 minutes. Salt and pepper.", "Set the toast on an oven-safe plate. Lay the turkey slices on the toast. Pour the sauce over the turkey.", "Broil 2–3 minutes, until the sauce is bubbling. Cross the bacon on top and add tomato slices. Serve hot."], ["hot brown"], { cal: 690, protein: 42, carbs: 36, fat: 40 }),
  place("la-red-beans-rice", "Louisiana red beans and rice", "American", ["louisiana", "usa"], "pork", "bowl", 150, "Monday pot: red beans, andouille, rice. The laundry-day classic.", [I("red beans", 1, "lb", "Pantry"), I("andouille", 12, "oz", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("green pepper", 1, "", "Produce"), I("rice", 2, "cups", "Pantry")], ["Soak beans. Sweat trinity with sausage. Simmer beans until creamy. Rice."], ["red beans"], { cal: 560, protein: 28, carbs: 68, fat: 18 }),
  place("me-lobster-roll", "Maine lobster roll", "American", ["maine", "usa"], "seafood", "toast", 20, "Cold mayo or warm butter, both legal. A split-top bun, toasted.", [I("cooked lobster meat", 1, "lb", "Meat & Seafood"), I("mayonnaise", 3, "tbsp", "Pantry"), I("split-top buns", 4, "", "Bakery"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce")], ["Fold lobster with mayo or warm it in butter. Toast buns. Fill. Lemon."], ["maine roll"], { cal: 440, protein: 28, carbs: 28, fat: 24 }),
  place("md-crab-cakes", "Maryland crab cakes", "American", ["maryland", "usa"], "seafood", "skillet", 25, "Mostly crab, barely any filler, Old Bay, a hot pan.", [I("lump crab", 1, "lb", "Meat & Seafood"), I("mayonnaise", 3, "tbsp", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("Old Bay", 2, "tsp", "Herbs & Spices"), I("saltines", 8, "", "Pantry")], ["Fold gently. Cake. Chill. Pan-fry until the crust is bronze."], ["old bay crab cakes"], { cal: 320, protein: 28, carbs: 8, fat: 18 }),
  place("ma-clam-chowder", "Massachusetts clam chowder", "American", ["massachusetts", "usa"], "seafood", "soup", 40, "New England: clams, potato, cream. Oyster crackers. No tomato in this house.", [I("chopped clams", 2, "cups", "Meat & Seafood"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("cream", 1, "cup", "Dairy & Eggs"), I("salt pork", 2, "oz", "Meat & Seafood")], ["Render salt pork. Onion, potato, clam liquor. When tender, clams and cream."], ["new england clam chowder"], { cal: 420, protein: 22, carbs: 28, fat: 24 }),
  place("mi-pasty", "Michigan pasty", "American", ["michigan", "usa"], "beef", "roast", 70, "Upper Peninsula miner food: beef, potato, rutabaga, crust you can hold.", [I("pie dough", 2, "rounds", "Bakery"), I("beef stew meat", 1, "lb", "Meat & Seafood"), I("potato", 2, "", "Produce"), I("rutabaga", 1, "", "Produce"), I("onion", 1, "", "Produce")], ["Dice filling. Fold into dough. Crimp. Bake until the crust is gold. Ketchup is a local argument."], ["up pasty", "cornish pasty michigan"], { cal: 640, protein: 28, carbs: 52, fat: 34 }),
  place("mn-wild-rice-soup", "Minnesota wild rice soup", "American", ["minnesota", "usa"], "chicken", "soup", 50, "Creamy wild rice, chicken, mushrooms. Cabin food.", [I("wild rice", 1, "cup", "Pantry"), I("chicken", 2, "cups", "Meat & Seafood"), I("mushrooms", 8, "oz", "Produce"), I("cream", 1, "cup", "Dairy & Eggs"), I("celery", 2, "stalks", "Produce")], ["Cook rice. Sweat veg. Add broth, rice, chicken. Cream at the end."], ["minnesota soup"], { cal: 430, protein: 26, carbs: 36, fat: 20 }),
  place("ms-come-back-shrimp", "Mississippi comeback shrimp", "American", ["mississippi", "usa"], "seafood", "skillet", 20, "Shrimp with Jackson comeback sauce — mayo, chili, lemon, garlic.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("mayonnaise", 0.5, "cup", "Pantry"), I("chili sauce", 3, "tbsp", "Pantry"), I("lemon", 1, "", "Produce"), I("garlic", 2, "cloves", "Produce")], ["Whisk sauce. Sauté shrimp. Toss or dunk."], ["come back sauce shrimp"], { cal: 360, protein: 32, carbs: 8, fat: 22 }),
  place("mo-toasted-ravioli", "Missouri toasted ravioli", "American", ["missouri", "usa"], "beef", "bowl", 30, "St. Louis: breaded ravioli, fried, marinara, parmesan.", [I("meat ravioli", 1, "lb", "Frozen"), I("breadcrumbs", 1, "cup", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("marinara", 1.5, "cups", "Pantry"), I("parmesan", 0.5, "cup", "Dairy & Eggs")], ["Bread thawed ravioli. Fry. Marinara and parmesan."], ["t-ravs", "st louis ravioli"], { cal: 540, protein: 22, carbs: 52, fat: 26 }),
  place("mt-bison-skillet", "Montana bison skillet", "American", ["montana", "usa"], "beef", "skillet", 35, "Bison or beef, mushrooms, whiskey-ish pan sauce, mashed potatoes.", [I("bison or beef steak", 1.5, "lb", "Meat & Seafood"), I("mushrooms", 8, "oz", "Produce"), I("onion", 1, "", "Produce"), I("beef broth", 0.75, "cup", "Pantry"), I("potato", 4, "", "Produce")], ["Sear meat. Mushrooms and onion. Deglaze. Potatoes mashed with butter."], ["montana steak skillet"], { cal: 560, protein: 42, carbs: 32, fat: 26 }),
  place("ne-runza", "Nebraska runza", "American", ["nebraska", "usa"], "beef", "toast", 50, "Yeast bun stuffed with beef, cabbage, onion. Road-trip food.", [I("bread dough", 1.5, "lb", "Bakery"), I("ground beef", 1, "lb", "Meat & Seafood"), I("cabbage", 0.5, "head", "Produce"), I("onion", 1, "", "Produce")], ["Cook beef with cabbage and onion. Wrap in dough. Bake until brown."], ["bierock", "runza sandwich"], { cal: 520, protein: 28, carbs: 48, fat: 22 }),
  place("nv-cowboy-ribeye", "Nevada cowboy ribeye", "American", ["nevada", "usa"], "beef", "skillet", 30, "A thick ribeye, salt, pepper, a screaming pan. Steakhouse desert energy.", [I("ribeye steaks", 2, "", "Meat & Seafood"), I("kosher salt", 2, "tsp", "Herbs & Spices"), I("black pepper", 2, "tsp", "Herbs & Spices"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Salt early. Sear hard. Butter baste. Rest."], ["vegas ribeye"], { cal: 720, protein: 52, carbs: 0, fat: 56 }),
  place("nh-maple-pork", "New Hampshire maple cider pork", "American", ["new-hampshire", "usa"], "pork", "skillet", 40, "Pork chops, maple, cider, mustard. Fall on a plate.", [I("pork chops", 4, "", "Meat & Seafood"), I("maple syrup", 3, "tbsp", "Pantry"), I("apple cider", 0.5, "cup", "Pantry"), I("dijon", 1, "tbsp", "Pantry")], ["Sear chops. Maple, cider, mustard in the pan. Reduce to a glaze."], ["maple pork chops"], { cal: 480, protein: 36, carbs: 18, fat: 28 }),
  place("nj-pork-roll", "New Jersey pork roll breakfast", "American", ["new-jersey", "usa"], "pork", "toast", 15, "Taylor pork roll, egg, cheese, a kaiser. The Garden State morning.", [I("pork roll", 8, "slices", "Meat & Seafood"), I("eggs", 4, "", "Dairy & Eggs"), I("american cheese", 4, "slices", "Dairy & Eggs"), I("kaiser rolls", 4, "", "Bakery")], ["Score and fry pork roll. Egg, cheese, roll."], ["taylor ham", "pork roll egg and cheese"], { cal: 540, protein: 28, carbs: 32, fat: 32 }),
  place("nm-stacked-enchiladas", "New Mexico stacked enchiladas", "American", ["new-mexico", "usa"], "chicken", "roast", 40, "Flat corn tortillas stacked with red or green chile, cheese, a fried egg.", [I("corn tortillas", 12, "", "Bakery"), I("red chile sauce", 2, "cups", "Pantry"), I("chicken", 2, "cups", "Meat & Seafood"), I("cheddar", 2, "cups", "Dairy & Eggs"), I("eggs", 4, "", "Dairy & Eggs")], ["Dip tortillas in chile. Stack with chicken and cheese. Bake. Egg on top."], ["christmas enchiladas"], { cal: 610, protein: 38, carbs: 42, fat: 30 }),
  place("ny-chopped-cheese", "New York chopped cheese", "American", ["new-york", "usa"], "beef", "toast", 20, "Bodega hero: chopped burger, cheese, onion, lettuce, tomato, hero roll.", [I("ground beef", 1, "lb", "Meat & Seafood"), I("american cheese", 6, "slices", "Dairy & Eggs"), I("hero rolls", 4, "", "Bakery"), I("onion", 1, "", "Produce"), I("lettuce", 0.5, "head", "Produce"), I("tomato", 2, "", "Produce")], ["Chop beef on the griddle with onion. Cheese. Hero with lettuce and tomato."], ["chop cheese"], { cal: 620, protein: 34, carbs: 40, fat: 34 }),
  place("nc-vinegar-pork", "North Carolina vinegar pork", "American", ["north-carolina", "usa"], "pork", "bowl", 240, "Pulled pork dressed in vinegar and pepper. Coleslaw on the tray.", [I("pork shoulder", 4, "lb", "Meat & Seafood"), I("apple cider vinegar", 1, "cup", "Pantry"), I("red pepper flakes", 2, "tsp", "Herbs & Spices"), I("cabbage", 0.5, "head", "Produce")], ["Slow-roast pork. Pull. Dress with vinegar, pepper, salt. Slaw."], ["eastern nc pork"], { cal: 540, protein: 42, carbs: 8, fat: 36 }),
  place("nd-knoephla", "North Dakota knoephla soup", "American", ["north-dakota", "usa"], "chicken", "soup", 45, "Creamy chicken and dumpling soup. German-Russian prairie food.", [I("chicken broth", 6, "cups", "Pantry"), I("potato", 3, "", "Produce"), I("cream", 1, "cup", "Dairy & Eggs"), I("flour", 1.5, "cups", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("celery", 2, "stalks", "Produce")], ["Simmer potato and celery in broth. Drop knoephla dough (flour, egg, water). Cream at the end."], ["knoephla"], { cal: 390, protein: 14, carbs: 48, fat: 16 }),
  place("oh-cincinnati-chili", "Ohio Cincinnati chili", "American", ["ohio", "usa"], "beef", "pasta", 90, "Spaghetti, spiced meat sauce, cheddar mountain. Three-way, four-way, five-way.", [I("ground beef", 2, "lb", "Meat & Seafood"), I("tomato sauce", 2, "cups", "Pantry"), I("cinnamon", 1, "tsp", "Herbs & Spices"), I("cocoa", 1, "tsp", "Pantry"), I("spaghetti", 1, "lb", "Pantry"), I("cheddar", 3, "cups", "Dairy & Eggs")], ["Simmer beef with tomato, cinnamon, cocoa, chili powder. Over spaghetti. Pile cheddar."], ["skyline chili", "3-way"], { cal: 680, protein: 38, carbs: 58, fat: 32 }),
  place("ok-chicken-fried-steak", "Oklahoma chicken-fried steak", "American", ["oklahoma", "usa"], "beef", "skillet", 35, "Cubed steak, peppered gravy, mashed potatoes. The state meal energy.", [I("cubed steak", 4, "", "Meat & Seafood"), I("flour", 1.5, "cups", "Pantry"), I("buttermilk", 1, "cup", "Dairy & Eggs"), I("milk", 2, "cups", "Dairy & Eggs"), I("potato", 4, "", "Produce")], ["Dredge and fry steaks. Gravy from the drippings. Potatoes."], ["cfs"], { cal: 740, protein: 38, carbs: 48, fat: 42 }),
  place("or-marionberry-pork", "Oregon marionberry pork", "American", ["oregon", "usa"], "pork", "skillet", 35, "Pork chops with marionberry or blackberry pan sauce.", [I("pork chops", 4, "", "Meat & Seafood"), I("blackberries", 1.5, "cups", "Produce"), I("shallot", 1, "", "Produce"), I("balsamic", 1, "tbsp", "Pantry")], ["Sear chops. Berries and shallot in the pan. Crush, reduce, spoon over."], ["oregon blackberry pork"], { cal: 460, protein: 36, carbs: 14, fat: 28 }),
  place("pa-cheesesteak", "Pennsylvania cheesesteak", "American", ["pennsylvania", "usa"], "beef", "toast", 20, "Ribeye, onions, Cheez Whiz or provolone, an Amoroso-style roll.", [I("ribeye", 1.5, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("provolone", 8, "slices", "Dairy & Eggs"), I("hoagie rolls", 4, "", "Bakery")], ["Chop steak on a griddle. Onions. Cheese. Roll. Do not overthink it."], ["philly cheesesteak"], { cal: 680, protein: 42, carbs: 40, fat: 38 }),
  place("ri-stuffies", "Rhode Island stuffies", "American", ["rhode-island", "usa"], "seafood", "fish", 40, "Stuffed quahogs: chopped clam, bread, chorizo, baked in the shell.", [I("chopped clams", 2, "cups", "Meat & Seafood"), I("stale bread", 3, "cups", "Bakery"), I("chorizo", 4, "oz", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 1, "stalk", "Produce")], ["Cook chorizo with onion. Mix with clams and bread. Bake in shells or a dish until browned."], ["stuffed quahogs"], { cal: 380, protein: 24, carbs: 32, fat: 16 }),
  place("sc-shrimp-grits", "South Carolina shrimp and grits", "American", ["south-carolina", "usa"], "seafood", "bowl", 35, "Lowcountry: creamy grits, shrimp, bacon, a little heat.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("grits", 1, "cup", "Pantry"), I("bacon", 4, "slices", "Meat & Seafood"), I("cheddar", 1, "cup", "Dairy & Eggs"), I("scallion", 4, "", "Produce")], ["Cook grits with cheddar. Bacon. Shrimp in the drippings. Pile on."], ["lowcountry shrimp and grits"], { cal: 560, protein: 38, carbs: 36, fat: 28 }),
  place("sd-chislic", "South Dakota chislic", "American", ["south-dakota", "usa"], "beef", "skillet", 20, "Cubes of lamb or beef, fried or grilled, garlic salt. A bar snack that is dinner.", [I("lamb or sirloin", 1.5, "lb", "Meat & Seafood"), I("garlic salt", 2, "tsp", "Herbs & Spices"), I("oil", 2, "tbsp", "Pantry")], ["Cube meat. Hot pan or grill. Garlic salt. Toothpicks."], ["chislic"], { cal: 420, protein: 36, carbs: 0, fat: 30 }),
  place("tn-hot-chicken", "Tennessee hot chicken", "American", ["tennessee", "usa"], "chicken", "skillet", 45, "Nashville: fried chicken painted with cayenne oil. Pickles, white bread.", [I("chicken pieces", 8, "", "Meat & Seafood"), I("buttermilk", 2, "cups", "Dairy & Eggs"), I("flour", 2, "cups", "Pantry"), I("cayenne", 3, "tbsp", "Herbs & Spices"), I("lard or oil", 3, "cups", "Pantry"), I("white bread", 8, "slices", "Bakery")], ["Soak, dredge, fry. Mix cayenne into hot frying oil. Paint. Bread and pickles."], ["nashville hot chicken"], { cal: 720, protein: 38, carbs: 36, fat: 46 }),
  place("tx-oven-brisket", "Texas oven brisket", "American", ["texas", "usa"], "beef", "roast", 300, "Salt, pepper, low oven, patience. Smoke if you have it. Slices with pickles.", [I("beef brisket", 4, "lb", "Meat & Seafood"), I("kosher salt", 2, "tbsp", "Herbs & Spices"), I("coarse black pepper", 2, "tbsp", "Herbs & Spices")], ["Season. 275°F until probe-tender. Rest in foil. Slice against the grain."], ["texas brisket"], { cal: 580, protein: 46, carbs: 0, fat: 42 }),
  place("ut-funeral-potatoes", "Utah funeral potatoes", "American", ["utah", "usa"], "veg", "roast", 50, "Hash browns, cream soup, sour cream, cornflakes. Comfort that travels well.", [I("hash browns", 30, "oz", "Frozen"), I("cream of chicken soup", 1, "can", "Pantry"), I("sour cream", 2, "cups", "Dairy & Eggs"), I("cheddar", 2, "cups", "Dairy & Eggs"), I("cornflakes", 2, "cups", "Pantry"), I("butter", 0.25, "cup", "Dairy & Eggs")], ["Mix potatoes with soup, sour cream, cheese. Cornflake-butter lid. Bake until bubbling."], ["cheesy potatoes"], { cal: 480, protein: 14, carbs: 38, fat: 30 }),
  place("vt-maple-mac", "Vermont maple cheddar mac", "American", ["vermont", "usa"], "veg", "pasta", 30, "Sharp cheddar, a whisper of maple, breadcrumbs.", [I("elbow pasta", 1, "lb", "Pantry"), I("sharp cheddar", 3, "cups", "Dairy & Eggs"), I("milk", 2, "cups", "Dairy & Eggs"), I("maple syrup", 1, "tbsp", "Pantry"), I("breadcrumbs", 0.5, "cup", "Pantry")], ["Béchamel, cheddar, maple. Pasta. Breadcrumb top. Bake 10 minutes."], ["vermont mac"], { cal: 620, protein: 26, carbs: 68, fat: 26 }),
  place("va-peanut-soup", "Virginia peanut soup", "American", ["virginia", "usa"], "veg", "soup", 35, "Colonial Williamsburg energy: peanut, celery, cream.", [I("peanut butter", 1, "cup", "Pantry"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("chicken broth", 4, "cups", "Pantry"), I("cream", 0.5, "cup", "Dairy & Eggs")], ["Sweat onion and celery. Whisk in broth and peanut butter. Cream. Smooth."], ["williamsburg peanut soup"], { cal: 380, protein: 16, carbs: 16, fat: 28 }),
  place("wa-cedar-salmon", "Washington cedar-plank salmon", "American", ["washington", "usa"], "fish", "fish", 30, "Salmon, brown sugar, a plank or a sheet pan if that is what you have.", [I("salmon fillet", 2, "lb", "Meat & Seafood"), I("brown sugar", 2, "tbsp", "Pantry"), I("soy sauce", 1, "tbsp", "Pantry"), I("lemon", 1, "", "Produce")], ["Soak a plank if using. Rub salmon. Roast or grill until just set. Lemon."], ["pnw salmon"], { cal: 420, protein: 38, carbs: 6, fat: 26 }),
  place("wv-pepperoni-rolls", "West Virginia pepperoni rolls", "American", ["west-virginia", "usa"], "pork", "toast", 40, "Soft rolls wrapped around pepperoni. Miner lunch, still a gas-station king.", [I("bread dough", 1.5, "lb", "Bakery"), I("pepperoni sticks", 8, "", "Meat & Seafood"), I("mozzarella", 1, "cup", "Dairy & Eggs")], ["Wrap dough around pepperoni (cheese if you like). Bake until the rolls are gold."], ["pepperoni roll"], { cal: 480, protein: 22, carbs: 44, fat: 24 }),
  place("wi-beer-brats", "Wisconsin beer brats", "American", ["wisconsin", "usa"], "pork", "skillet", 40, "Brats simmered in beer and onion, then grilled. Mustard, a hard roll.", [I("bratwurst", 6, "", "Meat & Seafood"), I("beer", 2, "bottles", "Pantry"), I("onion", 2, "", "Produce"), I("hard rolls", 6, "", "Bakery"), I("mustard", 4, "tbsp", "Pantry")], ["Simmer brats in beer and onion. Grill to snap. Onion on top. Mustard."], ["sheboygan brats"], { cal: 560, protein: 26, carbs: 32, fat: 34 }),
  place("wy-chili", "Wyoming range chili", "American", ["wyoming", "usa"], "beef", "bowl", 90, "Beef chili, no beans if you are stubborn, cheddar and onion if you are kind.", [I("beef chuck", 2, "lb", "Meat & Seafood"), I("chili powder", 3, "tbsp", "Herbs & Spices"), I("onion", 2, "", "Produce"), I("tomato sauce", 2, "cups", "Pantry"), I("beef broth", 1, "cup", "Pantry")], ["Brown beef. Onion, chili powder, tomato, broth. Simmer until thick."], ["range chili"], { cal: 520, protein: 42, carbs: 16, fat: 32 }),
];

export const PLACE_RECIPES: Recipe[] = [...ATLANTIC_RECIPES, ...USA];
