import { I, dish } from "./catalog-kit";
import type { Recipe } from "./types";

const farmer = {
  book: "The Boston Cooking-School Cook Book",
  author: "Fannie Merritt Farmer",
  year: 1918,
  era: "1910s",
  archiveId: "bostoncookingsc00farm",
  credit:
    "Fannie Merritt Farmer, The Boston Cooking-School Cook Book (1918). Public domain. Internet Archive bostoncookingsc00farm.",
};

const fisher = {
  book: "What Mrs. Fisher Knows About Old Southern Cooking",
  author: "Abby Fisher",
  year: 1881,
  era: "1880s",
  archiveId: "whatmrsfisherkno00fishrich",
  credit:
    "Abby Fisher, What Mrs. Fisher Knows About Old Southern Cooking (Women's Co-operative Printing Office, San Francisco, 1881). Public domain. Internet Archive whatmrsfisherkno00fishrich.",
};

function x(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: Recipe["source"],
  nutrition?: Recipe["nutrition"],
): Recipe {
  return dish({
    id,
    name,
    cuisine,
    description,
    minutes,
    protein,
    plate,
    tags: Array.from(new Set(tags)),
    ingredients,
    steps,
    nutrition,
    source,
  });
}

export const CLASSIC_RECIPES: Recipe[] = [
  x("ar-ff-parker-house-rolls", "Parker House rolls", "American", ["vintage", "era-1910s", "book-farmer", "baking", "vegetarian", "old-school"], "veg", "bowl", 180, "The Boston rolls: a buttered crease, a fold, a shine of milk.", [I("flour", 4, "cups", "Pantry"), I("milk", 1, "cups", "Dairy & Eggs"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry"), I("yeast", 1, "cake", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Scald the milk. Stir in the butter, sugar, and salt. Cool to lukewarm, then crumble in the yeast and stir until it dissolves.", "Beat in the flour to a soft dough. Knead on a board until smooth, 8 minutes. Set in a greased bowl, cover, and rise until double, about 90 minutes.", "Punch the dough down. Roll ⅓ inch thick. Cut 2½-inch rounds. Crease each through the center with a knife handle.", "Brush with melted butter, fold over, and set on a greased sheet. Rise until light, about 45 minutes.", "Bake at 425°F 12–15 minutes, until gold. Brush with butter. Serve hot."], farmer, { cal: 160, protein: 4, carbs: 26, fat: 4 }),
  x("ar-ff-boston-brown-bread", "Boston brown bread", "American", ["vintage", "era-1910s", "book-farmer", "baking", "vegetarian", "old-school"], "veg", "bowl", 210, "Rye, graham, cornmeal, molasses. Steamed in a tin, sliced hot with beans.", [I("rye meal", 1, "cups", "Pantry"), I("graham flour", 1, "cups", "Pantry"), I("cornmeal", 1, "cups", "Pantry"), I("molasses", 0.75, "cups", "Pantry"), I("sour milk", 2, "cups", "Dairy & Eggs"), I("soda", 1.5, "tsp", "Pantry")], ["Stir the rye meal, graham flour, cornmeal, and soda together in a bowl until even.", "Mix the molasses with the sour milk. Pour into the dry mix and stir just until no dry flour remains.", "Grease a 1-pound mold or coffee tin. Fill it two-thirds full. Cover tightly with a lid or foil.", "Steam 3 hours, keeping the water at a simmer and adding boiling water as it drops, so the tin never goes dry.", "Uncover and dry in a 300°F oven 15 minutes. Slice hot and serve with baked beans."], farmer, { cal: 220, protein: 5, carbs: 44, fat: 3 }),
  x("ar-ff-fish-chowder", "Fish chowder", "American", ["vintage", "era-1910s", "book-farmer", "soup", "old-school"], "fish", "soup", 45, "Cod, salt pork, potato, common crackers. New England in a kettle.", [I("cod or haddock", 4, "lb", "Meat & Seafood"), I("salt pork", 2, "oz", "Meat & Seafood"), I("potatoes", 4, "cups", "Produce"), I("onion", 1, "", "Produce"), I("milk", 4, "cups", "Dairy & Eggs"), I("common crackers", 8, "", "Bakery")], ["Cut the salt pork into dice. Try it out in a kettle over medium heat until the bits are crisp. Lift out the pork.", "Cook the sliced onion in the fat 5 minutes, until soft. Layer the fish and the cubed potatoes over the onion.", "Add water to barely cover. Simmer 20 minutes, until the potato is tender and the fish flakes.", "Pour in the milk. Add a spoon of butter, salt, and pepper. Heat until steaming — do not boil.", "Split the crackers in a tureen. Pour the chowder over and scatter the pork bits. Serve hot."], farmer, { cal: 380, protein: 32, carbs: 28, fat: 14 }),
  x("ar-ff-lobster-newburg", "Lobster à la Newburg", "American", ["vintage", "era-1910s", "book-farmer"], "seafood", "skillet", 25, "Lobster, cream, sherry, yolks. A hotel supper on toast.", [I("lobster meat", 2, "cups", "Meat & Seafood"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("cream", 1, "cups", "Dairy & Eggs"), I("egg yolks", 2, "", "Dairy & Eggs"), I("sherry", 2, "tbsp", "Pantry"), I("paprika", 0.25, "tsp", "Herbs & Spices")], ["Melt the butter in a chafing dish or skillet over medium-low heat. Add the lobster meat and cook 3 minutes, until it is hot through.", "Beat the yolks with the cream. Pour over the lobster, stirring.", "Cook, stirring, until the sauce thickens and coats the lobster, 3–4 minutes. Do not let it boil or the yolks will curdle.", "Stir in the sherry, salt, cayenne, and paprika.", "Spoon over hot toast and serve at once. This is a supper dish, not a bake."], farmer, { cal: 420, protein: 28, carbs: 6, fat: 28 }),
  x("ar-ff-white-sauce", "White sauce", "American", ["vintage", "era-1910s", "book-farmer", "sauce", "vegetarian"], "veg", "bowl", 12, "Butter, flour, milk. The mother sauce of the Boston kitchen.", [I("butter", 2, "tbsp", "Dairy & Eggs"), I("flour", 2, "tbsp", "Pantry"), I("milk", 1, "cups", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices")], ["Melt the butter in a saucepan over medium-low heat. Do not let it brown.", "Add the flour and cook 2 minutes, stirring, until the raw flour smell is gone.", "Pour in the milk slowly, stirring without stopping, until the sauce is smooth.", "Cook 3–4 minutes more, until it is thick enough to coat a spoon.", "Salt. Use at once on vegetables, fish, or toast. This is Farmer's thin white sauce."], farmer, { cal: 90, protein: 3, carbs: 6, fat: 6 }),
  x("ar-ff-popovers", "Popovers", "American", ["vintage", "era-1910s", "book-farmer", "baking", "breakfast", "vegetarian"], "eggs", "bowl", 40, "Eggs, milk, flour. A hot oven and they leap.", [I("flour", 1, "cups", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("milk", 1, "cups", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices"), I("butter", 1, "tbsp", "Dairy & Eggs")], ["Heat the oven to 450°F. Butter iron popover cups or a muffin tin and set them in the oven to heat.", "Beat the eggs slightly. Add the milk and salt, then the flour. Beat until the batter is smooth and pourable.", "Fill the hot cups half full. Do not open the oven after they go in.", "Bake 20 minutes at 450°F, then lower to 350°F and bake 15 minutes more, until they are tall and deep gold.", "Pierce each popover with a knife to let steam out. Serve at once; they fall as they cool."], farmer, { cal: 140, protein: 6, carbs: 18, fat: 4 }),
  x("ar-ff-molasses-gingerbread", "Soft molasses gingerbread", "American", ["vintage", "era-1910s", "book-farmer", "baking", "dessert", "vegetarian"], "veg", "dessert", 40, "Molasses, ginger, sour milk. A square for the lunch pail.", [I("molasses", 1, "cups", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("flour", 2.25, "cups", "Pantry"), I("soda", 1.5, "tsp", "Pantry"), I("ginger", 2, "tsp", "Herbs & Spices"), I("sour milk", 1, "cups", "Dairy & Eggs")], ["Heat the oven to 350°F. Grease an 8-inch square pan.", "Melt the butter in the molasses over low heat. Take off the heat.", "Stir the flour, soda, and ginger together. Add them to the molasses, then the sour milk, and mix until even.", "Pour into the pan. Bake 25 minutes, until a toothpick in the center comes out clean.", "Cool in the pan 10 minutes. Cut into squares. Serve warm or packed for the pail."], farmer, { cal: 240, protein: 4, carbs: 42, fat: 7 }),
  x("ar-ff-cream-tomato-soup", "Cream of tomato soup", "American", ["vintage", "era-1910s", "book-farmer", "soup", "vegetarian"], "veg", "soup", 25, "Tomato and white sauce, combined off the boil so it does not curdle.", [I("canned tomatoes", 2, "cups", "Pantry"), I("onion", 0.25, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("flour", 4, "tbsp", "Pantry"), I("milk", 4, "cups", "Dairy & Eggs"), I("soda", 0.25, "tsp", "Pantry")], ["Simmer the tomatoes with the onion 15 minutes. Rub through a strainer. Stir in the soda — it will foam.", "In another pan, melt the butter, add the flour, and cook 2 minutes without browning.", "Whisk in the milk and cook until you have a smooth white sauce, 5 minutes.", "Take both pans off the heat. Stir the tomato into the white sauce, not the other way, so it does not curdle.", "Salt and pepper. Serve at once. Do not boil after the two are combined."], farmer, { cal: 220, protein: 8, carbs: 16, fat: 14 }),
  x("ar-ff-eggs-goldenrod", "Eggs à la goldenrod", "American", ["vintage", "era-1910s", "book-farmer", "breakfast", "vegetarian"], "eggs", "toast", 20, "Chopped whites in cream sauce on toast, yolks riced over like goldenrod.", [I("hard-cooked eggs", 4, "", "Dairy & Eggs"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("milk", 1.5, "cups", "Dairy & Eggs"), I("toast", 6, "slices", "Bakery"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Peel the hard-cooked eggs. Chop the whites. Put the yolks through a strainer or ricer and keep them separate.", "Melt the butter, add the flour, and cook 2 minutes. Whisk in the milk until you have a smooth sauce, 4 minutes. Salt.", "Fold the chopped whites into the sauce. Heat 1 minute.", "Toast the bread. Spoon the creamed whites over the toast.", "Rice the yolks over the top so it looks like goldenrod. Dust with paprika. Serve at once."], farmer, { cal: 280, protein: 14, carbs: 22, fat: 14 }),
  x("ar-ff-welsh-rarebit", "Welsh rarebit", "American", ["vintage", "era-1910s", "book-farmer", "vegetarian", "quick"], "veg", "toast", 15, "Cheese melted with ale or milk, mustard, a dash of cayenne. Over toast.", [I("cheese", 2, "cups", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("milk or ale", 0.5, "cups", "Dairy & Eggs"), I("egg", 1, "", "Dairy & Eggs"), I("mustard", 0.5, "tsp", "Herbs & Spices"), I("toast", 6, "slices", "Bakery")], ["Melt the butter in a chafing dish or saucepan over low heat. Add the grated cheese and stir until it begins to melt.", "Pour in the milk or ale a little at a time, stirring, until the mix is smooth.", "Beat the egg. Stir it in with the mustard, salt, and a pinch of cayenne.", "Cook 1 minute more, stirring, until the rarebit is creamy. Do not let it boil.", "Pour over hot toast. Serve at once while it is still flowing."], farmer, { cal: 340, protein: 16, carbs: 18, fat: 22 }),
  x("ar-ff-boston-baked-beans", "Boston baked beans", "American", ["vintage", "era-1910s", "book-farmer", "old-school"], "pork", "bowl", 480, "Pea beans, salt pork, molasses. Saturday night, Sunday breakfast.", [I("pea beans", 4, "cups", "Pantry"), I("salt pork", 0.75, "lb", "Meat & Seafood"), I("molasses", 0.5, "cups", "Pantry"), I("sugar", 2, "tbsp", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices")], ["Soak the beans in cold water overnight. Drain. Cover with fresh water and parboil until the skins blow when you blow on a bean, about 20 minutes. Drain.", "Heat the oven to 250°F. Score the salt pork. Put the beans in a bean pot with the molasses, sugar, mustard, and salt.", "Bury the pork in the beans, rind up. Add boiling water to cover.", "Cover the pot. Bake 6–8 hours, adding boiling water if they dry, until the beans are tender and the liquor is thick and dark.", "Uncover the last hour if you want a brown top. Serve hot, Saturday night or Sunday morning."], farmer, { cal: 360, protein: 16, carbs: 48, fat: 12 }),
  x("ar-ff-spider-corn-cake", "Spider corn cake", "American", ["vintage", "era-1910s", "book-farmer", "breakfast", "baking", "vegetarian"], "veg", "skillet", 35, "Cornmeal batter in a hot spider, a streak of sour milk down the middle.", [I("cornmeal", 1.33, "cups", "Pantry"), I("flour", 0.33, "cups", "Pantry"), I("sugar", 3, "tbsp", "Pantry"), I("sour milk", 1.25, "cups", "Dairy & Eggs"), I("sweet milk", 0.75, "cups", "Dairy & Eggs"), I("egg", 1, "", "Dairy & Eggs")], ["Heat the oven to 400°F. Put a spider or 10-inch cast-iron skillet in the oven with a spoon of butter until the pan is hot.", "Stir the cornmeal, flour, sugar, and ½ teaspoon salt together.", "Beat the egg with the sour milk and 1 tablespoon melted butter. Stir into the dry mix.", "Pour the batter into the hot spider. Pour the sweet milk over the top in a streak — do not stir it in.", "Bake 25 minutes, until the edges are brown and a custard line runs through the middle. Cut in wedges. Serve hot."], farmer, { cal: 260, protein: 7, carbs: 38, fat: 8 }),
  x("ar-ff-chocolate-fudge", "Chocolate fudge", "American", ["vintage", "era-1910s", "book-farmer", "dessert", "cookies", "vegetarian"], "veg", "dessert", 30, "Sugar, milk, chocolate, butter. Beat until it begins to grain, pour, cut.", [I("sugar", 2, "cups", "Pantry"), I("milk", 0.67, "cups", "Dairy & Eggs"), I("unsweetened chocolate", 2, "oz", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("vanilla", 1, "tsp", "Pantry")], ["Butter a shallow pan. Put the sugar, milk, and chopped chocolate in a saucepan.", "Boil, stirring until the sugar dissolves, then cook without stirring to the soft-ball stage, 234°F, about 8 minutes.", "Take off the heat. Add the butter and vanilla. Do not stir yet. Cool until the pan is just warm, about 10 minutes.", "Beat until the fudge thickens and begins to grain, 3–5 minutes. Pour into the pan.", "When it is just set, cut into squares. This is candy, not a cake, and it is not baked."], farmer, { cal: 160, protein: 1, carbs: 28, fat: 5 }),
  x("ar-mf-jumberlie", "Jumberlie à la Creole", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "old-school"], "chicken", "bowl", 60, "Abby Fisher's jambalaya: rice, chicken or shrimp, tomato, pepper. San Francisco, 1881.", [I("rice", 2, "cups", "Pantry"), I("chicken", 1, "lb", "Meat & Seafood"), I("tomatoes", 4, "", "Produce"), I("onion", 1, "", "Produce"), I("green pepper", 1, "", "Produce"), I("ham", 0.25, "lb", "Meat & Seafood")], ["Cut the chicken and ham into pieces. Chop the onion and the green pepper.", "Fry the onion, pepper, ham, and chicken in a little fat 8 minutes, until they take color.", "Add the chopped tomatoes, the rice, salt, cayenne, and water to cover by ½ inch.", "Cover the pot tightly. Cook over low heat 25 minutes, without stirring, until the rice is steam-tender and the liquid is gone.", "Rest 5 minutes with the lid on. Fluff. Serve from the pot. This is Fisher's jumberlie, not a soup."], fisher, { cal: 420, protein: 28, carbs: 48, fat: 12 }),
  x("ar-mf-ochra-gumbo", "Ochra gumbo", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "soup", "old-school"], "beef", "soup", 90, "Mrs. Fisher's okra gumbo with beef and tomato. A long, quiet stew.", [I("okra", 2, "lb", "Produce"), I("beef", 1.5, "lb", "Meat & Seafood"), I("tomatoes", 4, "", "Produce"), I("onion", 1, "", "Produce"), I("green pepper", 1, "", "Produce"), I("flour", 2, "tbsp", "Pantry")], ["Cut the beef into cubes. Brown it in a heavy pot 8 minutes. Sprinkle the flour and stir 1 minute.", "Add the chopped onion and green pepper. Cook 4 minutes. Add the chopped tomatoes and the sliced okra.", "Pour in water to cover. Salt and pepper.", "Simmer 1½ hours, until the beef is tender and the okra silk has thickened the pot. Do not rush it.", "Serve in bowls over boiled rice. This is gumbo, not a fried dish."], fisher, { cal: 340, protein: 28, carbs: 18, fat: 16 }),
  x("ar-mf-sweet-potato-pie", "Sweet potato pie", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "dessert", "baking"], "veg", "dessert", 70, "Boiled sweets, butter, sugar, spice, a paste crust. Her San Francisco pie.", [I("sweet potatoes", 3, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("sugar", 0.75, "cups", "Pantry"), I("eggs", 3, "", "Dairy & Eggs"), I("milk", 0.5, "cups", "Dairy & Eggs"), I("pie crust", 1, "", "Bakery")], ["Boil the sweet potatoes in their skins until tender, 25 minutes. Drain, peel, and mash them smooth.", "Heat the oven to 375°F. Lay the crust in a pie tin.", "Beat the butter, sugar, eggs, and milk into the warm potato. Add nutmeg and cinnamon.", "Pour the sweet-potato filling into the crust.", "Bake 40 minutes, until the center is set and a knife comes out clean. Cool before slicing."], fisher, { cal: 380, protein: 7, carbs: 52, fat: 16 }),
  x("ar-mf-corn-bread", "Mrs. Fisher's corn bread", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "baking", "vegetarian"], "veg", "bowl", 35, "White cornmeal, buttermilk, a hot pan. Breakfast bread from 1881.", [I("white cornmeal", 2, "cups", "Pantry"), I("buttermilk", 2, "cups", "Dairy & Eggs"), I("eggs", 2, "", "Dairy & Eggs"), I("lard or butter", 2, "tbsp", "Dairy & Eggs"), I("soda", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 400°F. Put a greased pan in the oven to heat.", "Beat the eggs. Stir in the cornmeal, salt, and melted fat.", "Dissolve the soda in the buttermilk. Pour into the meal and beat until the batter is even.", "Pour into the hot pan. It should sizzle.", "Bake 25 minutes, until the top is gold and a toothpick comes out clean. Serve hot from the pan."], fisher, { cal: 240, protein: 7, carbs: 34, fat: 8 }),
  x("ar-mf-fried-chicken", "Mrs. Fisher's fried chicken", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "old-school"], "chicken", "skillet", 40, "Jointed chicken, salted, floured, fried in lard. The 1881 method.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 1, "cups", "Pantry"), I("lard", 1, "cups", "Pantry"), I("salt", 2, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices")], ["Joint the chicken into serving pieces. Pat dry. Salt and pepper both sides.", "Dredge each piece in flour, shaking off the extra.", "Heat the lard in a deep skillet until a pinch of flour sizzles at once, about 350°F.", "Fry the chicken without crowding, 8–10 minutes a side, until the crust is deep gold and the joints run clear. Turn only once.", "Drain on paper. Serve hot. This is fried in lard, not baked."], fisher, { cal: 480, protein: 36, carbs: 12, fat: 30 }),
  x("ar-mf-ginger-cookies", "Mrs. Fisher's ginger cookies", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "cookies", "baking", "dessert", "vegetarian"], "veg", "dessert", 30, "Molasses ginger cakes, rolled thin, cut, baked quick.", [I("molasses", 1, "cups", "Pantry"), I("sugar", 0.5, "cups", "Pantry"), I("lard or butter", 0.5, "cups", "Dairy & Eggs"), I("flour", 4, "cups", "Pantry"), I("ginger", 2, "tbsp", "Herbs & Spices"), I("soda", 1, "tsp", "Pantry")], ["Heat the oven to 375°F. Warm the molasses, fat, and sugar together until the fat melts. Cool until just warm.", "Stir in the ginger and the soda dissolved in a spoon of water.", "Add flour until you have a dough you can roll. Chill 15 minutes if it is sticky.", "Roll thin on a floured board. Cut into rounds.", "Bake 8 minutes, until the edges are set. Cool on the sheet. They crisp as they cool."], fisher, { cal: 120, protein: 2, carbs: 20, fat: 4 }),
  x("ar-mf-chow-chow", "Mrs. Fisher's chow-chow", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "sauce", "vegetarian", "vegan"], "veg", "bowl", 180, "Chopped pickle relish: cauliflower, cucumber, onion, mustard, vinegar.", [I("green tomatoes", 4, "lb", "Produce"), I("cucumbers", 6, "", "Produce"), I("onions", 6, "", "Produce"), I("cauliflower", 1, "head", "Produce"), I("mustard", 0.5, "cups", "Herbs & Spices"), I("vinegar", 6, "cups", "Pantry")], ["Chop the green tomatoes, cucumbers, onions, and cauliflower. Salt them in a crock overnight. Drain well in the morning.", "Boil the vinegar with the mustard, a spoon of turmeric, and 1 cup sugar 5 minutes.", "Pour the hot vinegar over the drained vegetables in a preserving kettle.", "Simmer until the vegetables are hot through but not mushy, about 15 minutes.", "Jar while hot. Cool. Serve as a relish with meats. This is a pickle, not a cooked supper."], fisher, { cal: 40, protein: 1, carbs: 8, fat: 0 }),
];
