import { I, dish } from "./catalog-kit";
import type { Recipe, RecipeSource } from "./types";

const ww1: RecipeSource = {
  book: "Foods That Will Win the War and How to Cook Them",
  author: "C. Houston Goudiss & Alberta M. Goudiss",
  year: 1918,
  era: "1910s",
  archiveId: "foodsthatwillwin00goud",
  credit:
    "C. Houston Goudiss and Alberta M. Goudiss, Foods That Will Win the War and How to Cook Them (1918). Public domain.",
};

const ww2: RecipeSource = {
  book: "National Wartime Nutrition Guide",
  author: "USDA",
  year: 1943,
  era: "1940s",
  archiveId: "nationalwartimen00unit",
  credit:
    "United States Department of Agriculture, National Wartime Nutrition Guide (1943). Public domain U.S. government work.",
};

function w(
  id: string,
  name: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: RecipeSource,
  nutrition: Recipe["nutrition"],
): Recipe {
  return dish({
    id,
    name,
    cuisine: "American",
    description,
    minutes,
    protein,
    plate,
    tags: Array.from(new Set(["vintage", "wartime", "old-school", ...tags])),
    ingredients,
    steps,
    nutrition,
    source,
  });
}

export const WARTIME_RECIPES: Recipe[] = [
  w(
    "vh-ww2-chipped-beef",
    "Creamed chipped beef",
    ["era-1940s", "budget", "quick"],
    "beef",
    "toast",
    20,
    "Dried beef in a white sauce on toast. The mess-hall plate of the 1940s.",
    [
      I("dried beef", 8, "oz", "Meat & Seafood"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
      I("white toast", 8, "slices", "Bakery"),
    ],
    [
      "Rinse the dried beef in hot water for 30 seconds to pull some of the salt, then drain and tear it into bite-size shreds.",
      "Melt the butter in a skillet over medium heat. Scatter the flour over the butter and cook 2 minutes, stirring, without letting it brown.",
      "Pour in the milk slowly, stirring the whole time, until the sauce is smooth and thick enough to coat a spoon, 4–5 minutes.",
      "Stir in the shredded beef. Grind black pepper over. Taste before you add salt — the beef is already salty.",
      "Toast the bread. Spoon the creamed beef over the toast and serve at once while the sauce is hot.",
    ],
    ww2,
    { cal: 390, protein: 22, carbs: 28, fat: 20 },
  ),
  w(
    "vh-ww2-pea-soup",
    "Split pea soup",
    ["era-1940s", "budget", "soup"],
    "pork",
    "soup",
    90,
    "Dried peas, a ham bone, onion. A pot that stretches a little meat a long way.",
    [
      I("dried split peas", 1, "lb", "Pantry"),
      I("ham bone or ham hock", 1, "", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bay leaf", 1, "", "Herbs & Spices"),
    ],
    [
      "Rinse the split peas. Put them in a pot with 8 cups of water and the ham bone.",
      "Bring to a boil, skim the foam, then add the chopped onion, carrot, celery, and bay leaf.",
      "Turn the heat to low. Simmer uncovered 75 minutes, stirring now and then so the peas do not stick, until they fall apart.",
      "Lift out the bone. Pull any meat off, chop it, and return it to the pot. Discard the bone and the bay leaf.",
      "Salt and pepper. If it is thicker than you like, add a splash of water. Ladle into bowls and serve hot.",
    ],
    ww2,
    { cal: 320, protein: 22, carbs: 42, fat: 6 },
  ),
  w(
    "vh-ww2-nut-loaf",
    "Wartime nut loaf",
    ["era-1940s", "vegetarian", "budget"],
    "veg",
    "roast",
    60,
    "Walnuts, crumbs, onion, and egg baked like a meat loaf. Meatless Monday in a pan.",
    [
      I("walnuts", 1.5, "cups", "Pantry"),
      I("bread crumbs", 1.5, "cups", "Bakery"),
      I("onion", 1, "", "Produce"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
      I("sage", 1, "tsp", "Herbs & Spices"),
    ],
    [
      "Heat the oven to 350°F. Chop the walnuts and the onion fine.",
      "In a bowl, mix the walnuts, crumbs, onion, sage, salt, and pepper.",
      "Beat the eggs with the milk. Pour over the dry mix and stir until it holds together like a meat loaf.",
      "Pack into a greased loaf pan. Bake 45 minutes, until the top is brown and a knife in the center comes out clean.",
      "Rest 10 minutes. Slice and serve with gravy or tomato sauce.",
    ],
    ww2,
    { cal: 380, protein: 12, carbs: 28, fat: 26 },
  ),
  w(
    "vh-ww2-succotash",
    "Victory succotash",
    ["era-1940s", "vegetarian", "gluten-free", "budget"],
    "veg",
    "skillet",
    25,
    "Corn and lima beans from the garden plot. Butter, a little milk, salt.",
    [
      I("lima beans", 2, "cups", "Produce"),
      I("corn kernels", 2, "cups", "Produce"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
      I("milk", 0.5, "cup", "Dairy & Eggs"),
      I("salt", 1, "tsp", "Herbs & Spices"),
      I("black pepper", 0.25, "tsp", "Herbs & Spices"),
    ],
    [
      "Simmer the lima beans in salted water until just tender, 12–15 minutes. Drain.",
      "Melt the butter in a skillet over medium heat. Add the corn and cook 4 minutes, stirring.",
      "Add the drained lima beans and the milk. Simmer 5 minutes, until the milk thickens a little around the vegetables.",
      "Salt and pepper. Taste. The dish should be creamy, not soupy.",
      "Serve hot as a side, or as a meatless plate with bread.",
    ],
    ww2,
    { cal: 220, protein: 8, carbs: 32, fat: 8 },
  ),
  w(
    "vh-ww1-oatmeal-cookies",
    "War oatmeal cookies",
    ["era-1910s", "dessert", "baking", "vegetarian", "budget"],
    "veg",
    "dessert",
    30,
    "Oats stretch the wheat. Molasses stands in for some of the sugar.",
    [
      I("rolled oats", 2, "cups", "Pantry"),
      I("flour", 1, "cup", "Pantry"),
      I("molasses", 0.5, "cup", "Pantry"),
      I("shortening or butter", 0.5, "cup", "Dairy & Eggs"),
      I("brown sugar", 0.5, "cup", "Pantry"),
      I("egg", 1, "", "Dairy & Eggs"),
    ],
    [
      "Heat the oven to 375°F. Cream the shortening with the brown sugar until even, 2 minutes.",
      "Beat in the egg and the molasses until the batter is even.",
      "Stir in the flour, oats, 1 teaspoon baking soda, and ½ teaspoon salt until no dry pockets of flour remain.",
      "Drop by tablespoons onto a greased sheet, 2 inches apart. Flatten each cookie slightly with a wet fork.",
      "Bake 10–12 minutes, until the edges are brown. Cool on the sheet 2 minutes, then move to a rack.",
    ],
    ww1,
    { cal: 140, protein: 2, carbs: 20, fat: 6 },
  ),
  w(
    "vh-ww2-cornmeal-mush",
    "Fried cornmeal mush",
    ["era-1940s", "breakfast", "vegetarian", "budget", "gluten-free"],
    "veg",
    "skillet",
    40,
    "Cornmeal cooked in salted water, chilled, sliced, and fried. Breakfast when wheat is short.",
    [
      I("cornmeal", 1, "cup", "Pantry"),
      I("water", 4, "cups", "Other"),
      I("salt", 1, "tsp", "Herbs & Spices"),
      I("butter or bacon fat", 3, "tbsp", "Dairy & Eggs"),
      I("maple syrup or molasses", 0.25, "cup", "Pantry"),
    ],
    [
      "Bring 3 cups of the water and the salt to a boil. Stir the cornmeal into the remaining cup of cold water until smooth.",
      "Pour the wet meal into the boiling water, stirring. Cook over low heat 15 minutes, until thick enough that a spoon stands.",
      "Pack into a greased loaf pan. Chill at least 2 hours, until firm enough to slice.",
      "Cut into ½-inch slices. Fry in butter or bacon fat over medium heat 4 minutes a side, until a brown crust forms.",
      "Serve the fried mush hot with molasses or maple syrup.",
    ],
    ww2,
    { cal: 240, protein: 4, carbs: 36, fat: 10 },
  ),
  w(
    "vh-ww2-potato-soup",
    "Wartime potato soup",
    ["era-1940s", "vegetarian", "budget", "soup", "gluten-free"],
    "veg",
    "soup",
    35,
    "Potatoes, onion, milk. The cheapest hot bowl in the house.",
    [
      I("potatoes", 2, "lb", "Produce"),
      I("onion", 1, "", "Produce"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
      I("milk", 3, "cups", "Dairy & Eggs"),
      I("parsley", 2, "tbsp", "Produce"),
      I("salt", 1, "tsp", "Herbs & Spices"),
    ],
    [
      "Peel and cube the potatoes. Chop the onion.",
      "Melt the butter in a pot over medium heat. Cook the onion 5 minutes, until soft, without browning.",
      "Add the potatoes and water to just cover. Simmer 15 minutes, until the potatoes mash easily against the side of the pot.",
      "Mash about half the potatoes in the pot so the soup thickens. Pour in the milk. Heat until steaming — do not boil.",
      "Salt and pepper. Stir in the parsley. Ladle into bowls and serve hot.",
    ],
    ww2,
    { cal: 260, protein: 8, carbs: 38, fat: 8 },
  ),
  w(
    "vh-ww1-carrot-marmalade",
    "Carrot marmalade",
    ["era-1910s", "vegetarian", "vegan", "plant-based", "budget", "sauce"],
    "veg",
    "bowl",
    50,
    "Carrots stand in for scarce citrus. A wartime spread for bread.",
    [
      I("carrots", 4, "cups", "Produce"),
      I("sugar", 3, "cups", "Pantry"),
      I("lemon", 2, "", "Produce"),
      I("water", 1.5, "cups", "Other"),
      I("ginger", 0.5, "tsp", "Herbs & Spices"),
    ],
    [
      "Peel and grate the carrots. Juice the lemons and slice the peel into thin strips.",
      "Put carrots, lemon juice, peel, and water in a saucepan. Simmer 20 minutes, until the carrot is very soft.",
      "Stir in the sugar and ginger. Boil, stirring, until the mixture sheets off a spoon, 15–20 minutes.",
      "Take off the heat. Pour into clean jars and cool.",
      "Cover the jars and keep them in the icebox. Spread the marmalade on bread or biscuits.",
    ],
    ww1,
    { cal: 80, protein: 0, carbs: 20, fat: 0 },
  ),
  w(
    "vh-ww1-wheatless-muffins",
    "Wheatless corn muffins",
    ["era-1910s", "breakfast", "baking", "vegetarian", "budget", "gluten-free"],
    "veg",
    "bowl",
    30,
    "Cornmeal and rye or all cornmeal. Goudiss wheat-saving muffins.",
    [
      I("cornmeal", 1.5, "cups", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("milk", 1.5, "cups", "Dairy & Eggs"),
      I("molasses", 2, "tbsp", "Pantry"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
      I("baking powder", 3, "tsp", "Pantry"),
    ],
    [
      "Heat the oven to 400°F. Grease a 12-cup muffin tin.",
      "Stir the cornmeal, baking powder, and ½ teaspoon salt together.",
      "Beat the eggs. Add the milk, molasses, and melted butter.",
      "Pour the wet into the dry and stir just until combined — do not beat. Fill the cups two-thirds full.",
      "Bake 18–20 minutes, until the tops are gold and a toothpick comes out clean. Serve warm.",
    ],
    ww1,
    { cal: 160, protein: 5, carbs: 22, fat: 6 },
  ),
  w(
    "vh-ww2-cabbage-pork",
    "Cabbage with salt pork",
    ["era-1940s", "budget", "gluten-free"],
    "pork",
    "skillet",
    40,
    "A little salt pork flavors a whole head of cabbage. Stretching meat the USDA way.",
    [
      I("green cabbage", 1, "head", "Produce"),
      I("salt pork", 4, "oz", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
      I("vinegar", 1, "tbsp", "Pantry"),
    ],
    [
      "Cut the salt pork into small dice. Cook it in a wide pot over medium heat 8 minutes, until the fat renders and the bits are crisp.",
      "Add the sliced onion and cook 4 minutes, until soft.",
      "Core the cabbage and cut it into wedges. Add to the pot with ½ cup water.",
      "Cover and cook 20 minutes, stirring once, until the cabbage is tender and silky.",
      "Pepper the cabbage. Splash with vinegar. Serve hot with the pork bits on top.",
    ],
    ww2,
    { cal: 280, protein: 10, carbs: 14, fat: 20 },
  ),
  w(
    "vh-ww2-stuffed-potato",
    "Baked stuffed potatoes",
    ["era-1940s", "vegetarian", "budget"],
    "veg",
    "roast",
    70,
    "A baked potato, scooped, mixed with milk and cheese, returned to the shell. A whole supper.",
    [
      I("russet potatoes", 4, "", "Produce"),
      I("milk", 0.5, "cup", "Dairy & Eggs"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
      I("cheddar", 0.5, "cup", "Dairy & Eggs"),
      I("chives or scallions", 2, "tbsp", "Produce"),
      I("salt", 1, "tsp", "Herbs & Spices"),
    ],
    [
      "Heat the oven to 400°F. Scrub the potatoes, prick them, and bake 50 minutes, until they give when squeezed.",
      "Cut each potato in half. Scoop the flesh into a bowl, leaving a ¼-inch shell.",
      "Mash the flesh with the milk, butter, salt, and most of the cheese until fluffy.",
      "Spoon back into the shells. Sprinkle the remaining cheese on top.",
      "Bake 12 minutes more, until the cheese melts. Scatter chives and serve hot.",
    ],
    ww2,
    { cal: 320, protein: 10, carbs: 44, fat: 12 },
  ),
  w(
    "vh-ww2-applesauce-cake",
    "Applesauce cake",
    ["era-1940s", "dessert", "baking", "vegetarian", "budget"],
    "veg",
    "dessert",
    55,
    "Applesauce replaces some of the fat and sugar. A loaf for the lunch pail.",
    [
      I("applesauce", 1.5, "cups", "Pantry"),
      I("flour", 2, "cups", "Pantry"),
      I("sugar", 0.75, "cup", "Pantry"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("cinnamon", 1, "tsp", "Herbs & Spices"),
    ],
    [
      "Heat the oven to 350°F. Grease a loaf pan.",
      "Cream the butter and sugar. Beat in the egg, then the applesauce.",
      "Stir in the flour, 1 teaspoon baking soda, cinnamon, and ½ teaspoon salt until the batter is even.",
      "Scrape into the pan. Bake 40–45 minutes, until a toothpick in the center comes out clean.",
      "Cool 10 minutes in the pan, then turn out. Slice when cool.",
    ],
    ww2,
    { cal: 220, protein: 3, carbs: 38, fat: 7 },
  ),
  w(
    "vh-ww2-navy-bean",
    "Navy bean soup",
    ["era-1940s", "budget", "soup"],
    "pork",
    "soup",
    120,
    "The Senate soup of the war years: navy beans, ham, onion, celery.",
    [
      I("dried navy beans", 1, "lb", "Pantry"),
      I("ham hock", 1, "", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("carrot", 1, "", "Produce"),
      I("garlic", 2, "cloves", "Produce"),
    ],
    [
      "Soak the beans in water overnight, or boil 2 minutes and sit 1 hour. Drain.",
      "Put the beans, ham hock, and 8 cups water in a pot. Bring to a boil and skim.",
      "Add the chopped onion, celery, carrot, and garlic. Simmer 90 minutes, until the beans are soft.",
      "Lift out the hock. Chop the meat and return it. Mash a cup of beans against the pot to thicken.",
      "Salt and pepper the beans. Serve them hot with bread.",
    ],
    ww2,
    { cal: 340, protein: 22, carbs: 44, fat: 8 },
  ),
  w(
    "vh-ww1-rice-pudding",
    "Wartime rice pudding",
    ["era-1910s", "dessert", "vegetarian", "budget", "gluten-free"],
    "veg",
    "dessert",
    70,
    "A little rice, a lot of milk, a spoon of sugar. Baked until the top skins.",
    [
      I("rice", 0.5, "cup", "Pantry"),
      I("milk", 4, "cups", "Dairy & Eggs"),
      I("sugar", 0.33, "cup", "Pantry"),
      I("butter", 1, "tbsp", "Dairy & Eggs"),
      I("vanilla", 1, "tsp", "Pantry"),
      I("nutmeg", 0.25, "tsp", "Herbs & Spices"),
    ],
    [
      "Heat the oven to 325°F. Butter a baking dish.",
      "Stir the rice, milk, sugar, vanilla, and a pinch of salt in the dish.",
      "Dot with butter and grate nutmeg over the top.",
      "Bake 60 minutes, stirring once at 20 minutes and once at 40, until the rice is tender and a skin has formed.",
      "Serve the rice pudding warm from the dish, or cold the next day. A spoon of jam on top if you have it.",
    ],
    ww1,
    { cal: 210, protein: 6, carbs: 34, fat: 6 },
  ),
  w(
    "vh-ww2-liver-onions",
    "Liver and onions",
    ["era-1940s", "budget", "gluten-free"],
    "beef",
    "skillet",
    25,
    "Calf or beef liver, floured, fried fast, onions cooked in the same pan. Organ meat when steak was rationed.",
    [
      I("beef liver", 1, "lb", "Meat & Seafood"),
      I("onions", 2, "", "Produce"),
      I("flour", 0.33, "cup", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("salt", 1, "tsp", "Herbs & Spices"),
      I("black pepper", 0.5, "tsp", "Herbs & Spices"),
    ],
    [
      "Slice the onions. Cook them in 1 tablespoon of the butter over medium heat 12 minutes, until soft and gold. Set aside.",
      "Pat the liver dry. Salt, pepper, and dredge in flour, shaking off the extra.",
      "Raise the heat to medium-high. Add the remaining butter. Fry the liver 2–3 minutes a side, until just pink in the center — do not overcook.",
      "Return the onions to the pan for 30 seconds to warm.",
      "Plate the liver with the onions on top. Serve at once.",
    ],
    ww2,
    { cal: 360, protein: 32, carbs: 14, fat: 18 },
  ),
  w(
    "vh-ww2-cottage-salad",
    "Cottage cheese fruit salad",
    ["era-1940s", "vegetarian", "gluten-free", "salad", "quick"],
    "veg",
    "green",
    10,
    "Cottage cheese, canned fruit, lettuce. A lunch that used the dairy ration well.",
    [
      I("cottage cheese", 2, "cups", "Dairy & Eggs"),
      I("canned peaches", 1, "cup", "Pantry"),
      I("lettuce", 1, "head", "Produce"),
      I("mayonnaise", 2, "tbsp", "Pantry"),
      I("paprika", 0.25, "tsp", "Herbs & Spices"),
    ],
    [
      "Drain the peaches and cut them into bite-size pieces.",
      "Wash the lettuce and arrange leaves on four plates.",
      "Spoon cottage cheese onto the lettuce. Nest the peaches beside it.",
      "Add a small spoon of mayonnaise if you want it. Dust with paprika.",
      "Serve cold the same day. Do not mix it into a batter or bake it.",
    ],
    ww2,
    { cal: 180, protein: 14, carbs: 14, fat: 8 },
  ),
];
