import type { Recipe } from "./types";

const I = (
  name: string,
  qty: number,
  unit: string,
  aisle: Recipe["ingredients"][number]["aisle"],
) => ({ name, qty, unit, aisle });

function dish(
  partial: Omit<Recipe, "nutrition" | "pack" | "servings"> & {
    nutrition?: Recipe["nutrition"];
    pack?: Recipe["pack"];
    servings?: number;
  },
): Recipe {
  return {
    pack: "free",
    servings: 4,
    nutrition: { cal: 420, protein: 22, carbs: 38, fat: 16 },
    ...partial,
  };
}

export const WORLD_RECIPES: Recipe[] = [
  dish({
    id: "sloppy-joes",
    name: "Sloppy joes",
    description: "Sweet-savory saucy beef on a toasted bun. Cafeteria legend, still a weeknight win.",
    minutes: 25,
    protein: "beef",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "american", "quick", "budget"],
    aliases: ["sloppy joe", "loose meat", "barbecue beef sandwich"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("ketchup", 0.75, "cup", "Pantry"),
      I("brown sugar", 1, "tbsp", "Pantry"),
      I("Worcestershire", 1, "tbsp", "Pantry"),
      I("hamburger buns", 4, "", "Bakery"),
    ],
    steps: [
      "Brown beef with chopped onion. Drain extra fat.",
      "Stir in ketchup, brown sugar, and Worcestershire. Simmer 10 minutes.",
      "Spoon onto toasted buns.",
    ],
  }),
  dish({
    id: "chicken-dumplings",
    name: "Chicken and dumplings",
    description: "Stewed chicken under fluffy drop dumplings. Grandmother energy.",
    minutes: 70,
    protein: "chicken",
    plate: "soup",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["chicken n dumplings", "chicken & dumplings", "dumpling stew"],
    ingredients: [
      I("bone-in chicken thighs", 2, "lb", "Meat & Seafood"),
      I("carrot", 3, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("onion", 1, "", "Produce"),
      I("flour", 1.5, "cups", "Pantry"),
      I("baking powder", 2, "tsp", "Pantry"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
      I("chicken broth", 6, "cups", "Pantry"),
    ],
    steps: [
      "Simmer chicken with onion, carrot, and celery in broth until tender. Shred the meat.",
      "Mix flour, baking powder, salt, and milk into a thick batter.",
      "Drop spoonfuls on the simmering stew. Cover 15 minutes — do not peek.",
    ],
  }),
  dish({
    id: "tater-tot-hotdish",
    name: "Tater tot hotdish",
    description: "Midwest church-basement classic: beef, cream soup, peas, tots.",
    minutes: 55,
    protein: "beef",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "american", "casserole", "budget"],
    aliases: ["hotdish", "tater tot casserole", "minnesota hotdish"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("frozen mixed vegetables", 2, "cups", "Frozen"),
      I("cream of mushroom soup", 1, "can", "Pantry"),
      I("frozen tater tots", 1, "bag", "Frozen"),
      I("onion", 1, "", "Produce"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 375°F. Brown the 1 pound of ground beef with the chopped onion in the 2 tablespoons of oil, 6–8 minutes, until no pink remains. Drain the fat.",
      "Stir in the 1 can of cream of mushroom soup, half a can of water, and the 2 cups of frozen mixed vegetables. Season.",
      "Scrape into a baking dish and level it.",
      "Stand the 1 bag of frozen tater tots over the top in tight rows — laid flat and packed, they crisp instead of steaming.",
      "Bake 35–40 minutes, until the tots are gold, then scatter the 1 cup of cheddar over and give it 5 minutes more.",
    ],
  }),
  dish({
    id: "salisbury-steak",
    name: "Salisbury steak",
    description: "Seasoned beef patties in onion gravy. TV-dinner glow, homemade.",
    minutes: 40,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["salisbury", "hamburger steak", "onion gravy patties"],
    ingredients: [
      I("ground beef", 1.5, "lb", "Meat & Seafood"),
      I("onion", 2, "", "Produce"),
      I("breadcrumbs", 0.5, "cup", "Pantry"),
      I("egg", 1, "", "Dairy & Eggs"),
      I("beef broth", 2, "cups", "Pantry"),
      I("Worcestershire", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Mix beef with breadcrumbs, egg, and Worcestershire. Shape oval patties and brown.",
      "Sauté onions, add broth, simmer patties in gravy 15 minutes.",
    ],
  }),
  dish({
    id: "swedish-meatballs",
    name: "Swedish meatballs",
    description: "Tiny meatballs in cream gravy. Ikea wishes it tasted like this.",
    minutes: 45,
    protein: "beef",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["swedish meatball", "köttbullar", "cream gravy meatballs"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("ground pork", 0.5, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("breadcrumbs", 0.5, "cup", "Pantry"),
      I("allspice", 0.5, "tsp", "Herbs & Spices"),
      I("beef broth", 2, "cups", "Pantry"),
      I("heavy cream", 0.5, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Mix the 1 pound of ground beef and the ½ pound of ground pork with the ½ cup of breadcrumbs, the finely grated onion, the ½ teaspoon of allspice, and salt. Work it just until it holds.",
      "Roll into small balls, about an inch across, with wet hands.",
      "Brown them in the 2 tablespoons of oil in a wide skillet, turning, 6–8 minutes, until coloured all over. Lift them out.",
      "Stir a spoon of flour into the fat, then whisk in the 2 cups of beef broth and simmer to a gravy. Stir in the ½ cup of heavy cream.",
      "Return the meatballs and simmer gently 10 minutes, until cooked through and the gravy clings. Serve with mash or lingonberry.",
    ],
  }),
  dish({
    id: "american-goulash",
    name: "American goulash",
    description: "One-pot elbow pasta, beef, and tomatoes. School-night old school.",
    minutes: 35,
    protein: "beef",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "american", "budget", "quick"],
    aliases: ["goulash", "american chop suey", "beefaroni", "chili mac"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("elbow macaroni", 12, "oz", "Pantry"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("garlic", 3, "cloves", "Produce"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Brown the 1 pound of ground beef in the 2 tablespoons of oil in a wide pot, breaking it up, until no pink remains. Drain the fat.",
      "Add the chopped onion and the 3 cloves of garlic and cook 4 minutes, until soft. Stir in the 1 teaspoon of paprika and cook 30 seconds.",
      "Add the 1 can of crushed tomatoes, the 1 teaspoon of salt, and 2 cups of water. Simmer 10 minutes.",
      "Tip in the 12 ounces of dry elbow macaroni and cook 10–12 minutes, stirring often so it does not catch, until tender and the sauce has thickened around it.",
      "Rest 5 minutes off the heat — it tightens as it sits — and serve.",
    ],
  }),
  dish({
    id: "scalloped-ham",
    name: "Ham and scalloped potatoes",
    description: "Sunday leftover ham tucked into creamy potatoes.",
    minutes: 80,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["scalloped potatoes and ham", "au gratin ham", "funeral potatoes"],
    ingredients: [
      I("potato", 3, "lb", "Produce"),
      I("cooked ham", 2, "cups", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 350°F. Melt the 3 tablespoons of butter, stir in the 3 tablespoons of flour, and cook 1 minute. Whisk in the 2 cups of milk a little at a time and simmer to a smooth sauce. Season well.",
      "Slice the 3 pounds of potato thin — a couple of millimetres, or they will not cook through — and slice the onion.",
      "Layer the potato, the 2 cups of chopped cooked ham, and the onion in a buttered dish, pouring some sauce over each layer.",
      "Cover with foil and bake 55 minutes, until a knife slides through the middle without resistance.",
      "Uncover, scatter the 1 cup of cheddar over, and bake 15 minutes more, until browned and bubbling.",
    ],
  }),
  dish({
    id: "stuffed-peppers",
    name: "Stuffed peppers",
    description: "Bell peppers packed with beef, rice, and tomato. 1970s table, forever.",
    minutes: 65,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american"],
    aliases: ["stuffed bell peppers", "pepper boats"],
    ingredients: [
      I("bell peppers", 4, "", "Produce"),
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("cooked rice", 1.5, "cups", "Pantry"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("cheddar", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Heat the oven to 375°F. Cut the tops off the 4 bell peppers and pull out the seeds and ribs.",
      "Brown the 1 pound of ground beef with the chopped onion in the 2 tablespoons of oil until no pink remains. Drain the fat and stir in the 1½ cups of cooked rice, half the 1 can of crushed tomatoes, and the 1 teaspoon of salt.",
      "Pack the filling into the peppers and stand them in a baking dish. Spoon the rest of the tomatoes around them and add a splash of water.",
      "Cover with foil and bake 40 minutes, until the peppers give when pressed.",
      "Uncover, scatter the 1 cup of cheddar over the tops, and bake 10 minutes more, until melted and browned.",
    ],
  }),
  dish({
    id: "stovetop-mac",
    name: "Stovetop mac and cheese",
    description: "A pot of elbows in sharp cheddar sauce. No box required.",
    minutes: 25,
    protein: "veg",
    plate: "pasta",
    cuisine: "Old school",
    tags: ["old-school", "american", "vegetarian", "quick", "budget"],
    aliases: ["mac n cheese", "macaroni and cheese", "mac & cheese", "homemade kraft"],
    ingredients: [
      I("elbow macaroni", 12, "oz", "Pantry"),
      I("sharp cheddar", 10, "oz", "Dairy & Eggs"),
      I("milk", 1.5, "cups", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 3, "tbsp", "Pantry"),
      I("mustard powder", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Bring a large pot of salted water to a boil. Cook the 12 ounces of elbow macaroni until just tender. Drain, saving a splash of the water.",
      "Melt the 3 tablespoons of butter in the same pot. Stir in the 3 tablespoons of flour and cook 1 minute. Whisk in the 1½ cups of milk until the sauce is smooth and thick.",
      "Take the pan off the heat. Stir in the 10 ounces of sharp cheddar and the ½ teaspoon of mustard powder until melted.",
      "Fold in the pasta. If the sauce is tight, loosen with a splash of the pasta water. Serve hot.",
    ],
  }),
  dish({
    id: "chicken-a-la-king",
    name: "Chicken à la king",
    description: "Creamed chicken with peppers and mushrooms on toast or rice.",
    minutes: 35,
    protein: "chicken",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "american", "comfort"],
    aliases: ["chicken a la king", "creamed chicken"],
    ingredients: [
      I("cooked chicken", 3, "cups", "Meat & Seafood"),
      I("mushrooms", 8, "oz", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("frozen peas", 1, "cup", "Frozen"),
      I("milk", 2, "cups", "Dairy & Eggs"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("flour", 4, "tbsp", "Pantry"),
      I("toast", 8, "slices", "Bakery"),
    ],
    steps: [
      "Melt the 4 tablespoons of butter in a skillet. Cook the 8 ounces of mushrooms and the chopped bell pepper until soft, 5 minutes.",
      "Stir in the 4 tablespoons of flour and cook 1 minute. Whisk in the 2 cups of milk until the sauce is smooth and thick.",
      "Add the 3 cups of cooked chicken and the 1 cup of frozen peas. Simmer 3–4 minutes, until everything is hot.",
      "Toast the 8 slices of toast. Spoon the chicken over the toast and serve at once.",
    ],
  }),
  dish({
    id: "pork-chops-apples",
    name: "Pork chops with applesauce",
    description: "Pan-seared chops and a warm cinnamon apple mash.",
    minutes: 30,
    protein: "pork",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "american", "quick"],
    aliases: ["pork chops and applesauce", "pork and apple"],
    ingredients: [
      I("pork chops", 4, "", "Meat & Seafood"),
      I("apples", 3, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cinnamon", 0.5, "tsp", "Herbs & Spices"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Pat the 4 pork chops dry and salt both sides with the 1 teaspoon of salt. Set a wide skillet over medium-high heat.",
      "Sear the chops 4–5 minutes a side, until browned and a thermometer in the thickest part reads 145°F. Move to a plate and rest 5 minutes — they carry on cooking.",
      "Melt the 2 tablespoons of butter in the same pan. Add the 3 sliced apples and the chopped onion with the ½ teaspoon of cinnamon.",
      "Cook 6–8 minutes, scraping up the browned bits, until the apples slump into a rough sauce.",
      "Spoon the apples over the chops with any juices from the plate and serve.",
    ],
  }),
  dish({
    id: "cabbage-rolls",
    name: "Cabbage rolls",
    description: "Beef and rice wrapped in cabbage, baked in tomato. Homemade hall-of-fame.",
    minutes: 110,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "comfort"],
    aliases: ["holubtsi", "golubtsi", "stuffed cabbage", "pigs in a blanket cabbage"],
    ingredients: [
      I("cabbage", 1, "head", "Produce"),
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("cooked rice", 1, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("crushed tomatoes", 2, "cans", "Pantry"),
    ],
    steps: [
      "Heat the oven to 325°F. Boil the whole head of cabbage 8 minutes. Pull off 12 large leaves and trim the thick rib so they roll.",
      "Mix the 1 pound of ground beef, the 1 cup of cooked rice, the chopped onion, salt, and pepper. Put 2 tablespoons in each leaf. Fold the sides in and roll.",
      "Lay the rolls in a dish. Pour the 2 cans of crushed tomatoes over.",
      "Cover and bake 90 minutes, until the leaves are silky and the filling is cooked through. Spoon the tomato over and serve.",
    ],
  }),
  dish({
    id: "classic-beef-stew",
    name: "Classic beef stew",
    description: "Chuck, potatoes, and carrots that fall apart if you give them time.",
    minutes: 150,
    protein: "beef",
    plate: "soup",
    cuisine: "Old school",
    tags: ["old-school", "american", "sunday"],
    aliases: ["beef stew", "irish stew beef", "pot of stew"],
    ingredients: [
      I("beef chuck", 2, "lb", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("beef broth", 4, "cups", "Pantry"),
      I("tomato paste", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Pat the 2 pounds of beef chuck dry and salt it. Set a heavy pot over medium-high heat.",
      "Brown the cubed chuck on all sides, 6–8 minutes. Add the chopped onion and the 2 tablespoons of tomato paste. Cook 1 minute.",
      "Pour in the 4 cups of beef broth. Simmer, partly covered, 90 minutes, until the beef starts to give.",
      "Add the 4 potatoes (chunked) and the 4 carrots. Cook until tender, 40 minutes more. Taste for salt and serve in warm bowls.",
    ],
  }),
  dish({
    id: "porcupine-meatballs",
    name: "Porcupine meatballs",
    description: "Rice-studded meatballs simmered in tomato. Kids named them, adults eat them.",
    minutes: 50,
    protein: "beef",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "american", "budget"],
    aliases: ["porcupine balls", "rice meatballs"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("uncooked rice", 0.5, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("tomato soup", 1, "can", "Pantry"),
      I("water", 1, "cup", "Other"),
    ],
    steps: [
      "Mix the 1 pound of ground beef with the ½ cup of uncooked rice, the finely chopped onion, and the 1 teaspoon of salt. The rice goes in raw — that is what makes the quills.",
      "Roll into 16 balls with wet hands.",
      "Brown them in the 2 tablespoons of oil in a wide lidded skillet, turning, until coloured all over.",
      "Stir the 1 can of tomato soup with the 1 cup of water and pour it around the meatballs, not over them.",
      "Cover and simmer very gently 40 minutes, until the rice has swelled and softened and the meatballs are cooked through. Add a splash of water if the sauce tightens too far.",
    ],
  }),
  dish({
    id: "tuna-melt",
    name: "Tuna melt",
    description: "Hot tuna salad under a blanket of cheddar. Lunch-counter forever.",
    minutes: 15,
    protein: "fish",
    plate: "toast",
    cuisine: "Old school",
    tags: ["old-school", "american", "quick"],
    aliases: ["tuna melt sandwich", "grilled tuna sandwich"],
    ingredients: [
      I("canned tuna", 2, "cans", "Pantry"),
      I("mayonnaise", 3, "tbsp", "Pantry"),
      I("celery", 1, "stalk", "Produce"),
      I("cheddar", 4, "slices", "Dairy & Eggs"),
      I("bread", 8, "slices", "Bakery"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Drain the canned tuna well and flake it into a bowl. Dice the celery fine and mix it in with the mayonnaise until the salad just holds together.",
      "Butter one side of each slice of bread. Lay four slices butter-side down, spread the tuna salad over them, and top each with a slice of cheddar and a second slice of bread, butter-side up.",
      "Griddle over medium heat 3–4 minutes a side, pressing lightly, until the bread is deep gold and the cheddar has run.",
      "Cut each sandwich in half on the diagonal and eat while the cheese is still molten.",
    ],
  }),
  dish({
    id: "corned-beef-hash",
    name: "Corned beef hash",
    description: "Crisp potatoes, chopped corned beef, a fried egg if you have one.",
    minutes: 30,
    protein: "beef",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "american", "breakfast"],
    aliases: ["hash", "canned hash homemade"],
    ingredients: [
      I("cooked corned beef", 2, "cups", "Meat & Seafood"),
      I("potato", 3, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("eggs", 4, "", "Dairy & Eggs"),
      I("butter", 2, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Dice the 3 potatoes and the onion. Set a wide skillet over medium-high heat with the 2 tablespoons of butter.",
      "Crisp the potato and onion, 8–10 minutes, pressing them into the pan so a crust forms.",
      "Add the 2 cups of chopped cooked corned beef. Press again and fry until the underside is crusty.",
      "Fry the 4 eggs in a second pan. Top each plate of hash with an egg and serve hot.",
    ],
  }),
  dish({
    id: "sunday-pot-roast",
    name: "Sunday pot roast",
    description: "Chuck roast, carrots, and potatoes in one pot. The house smells like home.",
    minutes: 210,
    protein: "beef",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "american", "sunday"],
    aliases: ["pot roast", "yankee pot roast", "chuck roast dinner"],
    ingredients: [
      I("beef chuck roast", 3, "lb", "Meat & Seafood"),
      I("potato", 6, "", "Produce"),
      I("carrot", 6, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("beef broth", 2, "cups", "Pantry"),
      I("tomato paste", 1, "tbsp", "Pantry"),
    ],
    steps: [
      "Heat the oven to 325°F. Pat the 3 pound chuck roast dry and season with the 1 teaspoon of salt. Brown it hard on all sides in the 2 tablespoons of oil in a heavy pot.",
      "Lift the roast out and soften the 2 sliced onions in the fat. Stir in the 1 tablespoon of tomato paste and cook a minute.",
      "Return the roast, pour in the 2 cups of beef broth, cover, and cook 2½ hours.",
      "Add the 6 potatoes and the 6 carrots in big chunks and cook 45 minutes more, until a fork twists in the beef with no resistance.",
      "Rest 15 minutes. Pull the beef into pieces rather than carving it — a pot roast this soft will not slice — and spoon the gravy over.",
    ],
  }),
  dish({
    id: "spaghetti-meatballs",
    name: "Spaghetti and meatballs",
    description: "Sunday sauce, fat meatballs, a mountain of spaghetti.",
    minutes: 75,
    protein: "beef",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["old-school", "italian", "comfort"],
    aliases: ["spag and balls", "spaghetti & meatballs", "meatball pasta"],
    ingredients: [
      I("ground beef", 1, "lb", "Meat & Seafood"),
      I("spaghetti", 1, "lb", "Pantry"),
      I("crushed tomatoes", 2, "cans", "Pantry"),
      I("garlic", 5, "cloves", "Produce"),
      I("breadcrumbs", 0.5, "cup", "Pantry"),
      I("parmesan", 2, "oz", "Dairy & Eggs"),
      I("fresh basil", 1, "bunch", "Produce"),
    ],
    steps: [
      "Mix the 1 pound of ground beef with the ½ cup of breadcrumbs, 2 of the minced garlic cloves, the 1 teaspoon of salt, and a splash of water. Roll into 16 balls.",
      "Brown them in the 2 tablespoons of oil in a wide pot, turning, until coloured all over. They finish in the sauce.",
      "Add the remaining 3 cloves of garlic for a minute, then the 2 cans of crushed tomatoes. Simmer gently 40 minutes, until the sauce is thick and the meatballs are cooked through.",
      "Boil the 1 pound of spaghetti until just shy of al dente, saving a cup of the water, and toss it through some of the sauce with a splash of that water.",
      "Plate the pasta with the meatballs and the rest of the sauce. Tear the 1 bunch of fresh basil over and shower with the 2 ounces of parmesan.",
    ],
  }),
  dish({
    id: "nl-fish-cakes",
    name: "Newfoundland fish cakes",
    description: "Salt cod and potato patties fried gold. Breakfast, supper, leftover scoff.",
    minutes: 40,
    protein: "fish",
    plate: "fish",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school"],
    aliases: ["fish cakes", "cod cakes", "salt fish cakes", "nl cakes"],
    ingredients: [
      I("salt cod", 1, "lb", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("savory", 1, "tsp", "Herbs & Spices"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 0.5, "cup", "Pantry"),
    ],
    steps: [
      "Soak the 1 pound of salt cod overnight, changing the water twice. Drain, cover with fresh water, and simmer 10–15 minutes, until it flakes. Drain and flake it, checking for bones.",
      "Boil the 4 potatoes until a fork slides through, then drain and mash them dry.",
      "Mix the fish, potato, the finely chopped onion, and the 1 teaspoon of savory. Taste before salting — the cod brings its own.",
      "Shape into cakes and dust both sides with the ½ cup of flour. Chill 15 minutes if they feel soft.",
      "Fry in the 3 tablespoons of butter over medium heat, 4–5 minutes a side, until both sides are crusted and gold.",
    ],
  }),
  dish({
    id: "pan-fried-cod",
    name: "Pan-fried cod",
    description: "Crisp-edged fresh cod, lemon, a knob of butter. Outport weeknight.",
    minutes: 20,
    protein: "fish",
    plate: "fish",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "quick"],
    aliases: ["fried fish", "cod fry", "nl fried fish"],
    ingredients: [
      I("cod fillets", 1.5, "lb", "Meat & Seafood"),
      I("flour", 0.5, "cup", "Pantry"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("lemon", 1, "", "Produce"),
      I("savory", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Pat the 1½ pounds of cod fillets dry and season with the 1 teaspoon of salt and the 1 teaspoon of savory.",
      "Dredge them in the ½ cup of flour and shake off everything loose — a thick coat steams instead of crisping.",
      "Get a skillet hot over medium-high with the 3 tablespoons of butter. Lay the fillets in and leave them alone 3–4 minutes, until the edges turn opaque and the underside is gold.",
      "Flip once and cook 2–4 minutes more, until the flesh flakes and the centre is just opaque. Spoon the foaming butter over as it finishes.",
      "Squeeze the lemon over and serve straight away.",
    ],
  }),
  dish({
    id: "moose-stew",
    name: "Moose stew",
    description: "Slow moose, root veg, and a dark gravy. Cabin cooking.",
    minutes: 180,
    protein: "beef",
    plate: "soup",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "old-school"],
    aliases: ["moose meat stew", "wild game stew", "nl stew"],
    ingredients: [
      I("moose stew meat or beef chuck", 2, "lb", "Meat & Seafood"),
      I("potato", 4, "", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("turnip", 1, "", "Produce"),
      I("onion", 2, "", "Produce"),
      I("beef broth", 4, "cups", "Pantry"),
    ],
    steps: [
      "Pat the 2 pounds of moose stew meat or beef chuck dry and season with the 1 teaspoon of salt. Brown it hard in the 2 tablespoons of oil in a heavy pot, in batches, and lift out.",
      "Soften the 2 chopped onions in the fat, scraping the pot clean.",
      "Return the meat with the 4 cups of beef broth, bring to a bare simmer, and cook covered 2 hours, until the meat starts to give.",
      "Add the 4 potatoes, the 4 carrots, and the turnip in big chunks and cook 40 minutes more, until everything is tender and the gravy has thickened.",
      "Skim the fat, taste for salt and pepper, and ladle into warm bowls.",
    ],
  }),
  dish({
    id: "hodge-podge",
    name: "Hodge podge",
    description: "Maritimes cream of new vegetables — beans, carrots, potatoes, a little butter.",
    minutes: 40,
    protein: "veg",
    plate: "soup",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "vegetarian", "maritimes"],
    aliases: ["hodgepodge", "hodge podge soup", "nova scotia hodge podge"],
    ingredients: [
      I("new potatoes", 1, "lb", "Produce"),
      I("green beans", 0.5, "lb", "Produce"),
      I("carrot", 4, "", "Produce"),
      I("peas", 1, "cup", "Produce"),
      I("cream", 1, "cup", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
    ],
    steps: [
      "Simmer the 1 pound of new potatoes, the 4 carrots, the ½ pound of green beans, and the 1 cup of peas in salted water until just tender, 12–15 minutes. Drain most of the water.",
      "Stir in the 1 cup of cream and the 3 tablespoons of butter. Do not boil hard.",
      "Taste for salt. Serve in warm bowls.",
    ],
  }),
  dish({
    id: "halifax-donair",
    name: "Halifax donair",
    description: "Spiced beef, sweet garlic sauce, tomato and onion in a pita. East Coast pride.",
    minutes: 50,
    protein: "beef",
    plate: "taco",
    cuisine: "Newfoundland",
    tags: ["newfoundland", "maritimes"],
    aliases: ["donair", "halifax donair", "east coast donair", "donair sauce"],
    ingredients: [
      I("ground beef", 1.5, "lb", "Meat & Seafood"),
      I("onion powder", 1, "tsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("paprika", 1, "tsp", "Herbs & Spices"),
      I("evaporated milk", 0.75, "cup", "Pantry"),
      I("sugar", 0.5, "cup", "Pantry"),
      I("garlic", 3, "cloves", "Produce"),
      I("pita", 4, "", "Bakery"),
      I("tomato", 2, "", "Produce"),
      I("onion", 1, "", "Produce"),
    ],
    steps: [
      "Knead the 1½ pounds of ground beef with the 1 teaspoon of onion powder, the 1 teaspoon of garlic powder, the 1 teaspoon of paprika, and salt for a full 5 minutes, until it turns tacky and smooth. That kneading is what gives donair meat its texture.",
      "Pack it into a loaf tin and bake at 350°F for 60 minutes, until a thermometer in the middle reads 160°F. Cool, then chill before slicing — warm, it crumbles.",
      "Whisk the ¾ cup of evaporated milk with the ½ cup of sugar and the 3 minced cloves of garlic, then add a splash of vinegar drop by drop, whisking, until it thickens. Add it too fast and it will not set.",
      "Slice the cold loaf paper-thin and crisp the slices in a dry hot pan.",
      "Warm the 4 pitas and fill with the meat, the 2 chopped tomatoes, the sliced onion, and a reckless amount of sauce.",
    ],
  }),
  dish({
    id: "poutine",
    name: "Poutine",
    description: "Fries, cheese curds, hot gravy. Quebec’s gift to late night.",
    minutes: 40,
    protein: "veg",
    plate: "bowl",
    cuisine: "American",
    tags: ["canadian", "vegetarian", "comfort"],
    aliases: ["quebec poutine", "fries gravy curds"],
    ingredients: [
      I("russet potatoes", 4, "", "Produce"),
      I("cheese curds", 2, "cups", "Dairy & Eggs"),
      I("beef or veg gravy", 2, "cups", "Pantry"),
      I("oil for frying", 4, "cups", "Pantry"),
    ],
    steps: [
      "Cut fries, soak, double-fry until crisp.",
      "Top with room-temp curds and boiling gravy so they squeak and slump.",
    ],
  }),
  dish({
    id: "tourtiere",
    name: "Tourtière",
    description: "Spiced meat pie for Christmas Eve and every cold Sunday after.",
    minutes: 90,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "canadian", "christmas"],
    aliases: ["tourtiere", "french canadian meat pie", "pork pie"],
    ingredients: [
      I("ground pork", 1.5, "lb", "Meat & Seafood"),
      I("ground beef", 0.5, "lb", "Meat & Seafood"),
      I("potato", 1, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cinnamon", 0.25, "tsp", "Herbs & Spices"),
      I("clove", 0.125, "tsp", "Herbs & Spices"),
      I("pie pastry", 1, "double crust", "Bakery"),
    ],
    steps: [
      "Boil the potato until soft, then mash it. Cook the 1½ pounds of ground pork and the ½ pound of ground beef with the chopped onion in a wide pan, breaking it up, until no pink remains.",
      "Stir in the mashed potato, the ¼ teaspoon of cinnamon, the ⅛ teaspoon of clove, the 1 teaspoon of salt, and pepper. Add a splash of water and simmer 20 minutes, until thick but not dry. Cool completely — hot filling melts the pastry.",
      "Line a pie dish with half the double crust pie pastry and fill it. Lay the second crust over, seal and crimp the edge, and cut two vents.",
      "Bake at 375°F for 45 minutes, until the crust is deep gold and steam comes from the vents.",
      "Rest 15 minutes before cutting. Serve with ketchup if you are honest about it.",
    ],
  }),
  dish({
    id: "toad-in-hole",
    name: "Toad in the hole",
    description: "Sausages baked in Yorkshire pudding batter. British supper, no amphibians.",
    minutes: 50,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "british"],
    aliases: ["toad in the hole", "sausage yorkshire", "toad-in-the-hole"],
    ingredients: [
      I("pork sausages", 8, "", "Meat & Seafood"),
      I("flour", 1, "cup", "Pantry"),
      I("eggs", 3, "", "Dairy & Eggs"),
      I("milk", 1, "cup", "Dairy & Eggs"),
      I("oil", 3, "tbsp", "Pantry"),
    ],
    steps: [
      "Whisk the 1 cup of flour, the 3 eggs, the 1 cup of milk, and the 1 teaspoon of salt to a smooth batter and rest it 30 minutes. Resting is what makes it rise.",
      "Heat the oven to 425°F. Put the 3 tablespoons of oil in a roasting tin with the 8 pork sausages and roast 15 minutes, until the sausages are browned and the fat is smoking hot.",
      "Pour the batter around the sausages in one go. It should hiss the moment it lands — if it does not, the fat was not hot enough and it will not puff.",
      "Bake 25–30 minutes without opening the door, until the batter is risen, deep gold, and crisp at the edges.",
      "Serve at once, before it sinks.",
    ],
  }),
  dish({
    id: "bangers-mash",
    name: "Bangers and mash",
    description: "Sausages, buttery potatoes, onion gravy. Pub plate at home.",
    minutes: 40,
    protein: "pork",
    plate: "roast",
    cuisine: "Old school",
    tags: ["old-school", "british"],
    aliases: ["bangers & mash", "sausage and mash", "bangers"],
    ingredients: [
      I("pork sausages", 8, "", "Meat & Seafood"),
      I("potato", 2, "lb", "Produce"),
      I("onion", 2, "", "Produce"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("beef broth", 1.5, "cups", "Pantry"),
    ],
    steps: [
      "Boil the 2 pounds of potato until a fork slides through, then drain and mash with half the 4 tablespoons of butter and the 1 teaspoon of salt. Keep warm.",
      "Brown the 8 pork sausages slowly in a skillet over medium heat, turning, 15–18 minutes, until deep gold all over and cooked through. Lift them out.",
      "Melt the rest of the butter in the pan and cook the 2 thinly sliced onions 15 minutes, until soft and sweet and browning at the edges.",
      "Stir in a spoon of flour, then the 1½ cups of beef broth, and simmer 5 minutes to a gravy.",
      "Pile the mash on plates, lay the sausages over, and pour the onion gravy across.",
    ],
  }),
  dish({
    id: "irish-stew",
    name: "Irish stew",
    description: "Lamb or mutton, potato, onion. Patience is the fourth ingredient.",
    minutes: 140,
    protein: "lamb",
    plate: "soup",
    cuisine: "Old school",
    tags: ["old-school", "irish"],
    aliases: ["irish lamb stew", "mutton stew"],
    ingredients: [
      I("lamb shoulder", 2, "lb", "Meat & Seafood"),
      I("potato", 2, "lb", "Produce"),
      I("onion", 3, "", "Produce"),
      I("carrot", 3, "", "Produce"),
      I("thyme", 4, "sprigs", "Produce"),
      I("stock", 4, "cups", "Pantry"),
    ],
    steps: [
      "Pat the 2 pounds of lamb shoulder dry, season with the 1 teaspoon of salt, and brown it in the 2 tablespoons of oil in a heavy pot. Lift out.",
      "Soften the 3 sliced onions in the fat, 6–8 minutes, scraping the pot clean.",
      "Return the lamb with the 4 sprigs of thyme and the 4 cups of stock, bring to a bare simmer, and cook covered 90 minutes.",
      "Add the 3 carrots and the 2 pounds of potato in big chunks and cook 40 minutes more, until the potatoes are soft enough to thicken the broth and the lamb pulls apart.",
      "Skim the fat, season, and ladle into warm bowls.",
    ],
  }),
  dish({
    id: "colcannon",
    name: "Colcannon",
    description: "Mashed potato folded with cabbage or kale and a well of butter.",
    minutes: 35,
    protein: "veg",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "irish", "vegetarian"],
    aliases: ["irish mash", "cabbage mash"],
    ingredients: [
      I("potato", 2, "lb", "Produce"),
      I("cabbage or kale", 0.5, "head", "Produce"),
      I("scallion", 4, "", "Produce"),
      I("butter", 6, "tbsp", "Dairy & Eggs"),
      I("milk", 0.75, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Boil the 2 pounds of potato in salted water until a fork slides through, 18–20 minutes. Drain and let them steam dry in the pot.",
      "Meanwhile cook the ½ head of shredded cabbage or kale in half the 6 tablespoons of butter over medium heat, 8–10 minutes, until soft and sweet.",
      "Warm the ¾ cup of milk with the sliced 4 scallions so they soften without browning.",
      "Mash the potatoes with the hot milk and scallions until smooth, then fold the cabbage through. Season with the 1 teaspoon of salt.",
      "Pile into a warm dish, make a well in the middle, and drop the rest of the butter into it to melt.",
    ],
  }),
  dish({
    id: "amatriciana",
    name: "Bucatini all’amatriciana",
    description: "Guanciale, tomato, pecorino. Roman, loud, not creamy.",
    minutes: 30,
    protein: "pork",
    plate: "pasta",
    cuisine: "Italian",
    tags: ["italian", "quick"],
    aliases: ["amatriciana", "bucatini amatriciana"],
    ingredients: [
      I("bucatini", 12, "oz", "Pantry"),
      I("guanciale", 5, "oz", "Meat & Seafood"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("pecorino romano", 2, "oz", "Dairy & Eggs"),
      I("red pepper flakes", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Cut the 5 ounces of guanciale into short batons and render them slowly in the 2 tablespoons of oil in a wide pan, 6–8 minutes, until the fat runs and the pieces crisp. Lift the crisp pieces out.",
      "Add the ½ teaspoon of red pepper flakes to the hot fat, then the 1 can of crushed tomatoes and the 1 teaspoon of salt. Simmer 12–15 minutes, until it darkens and thickens.",
      "Boil the 12 ounces of bucatini until just shy of al dente and save a cup of the water.",
      "Toss the pasta through the sauce with a splash of that water, over the heat, until it clings.",
      "Off the heat, return the crisp guanciale and toss with the 2 ounces of grated pecorino romano. Serve at once — there is no cream in this.",
    ],
  }),
  dish({
    id: "eggplant-parm",
    name: "Eggplant parmesan",
    description: "Fried eggplant, red sauce, mozzarella. Meatless Sunday.",
    minutes: 80,
    protein: "veg",
    plate: "roast",
    cuisine: "Italian",
    tags: ["italian", "vegetarian", "old-school"],
    aliases: ["eggplant parmigiana", "melanzane alla parmigiana", "eggplant parm"],
    ingredients: [
      I("eggplant", 2, "", "Produce"),
      I("mozzarella", 12, "oz", "Dairy & Eggs"),
      I("parmesan", 3, "oz", "Dairy & Eggs"),
      I("crushed tomatoes", 2, "cans", "Pantry"),
      I("breadcrumbs", 2, "cups", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
    ],
    steps: [
      "Slice the 2 eggplants into ½-inch rounds, salt them, and leave 30 minutes. Pat every slice properly dry.",
      "Heat the oven to 375°F. Beat the 2 eggs in one dish and put the 2 cups of breadcrumbs in another. Dip each slice in egg, then press it through the crumbs so it is coated all over.",
      "Fry the slices in the 2 tablespoons of oil, or bake them on an oiled sheet 25 minutes turning once, until gold and tender.",
      "Spread some of the 2 cans of crushed tomatoes in a dish, then layer eggplant, tomato, torn mozzarella from the 12 ounces, and some of the 3 ounces of parmesan. Repeat, finishing with cheese.",
      "Bake 30 minutes, until bubbling and browned. Rest 15 minutes before cutting so the layers hold.",
    ],
  }),
  dish({
    id: "avgolemono",
    name: "Avgolemono",
    description: "Greek lemon-egg chicken soup. Bright, silky, homemade.",
    minutes: 45,
    protein: "chicken",
    plate: "soup",
    cuisine: "Greek",
    tags: ["greek", "comfort"],
    aliases: ["avgolemono soup", "greek lemon soup", "egg lemon soup"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("rice", 0.5, "cup", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("lemon", 2, "", "Produce"),
      I("chicken broth", 8, "cups", "Pantry"),
    ],
    steps: [
      "Simmer the 1½ pounds of chicken thighs in the 8 cups of chicken broth with the 2 tablespoons of oil for 30 minutes, skimming, until the meat pulls apart. Lift the chicken out, shred it, and return it.",
      "Add the ½ cup of rice and cook 15 minutes, until tender. Then take the pot off the heat and let it stop bubbling.",
      "Beat the 2 eggs with the juice of the 2 lemons until frothy.",
      "Ladle a cup of the hot broth into the eggs in a thin stream, whisking hard the whole time. Do this twice more. Pouring eggs straight into a hot pot gives you lemon soup with scrambled egg in it.",
      "Stir the tempered mixture back into the pot off the heat. It will turn silky and pale. Season with the 1 teaspoon of salt and serve at once; do not reheat it to a boil.",
    ],
  }),
  dish({
    id: "gemista",
    name: "Gemista",
    description: "Tomatoes and peppers stuffed with herbed rice. Summer Greek table.",
    minutes: 90,
    protein: "veg",
    plate: "roast",
    cuisine: "Greek",
    tags: ["greek", "vegetarian"],
    aliases: ["yemista", "stuffed tomatoes greek"],
    ingredients: [
      I("ripe tomatoes", 6, "", "Produce"),
      I("bell peppers", 4, "", "Produce"),
      I("rice", 1, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("fresh mint", 0.5, "cup", "Produce"),
      I("olive oil", 0.5, "cup", "Pantry"),
      I("potato", 3, "", "Produce"),
    ],
    steps: [
      "Heat the oven to 375°F. Slice the tops off the 6 ripe tomatoes and the 4 bell peppers and keep them as lids. Scoop the tomato flesh out and chop it, keeping the shells whole.",
      "Soften the chopped onion in half the ½ cup of olive oil, 8 minutes. Stir in the 1 cup of rice, the chopped tomato flesh, the ½ cup of chopped mint, and the 1 teaspoon of salt, and cook 3 minutes.",
      "Fill the shells two-thirds full — the rice swells — and put the lids back on.",
      "Stand them in a roasting dish with the 3 potatoes cut into wedges tucked between. Pour the rest of the oil and a cup of water over.",
      "Bake 70 minutes, until the rice is tender, the shells have collapsed a little, and the tops are scorched. Serve warm, not hot.",
    ],
  }),
  dish({
    id: "huevos-rancheros",
    name: "Huevos rancheros",
    description: "Fried eggs on tortillas with a ranchero salsa. Breakfast that is dinner.",
    minutes: 25,
    protein: "eggs",
    plate: "taco",
    cuisine: "Mexican",
    tags: ["mexican", "vegetarian", "quick"],
    aliases: ["rancheros", "ranch eggs", "huevos"],
    ingredients: [
      I("eggs", 4, "", "Dairy & Eggs"),
      I("corn tortillas", 8, "", "Bakery"),
      I("tomato", 4, "", "Produce"),
      I("jalapeño", 1, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cilantro", 0.5, "bunch", "Produce"),
    ],
    steps: [
      "Chop the 4 tomatoes, the onion, and the jalapeño. Simmer in a skillet with a pinch of salt 8–10 minutes, until they slump into a salsa.",
      "Warm the 8 corn tortillas in a dry pan 20 seconds a side, until they flex.",
      "Fry the 4 eggs in a little oil over medium heat, 2–3 minutes, until the whites set and the yolks stay runny.",
      "Set the tortillas on plates. Top with an egg and a spoon of salsa. Scatter the cilantro over.",
    ],
  }),
  dish({
    id: "pozole-rojo",
    name: "Pozole rojo",
    description: "Pork and hominy in a chile broth. Garnish like you mean it.",
    minutes: 150,
    protein: "pork",
    plate: "soup",
    cuisine: "Mexican",
    tags: ["mexican", "sunday"],
    aliases: ["posole", "pozole", "red pozole"],
    ingredients: [
      I("pork shoulder", 2, "lb", "Meat & Seafood"),
      I("canned hominy", 2, "cans", "Pantry"),
      I("dried guajillo chiles", 6, "", "Herbs & Spices"),
      I("garlic", 6, "cloves", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cabbage", 0.25, "head", "Produce"),
      I("radish", 6, "", "Produce"),
      I("lime", 2, "", "Produce"),
    ],
    steps: [
      "Simmer the 2 pounds of pork shoulder with the quartered onion and half the 6 cloves of garlic in water to cover, 2 hours, skimming, until it shreds under a fork. Keep the broth.",
      "Meanwhile stem and seed the 6 dried guajillo chiles, toast them briefly in a dry pan until they smell sweet, then soak in hot water 20 minutes.",
      "Blend the soaked chiles with the rest of the garlic and a ladle of the broth, then push it through a sieve — the skins never soften.",
      "Shred the pork and return it with the chile puree and the 2 cans of drained hominy. Simmer 30 minutes so it all comes together. Salt well.",
      "Serve with the ¼ head of shredded cabbage, the 6 sliced radishes, and the 2 limes cut into wedges, so people dress their own bowl.",
    ],
  }),
  dish({
    id: "palak-paneer",
    name: "Palak paneer",
    description: "Spinach gravy, cubes of paneer. Homestyle Punjabi.",
    minutes: 40,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian"],
    aliases: ["saag paneer", "spinach paneer"],
    ingredients: [
      I("spinach", 1, "lb", "Produce"),
      I("paneer", 8, "oz", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("ginger", 1, "tbsp", "Produce"),
      I("garam masala", 1, "tsp", "Herbs & Spices"),
      I("cream", 0.25, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Blanch spinach, blend with ginger and garlic.",
      "Cook onion, add puree and garam masala, fold in fried paneer and cream.",
    ],
  }),
  dish({
    id: "dal-tadka",
    name: "Dal tadka",
    description: "Yellow lentils finished with a sizzling cumin-garlic tadka.",
    minutes: 40,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian", "budget"],
    aliases: ["tadka dal", "yellow dal", "daal"],
    ingredients: [
      I("toor or yellow lentils", 1, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("tomato", 2, "", "Produce"),
      I("cumin seed", 1, "tsp", "Herbs & Spices"),
      I("garlic", 4, "cloves", "Produce"),
      I("ghee or oil", 2, "tbsp", "Pantry"),
      I("turmeric", 0.5, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Rinse the 1 cup of toor or yellow lentils until the water runs clear. Simmer them with the ½ teaspoon of turmeric and 4 cups of water 30 minutes, until collapsing, whisking them smooth.",
      "Add the 2 chopped tomatoes and the 1 teaspoon of salt and cook 10 minutes more, loosening with water to a pourable dal.",
      "For the tadka, heat the 2 tablespoons of ghee or oil in a small pan until shimmering. Add the 1 teaspoon of cumin seed and let it crackle, 20 seconds.",
      "Add the sliced onion and the 4 sliced cloves of garlic and fry until deep gold — not pale, gold, or the dal will taste flat.",
      "Pour the whole sizzling panful over the dal and stir it in at the table. Serve with rice.",
    ],
  }),
  dish({
    id: "aloo-gobi",
    name: "Aloo gobi",
    description: "Dry-ish potato and cauliflower with cumin and turmeric.",
    minutes: 35,
    protein: "veg",
    plate: "curry",
    cuisine: "Indian",
    tags: ["indian", "vegetarian", "budget"],
    aliases: ["aloo gobhi", "potato cauliflower"],
    ingredients: [
      I("potato", 3, "", "Produce"),
      I("cauliflower", 1, "head", "Produce"),
      I("onion", 1, "", "Produce"),
      I("cumin seed", 1, "tsp", "Herbs & Spices"),
      I("turmeric", 0.5, "tsp", "Herbs & Spices"),
      I("garam masala", 1, "tsp", "Herbs & Spices"),
    ],
    steps: [
      "Set a wide pan over medium heat with the 2 tablespoons of oil. Add the 1 teaspoon of cumin seed and let it crackle, then add the chopped onion and cook 6–8 minutes, until gold.",
      "Stir in the ½ teaspoon of turmeric and the 1 teaspoon of garam masala and cook 30 seconds.",
      "Add the 3 potatoes in chunks and the head of cauliflower in florets and toss until every piece is coated in the spice.",
      "Add a splash of water, cover, and cook 20–25 minutes on low, shaking the pan rather than stirring so the florets stay whole, until a knife goes into the potato easily. This is a dry curry — it should not have a sauce.",
      "Season with the 1 teaspoon of salt and serve with rice.",
    ],
  }),
  dish({
    id: "bibimbap",
    name: "Bibimbap",
    description: "Rice, sautéed vegetables, a fried egg, gochujang. Mix at the table.",
    minutes: 40,
    protein: "eggs",
    plate: "bowl",
    cuisine: "East Asian",
    tags: ["east asian", "korean"],
    aliases: ["korean mixed rice", "bibim bap"],
    ingredients: [
      I("rice", 2, "cups", "Pantry"),
      I("spinach", 4, "cups", "Produce"),
      I("carrot", 2, "", "Produce"),
      I("zucchini", 1, "", "Produce"),
      I("bean sprouts", 2, "cups", "Produce"),
      I("eggs", 4, "", "Dairy & Eggs"),
      I("gochujang", 3, "tbsp", "Pantry"),
      I("sesame oil", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Cook the 2 cups of rice and keep it warm.",
      "Cook each vegetable separately and season each with a little of the 2 tablespoons of sesame oil and the 1 teaspoon of salt: wilt the 4 cups of spinach and squeeze it dry, stir-fry the julienned 2 carrots 2 minutes, the zucchini 2 minutes, and blanch the 2 cups of bean sprouts 1 minute. Keeping them apart is the whole look of the dish.",
      "Fry the 4 eggs so the whites are set and the yolks still liquid.",
      "Spoon rice into four warm bowls and arrange the vegetables in separate wedges on top.",
      "Sit an egg in the middle of each and put the 3 tablespoons of gochujang on the table. Mix it all together at the last moment.",
    ],
  }),
  dish({
    id: "pho-bo",
    name: "Phở bò",
    description: "Beef noodle soup with star anise broth. Homemade takes a Saturday.",
    minutes: 180,
    protein: "beef",
    plate: "soup",
    cuisine: "East Asian",
    tags: ["east asian", "vietnamese"],
    aliases: ["pho", "pho bo", "vietnamese beef noodles"],
    ingredients: [
      I("beef bones", 3, "lb", "Meat & Seafood"),
      I("beef sirloin", 0.75, "lb", "Meat & Seafood"),
      I("rice noodles", 1, "lb", "Pantry"),
      I("onion", 2, "", "Produce"),
      I("ginger", 1, "piece", "Produce"),
      I("star anise", 4, "", "Herbs & Spices"),
      I("fish sauce", 3, "tbsp", "Pantry"),
      I("Thai basil", 1, "bunch", "Produce"),
      I("lime", 2, "", "Produce"),
    ],
    steps: [
      "Blanch the 3 pounds of beef bones in boiling water 5 minutes, then rinse them and the pot. This is what keeps the broth clear.",
      "Char the 2 halved onions and the piece of ginger in a dry pan or under the broiler until blackened in patches, 8 minutes.",
      "Return the bones with the charred onion and ginger, the 4 star anise, and water to cover by 2 inches. Simmer very gently 3 hours, skimming — a hard boil turns it cloudy. Strain, then season with the 3 tablespoons of fish sauce and the 1 teaspoon of salt.",
      "Cook the 1 pound of rice noodles in a separate pot of water and divide them among bowls. Slice the ¾ pound of beef sirloin as thin as you can, half-frozen if that helps, and lay it raw over the noodles.",
      "Ladle the broth over boiling hot so it cooks the beef in the bowl. Serve with the 1 bunch of Thai basil and the 2 limes.",
    ],
  }),
  dish({
    id: "thai-green-curry",
    name: "Thai green curry",
    description: "Coconut, green curry paste, Thai basil. Heat you can tune.",
    minutes: 30,
    protein: "chicken",
    plate: "curry",
    cuisine: "East Asian",
    tags: ["east asian", "thai", "quick"],
    aliases: ["green curry", "gaeng keow wan"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("coconut milk", 1, "can", "Pantry"),
      I("green curry paste", 3, "tbsp", "Pantry"),
      I("Thai eggplant or zucchini", 2, "", "Produce"),
      I("Thai basil", 1, "bunch", "Produce"),
      I("fish sauce", 2, "tbsp", "Pantry"),
      I("palm or brown sugar", 1, "tsp", "Pantry"),
    ],
    steps: [
      "Spoon the thick cream from the top of the 1 can of coconut milk into a hot pot with the 2 tablespoons of oil and let it split and sizzle, 3 minutes.",
      "Fry the 3 tablespoons of green curry paste in that fat 2 minutes, until it darkens and smells fragrant. Frying the paste, not just warming it, is where the flavour comes from.",
      "Add the 1½ pounds of sliced chicken thighs and turn them in the paste, then pour in the rest of the coconut milk and bring to a simmer.",
      "Add the 2 Thai eggplant or zucchini in chunks and simmer 15 minutes, until the chicken is cooked through and the vegetables are tender. Season with the 2 tablespoons of fish sauce, the 1 teaspoon of palm or brown sugar, and the 1 teaspoon of salt.",
      "Take off the heat and stir in the 1 bunch of Thai basil so it wilts but stays green. Serve with the 1½ cups of rice.",
    ],
  }),
  dish({
    id: "kung-pao-chicken",
    name: "Kung pao chicken",
    description: "Diced chicken, dried chiles, peanuts. Sichuan-ish weeknight.",
    minutes: 25,
    protein: "chicken",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east asian", "chinese", "quick"],
    aliases: ["gong bao", "kung pao", "kungpo chicken"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("dried red chiles", 8, "", "Herbs & Spices"),
      I("roasted peanuts", 0.5, "cup", "Pantry"),
      I("soy sauce", 3, "tbsp", "Pantry"),
      I("Chinkiang vinegar", 1, "tbsp", "Pantry"),
      I("garlic", 4, "cloves", "Produce"),
      I("scallion", 4, "", "Produce"),
    ],
    steps: [
      "Dice the 1½ pounds of chicken thighs into ¾-inch cubes and toss with the 1 teaspoon of salt and a spoon of the soy sauce.",
      "Get a wok very hot with the 2 tablespoons of oil. Fry the 8 dried red chiles a few seconds, until they darken but do not blacken — burnt, they turn acrid and the whole dish with them.",
      "Add the chicken in one layer and leave it to sear, then stir-fry 4–5 minutes total, until browned and no longer pink inside.",
      "Add the 4 cloves of garlic and the white parts of the 4 scallions for 30 seconds, then the rest of the 3 tablespoons of soy sauce and the 1 tablespoon of Chinkiang vinegar. Toss until it glazes.",
      "Off the heat, stir in the ½ cup of roasted peanuts and the scallion greens so the nuts stay crunchy.",
    ],
  }),
  dish({
    id: "potstickers",
    name: "Potstickers",
    description: "Pan-fried dumplings, steamed in the same skillet. Dip in vinegar-soy.",
    minutes: 45,
    protein: "pork",
    plate: "skillet",
    cuisine: "East Asian",
    tags: ["east asian", "chinese"],
    aliases: ["gyoza", "guo tie", "dumplings", "jiaozi"],
    ingredients: [
      I("ground pork", 1, "lb", "Meat & Seafood"),
      I("napa cabbage", 2, "cups", "Produce"),
      I("scallion", 4, "", "Produce"),
      I("ginger", 1, "tbsp", "Produce"),
      I("dumpling wrappers", 40, "", "Frozen"),
      I("soy sauce", 3, "tbsp", "Pantry"),
    ],
    steps: [
      "Mix the 1 pound of ground pork with the 2 cups of finely chopped napa cabbage, the 4 sliced scallions, the 1 tablespoon of grated ginger, and 1 tablespoon of the soy sauce. Squeeze the cabbage dry first or the filling will weep.",
      "Put a teaspoon of filling on each of the 40 dumpling wrappers, wet the rim, fold into a half-moon and pleat one side closed.",
      "Set a wide lidded skillet over medium-high heat with the 2 tablespoons of oil. Sit the dumplings flat-side down in one layer and fry 2–3 minutes, until the bottoms are golden.",
      "Pour in ⅓ cup of water and clamp the lid on straight away. Steam 6–7 minutes, until the water is gone and the wrappers are translucent.",
      "Uncover and fry 1 minute more to crisp the bases. Lift out with a thin spatula and serve with the remaining soy sauce.",
    ],
  }),
  dish({
    id: "mujadara",
    name: "Mujadara",
    description: "Lentils, rice, and a pile of fried onions. Pantry feast.",
    minutes: 50,
    protein: "veg",
    plate: "bowl",
    cuisine: "Middle Eastern",
    tags: ["middle eastern", "vegetarian", "budget"],
    aliases: ["mujaddara", "lentils and rice", "mdardara"],
    ingredients: [
      I("brown lentils", 1, "cup", "Pantry"),
      I("rice", 1, "cup", "Pantry"),
      I("onion", 3, "", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("olive oil", 0.33, "cup", "Pantry"),
    ],
    steps: [
      "Slice the 3 onions thin. Fry them in the ⅓ cup of olive oil over medium heat 25–30 minutes, stirring, until deep brown and crisp. Take them past golden — this is the flavour of the dish. Lift out onto paper, leaving the oil.",
      "Simmer the 1 cup of brown lentils in plenty of water 20 minutes, until just tender but not split. Drain.",
      "Add the 1 cup of rice, the 1 teaspoon of cumin, and the 1 teaspoon of salt to the onion oil and stir a minute.",
      "Return the lentils with 2 cups of water, bring to a boil, then cover and cook on the lowest heat 18 minutes. Rest off the heat 10 minutes without lifting the lid.",
      "Fork it up, fold half the onions through, and pile the rest on top.",
    ],
  }),
  dish({
    id: "kofta",
    name: "Beef kofta",
    description: "Spiced ground meat on skewers, yogurt, herbs. Grill or broiler.",
    minutes: 35,
    protein: "beef",
    plate: "skillet",
    cuisine: "Middle Eastern",
    tags: ["middle eastern"],
    aliases: ["kefte", "kofta kebab", "kefta"],
    ingredients: [
      I("ground beef or lamb", 1.5, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("parsley", 0.5, "bunch", "Produce"),
      I("cumin", 1, "tsp", "Herbs & Spices"),
      I("coriander", 1, "tsp", "Herbs & Spices"),
      I("plain yogurt", 1, "cup", "Dairy & Eggs"),
      I("pita", 4, "", "Bakery"),
    ],
    steps: [
      "Grate the onion and squeeze the liquid out of it. Knead it into the 1½ pounds of ground beef or lamb with the ½ bunch of chopped parsley, the 1 teaspoon of cumin, the 1 teaspoon of coriander, and the 1 teaspoon of salt for 3–4 minutes, until the mixture turns sticky and holds together.",
      "Chill 20 minutes, then shape into fat fingers around skewers, squeezing firmly so they do not slide off.",
      "Grill, broil, or sear in the 2 tablespoons of oil, turning, 8–10 minutes, until browned all over and no pink remains in the middle.",
      "Warm the 4 pitas while they cook.",
      "Serve the skewers on the pita with the 1 cup of plain yogurt spooned over and more parsley scattered on top.",
    ],
  }),
  dish({
    id: "french-onion",
    name: "French onion soup",
    description: "Onions cooked past patience, stock, a Gruyère crouton.",
    minutes: 90,
    protein: "veg",
    plate: "soup",
    cuisine: "French",
    tags: ["french", "comfort"],
    aliases: ["soupe a l oignon", "onion soup"],
    ingredients: [
      I("onion", 4, "lb", "Produce"),
      I("beef broth", 8, "cups", "Pantry"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("dry white wine", 0.5, "cup", "Pantry"),
      I("baguette", 1, "", "Bakery"),
      I("Gruyère", 8, "oz", "Dairy & Eggs"),
    ],
    steps: [
      "Melt the 4 tablespoons of butter in a heavy pot over medium-low. Add the 4 pounds of sliced onions and cook 45 minutes, stirring often, until mahogany.",
      "Pour in the ½ cup of dry white wine and scrape the pot. Add the 8 cups of beef broth. Simmer 20 minutes.",
      "Heat the broiler. Ladle the soup into oven-safe bowls. Top with baguette slices and the 8 ounces of Gruyère.",
      "Broil 2–3 minutes, until the cheese bubbles. Serve hot.",
    ],
  }),
  dish({
    id: "ratatouille",
    name: "Ratatouille",
    description: "Late-summer vegetables stewed in olive oil until they agree.",
    minutes: 60,
    protein: "veg",
    plate: "skillet",
    cuisine: "French",
    tags: ["french", "vegetarian"],
    aliases: ["confit byaldi", "provencal vegetables"],
    ingredients: [
      I("eggplant", 1, "", "Produce"),
      I("zucchini", 2, "", "Produce"),
      I("bell pepper", 2, "", "Produce"),
      I("ripe tomatoes", 4, "", "Produce"),
      I("onion", 1, "", "Produce"),
      I("garlic", 4, "cloves", "Produce"),
      I("olive oil", 0.25, "cup", "Pantry"),
      I("fresh thyme", 4, "sprigs", "Produce"),
    ],
    steps: [
      "Cut the eggplant, the 2 zucchini, the 2 bell peppers, the 4 ripe tomatoes, and the onion into similar chunks. Salt the eggplant 10 minutes, then pat it dry.",
      "Brown each vegetable separately in the ¼ cup of olive oil over medium-high heat, 4–5 minutes each, starting with the eggplant, which drinks the most oil. Do not crowd the pan — crowded, they steam and go grey.",
      "Return everything to the pan with the 4 cloves of garlic and the 4 sprigs of fresh thyme.",
      "Stew on medium-low 30–40 minutes, until jammy and the oil separates at the edges.",
      "Season with the 1 teaspoon of salt. Serve warm or at room temperature — it is better an hour later than straight off the heat.",
    ],
  }),
  dish({
    id: "croque-monsieur",
    name: "Croque monsieur",
    description: "Ham, béchamel, Gruyère, broiled. Add an egg and it is a madame.",
    minutes: 25,
    protein: "pork",
    plate: "toast",
    cuisine: "French",
    tags: ["french", "quick"],
    aliases: ["croque madame", "french ham sandwich"],
    ingredients: [
      I("pain de mie or white bread", 8, "slices", "Bakery"),
      I("ham", 8, "slices", "Meat & Seafood"),
      I("Gruyère", 6, "oz", "Dairy & Eggs"),
      I("milk", 1, "cup", "Dairy & Eggs"),
      I("butter", 3, "tbsp", "Dairy & Eggs"),
      I("flour", 2, "tbsp", "Pantry"),
    ],
    steps: [
      "Melt the 3 tablespoons of butter, stir in the 2 tablespoons of flour, and cook 1 minute. Whisk in the 1 cup of milk a little at a time and simmer to a thick béchamel. Season.",
      "Heat the broiler. Lay the 8 slices of pain de mie or white bread out and spread a thin layer of béchamel on four of them.",
      "Add the 8 slices of ham and half the 6 ounces of grated Gruyère, then close each sandwich.",
      "Spread the rest of the béchamel over the tops and scatter the remaining Gruyère across.",
      "Broil 3–4 minutes, until the top is blistered and gold and the cheese has run down the sides. Eat hot.",
    ],
  }),
  dish({
    id: "paella",
    name: "Weeknight paella",
    description: "Saffron rice, chicken, shrimp, peas. Not Valencia-strict — Tuesday-friendly.",
    minutes: 50,
    protein: "chicken",
    plate: "skillet",
    cuisine: "Spanish",
    tags: ["spanish"],
    aliases: ["paella mixta", "spanish rice", "arroz con cosas"],
    ingredients: [
      I("short-grain rice", 1.5, "cups", "Pantry"),
      I("chicken thighs", 1, "lb", "Meat & Seafood"),
      I("shrimp", 0.75, "lb", "Meat & Seafood"),
      I("onion", 1, "", "Produce"),
      I("tomato", 2, "", "Produce"),
      I("saffron", 1, "pinch", "Herbs & Spices"),
      I("chicken broth", 4, "cups", "Pantry"),
      I("frozen peas", 1, "cup", "Frozen"),
    ],
    steps: [
      "Steep the pinch of saffron in a little warm water. Pat the 1 pound of chicken thighs dry, season with the 1 teaspoon of salt, and brown them in the 2 tablespoons of oil in a wide shallow pan. Lift out.",
      "Soften the chopped onion in the fat, then add the 2 grated tomatoes and cook down 5 minutes to a thick sofrito.",
      "Stir in the 1½ cups of short-grain rice until every grain is coated, then pour in the 4 cups of chicken broth and the saffron water. Return the chicken.",
      "Simmer 15 minutes without stirring — stirring makes it risotto, and the crust on the bottom is the point. Scatter the ¾ pound of shrimp and the 1 cup of frozen peas over the top and cook 5–8 minutes more, until the rice is tender and the shrimp are pink.",
      "Turn the heat up for the last minute to catch the base, then rest off the heat 5 minutes under a cloth before serving from the pan.",
    ],
  }),
  dish({
    id: "spanish-tortilla",
    name: "Spanish tortilla",
    description: "Potato, onion, egg. Thick omelette, room-temp or hot.",
    minutes: 40,
    protein: "eggs",
    plate: "skillet",
    cuisine: "Spanish",
    tags: ["spanish", "vegetarian"],
    aliases: ["tortilla española", "spanish omelette", "potato omelette"],
    ingredients: [
      I("potato", 2, "lb", "Produce"),
      I("onion", 1, "", "Produce"),
      I("eggs", 6, "", "Dairy & Eggs"),
      I("olive oil", 0.75, "cup", "Pantry"),
    ],
    steps: [
      "Slice the 2 pounds of potato thin and the onion thinly too. Warm the ¾ cup of olive oil in a skillet and cook them gently 20–25 minutes, until soft but not coloured. This is poaching, not frying.",
      "Drain them in a sieve over a bowl, keeping the oil, and season well.",
      "Beat the 6 eggs in a large bowl, fold the hot potato through, and leave 10 minutes so the potato drinks the egg.",
      "Return 2 tablespoons of the oil to the pan, pour the mixture in, and cook on low 8–10 minutes, easing the edges in, until the sides are set and the middle still wobbles.",
      "Slide it onto a plate, invert the pan over it, flip, and cook 3–4 minutes more. Rest 10 minutes and serve warm or at room temperature, never hot.",
    ],
  }),
  dish({
    id: "schnitzel",
    name: "Pork schnitzel",
    description: "Pound, bread, fry. Lemon wedge non-negotiable.",
    minutes: 30,
    protein: "pork",
    plate: "skillet",
    cuisine: "Old school",
    tags: ["old-school", "german", "quick"],
    aliases: ["wienerschnitzel", "wiener schnitzel", "breaded pork"],
    ingredients: [
      I("pork cutlets", 4, "", "Meat & Seafood"),
      I("flour", 0.5, "cup", "Pantry"),
      I("eggs", 2, "", "Dairy & Eggs"),
      I("breadcrumbs", 1.5, "cups", "Pantry"),
      I("lemon", 1, "", "Produce"),
      I("oil for frying", 1, "cup", "Pantry"),
    ],
    steps: [
      "Pound the 4 pork cutlets between sheets of plastic to ¼ inch. Pat dry and season with the 1 teaspoon of salt.",
      "Set out three dishes: the ½ cup of flour, the 2 beaten eggs, and the 1½ cups of breadcrumbs. Dredge each cutlet in flour, then egg, then crumbs — press lightly, do not pack them on, or the coating will not puff away from the meat.",
      "Heat the 1 cup of oil in a wide pan to about ⅓ inch deep and 340°F, hot enough that a crumb sizzles at once.",
      "Fry 2–3 minutes a side, swirling the pan so the oil washes over the top, until deep gold. Drain on a rack, never on paper, and never cover it.",
      "Serve immediately with the lemon cut into wedges. No sauce goes over a schnitzel.",
    ],
  }),
  dish({
    id: "pierogi",
    name: "Pierogi",
    description: "Potato-cheese dumplings boiled then butter-fried. Sour cream on the side.",
    minutes: 90,
    protein: "veg",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "polish", "vegetarian"],
    aliases: ["pyrohy", "vareniki", "perogies", "pierogies"],
    ingredients: [
      I("flour", 3, "cups", "Pantry"),
      I("eggs", 1, "", "Dairy & Eggs"),
      I("potato", 2, "lb", "Produce"),
      I("cheddar or farmer cheese", 1, "cup", "Dairy & Eggs"),
      I("onion", 1, "", "Produce"),
      I("butter", 4, "tbsp", "Dairy & Eggs"),
      I("sour cream", 1, "cup", "Dairy & Eggs"),
    ],
    steps: [
      "Boil the 2 pounds of potato until soft, drain, and mash. Soften the chopped onion in half the 4 tablespoons of butter and stir it in with the 1 cup of cheddar or farmer cheese and the 1 teaspoon of salt. Cool completely.",
      "Make the dough: mix the 3 cups of flour with the egg, a pinch of salt, and about ¾ cup of warm water to a soft dough. Knead 5 minutes, then rest it 30 minutes under a bowl — unrested dough springs back and will not seal.",
      "Roll thin and cut 3-inch rounds. Put a spoon of filling on each, fold, and pinch the edge firmly closed with dry fingers.",
      "Boil them in batches in well-salted water. They are done about 2 minutes after they float.",
      "Fry the drained pierogi in the rest of the butter until blistered and gold. Serve with the 1 cup of sour cream.",
    ],
  }),
  dish({
    id: "rice-and-peas",
    name: "Rice and peas",
    description: "Coconut rice with kidney beans, thyme, and Scotch bonnet. Jamaican table.",
    minutes: 45,
    protein: "veg",
    plate: "bowl",
    cuisine: "Caribbean",
    tags: ["caribbean", "vegetarian"],
    aliases: ["rice n peas", "coconut rice and beans"],
    ingredients: [
      I("rice", 2, "cups", "Pantry"),
      I("kidney beans", 1, "can", "Pantry"),
      I("coconut milk", 1, "can", "Pantry"),
      I("thyme", 4, "sprigs", "Produce"),
      I("scallion", 3, "", "Produce"),
      I("Scotch bonnet", 1, "", "Produce"),
    ],
    steps: [
      "Put the 1 can of kidney beans with their liquid in a pot with the 1 can of coconut milk, the 4 sprigs of thyme, the 3 crushed scallions, and the 1 teaspoon of salt. Bring to a simmer.",
      "Sit the whole Scotch bonnet on top. Leave it whole and do not pierce it — it perfumes the pot; burst, it makes the whole thing inedible.",
      "Rinse the 2 cups of rice and stir it in with the 2 tablespoons of oil, adding water so the liquid sits about an inch above the rice.",
      "Bring back to a boil, then cover and cook on the lowest heat 25 minutes without lifting the lid.",
      "Lift out the chile and the thyme stalks, fork the rice up, and serve.",
    ],
  }),
  dish({
    id: "gumbo",
    name: "Chicken and sausage gumbo",
    description: "Dark roux, holy trinity, okra or filé. Louisiana in a pot.",
    minutes: 120,
    protein: "chicken",
    plate: "soup",
    cuisine: "American",
    tags: ["american", "cajun"],
    aliases: ["gumbo ya ya", "chicken sausage gumbo"],
    ingredients: [
      I("chicken thighs", 1.5, "lb", "Meat & Seafood"),
      I("andouille sausage", 12, "oz", "Meat & Seafood"),
      I("flour", 0.75, "cup", "Pantry"),
      I("oil", 0.75, "cup", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("okra", 2, "cups", "Produce"),
      I("chicken broth", 8, "cups", "Pantry"),
      I("salt", 1, "tsp", "Herbs & Spices"),
      I("rice", 1.5, "cups", "Pantry"),
    ],
    steps: [
      "Season the 1½ pounds of chicken thighs with the 1 teaspoon of salt. Brown them in a heavy pot in a little of the ¾ cup of oil, then the 12 ounces of sliced andouille sausage. Lift both out.",
      "Pour the rest of the oil into the pot and whisk in the ¾ cup of flour. Cook over medium heat, stirring without stopping, 20–25 minutes, until the roux is the colour of milk chocolate. Do not walk away — a burnt roux is bitter and there is no saving it.",
      "Tip in the diced onion, the 2 stalks of celery, and the chopped bell pepper. They will hiss and stop the roux cooking. Stir 8 minutes, until soft.",
      "Whisk in the 8 cups of chicken broth a ladle at a time so it stays smooth. Return the chicken and sausage and simmer, uncovered, 45 minutes.",
      "Add the 2 cups of okra and simmer 15 minutes more, until it is tender and the gumbo has thickened. Shred the chicken back in, season, and ladle over rice.",
    ],
  }),
  dish({
    id: "jambalaya",
    name: "Jambalaya",
    description: "Rice cooked with chicken, sausage, the trinity, and a little heat.",
    minutes: 50,
    protein: "chicken",
    plate: "skillet",
    cuisine: "American",
    tags: ["american", "cajun"],
    aliases: ["cajun jambalaya", "creole jambalaya"],
    ingredients: [
      I("chicken thighs", 1, "lb", "Meat & Seafood"),
      I("andouille sausage", 12, "oz", "Meat & Seafood"),
      I("rice", 1.5, "cups", "Pantry"),
      I("onion", 1, "", "Produce"),
      I("celery", 2, "stalks", "Produce"),
      I("bell pepper", 1, "", "Produce"),
      I("crushed tomatoes", 1, "can", "Pantry"),
      I("chicken broth", 3, "cups", "Pantry"),
      I("Cajun seasoning", 1, "tbsp", "Herbs & Spices"),
    ],
    steps: [
      "Brown slices of the 12 ounces of andouille sausage in the 2 tablespoons of oil in a heavy pot and lift out. Season the 1 pound of chicken thighs with the 1 teaspoon of salt, brown them, and lift out too.",
      "Soften the chopped onion, the 2 stalks of celery, and the chopped bell pepper in the fat, 8 minutes. Stir in the 1 tablespoon of Cajun seasoning and cook 30 seconds.",
      "Add the 1 can of crushed tomatoes and cook 3 minutes, then stir in the 1½ cups of rice until coated.",
      "Pour in the 3 cups of chicken broth, return the chicken and sausage, and bring to a boil. Cover and cook on the lowest heat 25 minutes without stirring — stir it and the rice goes gluey.",
      "Rest off the heat 10 minutes, still covered, then fork it up and serve.",
    ],
  }),
  dish({
    id: "buttermilk-fried-chicken",
    name: "Buttermilk fried chicken",
    description: "Overnight buttermilk, a seasoned crust, a cast-iron pot.",
    minutes: 60,
    protein: "chicken",
    plate: "skillet",
    cuisine: "American",
    tags: ["american", "old-school"],
    aliases: ["fried chicken", "southern fried chicken"],
    ingredients: [
      I("chicken pieces", 3, "lb", "Meat & Seafood"),
      I("buttermilk", 2, "cups", "Dairy & Eggs"),
      I("flour", 2, "cups", "Pantry"),
      I("paprika", 1, "tbsp", "Herbs & Spices"),
      I("garlic powder", 1, "tsp", "Herbs & Spices"),
      I("oil for frying", 4, "cups", "Pantry"),
    ],
    steps: [
      "Soak the 3 pounds of chicken pieces in the 2 cups of buttermilk with the 1 teaspoon of salt overnight in the fridge, or at least 4 hours.",
      "Mix the 2 cups of flour with the 1 tablespoon of paprika, the 1 teaspoon of garlic powder, and plenty of salt and pepper. Lift each piece straight from the buttermilk and press it through the flour, hard, so it clings in ridges.",
      "Heat the 4 cups of oil in a deep heavy pot to 325°F — measure it, because too hot burns the crust before the bone is done and too cool makes it greasy.",
      "Fry in batches, never crowding, 12–15 minutes, turning once, until deep mahogany. The thickest piece must read 165°F at the bone; the crust colours long before that.",
      "Drain on a rack, not paper, and season again while hot. Rest 10 minutes before eating.",
    ],
  }),
  dish({
    id: "chicken-paprikash",
    name: "Chicken paprikash",
    description: "Chicken in a paprika-sour cream sauce. Dumplings or noodles under it.",
    minutes: 55,
    protein: "chicken",
    plate: "bowl",
    cuisine: "Old school",
    tags: ["old-school", "hungarian"],
    aliases: ["paprikash", "csirke paprikas", "paprika chicken"],
    ingredients: [
      I("chicken thighs", 2, "lb", "Meat & Seafood"),
      I("onion", 2, "", "Produce"),
      I("sweet paprika", 3, "tbsp", "Herbs & Spices"),
      I("sour cream", 1, "cup", "Dairy & Eggs"),
      I("chicken broth", 1.5, "cups", "Pantry"),
      I("egg noodles", 12, "oz", "Pantry"),
    ],
    steps: [
      "Pat the 2 pounds of chicken thighs dry and season with the 1 teaspoon of salt. Brown them skin-side down in the 2 tablespoons of oil, 6–7 minutes, and lift out.",
      "Soften the 2 sliced onions in the fat, 10 minutes, until sweet. Take the pan off the heat before stirring in the 3 tablespoons of sweet paprika — paprika scorches in seconds and turns bitter.",
      "Return the chicken with the 1½ cups of chicken broth, cover, and simmer 30 minutes, until the meat pulls easily from the bone.",
      "Lift the chicken out. Temper the 1 cup of sour cream with a ladle of the hot sauce, then stir it back in off the heat so it cannot split. Return the chicken to warm through.",
      "Cook the 12 ounces of egg noodles and serve the paprikash over them.",
    ],
  }),
];
