import { I, dish } from "./catalog-kit.ts";
import type { Recipe, RecipeSource } from "./types";

function src(book: string, author: string, year: number, era: string, archiveId: string, credit: string): RecipeSource {
  return { book, author, year, era, archiveId, credit };
}

const kephart = src("Camping and Woodcraft", "Horace Kephart", 1917, "1910s", "campingwoodcraft00keph", "Horace Kephart, Camping and Woodcraft (1917). Public domain.");
const kleber = src("The Suffrage Cook Book", "Mrs. L. O. Kleber", 1915, "1910s", "suffragecookbook00kleb", "Mrs. L. O. Kleber, The Suffrage Cook Book (Pittsburgh, 1915). Public domain.");
const hill = src("Salads, Sandwiches and Chafing Dishes", "Janet McKenzie Hill", 1909, "1900s", "saladssandwiches00hillrich", "Janet McKenzie Hill, Salads, Sandwiches and Chafing Dishes (1909). Public domain.");
const bosse = src("Chinese-Japanese Cook Book", "Sara Bosse & Onoto Watanna", 1914, "1910s", "chinesejapanesec00boss_1", "Sara Bosse and Onoto Watanna (Winnifred Eaton), Chinese-Japanese Cook Book (Rand McNally, 1914). Public domain.");
const oliveGreen = src("How to Cook Fish", "Olive Green", 1908, "1900s", "howtocookfish00gree", "Olive Green, How to Cook Fish (Putnam, 1908). Public domain.");

function h(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: Recipe["source"],
  nutrition: Recipe["nutrition"],
  /** Portions this makes. Left out, dish() stamps four, which is wrong for
   * a whole cake or a joint. */
  servings?: number,
): Recipe {
  return dish({
    id, name, cuisine, description, minutes, protein, plate,
    tags: Array.from(new Set(["vintage", ...tags])),
    ingredients, steps, nutrition, source,
      ...(servings ? { servings } : {}),
  });
}

export const TABLE_RECIPES: Recipe[] = [
  h("vh-kp-bannock", "Camp bannock", "American", ["era-1910s", "book-kephart", "camping", "vegetarian", "budget"], "veg", "skillet", 25, "Kephart's trail bread: flour, baking powder, fat, water, fried in a skillet.", [I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("lard or bacon fat", 2, "tbsp", "Pantry"), I("water", 0.75, "cup", "Other")], ["Mix the flour, baking powder, and salt. Rub in the fat until the mix looks like meal.", "Add water to make a soft dough. Pat it into a ¾-inch round.", "Heat a greased skillet over the fire or a medium burner.", "Cook 8 minutes a side, until the crust is brown and a stick in the center comes out clean. Do not burn the bottom — raise the pan if you need to.", "Serve the bannock split, hot, with bacon drippings or jam."], kephart, { cal: 285, protein: 6, carbs: 48, fat: 7 }),
  h("vh-kp-mulligan", "Camp mulligan", "American", ["era-1910s", "book-kephart", "camping", "old-school"], "beef", "soup", 90, "Kephart's hunter stew: whatever meat, potato, onion, a long pot.", [I("beef stew meat", 1.5, "lb", "Meat & Seafood"), I("potato", 4, "", "Produce"), I("onion", 2, "", "Produce"), I("carrot", 3, "", "Produce"), I("flour", 2, "tbsp", "Pantry"), I("salt", 1.5, "tsp", "Herbs & Spices")], ["Dredge the beef in flour. Brown it in a little fat in the pot, 8 minutes.", "Add the chopped onion. Cook 4 minutes. Cover with water.", "Simmer 45 minutes. Add cubed potato and carrot.", "Cook 25 minutes more, until the meat is tender and the pot is thick. Salt and pepper.", "Serve from the pot. Kephart says any game stands in for the beef."], kephart, { cal: 625, protein: 49, carbs: 44, fat: 28 }),
  h("vh-kp-trail-beans", "Trail beans", "American", ["era-1910s", "book-kephart", "camping", "budget"], "pork", "bowl", 180, "Dried beans, salt pork, a slow pot. Camp breakfast and supper.", [I("dried navy beans", 1, "lb", "Pantry"), I("salt pork", 4, "oz", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("molasses", 2, "tbsp", "Pantry"), I("mustard", 1, "tsp", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices")], ["Soak the 1 pound of dried navy beans overnight, or boil them 2 minutes and let them sit 1 hour. Drain.", "Put the beans in a pot with the 4 ounces of salt pork, diced, the chopped onion, the 2 tablespoons of molasses and the 1 teaspoon of mustard, and water to cover by an inch.", "Simmer 2 hours, adding water whenever they threaten to dry out, until the beans crush easily and the liquor is thick.", "Season with the 1 teaspoon of salt at the end — the pork has been salting the pot all along, so taste first.", "Spoon them from a cup, with bannock on the side."], kephart, { cal: 190, protein: 11, carbs: 37, fat: 1 }),
  h("vh-kp-foil-potato", "Campfire potatoes", "American", ["era-1910s", "book-kephart", "camping", "vegetarian", "gluten-free"], "veg", "roast", 50, "Whole potatoes in the coals, or wrapped if you have foil. Salt, butter.", [I("russet potatoes", 4, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Scrub the potatoes. Prick them. Rub with a little fat and salt.", "Bury in hot coals, or wrap and set at the edge of the fire, 45 minutes, until they give when squeezed.", "Split open. Add butter, salt, and pepper.", "Eat from the skin. A spoon of bacon grease if butter is short.", "Cook until the center is soft — a hard center is a wasted potato."], kephart, { cal: 235, protein: 4, carbs: 30, fat: 12 }),
  h("vh-kp-kabobs", "Scout kabobs", "American", ["era-1910s", "book-kephart", "camping"], "beef", "skillet", 25, "Meat and onion on a green stick, roasted over coals.", [I("beef sirloin", 1.5, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices"), I("bacon", 4, "slices", "Meat & Seafood")], ["Cut the beef into 1½-inch cubes. Cut the onion into wedges. Cut the bacon in half.", "Thread beef, onion, and bacon onto sticks or skewers. Salt and pepper.", "Hold or set over coals, turning, 12–15 minutes, until the beef is browned and just pink inside.", "Do not cook in the flame or the fat will catch.", "Slide off the stick onto a plate, or eat from the stick."], kephart, { cal: 480, protein: 53, carbs: 7, fat: 25 }),
  h("vh-kp-camp-coffee-stew", "Camp coffee beef", "American", ["era-1910s", "book-kephart", "camping"], "beef", "bowl", 120, "Leftover coffee in a beef stew — Kephart's trick for a dark gravy in camp.", [I("beef chuck", 2, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("strong coffee", 1, "cup", "Other"), I("water", 2, "cups", "Other"), I("potato", 3, "", "Produce"), I("flour", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Brown the cubed beef in fat 8 minutes. Add the sliced onion. Cook 4 minutes.", "Sprinkle the flour. Stir. Pour in the 1 cup of coffee and the 2 cups of water.", "Cover the pot and simmer the beef 75 minutes.", "Add cubed potato. Cook 25 minutes more, until tender.", "Salt and pepper. The coffee darkens the gravy; it should not taste like a cup of coffee."], kephart, { cal: 715, protein: 63, carbs: 32, fat: 37 }),

  h("vh-la-chicken-dumplings", "Church chicken and dumplings", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "old-school", "community"], "chicken", "soup", 80, "Ladies' Aid supper: a stewed hen, dropped dumplings on top.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("milk", 0.75, "cup", "Dairy & Eggs"), I("carrot", 3, "", "Produce"), I("celery", 3, "stalks", "Produce")], ["Cover the chicken with water. Add carrot, celery, salt. Simmer 50 minutes. Lift the chicken, pull the meat, return it. Keep the broth at a simmer.", "Stir flour, baking powder, ½ teaspoon salt, and milk into a soft dumpling dough.", "Drop spoonfuls onto the simmering broth. Cover tightly 15 minutes. Do not lift the lid.", "Cook until the dumplings are done through and the broth has thickened.", "Pepper, parsley if you have it. Serve in bowls."], undefined, { cal: 715, protein: 70, carbs: 56, fat: 23 }),
  h("vh-la-ham-loaf", "Ham loaf", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "old-school", "community"], "pork", "roast", 70, "Ground ham and pork, crumbs, a brown-sugar glaze. Church-supper slice.", [I("ground ham", 1, "lb", "Meat & Seafood"), I("ground pork", 0.5, "lb", "Meat & Seafood"), I("bread crumbs", 1, "cup", "Bakery"), I("egg", 1, "", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("brown sugar", 0.25, "cup", "Pantry")], ["Heat the oven to 350°F. Mix ham, pork, crumbs, egg, milk, pepper, and a pinch of mustard until it holds together.", "Pack the ham mixture firmly into a loaf pan.", "Stir the brown sugar with 2 tablespoons vinegar and 1 tablespoon mustard. Spread over the loaf.", "Bake 55 minutes, until the center is 160°F and the glaze is bubbling.", "Rest 10 minutes. Slice. Serve hot or cold."], undefined, { cal: 705, protein: 39, carbs: 38, fat: 44 }),
  h("vh-la-three-bean", "Three-bean salad", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "salad", "vegetarian", "vegan", "community"], "veg", "green", 15, "Green beans, wax beans, kidney beans, a sharp vinegar dressing. The covered-dish salad.", [I("green beans", 1, "lb", "Produce"), I("wax beans", 1, "lb", "Produce"), I("kidney beans", 1, "can", "Pantry"), I("onion", 0.5, "", "Produce"), I("cider vinegar", 0.5, "cup", "Pantry"), I("sugar", 0.25, "cup", "Pantry")], ["Trim the 1 pound of green beans and the 1 pound of wax beans and cook them in salted water 6 minutes, until just tender. Drain and cool them under cold water so they keep their colour.", "Drain and rinse the 1 can of kidney beans and slice the ½ onion thin.", "Heat the ½ cup of cider vinegar with the ¼ cup of sugar, the 2 tablespoons of oil, the 1 teaspoon of salt and pepper until the sugar dissolves, then cool it.", "Toss all three beans and the onion with the dressing.", "Chill at least 1 hour, and overnight if you can — it is better the next day. Serve cold."], undefined, { cal: 290, protein: 10, carbs: 47, fat: 8 }),
  h("vh-la-scalloped-potato", "Scalloped potatoes", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "vegetarian", "old-school", "community"], "veg", "roast", 75, "Sliced potatoes, milk, flour, butter, baked until the top browns.", [I("potatoes", 3, "lb", "Produce"), I("milk", 2.5, "cups", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("onion", 1, "", "Produce"), I("salt", 1.5, "tsp", "Herbs & Spices")], ["Heat the oven to 350°F. Peel and slice the potatoes thin. Slice the onion.", "Layer potato and onion in a buttered dish, dusting flour, dots of butter, salt, and pepper on each layer.", "Pour the milk over until it comes just below the top.", "Cover and bake 45 minutes. Uncover and bake 20 minutes more, until the top is gold and the potatoes are tender.", "Rest the potatoes 10 minutes. Serve them from the dish."], undefined, { cal: 495, protein: 13, carbs: 73, fat: 17 }),
  h("vh-la-jellied-fruit", "Jellied fruit salad", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "dessert", "community", "vegetarian"], "veg", "dessert", 20, "Gelatin, canned fruit, a mold. The Ladies' Aid sweet salad.", [I("lemon gelatin", 2, "boxes", "Pantry"), I("canned mixed fruit", 2, "cups", "Pantry"), I("celery", 0.5, "cup", "Produce"), I("boiling water", 2, "cups", "Other"), I("lettuce", 1, "head", "Produce")], ["Dissolve the gelatin in the boiling water. Stir until no granules remain. Add 1 cup cold water.", "Drain the fruit well. Chop the celery fine.", "When the gelatin is syrupy and just starting to thicken, fold in the fruit and celery. Pour into a mold.", "Chill the mold at least 4 hours, until the gelatin is set.", "Unmold the fruit salad onto a bed of lettuce. Serve cold. This is not baked, and there is no flour in it."], undefined, { cal: 205, protein: 6, carbs: 47, fat: 0 }),
  h("vh-la-baked-macaroni", "Ladies' Aid macaroni", "American", ["era-1880s", "book-ladies-aid", "book-suffrage", "hometown", "vegetarian", "old-school", "community"], "veg", "pasta", 45, "Elbows, a cheese sauce, crumbs. The church basement bake.", [I("elbow macaroni", 1, "lb", "Pantry"), I("cheddar", 12, "oz", "Dairy & Eggs"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("flour", 4, "tbsp", "Pantry"), I("milk", 3, "cups", "Dairy & Eggs"), I("bread crumbs", 0.75, "cup", "Bakery")], ["Heat the oven to 350°F. Boil the macaroni in salted water until just tender, 8 minutes. Drain.", "Melt the butter, add the flour, cook 2 minutes. Whisk in the milk until thick, 5 minutes. Stir in most of the cheese.", "Mix with the macaroni. Turn into a buttered pan. Top with crumbs and remaining cheese.", "Bake 25 minutes, until bubbling and the top is brown.", "Rest the macaroni 5 minutes. Serve it from the pan."], undefined, { cal: 1085, protein: 45, carbs: 115, fat: 48 }),

  h("vh-hi-tomato-aspic", "Tomato aspic", "American", ["era-1900s", "book-hill-salads", "salad", "vegetarian"], "veg", "green", 20, "Hill's molded tomato: gelatin, strained tomato, a ring mold, celery in the middle.", [I("canned tomatoes", 2, "cups", "Pantry"), I("gelatin", 2, "tbsp", "Pantry"), I("onion", 0.25, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("lemon juice", 1, "tbsp", "Produce"), I("lettuce", 1, "head", "Produce")], ["Bloom the 2 tablespoons of gelatin in ¼ cup of cold liquid drained from the 2 cups of canned tomatoes, 5 minutes.", "Simmer the rest of the tomatoes with the ¼ onion 10 minutes, then strain them, pressing the pulp.", "Stir the bloomed gelatin into the hot strained tomato until it has completely dissolved, then add the 1 tablespoon of lemon juice and the 1 teaspoon of salt.", "Pour into a ring mould and chill at least 4 hours, until firmly set.", "Unmould onto the 1 head of lettuce and fill the centre with the 2 stalks of celery, chopped.", "Serve cold. Nothing here is baked."], hill, { cal: 65, protein: 7, carbs: 10, fat: 0 }),
  h("vh-hi-chicken-salad", "Hill's chicken salad", "American", ["era-1900s", "book-hill-salads", "salad", "old-school"], "chicken", "green", 25, "Cold chicken, celery, mayonnaise. The 1909 chafing-dish-book salad.", [I("cooked chicken", 3, "cups", "Meat & Seafood"), I("celery", 1.5, "cups", "Produce"), I("mayonnaise", 0.75, "cup", "Pantry"), I("lemon juice", 1, "tbsp", "Produce"), I("lettuce", 1, "head", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Cut the chicken into small dice. Cut the celery the same size.", "Fold mayonnaise, lemon, salt, and pepper into the chicken and celery. Do not mash it.", "Chill the chicken salad 30 minutes so the dressing sets.", "Spoon the chicken salad onto lettuce leaves.", "Serve cold. Capers or a little onion if the table likes them."], hill, { cal: 515, protein: 31, carbs: 7, fat: 41 }),
  h("vh-hi-cucumber-sandwich", "Cucumber sandwiches", "American", ["era-1900s", "book-hill-salads", "sandwich", "vegetarian", "quick"], "veg", "toast", 15, "Thin bread, butter, paper-thin cucumber, a little salt. Hill's afternoon sandwich.", [I("white bread", 12, "slices", "Bakery"), I("cucumber", 1, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("white pepper", 0.25, "tsp", "Herbs & Spices")], ["Peel the cucumber. Slice it as thin as you can. Salt the slices 10 minutes, then pat dry.", "Spread butter on each slice of bread, all the way to the edges.", "Lay cucumber on half the slices. Dust with white pepper. Top with the remaining bread.", "Trim the crusts. Cut into triangles or fingers.", "Serve the same hour. They weep if they wait."], hill, { cal: 335, protein: 8, carbs: 44, fat: 14 }),
  h("vh-hi-stuffed-eggs", "Stuffed eggs", "American", ["era-1900s", "book-hill-salads", "vegetarian", "quick"], "eggs", "green", 20, "Hill's stuffed eggs: yolks mashed with butter, mustard, vinegar, piled back.", [I("eggs", 8, "", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("mustard", 1, "tsp", "Herbs & Spices"), I("vinegar", 1, "tsp", "Pantry"), I("paprika", 0.25, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Cover the eggs with cold water. Bring to a boil, then simmer 10 minutes. Cool in cold water. Peel.", "Halve the eggs the long way. Lift the yolks into a bowl.", "Mash the yolks with butter, mustard, vinegar, salt, and a pinch of cayenne until smooth.", "Pile or pipe the yolk mix back into the whites.", "Dust the stuffed eggs with paprika. Serve them cold."], hill, { cal: 195, protein: 13, carbs: 1, fat: 15 }),
  h("vh-hi-cheese-dreams", "Cheese dreams", "American", ["era-1900s", "book-hill-salads", "vegetarian", "quick"], "veg", "toast", 15, "Hill's chafing-dish cheese toast: bread, cheese, mustard, broiled until bubbling.", [I("white bread", 8, "slices", "Bakery"), I("cheddar", 8, "oz", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("mustard", 1, "tsp", "Herbs & Spices"), I("paprika", 0.25, "tsp", "Herbs & Spices")], ["Heat the broiler. Butter one side of each of the 8 slices of white bread with the 2 tablespoons of butter.", "Mix the 8 ounces of grated cheddar with the 1 teaspoon of mustard and the ¼ teaspoon of paprika.", "Spread the cheese on the unbuttered faces and set the slices buttered side down on a sheet pan.", "Broil 3–4 minutes, watching them, until the cheese bubbles and browns at the edges.", "Cut in half and serve at once, while the cheese is still molten."], hill, { cal: 430, protein: 19, carbs: 28, fat: 26 }),
  h("vh-hi-egg-salad-sandwich", "Egg salad sandwiches", "American", ["era-1900s", "book-hill-salads", "sandwich", "vegetarian"], "eggs", "toast", 20, "Chopped egg, mayonnaise, a little onion, between buttered bread.", [I("eggs", 6, "", "Dairy & Eggs"), I("mayonnaise", 0.33, "cup", "Pantry"), I("white bread", 8, "slices", "Bakery"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("onion", 1, "tbsp", "Produce"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Hard-cook the eggs 10 minutes. Cool, peel, and chop.", "Fold in mayonnaise, minced onion, salt, and pepper.", "Butter the bread. Spread the egg salad. Close the sandwiches.", "Trim crusts if it is a luncheon. Cut in half.", "Serve the egg sandwiches the same day they are made."], hill, { cal: 430, protein: 15, carbs: 28, fat: 28 }),

  h("vh-bj-miso-soup", "Miso soup", "Japanese", ["era-1910s", "book-chinese-japanese", "international", "japanese", "soup", "vegetarian"], "veg", "soup", 15, "Bosse and Watanna, 1914: miso stirred into dashi, tofu, a few greens.", [I("dashi or water", 4, "cups", "Other"), I("miso", 4, "tbsp", "Pantry"), I("tofu", 8, "oz", "Pantry"), I("scallions", 2, "", "Produce"), I("wakame or spinach", 1, "cup", "Produce")], ["Heat the 4 cups of dashi or water until it steams. Do not let it boil hard if you are using real dashi — a rolling boil turns it bitter.", "Put the 4 tablespoons of miso in a bowl, stir a ladle of the hot liquid into it until smooth, then return it to the pot.", "Add the 8 ounces of tofu, cubed, and the 1 cup of wakame or spinach, and heat 2 minutes. Never boil after the miso goes in; it goes flat and grainy.", "Taste before adding any of the 1 teaspoon of salt — miso is already salty.", "Ladle into bowls and scatter the 2 sliced scallions over each."], bosse, { cal: 115, protein: 11, carbs: 7, fat: 6 }),
  h("vh-bj-chicken-rice", "Chicken and rice, Japanese style", "Japanese", ["era-1910s", "book-chinese-japanese", "international", "japanese"], "chicken", "bowl", 40, "The 1914 book's donburi-like plate: chicken simmered with soy and sugar, over rice.", [I("chicken thighs", 1.5, "lb", "Meat & Seafood"), I("rice", 1.5, "cups", "Pantry"), I("soy sauce", 3, "tbsp", "Pantry"), I("sugar", 1, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("eggs", 2, "", "Dairy & Eggs")], ["Cook the rice in 3 cups water 18 minutes. Keep covered.", "Slice the chicken. Simmer it with soy, sugar, sliced onion, and ½ cup water 12 minutes, until cooked through to 175°F.", "Beat the eggs. Pour them over the chicken. Cover 1 minute, until just set.", "Spoon rice into bowls. Ladle chicken, onion, and egg over.", "Serve the chicken and rice at once while it is hot."], bosse, { cal: 605, protein: 45, carbs: 62, fat: 18 }),
  h("vh-bj-fried-rice", "Chinese fried rice", "Chinese", ["era-1910s", "book-chan-chinese", "international", "chinese"], "pork", "skillet", 20, "Cold rice, a little pork, egg, soy. The 1914 home-kitchen fried rice.", [I("cold cooked rice", 4, "cups", "Pantry"), I("roast pork", 6, "oz", "Meat & Seafood"), I("eggs", 2, "", "Dairy & Eggs"), I("scallions", 3, "", "Produce"), I("soy sauce", 2, "tbsp", "Pantry"), I("oil", 2, "tbsp", "Pantry")], ["Use rice that is cold and dry from the fridge. Dice the 6 ounces of roast pork and beat the 2 eggs.", "Heat the 2 tablespoons of oil in a wide pan until it is properly hot. Scramble the eggs 30 seconds, then push them to the side.", "Add the pork and the 4 cups of cold cooked rice and stir-fry 4 minutes, breaking up the clumps, until the rice is hot through.", "Add the 2 tablespoons of soy sauce and the 3 sliced scallions and toss 1 minute.", "Serve at once. Do not add water; it turns the rice gluey."], bosse, { cal: 900, protein: 25, carbs: 148, fat: 21 }),
  h("vh-bj-steamed-fish", "Ginger steamed fish", "Chinese", ["era-1910s", "book-chan-chinese", "international", "chinese", "pescatarian"], "fish", "fish", 20, "A white fish, ginger, soy, a plate over boiling water. The 1914 method.", [I("white fish fillets", 1.5, "lb", "Meat & Seafood"), I("ginger", 2, "tbsp", "Produce"), I("soy sauce", 2, "tbsp", "Pantry"), I("scallions", 3, "", "Produce"), I("sesame oil", 1, "tsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Pat the 1½ pounds of white fish fillets dry, salt them lightly with the ½ teaspoon of salt, and lay them on a heatproof plate.", "Scatter the 2 tablespoons of ginger, shredded, over the top.", "Set the plate on a rack over boiling water, cover, and steam 8–10 minutes, until the fish flakes at the thickest part.", "Pour off the watery liquid that has collected on the plate, then add the 2 tablespoons of soy sauce and the 1 teaspoon of sesame oil.", "Scatter the 3 sliced scallions over.", "Serve at once with the 1½ cups of hot rice."], bosse, { cal: 490, protein: 45, carbs: 57, fat: 8 }),
  h("vh-bj-sukiyaki", "Sukiyaki", "Japanese", ["era-1910s", "book-chinese-japanese", "international", "japanese"], "beef", "skillet", 30, "The 1914 American sukiyaki: thinly sliced beef, onion, soy, sugar, in a pan at the table.", [I("beef sirloin", 1, "lb", "Meat & Seafood"), I("onion", 2, "", "Produce"), I("soy sauce", 0.33, "cup", "Pantry"), I("sugar", 2, "tbsp", "Pantry"), I("beef broth", 1, "cup", "Pantry"), I("green onion", 4, "", "Produce")], ["Slice the beef as thin as you can, across the grain. Slice the onions.", "Heat a wide pan. Render a little of the beef fat, or use oil.", "Cook the onion 3 minutes. Add the beef and sear 2 minutes.", "Add soy, sugar, and broth. Simmer 8 minutes, until the beef is just cooked and the sauce is glossy.", "Add green onion at the end. Serve the sukiyaki with a bowl of rice."], bosse, { cal: 620, protein: 38, carbs: 70, fat: 19 }),
  h("vh-bj-cabbage-pork", "Cabbage with pork", "Chinese", ["era-1910s", "book-chan-chinese", "international", "chinese", "budget"], "pork", "skillet", 20, "Shredded cabbage, a little pork, soy. A 1914 weeknight from the Chinese-Japanese book.", [I("cabbage", 1, "head", "Produce"), I("pork loin", 8, "oz", "Meat & Seafood"), I("soy sauce", 2, "tbsp", "Pantry"), I("ginger", 1, "tsp", "Produce"), I("oil", 2, "tbsp", "Pantry"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Shred the cabbage fine. Slice the pork as thin as you can.", "Heat the oil in a wide pan until hot. Stir-fry the pork 3 minutes, until it loses its pink.", "Add ginger and cabbage. Stir-fry 5 minutes, until the cabbage wilts but still has a bite.", "Add the soy sauce. Toss the cabbage 1 minute.", "Serve the cabbage and pork with a bowl of rice."], bosse, { cal: 510, protein: 24, carbs: 69, fat: 15 }),

  h("vh-og-baked-stuffed-fish", "Baked stuffed fish", "American", ["era-1900s", "book-olive-green", "pescatarian"], "fish", "fish", 45, "Olive Green: a whole fish, crumb stuffing, baked.", [I("whole white fish", 3, "lb", "Meat & Seafood"), I("bread crumbs", 1.5, "cups", "Bakery"), I("onion", 0.5, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("parsley", 3, "tbsp", "Produce"), I("lemon", 1, "", "Produce")], ["Heat the oven to 400°F. Clean the fish. Salt the cavity.", "Cook the chopped onion in 2 tablespoons butter 4 minutes. Mix with crumbs, parsley, salt, and pepper.", "Stuff the fish. Sew or skewer the opening. Rub the skin with remaining butter.", "Bake 30 minutes, until the flesh by the bone is opaque. Baste once.", "Serve the baked fish on a platter with lemon wedges."], oliveGreen, { cal: 515, protein: 49, carbs: 32, fat: 20 }),
  h("vh-og-broiled-mackerel", "Broiled mackerel", "American", ["era-1900s", "book-olive-green", "pescatarian", "quick"], "fish", "fish", 20, "Olive Green's broiled mackerel: split, buttered, a hot broiler, lemon.", [I("mackerel", 2, "", "Meat & Seafood"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices"), I("parsley", 2, "tbsp", "Produce")], ["Heat the broiler. Split the mackerel. Pat dry. Salt and pepper.", "Melt the butter. Brush the fish on both sides.", "Broil skin-side down 5 minutes, then skin-side up 4–5 minutes, until the flesh flakes.", "Squeeze lemon over the mackerel. Scatter chopped parsley.", "Serve the mackerel at once. It waits badly once it is cooked."], oliveGreen, { cal: 225, protein: 26, carbs: 2, fat: 12 }),
  h("vh-og-fish-cakes", "Fish cakes", "American", ["era-1900s", "book-olive-green", "pescatarian", "budget"], "fish", "skillet", 30, "Leftover boiled fish, mashed potato, egg, fried cakes. Olive Green's economy plate.", [I("cooked white fish", 2, "cups", "Meat & Seafood"), I("mashed potato", 2, "cups", "Produce"), I("egg", 1, "", "Dairy & Eggs"), I("parsley", 2, "tbsp", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices")], ["Flake the fish, removing bones. Mix with the potato, egg, parsley, salt, and pepper.", "Shape into cakes ¾ inch thick. Chill 15 minutes if they feel soft.", "Fry in butter over medium heat 4 minutes a side, until a brown crust forms.", "Do not crowd the pan or the fish cakes will steam instead of brown.", "Serve the fish cakes hot, with lemon or a white sauce."], oliveGreen, { cal: 270, protein: 19, carbs: 18, fat: 13 }),
  h("vh-og-creamed-cod", "Creamed salt cod", "American", ["era-1900s", "book-olive-green", "pescatarian", "budget"], "fish", "toast", 40, "Soaked salt cod in cream sauce on toast. Olive Green's New England plate.", [I("salt cod", 1, "lb", "Meat & Seafood"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 3, "tbsp", "Pantry"), I("milk", 2, "cups", "Dairy & Eggs"), I("toast", 8, "slices", "Bakery"), I("parsley", 2, "tbsp", "Produce")], ["Soak the salt cod in cold water 12 hours, changing the water twice. Drain. Simmer 10 minutes. Flake, removing bones.", "Melt the butter, add the flour, cook 2 minutes. Whisk in the milk until smooth and thick, 4 minutes.", "Fold in the fish. Pepper. Taste before salting — it may not need any.", "Heat the creamed cod through 2 minutes. Do not let it boil.", "Spoon the creamed cod over toast. Scatter chopped parsley."], oliveGreen, { cal: 260, protein: 6, carbs: 33, fat: 11 }),
  h("vh-og-salmon-loaf", "Salmon loaf", "American", ["era-1900s", "book-olive-green", "pescatarian", "old-school"], "fish", "roast", 50, "Canned salmon, crumbs, egg, baked. Olive Green's loaf for a Friday table.", [I("canned salmon", 1, "lb", "Meat & Seafood"), I("bread crumbs", 1, "cup", "Bakery"), I("eggs", 2, "", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("lemon juice", 1, "tbsp", "Produce"), I("onion", 2, "tbsp", "Produce")], ["Heat the oven to 350°F. Drain the salmon. Remove skin and large bones. Flake it.", "Mix with crumbs, beaten eggs, milk, lemon, minced onion, salt, and pepper.", "Pack the salmon mix into a greased loaf pan.", "Bake 35–40 minutes, until set in the center.", "Rest 5 minutes. Slice. Serve with a white sauce or peas."], oliveGreen, { cal: 400, protein: 33, carbs: 22, fat: 19 }),
  h("vh-og-boiled-salmon", "Boiled salmon", "American", ["era-1900s", "book-olive-green", "pescatarian", "gluten-free"], "fish", "fish", 30, "A piece of salmon in salted water with vinegar, drained, served with a sauce.", [I("salmon", 2, "lb", "Meat & Seafood"), I("vinegar", 2, "tbsp", "Pantry"), I("salt", 1, "tbsp", "Herbs & Spices"), I("parsley", 4, "sprigs", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce")], ["Choose a pot that holds the fish. Add water, salt, vinegar, and parsley. Bring to a simmer.", "Lower the salmon in. The water should cover it. Simmer — never boil hard — 12 minutes per inch of thickness.", "The fish is done when the flesh is opaque and flakes. Lift it out carefully.", "Melt the butter with the lemon juice for a sauce.", "Serve the salmon with the butter and boiled potatoes."], oliveGreen, { cal: 555, protein: 50, carbs: 1, fat: 38 }),

  h("vh-sf-nut-bread", "Excellent nut bread", "American", ["era-1910s", "book-suffrage", "baking", "vegetarian", "old-school"], "veg", "dessert", 85, "Kleber 1915: white and graham flour, New Orleans molasses and soda — no sugar and no baking powder — and a twenty-minute rest before the oven.", [I("white flour", 2, "cups", "Pantry"), I("graham flour", 2, "cups", "Pantry"), I("molasses", 0.5, "cup", "Pantry"), I("milk", 2, "cups", "Dairy & Eggs"), I("chopped walnuts", 1, "cup", "Pantry"), I("baking soda", 1, "tsp", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Sift the 2 cups of white flour and stir the 2 cups of graham flour and the ½ teaspoon of salt in with it.", "Dissolve the 1 teaspoon of baking soda in the 2 cups of milk.", "Stir the flours, the ½ cup of molasses, the 1 cup of chopped walnuts cut up fine, the milk with the soda in it and the 2 tablespoons of melted butter together into a batter.", "Turn it into a greased loaf pan and let it raise 20 minutes on the table. Kleber is firm about that rest.", "Bake about one hour in a moderate oven, 350°F, until a straw comes out clean.", "Cool ten minutes, then turn out and slice thick."], kleber, { cal: 395, protein: 9, carbs: 61, fat: 13 }, 10),
  h("vh-sf-hot-slaw", "Hot slaw", "American", ["era-1910s", "book-suffrage", "vegetarian", "gluten-free", "old-school"], "veg", "green", 30, "Kleber: cabbage cooked twenty minutes in bacon fat and a little water with onion, and only a teaspoon each of sugar and vinegar at the very end. It must be sour-sweet.", [I("green cabbage", 1, "head", "Produce"), I("bacon fat", 1, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("sugar", 1, "tsp", "Pantry"), I("cider vinegar", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Cut the 1 small head of cabbage not too fine, and cut up the 1 onion.", "Heat the 1 tablespoon of bacon fat in a saucepan.", "Wash the cabbage and put it into the fat with a little water. Add the onion, the 1 teaspoon of salt and a little pepper.", "Cook about twenty minutes, until the cabbage is soft through.", "Then add the 1 teaspoon of sugar and the 1 teaspoon of cider vinegar. It must be sour-sweet. It is then ready to serve."], kleber, { cal: 105, protein: 3, carbs: 18, fat: 3 }),
  h("vh-sf-hawaiian-sandwich", "Hawaiian sandwiches", "American", ["era-1910s", "book-suffrage", "vegetarian", "quick", "old-school"], "veg", "toast", 15, "Kleber, entire: pimento, green pepper and a small cream cheese chopped fine with a good pinch of salt, spread between slices of buttered bread.", [I("pimento", 1, "", "Produce"), I("green pepper", 1, "", "Produce"), I("cream cheese", 3, "oz", "Dairy & Eggs"), I("white bread", 12, "slices", "Bakery"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Chop finely the 1 pimento and the 1 green pepper, freed from its seeds.", "Chop the 3 ounces of cream cheese in with them and add the good pinch of the ½ teaspoon of salt, working it until it spreads.", "Butter the 12 slices of white bread with the 3 tablespoons of butter.", "Spread the mixture between the slices of buttered bread and serve."], kleber, { cal: 395, protein: 10, carbs: 47, fat: 19 }),
  h("vh-sf-carrot-croquettes", "Carrot croquettes", "American", ["era-1910s", "book-suffrage", "vegetarian", "old-school"], "veg", "skillet", 50, "Kleber: boiled carrots through a sieve, bound with a cupful of thick white sauce and nothing else, chilled, then egged, crumbed and fried as the book's other croquettes are.", [I("carrots", 4, "", "Produce"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("flour", 2, "tbsp", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("egg", 1, "", "Dairy & Eggs"), I("bread crumbs", 1, "cup", "Bakery"), I("lard for frying", 4, "cups", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Boil the 4 large carrots until tender, about 20 minutes. Drain them and rub them through a sieve.", "Make the cupful of thick white sauce: melt the 2 tablespoons of butter, stir in the 2 tablespoons of flour and cook it two minutes, then whisk in the 1 cup of milk and cook until it is very thick.", "Add the sauce to the carrot, mix well, and season to taste with the 1 teaspoon of salt and pepper.", "When it is cold, shape it into croquettes.", "Fry them the same as the book's other croquettes: dip each in the 1 beaten egg, then in the 1 cup of bread crumbs, and fry in deep fat at 365°F until deep gold, 3 to 4 minutes. The lard stays in the pan.", "Drain them on paper and serve hot. These are a vegetable side, not a meat croquette."], kleber, { cal: 305, protein: 5, carbs: 16, fat: 25 }),
  h("vh-sf-tomato-toast", "Tomato toast", "American", ["era-1910s", "book-suffrage", "vegetarian", "quick", "old-school"], "veg", "toast", 20, "Kleber's savoury is a cheese one: butter, a spoonful of tomato and grated cheese melted together with paprika, poured over fried rounds of bread. The book's quantities serve one and are taken four times here.", [I("butter", 4, "tbsp", "Dairy & Eggs"), I("stewed tomato", 4, "tbsp", "Pantry"), I("grated cheese", 8, "oz", "Dairy & Eggs"), I("paprika", 0.5, "tsp", "Herbs & Spices"), I("white bread", 8, "slices", "Bakery"), I("butter for frying", 3, "tbsp", "Dairy & Eggs")], ["Melt the 4 tablespoons of butter and add the 4 tablespoons of stewed tomato, either canned or fresh stewed.", "Add the 8 ounces of grated cheese, sprinkle with the ½ teaspoon of paprika, and heat it on the stove until the cheese is melted and smooth.", "Cut the 8 slices of white bread into rounds or small squares and fry them in the 3 tablespoons of butter until gold on both sides.", "Pour the hot tomato mixture over each slice and serve at once, as a savoury."], kleber, { cal: 555, protein: 20, carbs: 30, fat: 40 }),
  h("vh-sf-escalloped-oysters", "Escalloped oysters", "American", ["era-1880s", "book-suffrage", "hometown", "community", "old-school"], "seafood", "roast", 40, "Burr's suffrage-book supper: oysters layered with crumbs and butter, baked until bubbling.", [I("oysters", 1, "quart", "Meat & Seafood"), I("cracker crumbs", 2, "cups", "Bakery"), I("butter", 6, "tbsp", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Heat the oven to 400°F. Drain the oysters, saving ¼ cup of the liquor. Pick over for shell.", "Butter a baking dish. Put in a layer of crumbs, then a layer of oysters, dots of butter, salt, and pepper. Repeat, ending with crumbs.", "Pour the oyster liquor and the milk around the edge — do not drown the top layer.", "Bake 25 minutes, until the top is brown and the liquor is bubbling.", "Serve hot from the dish. Do not overbake or the oysters go tough."], undefined, { cal: 555, protein: 26, carbs: 50, fat: 27 }),
];
