import { I, dish } from "./catalog-kit.ts";
import type { Recipe } from "./types";

// Cited as the edition these recipes were actually read from. The archive's
// 1918 scan is raw OCR and its two-column ingredient lists come out interleaved
// — Boston brown bread arrives spliced into New England brown bread — so the
// readings here are from the human-proofread Gutenberg text of the 1896 first
// edition. Where the 1918 printing legibly differs it is noted on the recipe.
const farmer = {
  book: "The Boston Cooking-School Cook Book",
  author: "Fannie Merritt Farmer",
  year: 1896,
  era: "1890s",
  archiveId: "bostoncookingsc00farm",
  credit:
    "Fannie Merritt Farmer, The Boston Cooking-School Cook Book (Little, Brown, 1896). Public domain. Project Gutenberg ebook 65061.",
};

const fisher = {
  book: "What Mrs. Fisher Knows About Old Southern Cooking",
  author: "Abby Fisher",
  year: 1881,
  era: "1880s",
  archiveId: "whatmrsfisherkno00fishrich",
  credit:
    "Abby Fisher, What Mrs. Fisher Knows About Old Southern Cooking (Women's Co-operative Printing Office, San Francisco, 1881). Public domain. Internet Archive whatmrsfisherkno00fishrich.",
};

function x(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: Recipe["source"],
  nutrition?: Recipe["nutrition"],
  /** Portions this makes. Left out, dish() stamps four, which is wrong for
   * a whole cake or a joint. */
  servings?: number,
): Recipe {
  return dish({
    id,
    name,
    cuisine,
    description,
    minutes,
    protein,
    plate,
    tags: Array.from(new Set(tags)),
    ingredients,
    steps,
    nutrition,
    source,
      ...(servings ? { servings } : {}),
  });
}

export const CLASSIC_RECIPES: Recipe[] = [
  x("ar-ff-parker-house-rolls", "Parker House rolls", "American", ["vintage", "era-1890s", "book-farmer", "baking", "vegetarian", "old-school"], "veg", "bowl", 180, "The Boston rolls: a buttered crease, a fold, a shine of milk.", [I("milk", 2, "cups", "Dairy & Eggs"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("yeast", 1, "cake", "Pantry"), I("flour", 5.5, "cups", "Pantry")], ["Add the 3 tablespoons of butter, the 2 tablespoons of sugar and the 1 teaspoon of salt to the 2 cups of scalded milk. When lukewarm, add the yeast cake dissolved in ¼ cup of lukewarm water and three cups of the flour.", "Beat thoroughly, cover, and let rise until light; cut down, and add enough flour to knead — it will take about two and one-half cups more.", "Let rise again, toss on a slightly floured board, knead, pat, and roll out to one-third inch thickness. Shape with a biscuit-cutter first dipped in flour.", "Dip the handle of a case knife in flour and with it make a crease through the middle of each piece; brush one half of each piece with melted butter, fold, and press the edges together.", "Place in a greased pan one inch apart, cover, let rise, and bake in a hot oven twelve to fifteen minutes. As the rolls rise they part slightly, and if hastened in rising they lose their shape."], farmer, { cal: 815, protein: 23, carbs: 144, fat: 15 }),
  x("ar-ff-boston-brown-bread", "Boston brown bread", "American", ["vintage", "era-1890s", "book-farmer", "baking", "vegetarian", "old-school"], "veg", "bowl", 210, "Rye, graham, cornmeal, molasses. Steamed in a tin, sliced hot with beans.", [I("rye meal", 1, "cup", "Pantry"), I("cornmeal", 1, "cup", "Pantry"), I("graham flour", 1, "cup", "Pantry"), I("baking soda", 0.75, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("molasses", 0.75, "cup", "Pantry"), I("sour milk", 2, "cups", "Dairy & Eggs")], ["Mix and sift the dry ingredients: the 1 cup of rye meal, the 1 cup of granulated corn meal, the 1 cup of Graham flour, the ¾ tablespoon of soda and the 1 teaspoon of salt.", "Add the ¾ cup of molasses and the 2 cups of sour milk — or 1¾ cups of sweet milk or water — and stir until well mixed.", "Turn into a well-buttered mould. The mould should never be filled more than two-thirds full. Butter the cover before putting it on and tie it down with string, or the bread rising may force it off.", "Place the mould on a trivet in a kettle of boiling water, the water coming half-way up around the mould, cover closely, and steam three and one-half hours, adding more boiling water as needed.", "A melon mould or one-pound baking-powder boxes make the best-shaped loaves, but a five-pound lard pail answers the purpose."], farmer, { cal: 655, protein: 15, carbs: 140, fat: 3 }),
  x("ar-ff-fish-chowder", "Fish chowder", "American", ["vintage", "era-1890s", "book-farmer", "soup", "old-school"], "fish", "soup", 45, "Cod, salt pork, potato, common crackers. New England in a kettle.", [I("cod or haddock", 4, "lb", "Meat & Seafood"), I("potatoes", 4, "cups", "Produce"), I("onion", 1, "", "Produce"), I("salt pork", 1, "piece", "Meat & Seafood"), I("salt", 1, "tbsp", "Herbs & Spices"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("milk", 4, "cups", "Dairy & Eggs"), I("common crackers", 8, "", "Bakery")], ["Order the 4 pounds of cod or haddock skinned, but with the head and tail left on. Cut off the head and tail and remove the fish from the backbone. Cut the fish in two-inch pieces and set aside.", "Put the head, tail and backbone broken in pieces in a stewpan, add two cups of cold water, bring slowly to the boiling-point and cook twenty minutes. That stock is what makes this a chowder rather than a milk soup.", "Cut the 1½-inch cube of fat salt pork in small pieces and try it out; add the sliced onion and fry five minutes; strain the fat into the stewpan.", "Parboil the 4 cups of potatoes, cut in ¾-inch cubes, five minutes in boiling water to cover; drain and add them to the fat, then add two cups of boiling water and cook five minutes. Add the liquor drained from the bones, then the fish; cover and simmer ten minutes.", "Add the 4 cups of scalded milk, the 1 tablespoon of salt, the ⅛ teaspoon of pepper, the 3 tablespoons of butter, and the 8 common crackers split and soaked in enough cold milk to moisten — otherwise they are soft outside and dry within."], farmer, { cal: 675, protein: 64, carbs: 50, fat: 23 }),
  x("ar-ff-lobster-newburg", "Lobster à la Newburg", "American", ["vintage", "era-1890s", "book-farmer"], "seafood", "skillet", 25, "Lobster, cream, sherry, yolks. A hotel supper on toast.", [I("lobster meat", 2, "lb", "Meat & Seafood"), I("butter", 0.25, "cup", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("cayenne", 1, "pinch", "Herbs & Spices"), I("nutmeg", 1, "pinch", "Herbs & Spices"), I("sherry", 1, "tbsp", "Other"), I("brandy", 1, "tbsp", "Other"), I("thin cream", 0.33, "cup", "Dairy & Eggs"), I("egg yolks", 2, "", "Dairy & Eggs")], ["Remove the 2 pounds of lobster meat from the shell and cut in slices.", "Melt the ¼ cup of butter, add the lobster, and cook three minutes.", "Add the ½ teaspoon of salt, a few grains of cayenne, a slight grating of nutmeg, the 1 tablespoon of Sherry and the 1 tablespoon of brandy, and cook one minute.", "Then add the ⅓ cup of thin cream and the 2 egg yolks slightly beaten. Stir until thickened — it must not boil, or the yolks curdle.", "Serve with toast or puff paste points."], farmer, { cal: 385, protein: 45, carbs: 4, fat: 20 }),
  x("ar-ff-white-sauce", "White sauce", "American", ["vintage", "era-1890s", "book-farmer", "sauce", "vegetarian"], "veg", "bowl", 12, "Butter, flour, milk. The mother sauce of the Boston kitchen.", [I("butter", 2, "tbsp", "Dairy & Eggs"), I("flour", 2, "tbsp", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices")], ["Put the 2 tablespoons of butter in a saucepan and stir until melted and bubbling.", "Add the 2 tablespoons of flour mixed with the ¼ teaspoon of salt and a few grains of pepper, and stir until thoroughly blended.", "Pour on gradually the 1 cup of scalded milk, adding about one-third at a time, stirring until well mixed.", "Then beat until smooth and glossy. If a wire whisk is used, all the milk may be added at once.", "Farmer's rule of thumb: two tablespoons each of butter and flour to one cup of liquid makes a sauce of average thickness."], farmer, { cal: 100, protein: 2, carbs: 6, fat: 8 }),
  x("ar-ff-popovers", "Popovers", "American", ["vintage", "era-1890s", "book-farmer", "baking", "breakfast", "vegetarian"], "eggs", "bowl", 40, "Eggs, milk, flour. A hot oven and they leap.", [I("flour", 1, "cup", "Pantry"), I("salt", 0.25, "tsp", "Herbs & Spices"), I("milk", 0.875, "cup", "Dairy & Eggs"), I("eggs", 2, "", "Dairy & Eggs"), I("butter", 0.5, "tsp", "Dairy & Eggs")], ["Mix the ¼ teaspoon of salt and the 1 cup of flour; add the ⅞ cup of milk gradually, in order to obtain a smooth batter.", "Add the 2 eggs, beaten until light, and the ½ teaspoon of melted butter.", "Beat two minutes with an egg-beater.", "Turn into hissing hot buttered iron gem pans. Hissing hot is the instruction, and it is what makes them climb.", "Bake thirty to thirty-five minutes in a hot oven (450°F). They may be baked in buttered earthen cups, when the bottom will have a glazed appearance."], farmer, { cal: 185, protein: 8, carbs: 26, fat: 5 }),
  x("ar-ff-molasses-gingerbread", "Soft molasses gingerbread", "American", ["vintage", "era-1890s", "book-farmer", "baking", "dessert", "vegetarian"], "veg", "dessert", 40, "Molasses, ginger, sour milk. A square for the lunch pail.", [I("molasses", 1, "cup", "Pantry"), I("butter", 0.33, "cup", "Dairy & Eggs"), I("baking soda", 1.75, "tsp", "Pantry"), I("sour milk", 0.5, "cup", "Dairy & Eggs"), I("egg", 1, "", "Dairy & Eggs"), I("flour", 2, "cups", "Pantry"), I("ground ginger", 2, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Put the ⅓ cup of butter and the 1 cup of molasses in a saucepan and cook until the boiling-point is reached.", "Remove from the fire, add the 1¾ teaspoons of soda, and beat vigorously. It foams up pale and light, and that foam is the whole leavening.", "Then add the ½ cup of sour milk and the egg well beaten.", "Add the remaining ingredients — the 2 cups of flour, the 2 teaspoons of ginger and the ½ teaspoon of salt — mixed and sifted.", "Bake fifteen minutes in buttered small tin pans, having the pans two-thirds filled with the mixture."], farmer, { cal: 635, protein: 9, carbs: 112, fat: 17 }),
  x("ar-ff-cream-tomato-soup", "Cream of tomato soup", "American", ["vintage", "era-1890s", "book-farmer", "soup", "vegetarian"], "veg", "soup", 25, "Tomato and white sauce, combined off the boil so it does not curdle.", [I("canned tomatoes", 0.5, "can", "Pantry"), I("sugar", 2, "tsp", "Pantry"), I("baking soda", 0.25, "tsp", "Pantry"), I("milk", 1, "quart", "Dairy & Eggs"), I("onion", 1, "slice", "Produce"), I("flour", 4, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("butter", 0.33, "cup", "Dairy & Eggs")], ["Scald the 1 quart of milk with the slice of onion, then remove the onion.", "Thicken the milk with the 4 tablespoons of flour diluted with cold water until thin enough to pour, being careful that the mixture is free from lumps. Cook twenty minutes, stirring constantly at first.", "Cook the ½ can of tomatoes with the 2 teaspoons of sugar fifteen minutes, add the ¼ teaspoon of soda, and rub through a sieve. The soda is what keeps the tomato from curdling the milk.", "Combine the mixtures.", "Strain into the tureen over the ⅓ cup of butter, the 1 teaspoon of salt and the ⅛ teaspoon of pepper."], farmer, { cal: 335, protein: 9, carbs: 23, fat: 23 }),
  x("ar-ff-eggs-goldenrod", "Eggs à la goldenrod", "American", ["vintage", "era-1890s", "book-farmer", "breakfast", "vegetarian"], "eggs", "toast", 20, "Chopped whites in cream sauce on toast, yolks riced over like goldenrod.", [I("hard-cooked eggs", 3, "", "Dairy & Eggs"), I("butter", 1, "tbsp", "Dairy & Eggs"), I("flour", 1, "tbsp", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("toast", 5, "slices", "Bakery"), I("parsley", 2, "sprigs", "Produce")], ["Make a thin white sauce with the 1 tablespoon of butter, the 1 tablespoon of flour, the 1 cup of milk, the ½ teaspoon of salt and the ⅛ teaspoon of pepper.", "Separate the yolks from the whites of the 3 hard-boiled eggs. Chop the whites finely and add them to the sauce.", "Cut four of the 5 slices of toast in halves lengthwise. Arrange on a platter and pour over the sauce.", "Force the yolks through a potato ricer or strainer, sprinkling over the top. Riced rather than chopped is what makes the goldenrod.", "Garnish with the parsley and the remaining slice of toast, cut in points."], farmer, { cal: 215, protein: 10, carbs: 22, fat: 10 }),
  x("ar-ff-welsh-rarebit", "Welsh rarebit", "American", ["vintage", "era-1890s", "book-farmer", "vegetarian", "quick"], "veg", "toast", 15, "Cheese melted with ale or milk, mustard, a dash of cayenne. Over toast.", [I("butter", 1, "tbsp", "Dairy & Eggs"), I("cornstarch", 1, "tsp", "Pantry"), I("thin cream", 0.5, "cup", "Dairy & Eggs"), I("soft mild cheese", 0.5, "lb", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices"), I("dry mustard", 0.25, "tsp", "Herbs & Spices"), I("cayenne", 1, "pinch", "Herbs & Spices"), I("toast", 6, "slices", "Bakery")], ["Melt the 1 tablespoon of butter, add the 1 teaspoon of corn-starch, and stir until well mixed.", "Then add the ½ cup of thin cream gradually, while stirring constantly, and cook two minutes.", "Add the ½ pound of soft mild cheese, cut in small pieces, and stir until the cheese is melted.", "Season with the ¼ teaspoon of salt, the ¼ teaspoon of mustard and a few grains of cayenne.", "Serve on zephyrettes, or on bread toasted on one side, the rarebit poured over the untoasted side. Much of the success of a rarebit depends on the quality of the cheese: it should be smooth and creamy, never stringy."], farmer, { cal: 420, protein: 19, carbs: 24, fat: 28 }),
  x("ar-ff-boston-baked-beans", "Boston baked beans", "American", ["vintage", "era-1890s", "book-farmer", "old-school"], "pork", "bowl", 480, "Pea beans, salt pork, molasses. Saturday night, Sunday breakfast.", [I("pea beans", 1, "quart", "Pantry"), I("salt pork", 0.75, "lb", "Meat & Seafood"), I("salt", 1, "tbsp", "Herbs & Spices"), I("molasses", 1, "tbsp", "Pantry"), I("sugar", 3, "tbsp", "Pantry"), I("dry mustard", 0.5, "tbsp", "Herbs & Spices")], ["Pick over the 1 quart of pea beans, cover with cold water, and soak over night.", "In the morning drain, cover with fresh water, heat slowly — keeping the water below boiling-point — and cook until the skins will burst, which is best told by taking a few beans on the tip of a spoon and blowing on them.", "Scald the rind of the ¾ pound of fat salt pork, scrape it, cut off a quarter-inch slice and put it in the bottom of the bean-pot. Cut through the rind of the rest every half inch, an inch deep. Put the beans in and bury the pork in them, leaving the rind exposed.", "Mix the 1 tablespoon of salt, the 1 tablespoon of molasses and the 3 tablespoons of sugar, add 1 cup of boiling water, and pour over the beans; then add enough more boiling water to cover. Half a tablespoon of mustard with the seasonings is said to make them more easily digested.", "Cover the pot and bake slowly six or eight hours, uncovering for the last hour so the rind browns and crisps. Add water as needed."], farmer, { cal: 120, protein: 3, carbs: 26, fat: 1 }),
  x("ar-ff-spider-corn-cake", "Spider corn cake", "American", ["vintage", "era-1890s", "book-farmer", "breakfast", "baking", "vegetarian"], "veg", "skillet", 35, "Cornmeal batter in a hot spider, a streak of sour milk down the middle.", [I("cornmeal", 1.25, "cups", "Pantry"), I("sour milk", 2, "cups", "Dairy & Eggs"), I("baking soda", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("eggs", 2, "", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Mix the 1 teaspoon of soda, the 1 teaspoon of salt and the 1¼ cups of corn meal.", "Gradually add the 2 eggs well beaten and the 2 cups of sour milk.", "Heat a frying-pan and grease the sides and bottom with the 2 tablespoons of butter. Greasing the sides as well as the bottom is what lets the cake climb them.", "Turn in the mixture.", "Place on the middle grate in a hot oven and cook twenty minutes."], farmer, { cal: 320, protein: 11, carbs: 46, fat: 10 }),
  x("ar-ff-chocolate-fudge", "Chocolate fudge", "American", ["american", "dessert", "vegetarian", "old-school"], "veg", "dessert", 30, "Sugar, milk, chocolate, butter. Beat until it begins to grain, pour, cut.", [I("sugar", 2, "cups", "Pantry"), I("milk", 0.67, "cups", "Dairy & Eggs"), I("unsweetened chocolate", 2, "oz", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("vanilla", 1, "tsp", "Pantry")], ["Butter a shallow pan. Put the sugar, milk, and chopped chocolate in a saucepan.", "Boil, stirring until the sugar dissolves, then cook without stirring to the soft-ball stage, 234°F, about 8 minutes.", "Take off the heat. Add the butter and vanilla. Do not stir yet. Cool until the pan is just warm, about 10 minutes.", "Beat until the fudge thickens and begins to grain, 3–5 minutes. Pour into the pan.", "When it is just set, cut into squares. This is candy, not a cake, and it is not baked."], undefined, { cal: 545, protein: 2, carbs: 111, fat: 11 }),
  x("ar-mf-jumberlie", "Jumberlie à la Creole", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "old-school"], "chicken", "bowl", 60, "Abby Fisher's jambalaya: rice, chicken or shrimp, tomato, pepper. San Francisco, 1881.", [I("rice", 2, "cups", "Pantry"), I("chicken", 1, "lb", "Meat & Seafood"), I("tomatoes", 4, "", "Produce"), I("onion", 1, "", "Produce"), I("green pepper", 1, "", "Produce"), I("ham", 0.25, "lb", "Meat & Seafood")], ["Cut the chicken and ham into pieces. Chop the onion and the green pepper.", "Fry the onion, pepper, ham, and chicken in a little fat 8 minutes, until they take color.", "Add the chopped tomatoes, the rice, salt, cayenne, and water to cover by ½ inch.", "Cover the pot tightly. Cook over low heat 25 minutes, without stirring, until the rice is steam-tender, the liquid is gone, and the chicken reads 175°F.", "Rest 5 minutes with the lid on. Fluff. Serve from the pot. This is Fisher's jumberlie, not a soup."], fisher, { cal: 565, protein: 33, carbs: 85, fat: 10 }),
  x("ar-mf-ochra-gumbo", "Ochra gumbo", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "soup", "old-school"], "beef", "soup", 90, "Mrs. Fisher's okra gumbo with beef and tomato. A long, quiet stew.", [I("okra", 2, "lb", "Produce"), I("beef", 1.5, "lb", "Meat & Seafood"), I("tomatoes", 4, "", "Produce"), I("onion", 1, "", "Produce"), I("green pepper", 1, "", "Produce"), I("flour", 2, "tbsp", "Pantry")], ["Cut the beef into cubes. Brown it in a heavy pot 8 minutes. Sprinkle the flour and stir 1 minute.", "Add the chopped onion and green pepper. Cook 4 minutes. Add the chopped tomatoes and the sliced okra.", "Pour in water to cover. Salt and pepper.", "Simmer 1½ hours, until the beef is tender and the okra silk has thickened the pot. Do not rush it.", "Serve in bowls over boiled rice. This is gumbo, not a fried dish."], fisher, { cal: 755, protein: 56, carbs: 86, fat: 22 }),
  x("ar-mf-sweet-potato-pie", "Sweet potato pie", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "dessert", "baking"], "veg", "dessert", 70, "Boiled sweets, butter, sugar, spice, a paste crust. Her San Francisco pie.", [I("sweet potatoes", 3, "", "Produce"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("sugar", 0.75, "cups", "Pantry"), I("eggs", 3, "", "Dairy & Eggs"), I("milk", 0.5, "cups", "Dairy & Eggs"), I("pie crust", 1, "", "Bakery")], ["Boil the sweet potatoes in their skins until tender, 25 minutes. Drain, peel, and mash them smooth.", "Heat the oven to 375°F. Lay the crust in a pie tin.", "Beat the butter, sugar, eggs, and milk into the warm potato. Add nutmeg and cinnamon.", "Pour the sweet-potato filling into the crust.", "Bake 40 minutes, until the center is set and a knife comes out clean. Cool before slicing."], fisher, { cal: 695, protein: 11, carbs: 91, fat: 33 }),
  x("ar-mf-corn-bread", "Mrs. Fisher's corn bread", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "baking", "vegetarian"], "veg", "bowl", 35, "White cornmeal, buttermilk, a hot pan. Breakfast bread from 1881.", [I("white cornmeal", 2, "cups", "Pantry"), I("buttermilk", 2, "cups", "Dairy & Eggs"), I("eggs", 2, "", "Dairy & Eggs"), I("lard or butter", 2, "tbsp", "Dairy & Eggs"), I("soda", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 400°F. Grease a pan with a little of the 2 tablespoons of lard or butter and set it in the oven to get hot.", "Beat the 2 eggs. Stir in the 2 cups of white cornmeal, the 1 teaspoon of salt and the rest of the fat, melted.", "Dissolve the 1 teaspoon of soda in the 2 cups of buttermilk. Pour it into the meal and beat until the batter is even.", "Pour the batter into the hot pan. It should sizzle as it goes in — that is what gives the crust.", "Bake 25 minutes, until the top is gold and a toothpick comes out clean. Serve hot from the pan."], fisher, { cal: 440, protein: 14, carbs: 69, fat: 11 }),
  x("ar-mf-fried-chicken", "Mrs. Fisher's fried chicken", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "old-school"], "chicken", "skillet", 40, "Jointed chicken, salted, floured, fried in lard. The 1881 method.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 1, "cups", "Pantry"), I("lard", 1, "cups", "Pantry"), I("salt", 2, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices")], ["Joint the chicken into serving pieces. Pat dry. Salt and pepper both sides.", "Dredge each piece in flour, shaking off the extra.", "Heat the lard in a deep skillet until a pinch of flour sizzles at once, about 350°F.", "Fry the chicken without crowding, 8–10 minutes a side, until the crust is deep gold and a thermometer at the thickest joint reads 175°F. Running juices are not a doneness test — the colour clears well before the meat is safe. Turn only once.", "Drain on paper. Serve hot. This is fried in lard, not baked."], fisher, { cal: 795, protein: 62, carbs: 7, fat: 57 }),
  x("ar-mf-ginger-cookies", "Mrs. Fisher's ginger cookies", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "cookies", "baking", "dessert", "vegetarian"], "veg", "dessert", 30, "Molasses ginger cakes, rolled thin, cut, baked quick.", [I("molasses", 1, "cups", "Pantry"), I("sugar", 0.5, "cups", "Pantry"), I("lard or butter", 0.5, "cups", "Dairy & Eggs"), I("flour", 4, "cups", "Pantry"), I("ginger", 2, "tbsp", "Herbs & Spices"), I("soda", 1, "tsp", "Pantry")], ["Heat the oven to 375°F. Warm the 1 cup of molasses, the ½ cup of lard or butter and the ½ cup of sugar together until the fat melts. Cool until just warm — hot syrup would cook the flour into a paste.", "Stir in the 2 tablespoons of ginger and the 1 teaspoon of soda dissolved in a spoon of water. It will foam.", "Work in the 4 cups of flour until you have a dough you can roll. Chill 15 minutes if it is sticky.", "Roll thin on a floured board and cut into rounds.", "Bake 8 minutes, until the edges are set. Cool them on the sheet; they crisp as they cool."], fisher, { cal: 135, protein: 2, carbs: 24, fat: 4 }, 30),
  x("ar-mf-chow-chow", "Mrs. Fisher's chow-chow", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "sauce", "vegetarian", "vegan"], "veg", "bowl", 180, "Chopped pickle relish: cauliflower, cucumber, onion, mustard, vinegar.", [I("green tomatoes", 4, "lb", "Produce"), I("cucumbers", 6, "", "Produce"), I("onions", 6, "", "Produce"), I("cauliflower", 1, "head", "Produce"), I("mustard", 0.5, "cups", "Herbs & Spices"), I("vinegar", 6, "cups", "Pantry"), I("turmeric", 1, "tbsp", "Herbs & Spices"), I("sugar", 1, "cup", "Pantry")], ["Chop the 4 pounds of green tomatoes, the 6 cucumbers, the 6 onions and the 1 head of cauliflower small. Layer them in a crock with the 1 teaspoon of salt and leave overnight, then drain them well in the morning.", "Boil the 6 cups of vinegar with the ½ cup of mustard, the 1 tablespoon of turmeric and the 1 cup of sugar 5 minutes.", "Pour the hot vinegar over the drained vegetables in a preserving kettle.", "Simmer 15 minutes, until everything is hot through but not mushy — the cauliflower should still have some bite.", "Ladle into clean jars while hot and screw the lids on.", "This is a refrigerator relish, not a canned one: a hot fill is not processing, so cool the jars and keep them in the fridge. They hold about a month."], fisher, { cal: 60, protein: 2, carbs: 12, fat: 0 }, 40),
];
