import { I, dish } from "./catalog-kit.ts";
import type { Recipe } from "./types";

// Cited as the edition these recipes were actually read from. The archive's
// 1918 scan is raw OCR and its two-column ingredient lists come out interleaved
// — Boston brown bread arrives spliced into New England brown bread — so the
// readings here are from the human-proofread Gutenberg text of the 1896 first
// edition. Where the 1918 printing legibly differs it is noted on the recipe.
const farmer = {
  book: "The Boston Cooking-School Cook Book",
  author: "Fannie Merritt Farmer",
  year: 1896,
  era: "1890s",
  archiveId: "bostoncookingsc00farm",
  credit:
    "Fannie Merritt Farmer, The Boston Cooking-School Cook Book (Little, Brown, 1896). Public domain. Project Gutenberg ebook 65061.",
};

const fisher = {
  book: "What Mrs. Fisher Knows About Old Southern Cooking",
  author: "Abby Fisher",
  year: 1881,
  era: "1880s",
  archiveId: "whatmrsfisherkno00fishrich",
  credit:
    "Abby Fisher, What Mrs. Fisher Knows About Old Southern Cooking (Women's Co-operative Printing Office, San Francisco, 1881). Public domain. Internet Archive whatmrsfisherkno00fishrich.",
};

function x(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: Recipe["source"],
  nutrition?: Recipe["nutrition"],
  /** Portions this makes. Left out, dish() stamps four, which is wrong for
   * a whole cake or a joint. */
  servings?: number,
  /** Other names the dish goes by, so a book's spelling of the title
   * does not hide it from search. */
  aliases?: string[],
): Recipe {
  return dish({
    id,
    name,
    cuisine,
    description,
    minutes,
    protein,
    plate,
    tags: Array.from(new Set(tags)),
    ingredients,
    steps,
    nutrition,
    source,
      ...(servings ? { servings } : {}),
      ...(aliases && aliases.length ? { aliases } : {}),
  });
}

export const CLASSIC_RECIPES: Recipe[] = [
  x("ar-ff-parker-house-rolls", "Parker House rolls", "American", ["vintage", "era-1890s", "book-farmer", "baking", "vegetarian", "old-school"], "veg", "bowl", 180, "The Boston rolls: a buttered crease, a fold, a shine of milk.", [I("milk", 2, "cups", "Dairy & Eggs"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("yeast", 1, "cake", "Pantry"), I("flour", 5.5, "cups", "Pantry")], ["Add the 3 tablespoons of butter, the 2 tablespoons of sugar and the 1 teaspoon of salt to the 2 cups of scalded milk. When lukewarm, add the yeast cake dissolved in ¼ cup of lukewarm water and three cups of the flour.", "Beat thoroughly, cover, and let rise until light; cut down, and add enough flour to knead — it will take about two and one-half cups more.", "Let rise again, toss on a slightly floured board, knead, pat, and roll out to one-third inch thickness. Shape with a biscuit-cutter first dipped in flour.", "Dip the handle of a case knife in flour and with it make a crease through the middle of each piece; brush one half of each piece with melted butter, fold, and press the edges together.", "Place in a greased pan one inch apart, cover, let rise, and bake in a hot oven twelve to fifteen minutes. As the rolls rise they part slightly, and if hastened in rising they lose their shape."], farmer, { cal: 815, protein: 23, carbs: 144, fat: 15 }),
  x("ar-ff-boston-brown-bread", "Boston brown bread", "American", ["vintage", "era-1890s", "book-farmer", "baking", "vegetarian", "old-school"], "veg", "bowl", 210, "Rye, graham, cornmeal, molasses. Steamed in a tin, sliced hot with beans.", [I("rye meal", 1, "cup", "Pantry"), I("cornmeal", 1, "cup", "Pantry"), I("graham flour", 1, "cup", "Pantry"), I("baking soda", 0.75, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("molasses", 0.75, "cup", "Pantry"), I("sour milk", 2, "cups", "Dairy & Eggs")], ["Mix and sift the dry ingredients: the 1 cup of rye meal, the 1 cup of granulated corn meal, the 1 cup of Graham flour, the ¾ tablespoon of soda and the 1 teaspoon of salt.", "Add the ¾ cup of molasses and the 2 cups of sour milk — or 1¾ cups of sweet milk or water — and stir until well mixed.", "Turn into a well-buttered mould. The mould should never be filled more than two-thirds full. Butter the cover before putting it on and tie it down with string, or the bread rising may force it off.", "Place the mould on a trivet in a kettle of boiling water, the water coming half-way up around the mould, cover closely, and steam three and one-half hours, adding more boiling water as needed.", "A melon mould or one-pound baking-powder boxes make the best-shaped loaves, but a five-pound lard pail answers the purpose."], farmer, { cal: 655, protein: 15, carbs: 140, fat: 3 }),
  x("ar-ff-fish-chowder", "Fish chowder", "American", ["vintage", "era-1890s", "book-farmer", "soup", "old-school"], "fish", "soup", 45, "Cod, salt pork, potato, common crackers. New England in a kettle.", [I("cod or haddock", 4, "lb", "Meat & Seafood"), I("potatoes", 4, "cups", "Produce"), I("onion", 1, "", "Produce"), I("salt pork", 1, "piece", "Meat & Seafood"), I("salt", 1, "tbsp", "Herbs & Spices"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("milk", 4, "cups", "Dairy & Eggs"), I("common crackers", 8, "", "Bakery")], ["Order the 4 pounds of cod or haddock skinned, but with the head and tail left on. Cut off the head and tail and remove the fish from the backbone. Cut the fish in two-inch pieces and set aside.", "Put the head, tail and backbone broken in pieces in a stewpan, add two cups of cold water, bring slowly to the boiling-point and cook twenty minutes. That stock is what makes this a chowder rather than a milk soup.", "Cut the 1½-inch cube of fat salt pork in small pieces and try it out; add the sliced onion and fry five minutes; strain the fat into the stewpan.", "Parboil the 4 cups of potatoes, cut in ¾-inch cubes, five minutes in boiling water to cover; drain and add them to the fat, then add two cups of boiling water and cook five minutes. Add the liquor drained from the bones, then the fish; cover and simmer ten minutes.", "Add the 4 cups of scalded milk, the 1 tablespoon of salt, the ⅛ teaspoon of pepper, the 3 tablespoons of butter, and the 8 common crackers split and soaked in enough cold milk to moisten — otherwise they are soft outside and dry within."], farmer, { cal: 750, protein: 64, carbs: 50, fat: 31 }),
  x("ar-ff-lobster-newburg", "Lobster \u00e0 la Newburg", "American", ["vintage", "era-1890s", "book-farmer"], "seafood", "skillet", 25, "Lobster, cream, sherry, yolks. A hotel supper on toast.", [I("lobster meat", 2, "lb", "Meat & Seafood"), I("butter", 0.25, "cup", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("cayenne", 1, "pinch", "Herbs & Spices"), I("nutmeg", 1, "pinch", "Herbs & Spices"), I("sherry", 1, "tbsp", "Other"), I("brandy", 1, "tbsp", "Other"), I("thin cream", 0.33, "cup", "Dairy & Eggs"), I("egg yolks", 2, "", "Dairy & Eggs")], ["Remove the 2 pounds of lobster meat from the shell and cut in slices.", "Melt the ¼ cup of butter, add the lobster, and cook three minutes.", "Add the ½ teaspoon of salt, a few grains of cayenne, a slight grating of nutmeg, the 1 tablespoon of Sherry and the 1 tablespoon of brandy, and cook one minute.", "Then add the ⅓ cup of thin cream and the 2 egg yolks slightly beaten. Stir until thickened — it must not boil, or the yolks curdle.", "Serve with toast or puff paste points."], farmer, { cal: 385, protein: 45, carbs: 4, fat: 20 }, undefined, ["lobster newburg", "newburg"]),
  x("ar-ff-white-sauce", "White sauce", "American", ["vintage", "era-1890s", "book-farmer", "sauce", "vegetarian"], "veg", "bowl", 12, "Butter, flour, milk. The mother sauce of the Boston kitchen.", [I("butter", 2, "tbsp", "Dairy & Eggs"), I("flour", 2, "tbsp", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices")], ["Put the 2 tablespoons of butter in a saucepan and stir until melted and bubbling.", "Add the 2 tablespoons of flour mixed with the ¼ teaspoon of salt and a few grains of pepper, and stir until thoroughly blended.", "Pour on gradually the 1 cup of scalded milk, adding about one-third at a time, stirring until well mixed.", "Then beat until smooth and glossy. If a wire whisk is used, all the milk may be added at once.", "Farmer's rule of thumb: two tablespoons each of butter and flour to one cup of liquid makes a sauce of average thickness."], farmer, { cal: 100, protein: 2, carbs: 6, fat: 8 }),
  x("ar-ff-popovers", "Popovers", "American", ["vintage", "era-1890s", "book-farmer", "baking", "breakfast", "vegetarian"], "eggs", "bowl", 40, "Eggs, milk, flour. A hot oven and they leap.", [I("flour", 1, "cup", "Pantry"), I("salt", 0.25, "tsp", "Herbs & Spices"), I("milk", 0.875, "cup", "Dairy & Eggs"), I("eggs", 2, "", "Dairy & Eggs"), I("butter", 0.5, "tsp", "Dairy & Eggs")], ["Mix the ¼ teaspoon of salt and the 1 cup of flour; add the ⅞ cup of milk gradually, in order to obtain a smooth batter.", "Add the 2 eggs, beaten until light, and the ½ teaspoon of melted butter.", "Beat two minutes with an egg-beater.", "Turn into hissing hot buttered iron gem pans. Hissing hot is the instruction, and it is what makes them climb.", "Bake thirty to thirty-five minutes in a hot oven (450°F). They may be baked in buttered earthen cups, when the bottom will have a glazed appearance."], farmer, { cal: 185, protein: 8, carbs: 26, fat: 5 }),
  x("ar-ff-molasses-gingerbread", "Soft molasses gingerbread", "American", ["vintage", "era-1890s", "book-farmer", "baking", "dessert", "vegetarian"], "veg", "dessert", 40, "Molasses, ginger, sour milk. A square for the lunch pail.", [I("molasses", 1, "cup", "Pantry"), I("butter", 0.33, "cup", "Dairy & Eggs"), I("baking soda", 1.75, "tsp", "Pantry"), I("sour milk", 0.5, "cup", "Dairy & Eggs"), I("egg", 1, "", "Dairy & Eggs"), I("flour", 2, "cups", "Pantry"), I("ground ginger", 2, "tsp", "Herbs & Spices"), I("salt", 0.5, "tsp", "Herbs & Spices")], ["Put the ⅓ cup of butter and the 1 cup of molasses in a saucepan and cook until the boiling-point is reached.", "Remove from the fire, add the 1¾ teaspoons of soda, and beat vigorously. It foams up pale and light, and that foam is the whole leavening.", "Then add the ½ cup of sour milk and the egg well beaten.", "Add the remaining ingredients — the 2 cups of flour, the 2 teaspoons of ginger and the ½ teaspoon of salt — mixed and sifted.", "Bake fifteen minutes in buttered small tin pans, having the pans two-thirds filled with the mixture."], farmer, { cal: 635, protein: 9, carbs: 112, fat: 17 }),
  x("ar-ff-cream-tomato-soup", "Cream of tomato soup", "American", ["vintage", "era-1890s", "book-farmer", "soup", "vegetarian"], "veg", "soup", 25, "Tomato and white sauce, combined off the boil so it does not curdle.", [I("canned tomatoes", 0.5, "can", "Pantry"), I("sugar", 2, "tsp", "Pantry"), I("baking soda", 0.25, "tsp", "Pantry"), I("milk", 1, "quart", "Dairy & Eggs"), I("onion", 1, "slice", "Produce"), I("flour", 4, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("butter", 0.33, "cup", "Dairy & Eggs")], ["Scald the 1 quart of milk with the slice of onion, then remove the onion.", "Thicken the milk with the 4 tablespoons of flour diluted with cold water until thin enough to pour, being careful that the mixture is free from lumps. Cook twenty minutes, stirring constantly at first.", "Cook the ½ can of tomatoes with the 2 teaspoons of sugar fifteen minutes, add the ¼ teaspoon of soda, and rub through a sieve. The soda is what keeps the tomato from curdling the milk.", "Combine the mixtures.", "Strain into the tureen over the ⅓ cup of butter, the 1 teaspoon of salt and the ⅛ teaspoon of pepper."], farmer, { cal: 335, protein: 9, carbs: 23, fat: 23 }),
  x("ar-ff-eggs-goldenrod", "Eggs \u00e0 la goldenrod", "American", ["vintage", "era-1890s", "book-farmer", "breakfast", "vegetarian"], "eggs", "toast", 20, "Chopped whites in cream sauce on toast, yolks riced over like goldenrod.", [I("hard-cooked eggs", 3, "", "Dairy & Eggs"), I("butter", 1, "tbsp", "Dairy & Eggs"), I("flour", 1, "tbsp", "Pantry"), I("milk", 1, "cup", "Dairy & Eggs"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("toast", 5, "slices", "Bakery"), I("parsley", 2, "sprigs", "Produce")], ["Make a thin white sauce with the 1 tablespoon of butter, the 1 tablespoon of flour, the 1 cup of milk, the ½ teaspoon of salt and the ⅛ teaspoon of pepper.", "Separate the yolks from the whites of the 3 hard-boiled eggs. Chop the whites finely and add them to the sauce.", "Cut four of the 5 slices of toast in halves lengthwise. Arrange on a platter and pour over the sauce.", "Force the yolks through a potato ricer or strainer, sprinkling over the top. Riced rather than chopped is what makes the goldenrod.", "Garnish with the parsley and the remaining slice of toast, cut in points."], farmer, { cal: 215, protein: 10, carbs: 22, fat: 10 }, undefined, ["eggs goldenrod", "creamed eggs on toast"]),
  x("ar-ff-welsh-rarebit", "Welsh rarebit", "American", ["vintage", "era-1890s", "book-farmer", "vegetarian", "quick"], "veg", "toast", 15, "Cheese melted with ale or milk, mustard, a dash of cayenne. Over toast.", [I("butter", 1, "tbsp", "Dairy & Eggs"), I("cornstarch", 1, "tsp", "Pantry"), I("thin cream", 0.5, "cup", "Dairy & Eggs"), I("soft mild cheese", 0.5, "lb", "Dairy & Eggs"), I("salt", 0.25, "tsp", "Herbs & Spices"), I("dry mustard", 0.25, "tsp", "Herbs & Spices"), I("cayenne", 1, "pinch", "Herbs & Spices"), I("toast", 6, "slices", "Bakery")], ["Melt the 1 tablespoon of butter, add the 1 teaspoon of corn-starch, and stir until well mixed.", "Then add the ½ cup of thin cream gradually, while stirring constantly, and cook two minutes.", "Add the ½ pound of soft mild cheese, cut in small pieces, and stir until the cheese is melted.", "Season with the ¼ teaspoon of salt, the ¼ teaspoon of mustard and a few grains of cayenne.", "Serve on zephyrettes, or on bread toasted on one side, the rarebit poured over the untoasted side. Much of the success of a rarebit depends on the quality of the cheese: it should be smooth and creamy, never stringy."], farmer, { cal: 420, protein: 19, carbs: 24, fat: 28 }),
  x("ar-ff-boston-baked-beans", "Boston baked beans", "American", ["vintage", "era-1890s", "book-farmer", "old-school"], "pork", "bowl", 480, "Pea beans, salt pork, molasses. Saturday night, Sunday breakfast.", [I("pea beans", 1, "quart", "Pantry"), I("salt pork", 0.75, "lb", "Meat & Seafood"), I("salt", 1, "tbsp", "Herbs & Spices"), I("molasses", 1, "tbsp", "Pantry"), I("sugar", 3, "tbsp", "Pantry"), I("dry mustard", 0.5, "tbsp", "Herbs & Spices")], ["Pick over the 1 quart of pea beans, cover with cold water, and soak over night.", "In the morning drain, cover with fresh water, heat slowly — keeping the water below boiling-point — and cook until the skins will burst, which is best told by taking a few beans on the tip of a spoon and blowing on them.", "Scald the rind of the ¾ pound of fat salt pork, scrape it, cut off a quarter-inch slice and put it in the bottom of the bean-pot. Cut through the rind of the rest every half inch, an inch deep. Put the beans in and bury the pork in them, leaving the rind exposed.", "Mix the 1 tablespoon of salt, the 1 tablespoon of molasses and the 3 tablespoons of sugar, add 1 cup of boiling water, and pour over the beans; then add enough more boiling water to cover. Half a tablespoon of mustard with the seasonings is said to make them more easily digested.", "Cover the pot and bake slowly six or eight hours, uncovering for the last hour so the rind browns and crisps. Add water as needed."], farmer, { cal: 755, protein: 7, carbs: 26, fat: 70 }),
  x("ar-ff-spider-corn-cake", "Spider corn cake", "American", ["vintage", "era-1890s", "book-farmer", "breakfast", "baking", "vegetarian"], "veg", "skillet", 35, "Cornmeal batter in a hot spider, a streak of sour milk down the middle.", [I("cornmeal", 1.25, "cups", "Pantry"), I("sour milk", 2, "cups", "Dairy & Eggs"), I("baking soda", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("eggs", 2, "", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Mix the 1 teaspoon of soda, the 1 teaspoon of salt and the 1¼ cups of corn meal.", "Gradually add the 2 eggs well beaten and the 2 cups of sour milk.", "Heat a frying-pan and grease the sides and bottom with the 2 tablespoons of butter. Greasing the sides as well as the bottom is what lets the cake climb them.", "Turn in the mixture.", "Place on the middle grate in a hot oven and cook twenty minutes."], farmer, { cal: 320, protein: 11, carbs: 46, fat: 10 }),
  x("ar-ff-chocolate-fudge", "Chocolate fudge", "American", ["american", "dessert", "vegetarian", "old-school"], "veg", "dessert", 30, "Sugar, milk, chocolate, butter. Beat until it begins to grain, pour, cut.", [I("sugar", 2, "cups", "Pantry"), I("milk", 0.67, "cups", "Dairy & Eggs"), I("unsweetened chocolate", 2, "oz", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("vanilla", 1, "tsp", "Pantry")], ["Butter a shallow pan. Put the sugar, milk, and chopped chocolate in a saucepan.", "Boil, stirring until the sugar dissolves, then cook without stirring to the soft-ball stage, 234°F, about 8 minutes.", "Take off the heat. Add the butter and vanilla. Do not stir yet. Cool until the pan is just warm, about 10 minutes.", "Beat until the fudge thickens and begins to grain, 3–5 minutes. Pour into the pan.", "When it is just set, cut into squares. This is candy, not a cake, and it is not baked."], undefined, { cal: 545, protein: 2, carbs: 111, fat: 11 }),
  x("ar-mf-jumberlie", "Jumberlie \u00e0 la Creole", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "old-school"], "chicken", "bowl", 60, "Abby Fisher's Creole dish: a jointed chicken, a pint of rice, six tomatoes and sweet ham. No water at all.", [I("chicken", 1, "bird", "Meat & Seafood"), I("rice", 1, "pint", "Pantry"), I("tomatoes", 6, "", "Produce"), I("ham", 0.5, "lb", "Meat & Seafood"), I("salt", 1, "tsp", "Herbs & Spices")], ["Take one chicken and cut it up, separating every joint, and add to it one pint of cleanly-washed rice.", "Take about half a dozen large tomatoes, scalding them well and taking the skins off with a knife. Cut them in small pieces and put them with the chicken in a pot or large porcelain saucepan.", "Then cut in small pieces two large pieces of sweet ham and add to the rest, seasoning high with pepper and salt.", "Do not put any water on it. The tomatoes are the liquid, which is why they are skinned and cut small rather than left in wedges.", "It will cook in twenty-five minutes. Check the chicken reads 175°F at the thickest joint before serving."], fisher, { cal: 885, protein: 79, carbs: 83, fat: 26 }, undefined, ["jambalaya", "jumberlie"]),
  x("ar-mf-ochra-gumbo", "Ochra gumbo", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "soup", "old-school"], "beef", "soup", 90, "A cracked beef shank boiled down to half, strained, and okra cut into the broth. Dry boiled rice alongside.", [I("beef shank", 1, "", "Meat & Seafood"), I("okra", 2, "lb", "Produce"), I("rice", 1.5, "cups", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Get a beef shank, have it cracked, and put it to boil in one gallon of water.", "Boil it down to half a gallon, then strain and put the broth back on the fire. That long reduction is the whole body of this gumbo — there is no roux and no tomato in it.", "Cut the 2 pounds of ochra in small pieces and put them in the soup. Don't put in any ends of ochra.", "Season with salt and pepper while cooking. Stir it occasionally and keep it from burning.", "To be sent to table with dry boiled rice. Season the rice with salt when it first goes on, don't have too much water in it, and never stir it while boiling."], fisher, { cal: 555, protein: 35, carbs: 72, fat: 14 }),
  x("ar-mf-sweet-potato-pie", "Sweet potato pie", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "dessert", "baking"], "veg", "dessert", 70, "Two pounds of potatoes make two pies. Orange juice and rind, five eggs beaten separate, one crust.", [I("sweet potatoes", 2, "lb", "Produce"), I("butter", 1, "tbsp", "Dairy & Eggs"), I("eggs", 5, "", "Dairy & Eggs"), I("milk", 0.5, "cup", "Dairy & Eggs"), I("sugar", 0.75, "cup", "Pantry"), I("orange", 1, "", "Produce"), I("salt", 0.5, "tsp", "Herbs & Spices"), I("pie crust", 2, "rounds", "Bakery")], ["Two pounds of potatoes will make two pies. Boil the potatoes soft, peel them, and mash fine through a colander while hot.", "One tablespoonful of butter is to be mashed in with the potato, and half a teaspoonful of salt.", "Take five eggs and beat the yolks and the whites separate, and add one gill of milk. Sweeten to taste.", "Squeeze the juice of one orange and grate one-half of the peel into the liquid. The orange is the flavouring here — there is no cinnamon and no nutmeg in it.", "Have only one crust, and that at the bottom of the plate. Bake quickly, until the centre is set."], fisher, { cal: 505, protein: 10, carbs: 69, fat: 22 }, 8),
  x("ar-mf-corn-bread", "Mrs. Fisher's corn egg bread", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "baking", "vegetarian"], "veg", "bowl", 35, "Two eggs, a pint of meal, half a pint of sour milk and a spoonful of soda. Beaten light, baked in an ordinary pan.", [I("cornmeal", 1, "pint", "Pantry"), I("sour milk", 0.5, "pint", "Dairy & Eggs"), I("eggs", 2, "", "Dairy & Eggs"), I("baking soda", 1, "tsp", "Pantry"), I("lard", 1, "tbsp", "Pantry")], ["Beat the 2 eggs very light. The book says so twice over; the eggs are the only lift this bread has besides the soda.", "Add the 1 pint of meal, the half pint of sour milk and the 1 teaspoonful of soda.", "Add the 1 tablespoonful of melted lard or butter.", "Mix all together, well stirred or beaten.", "Bake in an ordinary pan in a hot oven (400°F), about 25 minutes, until the top is gold and a straw comes out clean."], fisher, { cal: 385, protein: 12, carbs: 66, fat: 8 }),
  x("ar-mf-fried-chicken", "Mrs. Fisher's fried chicken", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "old-school"], "chicken", "skillet", 40, "Jointed, floured, dropped in very hot fat — and then a brown flour gravy made in the same skillet.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 1, "cup", "Pantry"), I("lard", 1, "cup", "Pantry"), I("salt", 2, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices")], ["Cut the chicken up, separating every joint, and wash clean.", "Salt and pepper it, and roll it into the 1 cup of flour well.", "Have your fat very hot, and drop the pieces into it, and let them cook brown. The book's test is that the chicken is done when the fork passes easily into it; a thermometer at the thickest joint should read 175°F, since running juices clear well before the meat is safe.", "After the chicken is all cooked, leave a little of the hot fat in the skillet.", "Then take a tablespoonful of dry flour and brown it in the fat, stirring it around, then pour water in and stir till the gravy is as thin as soup. The gravy is half the recipe, and it is made in the same pan."], fisher, { cal: 1010, protein: 64, carbs: 24, fat: 72 }),
  x("ar-mf-ginger-cookies", "Mrs. Fisher's ginger cookies", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "cookies", "baking", "dessert", "vegetarian"], "veg", "dessert", 30, "Molasses, a quart of flour, three spices and two spoonfuls of yeast powder. Rolled out and baked like a biscuit.", [I("molasses", 1, "cup", "Pantry"), I("sugar", 0.5, "cup", "Pantry"), I("butter", 1, "tbsp", "Dairy & Eggs"), I("lard", 1, "tbsp", "Pantry"), I("flour", 4, "cups", "Pantry"), I("ground ginger", 2, "tbsp", "Herbs & Spices"), I("cinnamon", 1, "tsp", "Herbs & Spices"), I("allspice", 1, "tsp", "Herbs & Spices"), I("baking powder", 2, "tbsp", "Pantry")], ["Cream the 1 tablespoonful of butter and the half teacup of sugar together, and add the 1 teacup of molasses.", "Sift the 2 tablespoonfuls of yeast powder and the 1 quart of flour together, and add to the butter, sugar and molasses.", "Then add the 1 tablespoonful of lard and the spices — the 2 tablespoonfuls of ginger, the 1 teaspoonful of cinnamon and the 1 teaspoonful of allspice — and work it up well.", "Roll out on a board and cut them out.", "Bake like you would a biscuit — a hot oven, 400°F, about 10 minutes."], fisher, { cal: 115, protein: 2, carbs: 25, fat: 1 }, 30),
  x("ar-mf-chow-chow", "Mrs. Fisher's Creole chow chow", "Southern", ["vintage", "era-1880s", "book-mrs-fisher", "southern", "sauce", "vegetarian", "vegan"], "veg", "bowl", 180, "Green tomatoes and silver skin onions, a night under salt, then a whole day on a slow fire.", [I("green tomatoes", 1, "gallon", "Produce"), I("onions", 6, "", "Produce"), I("salt", 1, "pint", "Herbs & Spices"), I("wine vinegar", 1, "gallon", "Pantry"), I("brown sugar", 2, "cups", "Pantry"), I("cayenne", 1, "tbsp", "Herbs & Spices"), I("black pepper", 1, "tbsp", "Herbs & Spices"), I("turmeric", 1, "tbsp", "Herbs & Spices")], ["Slice one gallon of green tomatoes thin and half a dozen silver skin onions thin.", "Put the onions and tomatoes together in a keg or jar, sprinkle over them one pint of salt, and let it so remain twenty-four hours.", "Then drain all the brine off from them through a colander.", "Put the one gallon of wine vinegar to them and add the seasoning — the two teacups of brown sugar, the tablespoonful of cayenne, the tablespoonful of black pepper and the tablespoonful of turmeric.", "Put to cook on a slow fire, stirring to keep it from burning. It will take the whole day to cook. Keep the jars in the fridge: a hot fill is not canning, and this recipe was never processed for the shelf."], fisher, { cal: 80, protein: 1, carbs: 18, fat: 0 }, 40),
];
