import { I, dish } from "./catalog-kit.ts";
import type { Recipe, RecipeSource } from "./types";

function src(book: string, author: string, year: number, era: string, archiveId: string, credit: string): RecipeSource {
  return { book, author, year, era, archiveId, credit };
}

const foreign365 = src("365 Foreign Dishes", "Anonymous", 1908, "1900s", "365foreigndishes00phil", "365 Foreign Dishes (George W. Jacobs, 1908). Public domain.");
const picayune = src("The Picayune Creole Cook Book", "The Picayune", 1901, "1900s", "cu31924003574187", "The Picayune Creole Cook Book (New Orleans, 1901). Public domain.");
const kephart = src("Camping and Woodcraft", "Horace Kephart", 1917, "1910s", "campingwoodcraft00keph", "Horace Kephart, Camping and Woodcraft (1917). Public domain.");
const ladiesAid = src("Woman Suffrage Cook Book", "Mrs. Hattie A. Burr", 1886, "1880s", "the-woman-suffrage-cook-book-compilation-accessible-version", "Mrs. Hattie A. Burr, The Woman Suffrage Cook Book (Boston, 1886), and typical Ladies' Aid church-supper dishes. Public domain.");
const hill = src("Salads, Sandwiches and Chafing Dishes", "Janet McKenzie Hill", 1909, "1900s", "saladssandwiches00hillrich", "Janet McKenzie Hill, Salads, Sandwiches and Chafing Dishes (1909). Public domain.");
const bosse = src("Chinese-Japanese Cook Book", "Sara Bosse & Onoto Watanna", 1914, "1910s", "chinesejapanesec00boss_1", "Sara Bosse and Onoto Watanna (Winnifred Eaton), Chinese-Japanese Cook Book (Rand McNally, 1914). Public domain.");
const oliveGreen = src("How to Cook Fish", "Olive Green", 1908, "1900s", "howtocookfish00gree", "Olive Green, How to Cook Fish (Putnam, 1908). Public domain.");
const jewish = src("The International Jewish Cook Book", "Florence Kreisler Greenbaum", 1918, "1910s", "cu31924003580952", "Florence Kreisler Greenbaum, The International Jewish Cook Book (Bloch, 1918). Public domain.");
const desserts365 = src("365 Desserts", "Anonymous", 1900, "1900s", "365dessertsdesse00nels", "365 Desserts: A Dessert for Every Day in the Year (1900). Public domain.");

function h(
  id: string,
  name: string,
  cuisine: string,
  tags: string[],
  protein: Recipe["protein"],
  plate: Recipe["plate"],
  minutes: number,
  description: string,
  ingredients: Recipe["ingredients"],
  steps: string[],
  source: Recipe["source"],
  nutrition: Recipe["nutrition"],
  /** Portions this makes. Left out, dish() stamps four, which is wrong for
   * a whole cake or a joint. */
  servings?: number,
): Recipe {
  return dish({
    id, name, cuisine, description, minutes, protein, plate,
    tags: Array.from(new Set(["vintage", ...tags])),
    ingredients, steps, nutrition, source,
      ...(servings ? { servings } : {}),
  });
}

export const BOOK_RECIPES: Recipe[] = [
  h("vh-365-goulash", "Hungarian beef stew", "Hungarian", ["era-1900s", "book-365-foreign", "international", "old-school", "gluten-free"], "beef", "bowl", 95, "The book's goulash under the name it prints: beef stewed in its own dripping, then potato, onion and paprika.", [I("beef chuck", 2, "lb", "Meat & Seafood"), I("beef dripping", 2, "tbsp", "Pantry"), I("potatoes", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("sweet paprika", 0.5, "tsp", "Herbs & Spices"), I("salt", 1, "tsp", "Herbs & Spices"), I("black pepper", 0.5, "tsp", "Herbs & Spices")], ["Cut the 2 pounds of beef chuck into small pieces. Season with the 1 teaspoon of salt and the ½ teaspoon of black pepper.", "Heat the 2 tablespoons of beef dripping in a saucepan. Add the meat, cover, and let it stew half an hour.", "Add the 3 potatoes cut into dice pieces, the 1 onion sliced thin, 1 cup of hot water and the ½ teaspoon of sweet paprika.", "Cover again and let all cook until the beef and the potato are tender, about an hour. Serve very hot."], foreign365, { cal: 740, protein: 62, carbs: 26, fat: 43 }),
  h("vh-365-irish-stew", "Irish mutton stew", "Irish", ["era-1900s", "book-365-foreign", "international", "old-school"], "lamb", "bowl", 95, "Mutton chops stewed under turnip, potato and onion, the liquor thickened with flour and milk.", [I("mutton or lamb chops", 2, "lb", "Meat & Seafood"), I("beef dripping", 1, "tbsp", "Pantry"), I("turnips", 2, "", "Produce"), I("potatoes", 2, "lb", "Produce"), I("onions", 3, "", "Produce"), I("flour", 1, "tbsp", "Pantry"), I("milk", 0.25, "cup", "Dairy & Eggs"), I("salt", 1.5, "tsp", "Herbs & Spices")], ["Season the 2 pounds of mutton chops with the 1½ teaspoons of salt and pepper.", "Put the 1 tablespoon of hot dripping in a saucepan. Add the chops, the 2 turnips sliced, the 2 pounds of potatoes sliced and the 3 onions sliced, with more salt and pepper.", "Cover with water and cook slowly until the meat and roots are tender, about 75 minutes.", "Mix the 1 tablespoon of flour smooth with the ¼ cup of milk. Stir it into the sauce and let it thicken 3 minutes.", "Season to taste and serve very hot."], foreign365, { cal: 870, protein: 64, carbs: 56, fat: 43 }),
  h("vh-365-swedish-balls", "Swedish meatballs", "Swedish", ["era-1900s", "book-365-foreign", "international"], "beef", "skillet", 40, "Beef and pork, crumbs, cream, browned, a pan sauce. The 1908 luncheon ball.", [I("ground beef", 0.75, "lb", "Meat & Seafood"), I("ground pork", 0.5, "lb", "Meat & Seafood"), I("bread crumbs", 0.5, "cup", "Bakery"), I("cream", 0.5, "cup", "Dairy & Eggs"), I("onion", 0.5, "", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("flour", 1, "tbsp", "Pantry")], ["Soak the ½ cup of bread crumbs in half the ½ cup of cream 5 minutes.", "Mix them with the ¾ pound of ground beef, the ½ pound of ground pork, the ½ onion, grated, the 1 teaspoon of salt and pepper, and shape into small balls.", "Brown the balls in the 3 tablespoons of butter over medium heat, turning, 8 minutes. Take them out.", "Stir the 1 tablespoon of flour into the drippings and cook 1 minute, then pour in the rest of the cream and ½ cup of water.", "Return the balls and simmer 10 minutes, until they read 160°F through the middle and the sauce coats them.", "Serve with boiled potatoes or buttered noodles."], undefined, { cal: 585, protein: 35, carbs: 15, fat: 43 }),
  h("vh-365-borscht", "Russian beet soup", "Russian", ["era-1900s", "book-365-foreign", "international", "soup", "gluten-free"], "chicken", "soup", 60, "Beets boiled, chopped into a seasoned chicken broth, then lemon, cinnamon, nutmeg and a glass of red wine. No cabbage and no sour cream.", [I("beets", 5, "", "Produce"), I("chicken broth", 8, "cups", "Pantry"), I("lemon", 1, "", "Produce"), I("cinnamon", 0.25, "tsp", "Herbs & Spices"), I("nutmeg", 0.25, "tsp", "Herbs & Spices"), I("red wine", 4, "oz", "Pantry"), I("brown sugar", 1, "tsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices")], ["Boil the 5 medium beets until tender, about 40 minutes. Slip the skins off and chop them.", "Season the 8 cups of chicken broth highly with the 1 teaspoon of salt and pepper, bring it to a simmer, and add the chopped beets.", "Add the juice of the 1 lemon and the ¼ teaspoon each of cinnamon and nutmeg. Let it boil fifteen minutes.", "Mix the 1 teaspoon of brown sugar into the 4 ounces of red wine and stir that in. Bring the soup back to a boil and serve hot."], foreign365, { cal: 115, protein: 7, carbs: 18, fat: 1 }),
  h("vh-365-german-potato", "Warm German potato salad", "German", ["era-1900s", "book-365-foreign", "international", "salad"], "pork", "green", 30, "Hot potatoes, bacon, vinegar, onion. Dressed while the potatoes can drink.", [I("waxy potatoes", 2, "lb", "Produce"), I("bacon", 6, "slices", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("cider vinegar", 0.33, "cup", "Pantry"), I("sugar", 1, "tsp", "Pantry"), I("parsley", 2, "tbsp", "Produce")], ["Boil the potatoes in their skins until just tender, 20 minutes. Drain, peel, and slice while warm.", "Cook the bacon until crisp. Lift out. Cook the chopped onion in the fat 4 minutes.", "Stir in vinegar, sugar, salt, and pepper. Bring to a bubble.", "Pour the hot dressing over the potatoes. Fold in crumbled bacon and parsley.", "Serve warm. This is a salad, not a bake."], undefined, { cal: 345, protein: 15, carbs: 44, fat: 12 }),
  h("vh-365-curry-chicken", "Madras stewed chicken", "Indian", ["era-1900s", "book-365-foreign", "international", "curry"], "chicken", "curry", 80, "A spring chicken fried with mutton chops, stewed with curried rice, onion and apple, finished with oysters and lemon.", [I("chicken", 1, "bird", "Meat & Seafood"), I("mutton or lamb chops", 1, "lb", "Meat & Seafood"), I("lard", 2, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("rice", 2, "oz", "Pantry"), I("curry powder", 1, "tsp", "Herbs & Spices"), I("apple", 1, "", "Produce"), I("chicken broth", 4, "cups", "Pantry"), I("shucked oysters", 1, "pint", "Meat & Seafood"), I("lemon", 0.5, "", "Produce"), I("eggplant", 1, "", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Cut the chicken into pieces at the joints and season them with the 1 teaspoon of salt and pepper.", "Fry the chicken in the 2 tablespoons of hot lard with the 1 pound of tender mutton chops until both are browned, about 10 minutes.", "Fry the 1 sliced onion in the 2 tablespoons of hot butter with the 2 ounces of rice, the 1 teaspoon of curry powder and the 1 chopped apple, 4 minutes. Add all of it to the chicken.", "Moisten with the 4 cups of chicken broth, season to taste, and let it simmer until the chicken and the mutton are very tender, about 40 minutes. The thickest joint should read 175°F.", "Slice the 1 eggplant, salt the slices, and fry them in a little of the fat until gold, about 5 minutes a side.", "Add the 1 pint of shucked oysters with their liquor and the juice of the ½ lemon. Cook 3 minutes more, just until the oysters plump and their edges curl — the book adds them already hot, but they are raw shellfish and want that much heat.", "Serve on a platter with the fried eggplant."], foreign365, { cal: 1055, protein: 104, carbs: 35, fat: 56 }),
  h("vh-365-onion-soup", "French onion soup", "French", ["era-1900s", "book-365-foreign", "international", "soup"], "beef", "soup", 70, "Onions cooked long in butter, beef broth, toast, cheese.", [I("onions", 2, "lb", "Produce"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("beef broth", 6, "cups", "Pantry"), I("baguette", 8, "slices", "Bakery"), I("gruyere or Swiss", 6, "oz", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices")], ["Slice the onions thin. Cook them in the butter over medium-low heat 30 minutes, stirring, until they are deep gold and sweet. Do not rush this.", "Add the broth. Simmer 20 minutes. Salt and pepper.", "Toast the bread. Ladle the soup into oven-safe bowls. Float toast on each. Cover with grated cheese.", "Broil 2–3 minutes, until the cheese bubbles and browns.", "Serve at once. Warn the table the bowls are hot."], undefined, { cal: 510, protein: 22, carbs: 50, fat: 25 }),
  h("vh-365-spanish-rice", "Spanish rice", "Spanish", ["era-1900s", "book-365-foreign", "international", "budget", "quick"], "veg", "bowl", 25, "Onion fried with tomato, a cup of stock, and boiled rice stirred through with butter. No ham and no pepper in the 1908 book.", [I("onion", 1, "", "Produce"), I("tomatoes", 2, "cups", "Produce"), I("stock", 1, "cup", "Pantry"), I("cooked rice", 2, "cups", "Pantry"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("salt", 1, "tsp", "Herbs & Spices")], ["Fry the 1 large chopped onion with the 2 cups of tomatoes in 2 tablespoons of the butter, 6 minutes.", "Add the 1 cup of stock and the 1 teaspoon of salt and pepper to taste. Cover and let simmer ten minutes.", "Add the 2 cups of cooked rice and mix well together with the last 1 tablespoon of butter.", "Let it get very hot and serve."], foreign365, { cal: 455, protein: 9, carbs: 83, fat: 10 }),

  h("vh-pd-pot-pie", "Pennsylvania pot pie", "American", ["era-1900s", "old-school", "hometown"], "chicken", "soup", 90, "Bott boi: chicken stew with square noodle dough dropped on top, not a crust pie.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 2, "cups", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("potato", 3, "", "Produce"), I("onion", 1, "", "Produce"), I("parsley", 3, "tbsp", "Produce")], ["Cover the chicken with water. Simmer 45 minutes. Lift out, pull the meat, return it. Add cubed potato and onion.", "Make a stiff dough of flour, egg, ½ teaspoon salt, and enough water to bring it together. Roll thin. Cut into 2-inch squares.", "When the potato is half done, lay the dough squares on the simmering stew. They will steam, not boil hard.", "Cover 15 minutes, until the squares are cooked through and the stew is thick.", "Salt, pepper, parsley. Serve in bowls. This is noodle pot pie, not a baked crust."], undefined, { cal: 795, protein: 72, carbs: 73, fat: 23 }),
  h("vh-pd-schnitz", "Schnitz un knepp", "American", ["era-1900s", "old-school"], "pork", "bowl", 120, "Ham, dried apples, dumplings. The Pennsylvania German pot of sweet and salt.", [I("smoked ham", 2, "lb", "Meat & Seafood"), I("dried apples", 2, "cups", "Pantry"), I("flour", 2, "cups", "Pantry"), I("baking powder", 2, "tsp", "Pantry"), I("milk", 0.75, "cup", "Dairy & Eggs"), I("brown sugar", 2, "tbsp", "Pantry")], ["Soak the dried apples in water 1 hour. Cover the ham with water and simmer 60 minutes.", "Add the apples with their soaking water and the brown sugar. Simmer 20 minutes more.", "Stir flour, baking powder, ½ teaspoon salt, and milk into a drop-dumpling batter.", "Drop spoonfuls onto the simmering ham and apples. Cover tightly 15 minutes — do not lift the lid.", "Slice the ham. Serve with apples and dumplings in the liquor."], undefined, { cal: 970, protein: 52, carbs: 68, fat: 55 }),
  h("vh-pd-sauerkraut", "Pork and sauerkraut", "American", ["era-1900s", "old-school", "gluten-free"], "pork", "roast", 180, "A pork roast on sauerkraut, slow. New Year's on the Pennsylvania table any day.", [I("pork shoulder", 3, "lb", "Meat & Seafood"), I("sauerkraut", 2, "lb", "Pantry"), I("onion", 1, "", "Produce"), I("apple", 1, "", "Produce"), I("caraway", 1, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 325°F. Salt and pepper the pork. Brown it on all sides in a Dutch oven, 8 minutes.", "Add the drained sauerkraut, sliced onion, sliced apple, and caraway around the meat.", "Pour ½ cup water around the pork. Cover the pot tightly.", "Bake 2½ hours, until the pork pulls with a fork.", "Slice the pork. Serve on the sauerkraut with boiled potatoes."], undefined, { cal: 285, protein: 29, carbs: 7, fat: 15 }, 13),
  h("vh-pd-rivvel", "Rivvel soup", "American", ["era-1900s", "soup", "budget", "old-school"], "chicken", "soup", 30, "Chicken broth with tiny flour-and-egg crumbs dropped in. Rivels, not noodles.", [I("chicken broth", 8, "cups", "Pantry"), I("flour", 1, "cup", "Pantry"), I("egg", 1, "", "Dairy & Eggs"), I("potato", 2, "", "Produce"), I("parsley", 2, "tbsp", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Bring the broth to a simmer with cubed potato. Cook 12 minutes.", "Rub the egg into the flour and salt with your fingers until you have pea-size crumbs — rivels.", "Drop the rivels into the simmering broth, stirring so they do not clump.", "Cook 8 minutes, until the rivels are tender and the soup has thickened slightly.", "Salt the soup. Scatter parsley. Serve hot in bowls."], undefined, { cal: 230, protein: 11, carbs: 41, fat: 3 }),
  h("vh-pd-shoofly", "Shoofly pie", "American", ["era-1900s", "dessert", "baking", "vegetarian", "old-school"], "veg", "dessert", 55, "Molasses crumb pie: wet bottom, crumbs on top, baked in a crust.", [I("pie crust", 1, "", "Bakery"), I("molasses", 1, "cup", "Pantry"), I("flour", 1.5, "cups", "Pantry"), I("brown sugar", 0.75, "cup", "Pantry"), I("butter", 4, "tbsp", "Dairy & Eggs"), I("baking soda", 1, "tsp", "Pantry")], ["Heat the oven to 375°F. Lay the crust in a 9-inch pie tin. Crimp the edge.", "Rub the flour, brown sugar, and butter into crumbs with your fingers.", "Stir the baking soda into ¾ cup hot water, then into the molasses.", "Pour the molasses mix into the crust. Scatter the crumbs evenly over the top.", "Bake 35–40 minutes, until the filling is set and the crumbs are gold. Cool before slicing."], undefined, { cal: 465, protein: 4, carbs: 82, fat: 14 }, 8),
  h("vh-pd-scrapple", "Scrapple", "American", ["era-1900s", "breakfast", "old-school"], "pork", "skillet", 90, "Pork broth, cornmeal, sage, chilled and fried. The Pennsylvania breakfast slice.", [I("pork shoulder", 1.5, "lb", "Meat & Seafood"), I("cornmeal", 1.5, "cups", "Pantry"), I("sage", 1, "tsp", "Herbs & Spices"), I("black pepper", 1, "tsp", "Herbs & Spices"), I("salt", 2, "tsp", "Herbs & Spices"), I("lard or oil", 3, "tbsp", "Pantry")], ["Cover the pork with water. Simmer 60 minutes until it shreds. Lift out, chop fine, and measure 4 cups of the broth.", "Bring the broth to a boil. Rain in the cornmeal, stirring. Add the pork, sage, salt, and pepper.", "Cook over low heat 15 minutes, until very thick. Pack into a greased loaf pan. Chill until firm, at least 4 hours.", "Slice ½ inch thick. Fry in fat over medium heat 4 minutes a side, until a brown crust forms.", "Serve the fried scrapple hot with molasses or fried eggs."], undefined, { cal: 740, protein: 52, carbs: 48, fat: 36 }),
  h("vh-pd-corn-pie", "Pennsylvania corn pie", "American", ["era-1900s", "vegetarian", "baking", "old-school"], "eggs", "roast", 50, "Sweet corn in a custard, a crust, baked until set. A harvest pie that is not dessert.", [I("corn kernels", 3, "cups", "Produce"), I("eggs", 3, "", "Dairy & Eggs"), I("milk", 1, "cup", "Dairy & Eggs"), I("butter", 2, "tbsp", "Dairy & Eggs"), I("pie crust", 1, "", "Bakery"), I("salt", 1, "tsp", "Herbs & Spices")], ["Heat the oven to 375°F. Lay the crust in a pie tin.", "Beat the eggs with the milk, melted butter, salt, and pepper.", "Stir the corn into the custard. Pour the filling into the crust.", "Bake 35–40 minutes, until the center is just set and a knife comes out clean.", "Cool 10 minutes. Serve warm as a supper pie, not as a sweet."], undefined, { cal: 500, protein: 14, carbs: 50, fat: 30 }),

  h("vh-pc-gumbo-file", "Gumbo filé", "Creole", ["era-1900s", "book-picayune", "southern", "soup"], "chicken", "soup", 90, "The Picayune's filé gumbo: a brown roux, chicken, oyster or shrimp, filé off the fire.", [I("chicken", 1, "bird", "Meat & Seafood"), I("flour", 0.33, "cup", "Pantry"), I("lard or oil", 0.33, "cup", "Pantry"), I("onion", 2, "", "Produce"), I("oysters or shrimp", 1, "pint", "Meat & Seafood"), I("filé powder", 1, "tbsp", "Herbs & Spices")], ["Joint the chicken. Make a roux of the ⅓ cup of lard or oil and the ⅓ cup of flour over medium heat, stirring without stopping, 12–15 minutes, until it is the colour of peanut butter. A burnt roux is bitter and there is no saving it.", "Add the 2 chopped onions and cook 4 minutes. Add the chicken and 2 quarts of water and simmer 45 minutes.", "Add the 1 pint of oysters or shrimp and cook 5 minutes, until the oysters ruffle or the shrimp turn pink.", "Take the pot off the heat and only then stir in the 1 tablespoon of filé. Boiled after the filé goes in, the gumbo turns stringy and slick.", "Season with the 1 teaspoon of salt and the ¼ teaspoon of cayenne and serve over the 1½ cups of rice."], picayune, { cal: 660, protein: 51, carbs: 50, fat: 28 }, 6),
  h("vh-pc-red-beans", "Red beans and rice", "Creole", ["era-1900s", "book-picayune", "southern", "budget"], "pork", "bowl", 180, "Monday beans: red beans, a ham bone, onion, celery, bell pepper, rice on the side.", [I("dried red beans", 1, "lb", "Pantry"), I("ham bone or pickled pork", 1, "", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("green pepper", 1, "", "Produce"), I("rice", 1.5, "cups", "Pantry")], ["Soak the 1 pound of dried red beans overnight. Drain them.", "Cover them with fresh water, add the ham bone or pickled pork, and simmer 1 hour.", "Add the chopped onion, the 2 stalks of celery and the green pepper and cook 45 minutes more, until the beans crush easily between two fingers.", "Mash a cup of beans against the side of the pot to thicken it. Season with the 1 teaspoon of salt, the ¼ teaspoon of cayenne and a bay leaf, and simmer 15 minutes.", "Boil the 1½ cups of rice in salted water until tender, 18 minutes, and drain it.", "Serve the beans over or beside the rice. This is a Monday pot and it is better on Tuesday."], picayune, { cal: 480, protein: 24, carbs: 87, fat: 4 }),
  h("vh-pc-grillades", "Grillades and grits", "Creole", ["era-1900s", "book-picayune", "southern"], "beef", "skillet", 70, "Browned beef rounds in a tomato gravy, grits underneath. The Picayune breakfast.", [I("beef round steaks", 1.5, "lb", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("tomatoes", 3, "", "Produce"), I("flour", 0.33, "cup", "Pantry"), I("grits", 1, "cup", "Pantry"), I("butter", 2, "tbsp", "Dairy & Eggs")], ["Pound the steaks thin. Salt, pepper, and dredge in flour. Brown in fat 3 minutes a side. Take out.", "Cook the chopped onion 5 minutes. Add chopped tomatoes and 1 cup water. Simmer 10 minutes.", "Return the meat. Cover and simmer 40 minutes, until the grillades are tender.", "Cook the grits in 4 cups salted water 20 minutes, stirring, until thick. Stir in butter.", "Spoon grits onto plates. Lay grillades and gravy over. Serve hot."], picayune, { cal: 625, protein: 52, carbs: 47, fat: 24 }),
  h("vh-pc-trout-meuniere", "Trout meunière", "Creole", ["era-1900s", "book-picayune", "southern", "quick"], "fish", "fish", 20, "The Picayune trout: floured, fried in butter, a lemon-butter pan sauce.", [I("trout fillets", 1.5, "lb", "Meat & Seafood"), I("flour", 0.5, "cup", "Pantry"), I("butter", 6, "tbsp", "Dairy & Eggs"), I("lemon", 1, "", "Produce"), I("parsley", 2, "tbsp", "Produce"), I("salt", 1, "tsp", "Herbs & Spices")], ["Pat the 1½ pounds of trout fillets dry, salt and pepper them, and dredge them in the ½ cup of flour, shaking off the extra.", "Heat 3 tablespoons of the 6 tablespoons of butter in a skillet until it foams. Fry the fish 3 minutes a side, until gold and the flesh flakes, then lift it onto plates.", "Wipe the pan out and add the remaining butter. Cook it 1 minute, until it foams, quiets and smells nutty — brown, not black.", "Squeeze the lemon in; it will hiss. Stir in the 2 tablespoons of parsley.", "Pour the browned butter over the trout and serve at once, with the 1 teaspoon of salt at the table."], picayune, { cal: 295, protein: 22, carbs: 5, fat: 21 }),
  h("vh-pc-calas", "Calas", "Creole", ["era-1900s", "book-picayune", "southern", "breakfast", "vegetarian"], "veg", "skillet", 40, "Rice fritters, yeasted, fried, sugared. The old New Orleans street cry.", [I("cooked rice", 2, "cups", "Pantry"), I("flour", 0.5, "cup", "Pantry"), I("eggs", 2, "", "Dairy & Eggs"), I("sugar", 3, "tbsp", "Pantry"), I("yeast", 1, "tsp", "Pantry"), I("oil for frying", 2, "cups", "Pantry")], ["Mash the 2 cups of cooked rice. Mix it with the ½ cup of flour, the 2 eggs, 2 tablespoons of the 3 tablespoons of sugar, the 1 teaspoon of yeast and ¼ cup of warm water.", "Cover and rest 1 hour, until the batter is puffy and smells yeasty.", "Heat 2 inches of the 2 cups of oil for frying in a deep pot to 365°F. The oil stays in the pot; none of it goes in the batter.", "Drop the batter in by tablespoons and fry 2–3 minutes, turning, until deep gold all over.", "Drain them on paper and dust with the last tablespoon of sugar while they are hot.", "Serve at once. Calas do not keep — that is why they were sold on the street hot."], picayune, { cal: 590, protein: 12, carbs: 95, fat: 18 }),
  h("vh-pc-pain-perdu", "Pain perdu", "Creole", ["era-1900s", "book-picayune", "southern", "breakfast", "vegetarian"], "eggs", "skillet", 20, "Lost bread: stale slices soaked in egg and milk, fried, sugared.", [I("stale French bread", 8, "slices", "Bakery"), I("eggs", 3, "", "Dairy & Eggs"), I("milk", 1, "cup", "Dairy & Eggs"), I("vanilla", 1, "tsp", "Pantry"), I("butter", 3, "tbsp", "Dairy & Eggs"), I("sugar", 2, "tbsp", "Pantry")], ["Beat the 3 eggs with the 1 cup of milk, the 1 teaspoon of vanilla and a pinch of the 1 teaspoon of salt.", "Soak the 8 slices of stale French bread in the custard 1 minute a side, until they drink it up without falling apart. Stale bread is the point — fresh bread turns to mush.", "Melt the 3 tablespoons of butter in a skillet over medium heat and fry the slices 3 minutes a side, until gold.", "Dust with the 2 tablespoons of sugar while they are hot, so it sticks.", "Serve at once, with cane syrup if you have it."], picayune, { cal: 310, protein: 10, carbs: 35, fat: 14 }),
  h("vh-pc-courtbouillon", "Redfish courtbouillon", "Creole", ["era-1900s", "book-picayune", "southern"], "fish", "soup", 45, "A Creole courtbouillon: a roux, tomato, a firm fish simmered in the sauce.", [I("redfish or snapper", 2, "lb", "Meat & Seafood"), I("flour", 3, "tbsp", "Pantry"), I("onion", 1, "", "Produce"), I("tomatoes", 4, "", "Produce"), I("green pepper", 1, "", "Produce"), I("oil", 3, "tbsp", "Pantry")], ["Make a light-brown roux of the 3 tablespoons of oil and the 3 tablespoons of flour, stirring, 8 minutes. Add the chopped onion and the green pepper and cook 4 minutes.", "Add the 4 chopped tomatoes and 2 cups of water and simmer 15 minutes, so the sauce is made before the fish goes near it.", "Season with the 1 teaspoon of salt, the ¼ teaspoon of cayenne and a bay leaf.", "Cut the 2 pounds of redfish or snapper into large pieces and lay them into the sauce.", "Cover and simmer 12 minutes, until the fish just flakes. Do not stir — the pieces break.", "Serve in soup plates with the 1½ cups of boiled rice."], picayune, { cal: 705, protein: 60, carbs: 71, fat: 19 }),
  h("vh-pc-shrimp-creole", "Shrimp Creole", "Creole", ["era-1900s", "book-picayune", "southern"], "seafood", "bowl", 35, "The Picayune tomato shrimp: the trinity, a short simmer, rice.", [I("shrimp", 1.5, "lb", "Meat & Seafood"), I("onion", 1, "", "Produce"), I("celery", 2, "stalks", "Produce"), I("green pepper", 1, "", "Produce"), I("tomatoes", 4, "", "Produce"), I("rice", 1.5, "cups", "Pantry"), I("oil", 2, "tbsp", "Pantry"), I("salt", 1, "tsp", "Herbs & Spices"), I("cayenne", 0.25, "tsp", "Herbs & Spices"), I("thyme", 0.5, "tsp", "Herbs & Spices")], ["Cook the rice in salted water until tender, 18 minutes. Keep warm.", "Cook chopped onion, celery, and pepper in oil 6 minutes. Add chopped tomatoes. Simmer 12 minutes.", "Add the peeled shrimp. Cook 4–5 minutes, until they turn pink and curl. Do not overcook.", "Add salt, cayenne, and a pinch of thyme. Taste the sauce.", "Serve the shrimp and sauce over the rice."], picayune, { cal: 535, protein: 48, carbs: 67, fat: 8 }),
];
