/** Exercise library: muscles, cues, and defaults on top of the lift catalog. */

import { LIFT_MOVES, type LiftMove, type LiftSession, type Muscle } from "./lift.ts";

export type MuscleId =
  | "chest"
  | "front-delts"
  | "side-delts"
  | "rear-delts"
  | "biceps"
  | "triceps"
  | "forearms"
  | "traps"
  | "lats"
  | "upper-back"
  | "lower-back"
  | "abs"
  | "obliques"
  | "glutes"
  | "quads"
  | "hamstrings"
  | "calves"
  | "adductors";

export type Equipment = "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "kettlebell";

export const MUSCLE_LABEL: Record<MuscleId, string> = {
  chest: "Chest",
  "front-delts": "Front delts",
  "side-delts": "Side delts",
  "rear-delts": "Rear delts",
  biceps: "Biceps",
  triceps: "Triceps",
  forearms: "Forearms",
  traps: "Traps",
  lats: "Lats",
  "upper-back": "Upper back",
  "lower-back": "Lower back",
  abs: "Abs",
  obliques: "Obliques",
  glutes: "Glutes",
  quads: "Quads",
  hamstrings: "Hamstrings",
  calves: "Calves",
  adductors: "Adductors",
};

export const MUSCLE_VIEW: Record<MuscleId, "front" | "back" | "both"> = {
  chest: "front",
  "front-delts": "front",
  "side-delts": "both",
  "rear-delts": "back",
  biceps: "front",
  triceps: "back",
  forearms: "both",
  traps: "back",
  lats: "back",
  "upper-back": "back",
  "lower-back": "back",
  abs: "front",
  obliques: "front",
  glutes: "back",
  quads: "front",
  hamstrings: "back",
  calves: "back",
  adductors: "front",
};

export type Exercise = LiftMove & {
  primary: MuscleId[];
  secondary: MuscleId[];
  equipment: Equipment;
  setup: string;
  cues: string[];
  mistakes: string[];
  defaultSets: number;
  defaultReps: string;
  restSec: number;
};

type Meta = Omit<Exercise, keyof LiftMove | "id" | "name" | "muscle" | "romM" | "bar" | "bodyweight">;

const META: Record<string, Meta> = {
  squat: {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "adductors", "lower-back"],
    equipment: "barbell",
    setup: "Bar on the upper back, feet about shoulder-width, toes slightly out.",
    cues: ["Brace before you unrack.", "Sit between the hips, not forward on the knees.", "Drive the floor away."],
    mistakes: ["Knees caving in.", "Losing the brace at the bottom.", "Heels lifting."],
    defaultSets: 4,
    defaultReps: "6-8",
    restSec: 150,
  },
  "front-squat": {
    primary: ["quads"],
    secondary: ["glutes", "abs", "upper-back"],
    equipment: "barbell",
    setup: "Bar on the front delts, elbows high, chest tall.",
    cues: ["Elbows stay up.", "Sit down more than back.", "Keep the torso vertical."],
    mistakes: ["Elbows dropping.", "Rounding the upper back."],
    defaultSets: 3,
    defaultReps: "6-8",
    restSec: 150,
  },
  goblet: {
    primary: ["quads", "glutes"],
    secondary: ["abs", "upper-back"],
    equipment: "dumbbell",
    setup: "Hold a dumbbell at the chest, elbows in, feet shoulder-width.",
    cues: ["Chest up.", "Sit between the heels.", "Knees track the toes."],
    mistakes: ["Torso collapsing forward.", "Heels rising."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 90,
  },
  "split-squat": {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    equipment: "dumbbell",
    setup: "Rear foot on a bench, front foot far enough that the shin stays tall.",
    cues: ["Drop the back knee.", "Front heel stays down.", "Don't rush the stretch."],
    mistakes: ["Front knee shooting past the toes with the heel up.", "Leaning the whole torso onto the front leg."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 90,
  },
  rdl: {
    primary: ["hamstrings", "glutes"],
    secondary: ["lower-back", "traps"],
    equipment: "dumbbell",
    setup: "Soft knees, bells against the thighs, shoulder blades set.",
    cues: ["Push the hips back.", "Bells stay close.", "Stop when the hamstrings load, not the low back."],
    mistakes: ["Rounding the back.", "Squatting the weight down."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 120,
  },
  deadlift: {
    primary: ["hamstrings", "glutes", "lower-back"],
    secondary: ["traps", "quads", "forearms"],
    equipment: "barbell",
    setup: "Bar over mid-foot, shins close, hips above knees, chest up.",
    cues: ["Push the floor.", "The hips and shoulders rise together.", "Lock out without leaning back."],
    mistakes: ["Jerking the bar.", "Hips shooting up first.", "Rounding the upper back hard."],
    defaultSets: 3,
    defaultReps: "5",
    restSec: 180,
  },
  lunge: {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "abs"],
    equipment: "dumbbell",
    setup: "Stand tall, step long enough that both knees can bend to about 90°.",
    cues: ["Front heel down.", "Torso stays stacked.", "Push back through the front foot."],
    mistakes: ["Tiny steps that dump the knee forward.", "Slamming the back knee."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 90,
  },
  "hip-thrust": {
    primary: ["glutes"],
    secondary: ["hamstrings", "quads"],
    equipment: "barbell",
    setup: "Upper back on a bench, bar over the hips, chin tucked.",
    cues: ["Ribs down.", "Squeeze at the top, not hyperextend.", "Pause one beat."],
    mistakes: ["Arching the low back to finish.", "Walking the feet too far out."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "leg-press": {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: "machine",
    setup: "Feet mid-platform, lower back glued to the pad.",
    cues: ["Don't lock out angrily.", "Control the drop.", "Keep the hips from tucking under."],
    mistakes: ["Range so deep the low back peels off.", "Bouncing the sled."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 90,
  },
  calf: {
    primary: ["calves"],
    secondary: [],
    equipment: "machine",
    setup: "Ball of the foot on the edge, stretch at the bottom.",
    cues: ["Full stretch.", "Pause at the top.", "Don't bounce."],
    mistakes: ["Using the knees to cheat.", "Tiny range."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  bench: {
    primary: ["chest", "triceps"],
    secondary: ["front-delts"],
    equipment: "barbell",
    setup: "Eyes under the bar, feet planted, shoulder blades pinched and down.",
    cues: ["Row the bar to the chest.", "Elbows about 45°.", "Press back toward the rack."],
    mistakes: ["Flaring the elbows to 90°.", "Bouncing off the chest.", "Hips leaving the bench."],
    defaultSets: 4,
    defaultReps: "6-8",
    restSec: 150,
  },
  incline: {
    primary: ["chest", "front-delts"],
    secondary: ["triceps"],
    equipment: "barbell",
    setup: "Bench 15–30°. Same shoulder set as flat bench.",
    cues: ["Touch the upper chest.", "Don't let the bar drift toward the face.", "Keep the ribs down."],
    mistakes: ["Bench too steep — it becomes a shoulder press.", "Elbows flaring."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 120,
  },
  ohp: {
    primary: ["front-delts", "side-delts"],
    secondary: ["triceps", "traps", "abs"],
    equipment: "barbell",
    setup: "Bar at the collarbone, glutes tight, ribs stacked over the pelvis.",
    cues: ["Press up and slightly back.", "Head through at the top.", "Don't lean back to cheat."],
    mistakes: ["Overarching the low back.", "Pressing out in front of the face."],
    defaultSets: 4,
    defaultReps: "6-8",
    restSec: 150,
  },
  dip: {
    primary: ["chest", "triceps"],
    secondary: ["front-delts"],
    equipment: "bodyweight",
    setup: "Hands on the bars, shoulders down, slight lean for chest, upright for triceps.",
    cues: ["Shoulders stay packed.", "Go to a stretch you own.", "Don't dump the chest forward."],
    mistakes: ["Neck craning.", "Bouncing out of the bottom."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  pushup: {
    primary: ["chest", "triceps"],
    secondary: ["front-delts", "abs"],
    equipment: "bodyweight",
    setup: "Hands under the shoulders, body one line from head to heels.",
    cues: ["Screw the hands into the floor.", "Chest to a fist off the floor.", "Don't pike the hips."],
    mistakes: ["Hips sagging.", "Only bending the elbows with a stiff torso."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 75,
  },
  fly: {
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "dumbbell",
    setup: "Slight elbow bend, palms facing, on a flat or slight incline.",
    cues: ["Sweep wide.", "Stop when the chest is loaded.", "Don't turn it into a press."],
    mistakes: ["Straight elbows stressing the joints.", "Banging the bells together."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 75,
  },
  tricep: {
    primary: ["triceps"],
    secondary: [],
    equipment: "cable",
    setup: "Elbows pinned at the sides, tall torso.",
    cues: ["Only the forearms move.", "Squeeze at lockout.", "Don't swing the shoulders."],
    mistakes: ["Elbows flaring and drifting forward."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  lateral: {
    primary: ["side-delts"],
    secondary: ["traps"],
    equipment: "dumbbell",
    setup: "Soft elbows, bells slightly in front of the hips.",
    cues: ["Lead with the elbows.", "Stop at shoulder height.", "Don't shrug."],
    mistakes: ["Swinging.", "Turning it into a front raise."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  row: {
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts", "hamstrings"],
    equipment: "barbell",
    setup: "Hinge to a flat-ish back, bar hanging at the knees.",
    cues: ["Pull to the hip, not the neck.", "Elbows in.", "Pause on the torso."],
    mistakes: ["Yanking with the low back.", "Standing more upright every rep."],
    defaultSets: 4,
    defaultReps: "6-8",
    restSec: 120,
  },
  pullup: {
    primary: ["lats"],
    secondary: ["biceps", "upper-back", "rear-delts"],
    equipment: "bodyweight",
    setup: "Hang dead, scapula set, slightly hollow.",
    cues: ["Pull the elbows to the ribs.", "Chest to the bar.", "Lower all the way."],
    mistakes: ["Kipping when the plan is strict.", "Chin-only range."],
    defaultSets: 3,
    defaultReps: "6-10",
    restSec: 120,
  },
  lat: {
    primary: ["lats"],
    secondary: ["biceps", "upper-back"],
    equipment: "cable",
    setup: "Sit tall, thighs locked, a grip you can pull to the collarbone.",
    cues: ["Pull the bar to the chest.", "Don't lean way back.", "Control the stretch up top."],
    mistakes: ["Turning it into a behind-the-neck pull.", "Using the lower back to finish."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "face-pull": {
    primary: ["rear-delts", "upper-back"],
    secondary: ["traps", "side-delts"],
    equipment: "cable",
    setup: "Rope at face height, thumbs back.",
    cues: ["Pull to the ears.", "Externally rotate at the end.", "Don't shrug the whole trap."],
    mistakes: ["Heavy weight that becomes a row."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  curl: {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    setup: "Arms at the sides, palms forward, elbows quiet.",
    cues: ["Squeeze at the top.", "Lower slower than you lift.", "Don't swing the hips."],
    mistakes: ["Elbows drifting forward every rep."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  hammer: {
    primary: ["biceps", "forearms"],
    secondary: [],
    equipment: "dumbbell",
    setup: "Neutral grip, same rules as a curl.",
    cues: ["Thumbs stay up.", "Don't rotate.", "Control the lower half."],
    mistakes: ["Swinging from the shoulders."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  shrug: {
    primary: ["traps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    setup: "Bells at the sides, arms long, chest up.",
    cues: ["Straight up, not roll.", "Pause at the top.", "Don't bend the elbows."],
    mistakes: ["Rolling the shoulders in a circle."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  "smith-shrug": {
    primary: ["traps"],
    secondary: ["forearms"],
    equipment: "machine",
    setup: "Bar in the Smith, standing tall, arms long, chest up.",
    cues: ["Straight up, not roll.", "Pause at the top.", "Don't bend the elbows."],
    mistakes: ["Rolling the shoulders in a circle."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  swing: {
    primary: ["glutes", "hamstrings"],
    secondary: ["abs", "lats", "forearms"],
    equipment: "kettlebell",
    setup: "Bell in front, hike it back like a snap, then stand tall.",
    cues: ["Hinge, don't squat.", "Snap the hips.", "The arms are ropes."],
    mistakes: ["Squatting the swing.", "Lifting with the low back."],
    defaultSets: 4,
    defaultReps: "12-15",
    restSec: 60,
  },
  farmer: {
    primary: ["forearms", "traps"],
    secondary: ["abs", "glutes", "calves"],
    equipment: "dumbbell",
    setup: "Heavy bells at the sides, tall walk.",
    cues: ["Ribs down.", "Don't lean.", "Short, quick steps."],
    mistakes: ["Shrugging the whole time.", "Leaning into one side."],
    defaultSets: 3,
    defaultReps: "30-40m",
    restSec: 75,
  },
  plank: {
    primary: ["abs"],
    secondary: ["obliques", "glutes"],
    equipment: "bodyweight",
    setup: "Elbows under the shoulders, body one line.",
    cues: ["Squeeze the glutes.", "Push the floor.", "Don't let the hips pike or sag."],
    mistakes: ["Holding the breath.", "Hips high to make it easier."],
    defaultSets: 3,
    defaultReps: "30-45s",
    restSec: 45,
  },
  "ab-wheel": {
    primary: ["abs"],
    secondary: ["lats", "obliques"],
    equipment: "bodyweight",
    setup: "Kneel, wheel under the shoulders, ribs down, glutes tight.",
    cues: ["Reach long without dumping the low back.", "Pull the wheel back with the abs.", "Don't pike the hips."],
    mistakes: ["Sagging into a banana. Rushing the reach."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 60,
  },
  "hanging-leg": {
    primary: ["abs"],
    secondary: ["forearms", "obliques"],
    equipment: "bodyweight",
    setup: "Hang still, slight hollow, knees bent.",
    cues: ["Pelvis curls, knees don't just swing.", "Control the lower.", "Don't use momentum."],
    mistakes: ["Kipping the hips."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 60,
  },
  "step-up": {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    setup: "Box at about knee height. Whole foot on top.",
    cues: ["Push through the top heel.", "Don't push off the trailing foot.", "Stand tall at the top."],
    mistakes: ["Box too high, hip hiking."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 75,
  },
  "leg-curl": {
    primary: ["hamstrings"],
    secondary: ["calves", "glutes"],
    equipment: "machine",
    setup: "Pad just above the ankles, hips glued down.",
    cues: ["Full squeeze.", "Don't yank.", "Slow on the way out."],
    mistakes: ["Lifting the hips to finish."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  "leg-ext": {
    primary: ["quads"],
    secondary: [],
    equipment: "machine",
    setup: "Pad on the shins, back against the seat.",
    cues: ["Don't slam lockout.", "Pause a beat.", "Control the drop."],
    mistakes: ["Using momentum from the hips."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 60,
  },
  "chest-press": {
    primary: ["chest", "triceps"],
    secondary: ["front-delts"],
    equipment: "machine",
    setup: "Handles at mid-chest, shoulders down and back.",
    cues: ["Don't lock out with a slam.", "Keep the shoulders packed.", "Full range you own."],
    mistakes: ["Shrugging into the handles."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "seated-row": {
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts"],
    equipment: "cable",
    setup: "Sit at the cable, chest up, arms long at the start.",
    cues: ["Pull to the ribs.", "Don't lean way back.", "Shoulder blades squeeze, then arms."],
    mistakes: ["Using the lower back as the mover."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "cable-row": {
    primary: ["lats", "upper-back"],
    secondary: ["biceps"],
    equipment: "cable",
    setup: "Sit tall, strap or bar in hand, stretch at the start.",
    cues: ["Elbows back.", "Pause on the body.", "Don't round forward on the reach."],
    mistakes: ["Torso rocking every rep."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  "rear-fly": {
    primary: ["rear-delts"],
    secondary: ["upper-back"],
    equipment: "dumbbell",
    setup: "Hinge, soft elbows, bells hanging under the chest.",
    cues: ["Sweep out, not back to the hips.", "Pinkies slightly up.", "Don't yank."],
    mistakes: ["Turning it into a row with bent elbows."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  "good-morning": {
    primary: ["hamstrings", "lower-back", "glutes"],
    secondary: ["upper-back"],
    equipment: "barbell",
    setup: "Bar on the upper back, soft knees, brace hard.",
    cues: ["Hips back.", "Shin angle barely changes.", "Stop before the back rounds."],
    mistakes: ["Going too deep with a light brace."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 90,
  },
  skullcrusher: {
    primary: ["triceps"],
    secondary: ["front-delts"],
    equipment: "barbell",
    setup: "On a bench, bar over the shoulders, elbows pointed up.",
    cues: ["Only the elbows bend.", "Lower toward the hairline.", "Don't flare wide."],
    mistakes: ["Letting the elbows walk forward every set."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  preacher: {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    setup: "Arm on the pad, armpit into the top edge.",
    cues: ["Don't hyperextend the elbow at the bottom.", "Squeeze short of the top.", "Slow down."],
    mistakes: ["Rocking the shoulder off the pad."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  pullover: {
    primary: ["lats", "chest"],
    secondary: ["triceps"],
    equipment: "dumbbell",
    setup: "Upper back on a bench, bell over the chest, slight elbow bend.",
    cues: ["Reach long.", "Don't turn it into a skull crusher.", "Ribs stay down."],
    mistakes: ["Bending the elbows more as you fatigue."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  crunch: {
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: "bodyweight",
    setup: "Knees bent, low back into the floor, hands at the temples.",
    cues: ["Ribs toward the hips.", "Don't yank the neck.", "Short range, hard squeeze."],
    mistakes: ["Sit-up momentum."],
    defaultSets: 3,
    defaultReps: "12-20",
    restSec: 45,
  },
  woodchop: {
    primary: ["obliques", "abs"],
    secondary: ["glutes", "front-delts"],
    equipment: "cable",
    setup: "Stand tall, cable or a light plate in both hands, arms long.",
    cues: ["Rotate from the ribs.", "Hips stay mostly quiet.", "Don't shrug."],
    mistakes: ["Squatting the chop.", "Bending the arms to make it a press."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "hip-abduction": {
    primary: ["glutes"],
    secondary: [],
    equipment: "machine",
    setup: "Pads on the outside of the knees, tall torso.",
    cues: ["Push out, pause.", "Don't lean the torso to cheat.", "Control in."],
    mistakes: ["Tiny range with too much weight."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "reverse-lunge": {
    primary: ["glutes", "quads"],
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    setup: "Step back, both knees toward 90°, torso tall.",
    cues: ["Front heel down.", "Hips square.", "Push through the front foot to stand."],
    mistakes: ["Tiny back step that dumps the front knee."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 90,
  },
  "close-grip": {
    primary: ["triceps", "chest"],
    secondary: ["front-delts"],
    equipment: "barbell",
    setup: "Hands about shoulder-width, same bench set as a regular press.",
    cues: ["Elbows stay closer.", "Touch the lower chest.", "Don't bounce."],
    mistakes: ["Hands so close the wrists fold."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 90,
  },
  "chin-up": {
    primary: ["lats", "biceps"],
    secondary: ["upper-back"],
    equipment: "bodyweight",
    setup: "Supinated grip, hang long, slight hollow.",
    cues: ["Chest to the bar.", "Don't kip.", "Lower all the way."],
    mistakes: ["Cutting range at the bottom."],
    defaultSets: 3,
    defaultReps: "6-10",
    restSec: 120,
  },
  "ham-slide": {
    primary: ["hamstrings", "glutes"],
    secondary: ["calves"],
    equipment: "bodyweight",
    setup: "Lie on your back, heels on sliders or a towel, hips up.",
    cues: ["Keep the hips high.", "Curl the heels under.", "Don't let the hips crash."],
    mistakes: ["Dropping into a crunch.", "Tiny range with the hips sagging."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 75,
  },
  nordic: {
    primary: ["hamstrings"],
    secondary: ["glutes", "calves"],
    equipment: "bodyweight",
    setup: "Kneel, ankles locked, torso tall, hands ready to catch.",
    cues: ["Hips stay open.", "Lower as slow as you own.", "Pull back with the hamstrings, not a hip hinge."],
    mistakes: ["Folding at the hips.", "Falling with no control."],
    defaultSets: 3,
    defaultReps: "4-6",
    restSec: 120,
  },
  cossack: {
    primary: ["quads", "adductors"],
    secondary: ["glutes", "hamstrings"],
    equipment: "dumbbell",
    setup: "Wide stance, sit into one hip, other leg long.",
    cues: ["Heel of the working leg stays down.", "Chest tall.", "Don't collapse the knee inward."],
    mistakes: ["Tiny side-to-side rocks with no depth."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 75,
  },
  kickback: {
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: "bodyweight",
    setup: "On all fours, working knee under the hip, foot flexed.",
    cues: ["Drive the heel to the ceiling.", "Don't arch the low back.", "Pause at the squeeze."],
    mistakes: ["Swinging the whole torso."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "glute-bridge": {
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: "bodyweight",
    setup: "On your back, feet close, ribs down.",
    cues: ["Drive through the heels.", "Squeeze without hyperextending.", "Pause one beat."],
    mistakes: ["Pushing from the low back."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "pec-deck": {
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "machine",
    setup: "Pads on the forearms, chest proud, shoulders down.",
    cues: ["Hug, don't shrug.", "Stop when the chest is loaded.", "Control the open."],
    mistakes: ["Banging the pads together."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  arnold: {
    primary: ["front-delts", "side-delts"],
    secondary: ["triceps"],
    equipment: "dumbbell",
    setup: "Start at the shoulders, palms toward you, then rotate as you press.",
    cues: ["Rotate through the press, not at the top.", "Don't lean back.", "Control the reverse."],
    mistakes: ["Turning it into a chaotic swing."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "hack-squat": {
    primary: ["quads"],
    secondary: ["glutes", "adductors"],
    equipment: "machine",
    setup: "Back against the pad, feet mid-platform, knees track the toes.",
    cues: ["Don't lock out angrily.", "Keep the hips from tucking.", "Own the bottom."],
    mistakes: ["Feet so high it becomes a hinge with no knee bend."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 120,
  },
  "cable-fly": {
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "machine",
    setup: "Sit tall on the fly machine, elbows slightly bent, handles at chest height.",
    cues: ["Hug, don't press.", "Stop when the chest is loaded.", "Control the open."],
    mistakes: ["Straight elbows. Turning it into a press."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  "suspension-curl": {
    primary: ["hamstrings", "glutes"],
    secondary: ["calves"],
    equipment: "bodyweight",
    setup: "Heels in the straps, hips up, body one line.",
    cues: ["Curl the heels under.", "Hips stay high.", "Don't pike."],
    mistakes: ["Letting the hips drop so the back does the work."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 75,
  },
  concentration: {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    setup: "Seated, elbow braced on the inner thigh, palming up.",
    cues: ["Only the forearm moves.", "Squeeze short of the top.", "Lower slower than you lift."],
    mistakes: ["Rocking the torso to finish."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "hip-adduction": {
    primary: ["adductors"],
    secondary: [],
    equipment: "machine",
    setup: "Pads on the inside of the knees, tall torso.",
    cues: ["Squeeze in, pause.", "Don't lean to cheat.", "Control the open."],
    mistakes: ["Tiny range with too much weight."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  decline: {
    primary: ["chest", "triceps"],
    secondary: ["front-delts"],
    equipment: "barbell",
    setup: "Decline bench, eyes under the bar, shoulder blades set.",
    cues: ["Touch the lower chest.", "Elbows about 45°.", "Don't bounce."],
    mistakes: ["Letting the bar drift toward the face.", "Hips sliding down the pad."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 120,
  },
  "decline-db": {
    primary: ["chest"],
    secondary: ["triceps", "front-delts"],
    equipment: "dumbbell",
    setup: "Decline bench, bells over the lower chest, wrists stacked.",
    cues: ["Lower with control.", "Press up, don't clang.", "Keep the shoulders packed."],
    mistakes: ["Flaring the elbows to 90°."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 90,
  },
  "cable-crossover": {
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "cable",
    setup: "Cables high, step forward, slight elbow bend.",
    cues: ["Sweep in to the midline.", "Chest leads.", "Don't crash the handles."],
    mistakes: ["Turning it into a press. Straight elbows."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  "incline-db": {
    primary: ["chest", "front-delts"],
    secondary: ["triceps"],
    equipment: "dumbbell",
    setup: "Bench 15–30°, bells over the upper chest.",
    cues: ["Lower to the outer chest.", "Don't let the bells drift back.", "Ribs stay down."],
    mistakes: ["Bench too steep — it becomes a shoulder press."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "db-bench": {
    primary: ["chest", "triceps"],
    secondary: ["front-delts"],
    equipment: "dumbbell",
    setup: "Flat bench, feet planted, bells over mid-chest.",
    cues: ["Lower with the elbows about 45°.", "Press up without banging.", "Shoulders stay packed."],
    mistakes: ["Bouncing off the chest.", "Wrists collapsing."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "straight-arm-pulldown": {
    primary: ["lats"],
    secondary: ["triceps", "abs"],
    equipment: "cable",
    setup: "Bar or rope high, hinge slightly, arms long.",
    cues: ["Sweep the bar to the thighs.", "Don't bend the elbows.", "Pause on the squeeze."],
    mistakes: ["Turning it into a crunch. Using the triceps as the mover."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  "one-arm-row": {
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts"],
    equipment: "dumbbell",
    setup: "Hand and knee on a bench, working arm hanging long.",
    cues: ["Pull to the hip.", "Don't rotate the torso.", "Lower all the way."],
    mistakes: ["Yanking with the low back.", "Shrugging the trap to finish."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 75,
  },
  "t-bar-row": {
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts"],
    equipment: "barbell",
    setup: "Straddle the bar, hinge, chest proud, arms long.",
    cues: ["Pull to the lower chest.", "Elbows in.", "Don't stand up every rep."],
    mistakes: ["Using the hips as a cheat curl."],
    defaultSets: 3,
    defaultReps: "8-10",
    restSec: 90,
  },
  "chest-supported-row": {
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts"],
    equipment: "machine",
    setup: "Chest on the pad, arms hanging, head neutral.",
    cues: ["Pull to the ribs.", "Squeeze the shoulder blades.", "Don't yank the neck off the pad."],
    mistakes: ["Turning it into a shrug."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  "one-arm-cable-row": {
    primary: ["lats"],
    secondary: ["biceps", "upper-back"],
    equipment: "dumbbell",
    setup: "Chest on an incline bench, one dumbbell hanging, head neutral.",
    cues: ["Elbow to the hip.", "Don't yank the neck off the pad.", "Control the lower."],
    mistakes: ["Twisting the torso off the bench."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "smith-squat": {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: "machine",
    setup: "Bar on the upper back, feet slightly in front, toes out a touch.",
    cues: ["Sit between the hips.", "Don't crash the safeties.", "Drive the floor away."],
    mistakes: ["Feet so far forward it becomes a good morning."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 120,
  },
  "sumo-squat": {
    primary: ["glutes", "adductors", "quads"],
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    setup: "Wide stance, toes out, bell or plate at the chest or hanging.",
    cues: ["Knees track the toes.", "Sit between the heels.", "Chest stays tall."],
    mistakes: ["Knees caving in. Tiny range."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 75,
  },
  "seated-leg-curl": {
    primary: ["hamstrings"],
    secondary: ["calves"],
    equipment: "machine",
    setup: "Pad on the ankles, back against the seat, thighs locked.",
    cues: ["Curl all the way.", "Don't yank.", "Slow on the way out."],
    mistakes: ["Lifting the hips off the pad."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 75,
  },
  "sissy-squat": {
    primary: ["quads"],
    secondary: [],
    equipment: "bodyweight",
    setup: "Hold a support, heels down or slightly elevated, torso leans back as the knees travel forward.",
    cues: ["Knees go forward, hips stay open.", "Don't fold at the waist.", "Own the stretch."],
    mistakes: ["Turning it into a regular squat. Knees collapsing in."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 60,
  },
  "pendulum-squat": {
    primary: ["quads"],
    secondary: ["glutes"],
    equipment: "machine",
    setup: "Back on the 45° pad, feet mid-platform, shoulders under the yoke.",
    cues: ["Don't lock out angrily.", "Own the bottom.", "Keep the hips from tucking."],
    mistakes: ["Tiny range with too much load."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 120,
  },
  "donkey-kick": {
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: "bodyweight",
    setup: "On all fours, working knee under the hip, foot flexed.",
    cues: ["Drive the heel to the ceiling.", "Don't arch the low back.", "Pause at the squeeze."],
    mistakes: ["Swinging the whole torso."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "pull-through": {
    primary: ["glutes", "hamstrings"],
    secondary: ["abs"],
    equipment: "cable",
    setup: "Cable low, straddle the rope, hinge until the hips load.",
    cues: ["Snap the hips through.", "Don't squat it.", "Arms stay long."],
    mistakes: ["Pulling with the arms. Rounding the back."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  "seated-db-press": {
    primary: ["front-delts", "side-delts"],
    secondary: ["triceps"],
    equipment: "dumbbell",
    setup: "Seat upright, bells at the shoulders, ribs stacked.",
    cues: ["Press up, not forward.", "Don't lean back to cheat.", "Control the lower."],
    mistakes: ["Banging the bells together at the top."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "cable-lateral": {
    primary: ["side-delts"],
    secondary: ["traps"],
    equipment: "cable",
    setup: "Cable low, stand side-on, slight elbow bend.",
    cues: ["Lead with the elbow.", "Stop at shoulder height.", "Don't shrug."],
    mistakes: ["Swinging. Turning it into a front raise."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "front-raise": {
    primary: ["front-delts"],
    secondary: ["side-delts"],
    equipment: "dumbbell",
    setup: "Bells at the thighs, soft elbows, tall torso.",
    cues: ["Raise to eye height.", "Don't swing the hips.", "Lower slower than you lift."],
    mistakes: ["Using momentum from the low back."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "machine-press": {
    primary: ["front-delts", "side-delts"],
    secondary: ["triceps"],
    equipment: "machine",
    setup: "Handles at shoulder height, back against the pad.",
    cues: ["Don't lock out with a slam.", "Keep the ribs down.", "Full range you own."],
    mistakes: ["Shrugging into the handles."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 90,
  },
  "reverse-pec-deck": {
    primary: ["rear-delts"],
    secondary: ["upper-back"],
    equipment: "machine",
    setup: "Chest on the pad, handles in front, soft elbows.",
    cues: ["Sweep out, not back to the hips.", "Don't yank.", "Pause on the squeeze."],
    mistakes: ["Turning it into a row with bent elbows."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "upright-row": {
    primary: ["side-delts", "traps"],
    secondary: ["biceps"],
    equipment: "dumbbell",
    setup: "Bells at the thighs, tall chest, soft elbows.",
    cues: ["Elbows lead.", "Stop at the chest, not the chin.", "Don't roll the shoulders."],
    mistakes: ["Hands too close. Yanking past the shoulders."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "cable-curl": {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "cable",
    setup: "Cable low, arms at the sides, elbows quiet.",
    cues: ["Squeeze at the top.", "Don't swing.", "Lower slower than you lift."],
    mistakes: ["Elbows drifting forward every rep."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "ez-curl": {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "barbell",
    setup: "EZ bar, standing tall, elbows at the sides.",
    cues: ["Don't swing the hips.", "Squeeze short of the top.", "Control the lower half."],
    mistakes: ["Leaning back to finish."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 60,
  },
  "spider-curl": {
    primary: ["biceps"],
    secondary: [],
    equipment: "barbell",
    setup: "EZ bar on a preacher pad, chest tall, arms long over the pad.",
    cues: ["Only the forearms move.", "Don't swing.", "Squeeze short of the top."],
    mistakes: ["Lifting the hips to finish."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "incline-curl": {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    setup: "Incline bench, arms hanging long, palms forward.",
    cues: ["Keep the upper arm quiet.", "Don't swing.", "Own the stretch at the bottom."],
    mistakes: ["Sitting up to finish the last reps."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "preacher-machine": {
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "machine",
    setup: "Armpit into the pad, handles in hand, wrist stacked.",
    cues: ["Don't hyperextend at the bottom.", "Squeeze short of the top.", "Slow down."],
    mistakes: ["Rocking the shoulder off the pad."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "overhead-ext": {
    primary: ["triceps"],
    secondary: ["front-delts"],
    equipment: "dumbbell",
    setup: "Bell overhead, elbows pointed up, ribs stacked.",
    cues: ["Only the elbows bend.", "Don't flare wide.", "Control the stretch."],
    mistakes: ["Turning it into a pullover. Arching the low back."],
    defaultSets: 3,
    defaultReps: "10-12",
    restSec: 60,
  },
  "tricep-kickback": {
    primary: ["triceps"],
    secondary: [],
    equipment: "dumbbell",
    setup: "Hinge, upper arm glued to the side, palm in.",
    cues: ["Only the forearm moves.", "Pause at lockout.", "Don't swing."],
    mistakes: ["Dropping the elbow every rep."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "overhead-cable": {
    primary: ["triceps"],
    secondary: [],
    equipment: "cable",
    setup: "Cable high behind you, elbows up, rope in hand.",
    cues: ["Extend over the head.", "Elbows stay put.", "Don't shrug."],
    mistakes: ["Turning it into a pulldown."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 60,
  },
  "bench-dip": {
    primary: ["triceps"],
    secondary: ["front-delts", "chest"],
    equipment: "bodyweight",
    setup: "Hands on a bench behind you, feet out, hips close to the edge.",
    cues: ["Shoulders stay packed.", "Go to a stretch you own.", "Don't dump the chest forward."],
    mistakes: ["Neck craning. Bouncing out of the bottom."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 60,
  },
  bicycle: {
    primary: ["abs", "obliques"],
    secondary: [],
    equipment: "bodyweight",
    setup: "On your back, hands at the temples, shoulders off the floor.",
    cues: ["Elbow to the opposite knee.", "Don't yank the neck.", "Slow enough to feel it."],
    mistakes: ["Tugging the head. Tiny range."],
    defaultSets: 3,
    defaultReps: "16-24",
    restSec: 45,
  },
  "sit-up": {
    primary: ["abs"],
    secondary: [],
    equipment: "bodyweight",
    setup: "Knees bent, feet down, arms across the chest or at the temples.",
    cues: ["Ribs toward the hips first.", "Don't yank the neck.", "Control the lower."],
    mistakes: ["Using momentum from the arms."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "reverse-crunch": {
    primary: ["abs"],
    secondary: [],
    equipment: "bodyweight",
    setup: "On your back, knees bent, low back into the floor.",
    cues: ["Curl the pelvis off the floor.", "Don't swing the legs.", "Slow on the way down."],
    mistakes: ["Kipping the hips."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 45,
  },
  "russian-twist": {
    primary: ["obliques", "abs"],
    secondary: [],
    equipment: "bodyweight",
    setup: "Sit tall, heels down or up, torso leaned back a touch.",
    cues: ["Rotate from the ribs.", "Don't round into a slump.", "Touch each side with control."],
    mistakes: ["Only moving the arms."],
    defaultSets: 3,
    defaultReps: "16-20",
    restSec: 45,
  },
  "cable-crunch": {
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: "cable",
    setup: "Kneel, rope at the shoulders, hips quiet.",
    cues: ["Ribs toward the hips.", "Don't pull with the arms.", "Pause at the squeeze."],
    mistakes: ["Turning it into a pulldown."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "v-up": {
    primary: ["abs"],
    secondary: [],
    equipment: "bodyweight",
    setup: "Lie long, arms overhead, legs together.",
    cues: ["Reach hands toward the feet.", "Don't yank the neck.", "Lower both halves with control."],
    mistakes: ["Bending the knees to cheat the range."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 45,
  },
  "flutter-kick": {
    primary: ["abs"],
    secondary: [],
    equipment: "bodyweight",
    setup: "On your back, low back pressed down, legs long and hovering.",
    cues: ["Small kicks.", "Don't let the back peel off.", "Breathe."],
    mistakes: ["Giant kicks that dump the low back."],
    defaultSets: 3,
    defaultReps: "30-45s",
    restSec: 45,
  },
  "decline-situp": {
    primary: ["abs"],
    secondary: [],
    equipment: "bodyweight",
    setup: "Decline bench, feet locked, arms at the chest.",
    cues: ["Ribs toward the hips.", "Don't yank the neck.", "Control the lower."],
    mistakes: ["Using the hip flexors as a swing."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 45,
  },
  "machine-crunch": {
    primary: ["abs"],
    secondary: [],
    equipment: "machine",
    setup: "Pad on the chest or handles at the shoulders, hips locked.",
    cues: ["Curl, don't pull with the arms.", "Pause.", "Control the return."],
    mistakes: ["Tiny range with too much weight."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "seated-calf": {
    primary: ["calves"],
    secondary: [],
    equipment: "machine",
    setup: "Pad on the thighs, balls of the feet on the edge.",
    cues: ["Full stretch.", "Pause at the top.", "Don't bounce."],
    mistakes: ["Using the quads to cheat. Tiny range."],
    defaultSets: 3,
    defaultReps: "12-15",
    restSec: 45,
  },
  "single-calf": {
    primary: ["calves"],
    secondary: [],
    equipment: "bodyweight",
    setup: "Ball of one foot on an edge, other foot hovering.",
    cues: ["Full stretch.", "Pause at the top.", "Don't bounce."],
    mistakes: ["Cutting range. Using the other leg to push off."],
    defaultSets: 3,
    defaultReps: "10-15",
    restSec: 45,
  },
  "jump-rope": {
    primary: ["calves"],
    secondary: ["forearms", "abs"],
    equipment: "bodyweight",
    setup: "Rope at the sides, soft knees, tall posture.",
    cues: ["Quiet jumps.", "Wrists turn the rope, not the shoulders.", "Stay light."],
    mistakes: ["Pounding the heels. Giant jumps."],
    defaultSets: 4,
    defaultReps: "45-60s",
    restSec: 30,
  },
  "mountain-climber": {
    primary: ["abs"],
    secondary: ["quads", "front-delts"],
    equipment: "bodyweight",
    setup: "High plank, hands under the shoulders, body one line.",
    cues: ["Drive the knees, hips stay quiet.", "Don't bounce the butt up.", "Breathe."],
    mistakes: ["Collapsing the shoulders. Piking."],
    defaultSets: 3,
    defaultReps: "30-40s",
    restSec: 30,
  },
  "jumping-jack": {
    primary: ["calves", "side-delts"],
    secondary: ["glutes"],
    equipment: "bodyweight",
    setup: "Stand tall, arms at the sides.",
    cues: ["Jump the feet out as the arms go up.", "Land quiet.", "Keep the ribs down."],
    mistakes: ["Pounding the floor. Shrugging the neck."],
    defaultSets: 3,
    defaultReps: "30-45s",
    restSec: 30,
  },
  "high-knees": {
    primary: ["quads", "abs"],
    secondary: ["calves"],
    equipment: "bodyweight",
    setup: "Stand tall, light on the balls of the feet.",
    cues: ["Knees toward the chest.", "Arms pump.", "Don't lean back."],
    mistakes: ["Shuffling in place with no knee lift."],
    defaultSets: 3,
    defaultReps: "20-30s",
    restSec: 30,
  },
  burpee: {
    primary: ["quads", "chest"],
    secondary: ["abs", "front-delts", "glutes"],
    equipment: "bodyweight",
    setup: "Stand tall, then squat, plank, push-up, jump.",
    cues: ["Chest to the floor if you own it.", "Jump with the hips, not a slump.", "Breathe every rep."],
    mistakes: ["Sagging in the plank. Skipping the stand-up."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 45,
  },
  bike: {
    primary: ["quads"],
    secondary: ["hamstrings", "calves"],
    equipment: "machine",
    setup: "Seat so the knee stays soft at the bottom, tall torso.",
    cues: ["Smooth circles.", "Don't bounce in the saddle.", "Keep the ribs stacked."],
    mistakes: ["Mashing only the downstroke."],
    defaultSets: 1,
    defaultReps: "10-20m",
    restSec: 0,
  },
  "jump-squat": {
    primary: ["quads", "glutes"],
    secondary: ["calves", "hamstrings"],
    equipment: "bodyweight",
    setup: "Feet shoulder-width, sit into a squat, then jump.",
    cues: ["Land quiet, then own the next squat.", "Don't crash the knees in.", "Arms help the jump."],
    mistakes: ["Tiny pulses with no squat. Pounding the landing."],
    defaultSets: 3,
    defaultReps: "8-12",
    restSec: 60,
  },
  rower: {
    primary: ["lats", "quads"],
    secondary: ["hamstrings", "upper-back", "biceps"],
    equipment: "machine",
    setup: "Feet strapped, sit tall, arms long at the catch.",
    cues: ["Legs, then hips, then arms.", "Don't yank with the low back.", "Control the return."],
    mistakes: ["Opening the back first. Hunching at the finish."],
    defaultSets: 1,
    defaultReps: "500-1000m",
    restSec: 0,
  },
  sprint: {
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "calves"],
    equipment: "bodyweight",
    setup: "Slight lean, arms ready, first steps short then open up.",
    cues: ["Drive the knees.", "Don't overstride.", "Stay tall through the torso."],
    mistakes: ["Sitting back. Swinging the arms across the body."],
    defaultSets: 6,
    defaultReps: "10-20s",
    restSec: 60,
  },
  "battle-rope": {
    primary: ["front-delts", "abs"],
    secondary: ["side-delts", "forearms"],
    equipment: "cable",
    setup: "Athletic stance, ropes in both hands, ribs down.",
    cues: ["Waves from the shoulders, not a squat bounce.", "Stay tall.", "Don't shrug the neck."],
    mistakes: ["Only moving the wrists. Collapsing the torso."],
    defaultSets: 4,
    defaultReps: "20-30s",
    restSec: 30,
  },
};

const FALLBACK: Meta = {
  primary: ["chest"],
  secondary: [],
  equipment: "dumbbell",
  setup: "Set up in a stable stance with the load under control.",
  cues: ["Brace.", "Own the range.", "Don't rush the last reps."],
  mistakes: ["Using momentum instead of the target muscle."],
  defaultSets: 3,
  defaultReps: "8-10",
  restSec: 90,
};

export const EXERCISES: Exercise[] = LIFT_MOVES.map((move) => {
  const meta = META[move.id] ?? FALLBACK;
  return { ...move, ...meta, primary: meta.primary, secondary: meta.secondary.filter((id) => id in MUSCLE_LABEL) };
});

export function exerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function exercisesForMuscle(id: MuscleId | "all", group?: Muscle): Exercise[] {
  return EXERCISES.filter((e) => {
    if (group && e.muscle !== group) return false;
    if (id === "all") return true;
    return e.primary.includes(id) || e.secondary.includes(id);
  });
}

export const EQUIPMENT_LABEL: Record<Equipment, string> = {
  barbell: "Barbell",
  dumbbell: "Dumbbell",
  machine: "Machine",
  cable: "Cable",
  bodyweight: "Bodyweight",
  kettlebell: "Kettlebell",
};

export const MUSCLE_GROUPS: { id: MuscleId; label: string }[] = [
  { id: "chest", label: "Chest" },
  { id: "lats", label: "Back" },
  { id: "front-delts", label: "Shoulders" },
  { id: "biceps", label: "Biceps" },
  { id: "triceps", label: "Triceps" },
  { id: "abs", label: "Abs" },
  { id: "quads", label: "Quads" },
  { id: "hamstrings", label: "Hams" },
  { id: "glutes", label: "Glutes" },
  { id: "calves", label: "Calves" },
  { id: "forearms", label: "Forearms" },
  { id: "adductors", label: "Adductors" },
];

export const EQUIPMENT_FILTER: Equipment[] = [
  "barbell",
  "dumbbell",
  "machine",
  "cable",
  "bodyweight",
  "kettlebell",
];

/** Same-pattern swaps so a session stays on-goal when a move is swapped. */
export function substituteMoves(moveId: string, limit = 8): Exercise[] {
  const ex = exerciseById(moveId);
  if (!ex) return [];
  const primary = ex.primary[0];
  return EXERCISES.filter((e) => e.id !== moveId)
    .map((e) => {
      let score = 0;
      if (primary && e.primary.includes(primary)) score += 4;
      if (e.muscle === ex.muscle) score += 2;
      if (e.equipment === ex.equipment) score += 1;
      if (primary && e.secondary.includes(primary)) score += 1;
      return { e, score };
    })
    .filter((x) => x.score >= 2)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.e);
}

/** Hours since a muscle last got a working set. Under 36h = still working. */
export function muscleReadiness(
  sessions: LiftSession[],
  today: string,
): { sore: MuscleId[]; ready: MuscleId[] } {
  const last: Partial<Record<MuscleId, number>> = {};
  const now = Date.parse(`${today}T12:00:00`);
  for (const s of sessions) {
    const t = Date.parse(`${s.date}T12:00:00`);
    if (Number.isNaN(t) || t > now) continue;
    for (const line of s.lines) {
      if (!line.sets.some((x) => x.done && !x.warmup)) continue;
      const ex = exerciseById(line.moveId);
      for (const m of ex?.primary ?? []) {
        last[m] = Math.max(last[m] ?? 0, t);
      }
    }
  }
  const sore: MuscleId[] = [];
  const ready: MuscleId[] = [];
  for (const id of Object.keys(last) as MuscleId[]) {
    const hours = (now - (last[id] ?? 0)) / 36e5;
    if (hours < 36) sore.push(id);
    else if (hours < 96) ready.push(id);
  }
  return { sore, ready };
}
