import assert from "node:assert/strict";
import test from "node:test";
import { COAT_ADHERES, FRY_ABSORBED, foodFor, fromIngredients, gramsFor } from "./food-energy.ts";
import { RECIPES } from "./recipes.ts";
import type { Ingredient } from "./types.ts";

const row = (name: string, qty: number, unit = ""): Ingredient => ({
  name,
  qty,
  unit,
  aisle: "Pantry",
});

const grams = (name: string, qty: number, unit = "") => {
  const food = foodFor(name);
  assert.ok(food, `no composition row for "${name}"`);
  const g = gramsFor(row(name, qty, unit), food);
  assert.notEqual(g, null, `cannot weigh "${qty} ${unit} ${name}"`);
  return g as number;
};

test("every ingredient row in the catalog can be weighed", () => {
  const gaps: string[] = [];
  for (const recipe of RECIPES) {
    const { unresolved } = fromIngredients(recipe);
    if (unresolved.length) gaps.push(`${recipe.id}: ${unresolved.join(", ")}`);
  }
  // A row the table cannot read is silently dropped from the total, which makes
  // the recipe look lighter than it is. There is no acceptable number here but
  // zero.
  assert.deepEqual(gaps, [], gaps.slice(0, 10).join("\n"));
});

test("a piece of meat weighs what one piece weighs, not what the joint weighs", () => {
  // Eight chicken pieces once read as eight whole birds, and the hot chicken
  // came out at 5,925 calories a serving.
  assert.ok(grams("chicken pieces", 8) < 1400, "eight pieces should not be eight birds");
  assert.ok(grams("lamb chops", 8) < 1400, "eight chops should not be eight shoulders");
  assert.ok(grams("pork loin chops", 4) < 1000, "a loin chop is not a loin");
  assert.ok(grams("cubed steak", 4) < 900);
  assert.ok(grams("quail", 8) < 1500, "a quail is not a squab");
  assert.ok(grams("hot dogs", 8) < 500);
  assert.ok(grams("frog legs", 8) < 500);
  assert.ok(grams("cooked meatballs", 12) < 600);
  // The whole-cut names still weigh the whole cut.
  assert.ok(grams("whole chicken", 1) > 1000);
  assert.ok(grams("pork shoulder", 1) > 700);
});

test("hamburger buns are bread, not beef", () => {
  // `hamburger` matched first and handed back mince.
  assert.ok(grams("hamburger buns", 4) < 500);
});

test("volume units use the food's own density", () => {
  // A cup of flour is 125 g and a cup of water is 237. Treating every cup as
  // water put 800 calories of flour into a pancake batter.
  assert.ok(Math.abs(grams("flour", 1, "cup") - 125) < 10);
  assert.ok(Math.abs(grams("water", 1, "cup") - 237) < 10);
  assert.ok(Math.abs(grams("olive oil", 1, "tbsp") - 13.6) < 2);
  assert.ok(Math.abs(grams("popcorn", 10, "cups") - 80) < 20, "popcorn is mostly air");
});

test("spirits in oz are fluid ounces, not weight", () => {
  assert.ok(Math.abs(grams("bourbon", 2, "oz") - 55) < 8);
});

test("alcohol carries energy that none of the macros account for", () => {
  const julep = RECIPES.find((r) => r.id === "so-mint-julep");
  assert.ok(julep);
  const { nutrition } = fromIngredients(julep);
  const fromMacros = nutrition.protein * 4 + nutrition.carbs * 4 + nutrition.fat * 9;
  assert.ok(
    nutrition.cal > fromMacros + 100,
    `a julep is mostly ethanol: ${nutrition.cal} kcal against ${fromMacros} from macros`,
  );
});

test("a frying bath is not eaten, and a pound of butter in shortbread is", () => {
  const shortbread = RECIPES.find((r) => r.id === "so-shortnin-bread");
  assert.ok(shortbread);
  const short = fromIngredients(shortbread);
  // Four cups of flour and a POUND of butter across sixteen pieces. Reading the
  // butter as a pot to fry in took this to four grams of fat a piece.
  assert.ok(short.nutrition.fat > 15, `shortbread lost its butter: ${short.nutrition.fat} g fat`);

  const frogs = RECIPES.find((r) => r.id === "so-frogs-legs");
  assert.ok(frogs);
  const fried = fromIngredients(frogs);
  // Four cups of lard, of which the legs take up a tenth of their own weight.
  assert.ok(
    fried.nutrition.fat < 40,
    `the frying bath was counted as eaten: ${fried.nutrition.fat} g fat a serving`,
  );
});

test("the discards are fractions, not all-or-nothing", () => {
  assert.ok(FRY_ABSORBED > 0 && FRY_ABSORBED < 0.3);
  assert.ok(COAT_ADHERES > 0 && COAT_ADHERES < 0.6);
});

test("no wired recipe computes to an impossible plate", () => {
  const silly = RECIPES.filter((r) => {
    const { nutrition } = fromIngredients(r);
    return nutrition.cal < 0 || nutrition.cal > 4000;
  }).map((r) => r.id);
  assert.deepEqual(silly, [], silly.join(", "));
});

test("stored nutrition is the computed nutrition", () => {
  // The catalog's figures are generated by this module. A hand edit to a
  // nutrition literal, or a changed ingredient row, shows up here rather than
  // as a quietly wrong number on a plate.
  const drifted: string[] = [];
  for (const recipe of RECIPES) {
    const { nutrition } = fromIngredients(recipe);
    const stored = recipe.nutrition;
    if (
      stored.cal !== nutrition.cal ||
      stored.protein !== nutrition.protein ||
      stored.carbs !== nutrition.carbs ||
      stored.fat !== nutrition.fat
    ) {
      drifted.push(
        `${recipe.id}: stored ${stored.cal}/${stored.protein}/${stored.carbs}/${stored.fat}` +
          ` vs computed ${nutrition.cal}/${nutrition.protein}/${nutrition.carbs}/${nutrition.fat}`,
      );
    }
  }
  assert.deepEqual(drifted, [], `${drifted.length} recipes drifted:\n${drifted.slice(0, 10).join("\n")}`);
});
