/**
 * Recipes that have been read line by line against the book they credit, and
 * corrected to match it.
 *
 * Membership here is a promise: the text in the catalog is the text that
 * reaches the cook. `polishRecipe` returns these untouched — no step
 * rewriting, no enrichment, no list alignment — because every one of those
 * passes is free to alter wording that was checked against a source, and
 * several of them did. A verified step that says "two heaping tablespoons"
 * says it because the book does.
 *
 * That makes this list load-bearing rather than decorative, so
 * `source-verified.test.ts` asserts the promise holds: for every id below,
 * what the catalog stores and what RECIPES renders must be identical.
 *
 * Add an id only after reading the recipe against the source text. The
 * running record, including the quantities the scan cannot settle, is in
 * docs/source-verification.md.
 */
export const VERIFIED_AGAINST_SOURCE: ReadonlySet<string> = new Set([
  // The Italian Cook Book — Maria Gentile, 1919 (Project Gutenberg #24407)
  "vh-gt-brodo",
  "vh-gt-minestrone",
  "vh-gt-risotto",
  "vh-gt-cacciatora",
  "vh-gt-pomodoro",
  "vh-gt-balsamella",
  "vh-gt-spaghetti-burro",
  "vh-gt-gnocchi",
  "vh-gt-zucchine",
  "vh-gt-panata",

  // The Southern Cook Book — Lustig, Sondheim & Rensel, 1935
  "so-avocado-canapes",
  "so-cheese-appetizer",
  "so-delicious-appetizer",
  "so-papaya-canape",
  "so-papaya-cocktail",
  "so-pigs-in-blankets",
  "so-shrimp-avocado-cocktail",
  "so-shrimp-paste",
  "so-egg-nog",
  "so-idle-hour-cocktail",
  "so-mint-julep",
  "so-mint-tea",
  "so-orange-julep",
  "so-planters-punch",
  "so-spiced-cider",
  "so-syllabub",
  "so-tom-and-jerry",
  "so-creole-batter-bread",
  "so-baking-powder-biscuits",
  "so-beaten-biscuits",
  "so-chitterlings",
  "so-corned-beef-hash-south",
  "so-creole-beef-stew",
  "so-creole-goulash",
  "so-dried-beef-maryland",
  "so-frogs-legs",
  "so-ham-pineapple",
  "so-baked-ham",
  "so-smithfield-ham",
  "so-broiled-ham",
  "so-stuffed-pork-chops",
  "so-parsnips-pork",
  "so-ribs-mission",
  "so-veal-fricassee",
  "so-veal-paprika",
  "so-chicken-tartare",
  "so-barbecued-chicken",
  "so-fried-chicken-maryland",
  "so-chicken-pot-pie",
  "so-roast-chicken",
  "so-roast-turkey",
  "so-chicken-cakes",
  "so-chicken-hash",
  "so-chicken-dumplings",
  "so-chicken-terrapin",
  "so-roast-duck",
  "so-roast-partridge",
  "so-mock-terrapin",
  "so-rice-chicken-casserole",
  "so-pigeon-pie",
  "so-squab-pilau",
  "so-cornbread-dressing",
  "so-oyster-stuffing",
  "so-apple-stuffing",
  "so-chestnut-stuffing",
  "so-bread-stuffing",
  "so-eggs-new-orleans",
  "so-eggs-ponce",
  "so-chicken-liver-ramekins",
  "so-chicken-gumbo",
  "so-southern-gumbo",
  "so-shrimp-gumbo",
  "so-almond-chicken-soup",
  "so-southern-bean-soup",
  "so-okra-soup",
  "so-chicken-cream-soup",
  "so-black-bean-soup",
  "so-md-crab-soup",
  "so-baltimore-crab-soup",
  "so-oyster-soup",
  "so-onion-au-gratin",
  "so-plantation-soup",
  "so-jellied-melange",
  "so-vegetable-bouillon",
  "so-small-burgoo",
  "so-crayfish-bisque",
  "so-oyster-bisque",
  "so-chicken-oyster-gumbo",
  "so-madame-begue-soup",
  "so-jugged-soup",
  "so-pot-likker",
  "so-cornmeal-dodger",
  "so-brunswick-stew",
  "so-kentucky-burgoo",
  "so-southern-corn-bread",
  "so-richmond-corn-cakes",
  "so-corn-meal-muffins",
  "so-crackling-bread",
  "so-tea-scones",
  "so-sally-lunn",
  "so-spoon-bread",
  "so-good-morning-biscuits",
  "so-corn-sticks",
  "so-raisin-biscuits",
  "so-buttermilk-muffins",
  "so-cheese-biscuits",
  "so-belgian-hare",
  "so-sweetbreads",
  "so-liver-begue",
  "so-opossum",
  "so-barbecued-lamb",
  "so-jambalayah",
  "so-chicken-chili",
  "so-scrapple",
  "so-suckling-pig",
  "so-chestnut-souffle",
  "so-curds-cream",
  "so-welsh-rarebit-south",
  "so-creole-omelet",
  "so-louisiana-waffles",
  "so-virginia-waffles",
  "so-rice-waffles",
  "so-georgia-flapjacks",
  "so-sour-milk-cakes",
  "so-flannel-cakes",
  "so-griddle-cakes",
  "so-hush-puppies",
  "so-hoe-cake",
  "so-popovers",
  "so-corn-fritters",
  "so-hopping-john",
  "so-fruit-fritter-batter",
  "so-apple-fritters",
  "so-peach-fritters",
  "so-apricot-fritters",
  "so-pear-fritters",
  "so-orange-fritters",
  "so-corn-bread-fritters",
  "so-grits",
  "so-corn-custard",
  "so-corn-pudding",
  "so-okra-tomatoes",
  "so-fried-okra",
  "so-string-beans-bacon",
  "so-baked-beans",
  "so-salsify",
  "so-lima-beans",
  "so-boiled-okra",
  "so-creole-rice-cakes",
  "so-rice-croquettes",
  "so-curried-rice",
  "so-wild-rice-mushrooms",
  "so-rice-pineapple",
  "so-baked-grits",
  "so-cornmeal-mush",
  "so-fried-eggplant",
  "so-artichokes",
  "so-candied-carrots",
  "so-fried-squash-cakes",
  "so-stuffed-squash",
  "so-creamed-peas",
  "so-tomato-bacon-rice",
  "so-chess-pie",
  "so-kentucky-pie",
  "so-lemon-pie",
  "so-jelly-pie",
  "so-coconut-pie",
  "so-pumpkin-pie",
  "so-pecan-pie",
  "so-apple-pot-pie",
  "so-raisin-pie",
  "so-butterscotch-pie",
  "so-pineapple-custard-pie",
  "so-candied-yams",
  "so-sugared-yams",
  "so-yam-puff",
  "so-georgian-sweets",
  "so-sweet-potato-pone",
  "so-stuffed-sweets",
  "so-scalloped-sweets",
  "so-sweets-honey",
  "so-marshmallow-sweets",
  "so-hashed-browns",
  "so-potato-croquettes",
  "so-stuffed-potatoes",
  "so-scalloped-potatoes",
  "so-ambrosia",
  "so-plum-pudding",
  "so-queen-trifle",
  "so-boiled-custard",
  "so-apple-dumplings",
  "so-pandowdy",
  // Sauces
  "so-white-sauce", "so-tomato-sauce", "so-mushroom-sauce", "so-barbecue-sauce",
  "so-creamed-gravy", "so-poultry-sauce", "so-raisin-ham-sauce", "so-apple-ball-sauce",
  "so-hard-sauce", "so-foaming-sauce", "so-brandy-sauce", "so-lemon-fritter-sauce",
  "so-egg-nog-sauce", "so-hollandaise-south", "so-horseradish-sauce", "so-shrimp-sauce",
  "so-rhubarb-sauce", "so-mint-ice",
  // Dressings, icings and candies
  "so-mayonnaise-south", "so-french-dressing", "so-sour-cream-dressing", "so-richmond-dressing",
  "so-butter-icing", "so-never-fail-icing", "so-mocha-icing", "so-orange-icing",
  "so-brown-sugar-frosting", "so-pralines", "so-coconut-pralines", "so-goober-brittle",
  "so-fudge", "so-caramels", "so-pecan-fondant", "so-candied-peel",
  // Fish and shellfish
  "so-bouillabaisse", "so-deviled-crabs", "so-crab-croquettes", "so-oyster-loaf",
  "so-oysters-louisiane", "so-fried-oysters", "so-browned-oysters", "so-oyster-pie",
  "so-lobster-thermidor", "so-lobster-newburg", "so-pompano", "so-fish-cakes",
  "so-roe-herring", "so-spanish-mackerel", "so-chesapeake-turtle", "so-flounder",
  "so-planked-shad", "so-shrimps-caliente", "so-shrimp-rice-croquettes",
  // Salads, relishes, preserved and baked fruit
  "so-shrimp-pea-salad", "so-lafite-salad", "so-grapefruit-ring", "so-cinnamon-apple-salad",
  "so-chicken-fruit-salad", "so-avocado-salad", "so-poinsettia-salad", "so-cole-slaw",
  "so-guspachy", "so-apple-chutney", "so-pepper-relish", "so-india-relish",
  "so-pickled-cherries", "so-glazed-apples", "so-baked-bananas", "so-fried-peaches",
  "so-baked-oranges", "so-baked-papaya", "so-stewed-prunes", "so-kumquat-prunes",
  "so-spiced-cantaloupe", "so-orange-marmalade", "so-grapefruit-marmalade", "so-guava-jelly",
  "so-pear-chips", "so-sherry-jelly",
  // Puddings and cold desserts
  "so-plantation-plum", "so-marmalade-pudding", "so-batter-pudding", "so-molasses-pudding",
  "so-bread-pudding", "so-barbara-fritchie", "so-rice-custard", "so-cottage-pudding",
  "so-orange-fluff", "so-southern-whip", "so-spanish-cream", "so-apple-float",
  "so-jelly-meringue", "so-carrot-pudding",
  // Cakes
  "so-lady-baltimore", "so-angel-food", "so-fruit-cake", "so-marble-cake",
  "so-poinciana-cake", "so-poinciana-filling", "so-shortnin-bread", "so-gingerbread",
  "so-hot-frosted-ginger", "so-jelly-roll", "so-strawberry-shortcake", "so-orange-cake",
  "so-strawberry-jam-cake", "so-blackberry-roll", "so-pecan-cake", "so-brown-white-cake",
  "so-devils-food", "so-coffee-cake", "so-pineapple-upside-down", "so-christening-cake",
  // Cookies, breakfast and the last of the book
  "so-zazarac-cocktail", "so-nut-bread", "so-turtle-soup", "so-ham-apples",
  "so-hamburger-bacon-roast", "so-broiled-hamburger", "so-dixie-shortcake", "so-crepes-suzette",
  "so-biltmore-eggs", "so-eggs-livers", "so-rice-flour-waffles", "so-creole-peppers",
  "so-southern-pastry", "so-doughnuts", "so-nut-drop-cookies", "so-sour-cream-cookies",
  "so-currant-cakes", "so-ginger-cookies", "so-colonial-cookies", "so-orange-cookies",
  "so-chocolate-brownies", "so-pecan-brownies",
  // The Boston Cooking-School Cook Book — Fannie Farmer, 1896 (Gutenberg 65061)
  "ar-ff-parker-house-rolls", "ar-ff-boston-brown-bread", "ar-ff-fish-chowder",
  "ar-ff-lobster-newburg", "ar-ff-white-sauce", "ar-ff-popovers",
  "ar-ff-molasses-gingerbread", "ar-ff-cream-tomato-soup", "ar-ff-eggs-goldenrod",
  "ar-ff-welsh-rarebit", "ar-ff-boston-baked-beans", "ar-ff-spider-corn-cake",
  // What Mrs. Fisher Knows About Old Southern Cooking — Abby Fisher, 1881
  "ar-mf-jumberlie", "ar-mf-ochra-gumbo", "ar-mf-sweet-potato-pie",
  "ar-mf-corn-bread", "ar-mf-fried-chicken", "ar-mf-ginger-cookies",
  "ar-mf-chow-chow",
  // The White House Cook Book — Gillette & Ziemann, 1887 (floating island not in the scan)
  "vh-wh-oyster-stew", "vh-wh-clam-chowder", "vh-wh-beef-a-la-mode",
  "vh-wh-saratoga", "vh-wh-chicken-croquettes", "vh-wh-macaroni-cheese",
  "vh-wh-hash",
  // 365 Foreign Dishes — anonymous, 1908. Five of the eight dishes that cited
  // it are in it; the book has no Swedish meat ball, no German potato salad
  // and no onion soup, so those three lost the credit instead.
  "vh-365-goulash", "vh-365-irish-stew", "vh-365-borscht",
  "vh-365-curry-chicken", "vh-365-spanish-rice",
  // The Picayune Creole Cook Book, 1901. Seven of the eight are in it. There is
  // no trout meuniere anywhere in the book, so that one lost its credit.
  "vh-pc-gumbo-file", "vh-pc-red-beans", "vh-pc-grillades", "vh-pc-calas",
  "vh-pc-pain-perdu", "vh-pc-courtbouillon", "vh-pc-shrimp-creole",
  // The International Jewish Cook Book — Greenbaum, 1918. Six of the eight are
  // in it. The book has no tzimmes and no chopped liver, so those lost theirs.
  "vh-jw-matzo-ball", "vh-jw-gefilte", "vh-jw-latkes", "vh-jw-kugel",
  "vh-jw-cabbage-rolls", "vh-jw-blintzes",
  // 365 Desserts, 1900. Six of the eight are in it. There is no snow pudding
  // and no boiled custard of its own, so those two lost their credit.
  "vh-ds-blancmange", "vh-ds-cottage-pudding", "vh-ds-apple-tapioca",
  "vh-ds-prune-whip", "vh-ds-rice-pudding", "vh-ds-charlotte",
]);
