/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiAdRewardRouteImport } from './routes/api/ad-reward'
import { Route as ApiGroceryCartRouteImport } from './routes/api/grocery-cart'
import { Route as ApiGrocerySearchRouteImport } from './routes/api/grocery-search'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as CascadeIndexRouteImport } from './routes/cascade.index'
import { Route as CascadeRulesRouteImport } from './routes/cascade.rules'
import { Route as CascadeVerifyRouteImport } from './routes/cascade.verify'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdRewardRoute = ApiAdRewardRouteImport.update({
  id: '/api/ad-reward',
  path: '/api/ad-reward',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroceryCartRoute = ApiGroceryCartRouteImport.update({
  id: '/api/grocery-cart',
  path: '/api/grocery-cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrocerySearchRoute = ApiGrocerySearchRouteImport.update({
  id: '/api/grocery-search',
  path: '/api/grocery-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadeIndexRoute = CascadeIndexRouteImport.update({
  id: '/cascade/',
  path: '/cascade/',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadeRulesRoute = CascadeRulesRouteImport.update({
  id: '/cascade/rules',
  path: '/cascade/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadeVerifyRoute = CascadeVerifyRouteImport.update({
  id: '/cascade/verify',
  path: '/cascade/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/watch': typeof WatchRoute
  '/api/ad-reward': typeof ApiAdRewardRoute
  '/api/grocery-cart': typeof ApiGroceryCartRoute
  '/api/grocery-search': typeof ApiGrocerySearchRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/cascade/rules': typeof CascadeRulesRoute
  '/cascade/verify': typeof CascadeVerifyRoute
  '/cascade/': typeof CascadeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/watch': typeof WatchRoute
  '/api/ad-reward': typeof ApiAdRewardRoute
  '/api/grocery-cart': typeof ApiGroceryCartRoute
  '/api/grocery-search': typeof ApiGrocerySearchRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/cascade/rules': typeof CascadeRulesRoute
  '/cascade/verify': typeof CascadeVerifyRoute
  '/cascade': typeof CascadeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/watch': typeof WatchRoute
  '/api/ad-reward': typeof ApiAdRewardRoute
  '/api/grocery-cart': typeof ApiGroceryCartRoute
  '/api/grocery-search': typeof ApiGrocerySearchRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/cascade/rules': typeof CascadeRulesRoute
  '/cascade/verify': typeof CascadeVerifyRoute
  '/cascade/': typeof CascadeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/watch'
    | '/api/ad-reward'
    | '/api/grocery-cart'
    | '/api/grocery-search'
    | '/api/stripe-webhook'
    | '/cascade/rules'
    | '/cascade/verify'
    | '/cascade/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/watch'
    | '/api/ad-reward'
    | '/api/grocery-cart'
    | '/api/grocery-search'
    | '/api/stripe-webhook'
    | '/cascade/rules'
    | '/cascade/verify'
    | '/cascade'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/watch'
    | '/api/ad-reward'
    | '/api/grocery-cart'
    | '/api/grocery-search'
    | '/api/stripe-webhook'
    | '/cascade/rules'
    | '/cascade/verify'
    | '/cascade/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WatchRoute: typeof WatchRoute
  ApiAdRewardRoute: typeof ApiAdRewardRoute
  ApiGroceryCartRoute: typeof ApiGroceryCartRoute
  ApiGrocerySearchRoute: typeof ApiGrocerySearchRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CascadeRulesRoute: typeof CascadeRulesRoute
  CascadeVerifyRoute: typeof CascadeVerifyRoute
  CascadeIndexRoute: typeof CascadeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ad-reward': {
      id: '/api/ad-reward'
      path: '/api/ad-reward'
      fullPath: '/api/ad-reward'
      preLoaderRoute: typeof ApiAdRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grocery-cart': {
      id: '/api/grocery-cart'
      path: '/api/grocery-cart'
      fullPath: '/api/grocery-cart'
      preLoaderRoute: typeof ApiGroceryCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grocery-search': {
      id: '/api/grocery-search'
      path: '/api/grocery-search'
      fullPath: '/api/grocery-search'
      preLoaderRoute: typeof ApiGrocerySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascade/': {
      id: '/cascade/'
      path: '/cascade'
      fullPath: '/cascade/'
      preLoaderRoute: typeof CascadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascade/rules': {
      id: '/cascade/rules'
      path: '/cascade/rules'
      fullPath: '/cascade/rules'
      preLoaderRoute: typeof CascadeRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascade/verify': {
      id: '/cascade/verify'
      path: '/cascade/verify'
      fullPath: '/cascade/verify'
      preLoaderRoute: typeof CascadeVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WatchRoute: WatchRoute,
  ApiAdRewardRoute: ApiAdRewardRoute,
  ApiGroceryCartRoute: ApiGroceryCartRoute,
  ApiGrocerySearchRoute: ApiGrocerySearchRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CascadeRulesRoute: CascadeRulesRoute,
  CascadeVerifyRoute: CascadeVerifyRoute,
  CascadeIndexRoute: CascadeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
